### ISSUE TITLE
IsSubscribed()

### ISSUE THREAD

**Issue by michidk** [Facepunch/Facepunch.Steamworks#10]
Hey,
Steamworks.net has this method where you can verify that a user owns a certain app. (https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamAppsTest.cs#L25) I can't find a method in Facepunch.Steamworks.. where is that?

**Comment by garrynewman** [comment]
Yep I can add this quite easily if you want it

**Comment by garrynewman** [comment]
Okay done, you can find it on Client now, so just client.IsSubscribed

**Comment by michidk** [comment]
That was quick! Thank you Garry.
