### ISSUE TITLE
How to implement Achievements in Unity?

### ISSUE THREAD

**Issue by viruscro** [Facepunch/Facepunch.Steamworks#100]
Hey everyone, sorry if this is the wrong place - I do not know how to properly make them work. Would love some guidance. I have managed to make everything work from the test Unity project, so its not that. I just have no clue where to properly start. Thanks in advance!

**Comment by viruscro** [comment]
```
 Client client = new Client(753660);
        Achievement achievement = client.Achievements.Find("1/0");
        if (achievement != null)
            achievement.Trigger();

```

Used this to trigger an achievement. Now I've done the same for another achievement and Unity crashed...

**Comment by viruscro** [comment]
```
 public void Test()
    {

        using (var client = new Facepunch.Steamworks.Client(753660))
        {
            Assert.IsTrue(client.IsValid);

            var gotStats = false;
            client.Achievements.OnUpdated += () => { gotStats = true; };

            while (!gotStats)
            {
                client.Update();
            }

         

            foreach (var ach in client.Achievements.All)
            {
                ach.Trigger();
            }
        }
}
```

And this works to get every achievement - but it says Steam Client failed...

**Comment by Ornias1993** [comment]
Did you have the client.update put in correctly?
Try using the script that is in the Unity Package to setup your client and then tryout the achievement system. Solid base before new features is most often the way to go about things ;)

**Comment by viruscro** [comment]
I'm using the code from AchievementsTest.cs, so I did not think I would need to put stuff in randomly to make it work. :( 

But I've managed to get the leaderboards working, sometimes the achievements do work out, other times, they crash the game.

//////////////////////////////// CODE
 public void ActivateAchievement(string achievementId)
    {
        using (var client = new Facepunch.Steamworks.Client(753660))
        {
            Assert.IsTrue(client.IsValid);

            var gotStats = false;
            client.Achievements.OnUpdated += () => { gotStats = true; };

            while (!gotStats)
            {
                client.Update();
            }

            foreach (var ach in client.Achievements.All)
            {
                Assert.IsNotNull(ach.Id);

                if (ach.Id.CompareTo(achievementId) == 0)
                {
                   if (!ach.State)
                    {
                        ach.Trigger();
                        UnityEngine.Debug.Log("Triggered = " + ach.Id);
                    }
                    else
                    {
                        UnityEngine.Debug.Log(ach.Id + " is already unlocked!");
                    }
                }
            }
        }

    }
/////////////////////////////// END CODE

Sometimes works, sometimes crashes the whole game.

Unity Editor [version: Unity 2017.3.0f3_a9f86dcd79df]

steam_api64.dll caused an Access Violation (0xc0000005)
  in module steam_api64.dll at 0033:59195153.

**Comment by speedis** [comment]
we simply do this:
```
    public void TriggerAchievement(string achievementId)
    {
        if(SteamClient != null)
        {
            SteamClient.Achievements.Trigger(achievementId);
            SteamClient.Stats.StoreStats();
        }
    }
```

Then if something matches (say the player reaches level 10), we just call:


`TriggerAchievement("LEVEL10");`

LEVEL10 is the internal steam ID for the achivement.

**Comment by viruscro** [comment]
Thank you very much, this is a life saver!
