### ISSUE TITLE
Crashes on startup of SteamApi_SteamInternal_CreateInterface

### ISSUE THREAD

**Issue by Danthekilla** [Facepunch/Facepunch.Steamworks#101]
When trying to startup we get this exceptoin after updating the steam_api64.dll to version 4.28.51.7

And our 32bit branch has always thrown this same error.

What version of steams dll should we be using or is this a library bug?

Exception info
`Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'Facepunch.Steamworks!SteamNative.Platform+Win32+Native::SteamInternal_CreateInterface' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'`

**Comment by garrynewman** [comment]
This should be fixed now
