### ISSUE TITLE
Setting Achievements on Server Side

### ISSUE THREAD

**Issue by speedis** [Facepunch/Facepunch.Steamworks#103]
Hey,

As mentioned before, your integration rocks.
Setting achivements client side works great, but I'd like to have it so the server is the one setting it rather than the client. Would it please be possible to add support for this?

https://partner.steamgames.com/doc/api/ISteamGameServerStats

https://partner.steamgames.com/doc/features/achievements (under "Game Server Stats" )

**Comment by shubhank008** [comment]
I am also interested on knowing about this. Were using MasterServerFramework to host our own gameservers and wanted to secure steam code executions on server side (achievements, etc.) but since linux server won't have a steam client running, whats the proper way to do it ?

**Comment by viruscro** [comment]
How did you make your achievements work great on client side? Sorry for being offtopic, but currently I am pulling my hair out with my problem and starting to go hopeless... Can you please check my problem?

**Comment by speedis** [comment]
viruscro: I replied in your other thread

**Comment by garrynewman** [comment]
Added :D
