### ISSUE TITLE
Dedicated server, to client or not to client

### ISSUE THREAD

**Issue by Ornias1993** [Facepunch/Facepunch.Steamworks#105]
@garrynewman There is something I absolutely don't get:
How do you set things up to run as a dedicated server?

Would I still need to create a client, or would you just if(!isdedicated){ } the client initialisation?

I know I can add the server.dedicated, which I currently added like the picture below... But I am struggling to find out what I should do with the client? It would take me a lot of uploads to a linux dedi machine to figure things out myself...

Also something positive: Facepunch.steamworks auth runs like a charm once you figure out how to set things up the right way... Thanks a lot for the feedback, Maybe i'll post some code examples for general use as a thankyou later! 👍 

<img width="397" alt="screen shot 2018-01-24 at 16 32 40" src="https://user-images.githubusercontent.com/7613738/35340844-834f80ca-0124-11e8-978f-0ae979fc7da1.png">

**Comment by garrynewman** [comment]
Just don't init the Client, only the server.

**Comment by Ornias1993** [comment]
Wow, indeed that works like a charm!
