### ISSUE TITLE
NRE when running dedicated Linux server: Facepunch.Steamworks.Server.set_ServerName

### ISSUE THREAD

**Issue by Ornias1993** [Facepunch/Facepunch.Steamworks#106]
I keep getting This NRE when I try to run a dedicated server on Linux...

As I added a failsafe to prevent an NRE trying to name a non existing server, this just shouldn't be there...

NRE:
<img width="1427" alt="screen shot 2018-01-24 at 22 59 04" src="https://user-images.githubusercontent.com/7613738/35359396-3953e93a-015a-11e8-8287-864046a4926c.png">

Code:
<img width="1056" alt="screen shot 2018-01-24 at 23 00 05" src="https://user-images.githubusercontent.com/7613738/35359431-5c425a3a-015a-11e8-831a-151375e10840.png">

In the console another error shows itself:
<img width="939" alt="screen shot 2018-01-24 at 23 12 29" src="https://user-images.githubusercontent.com/7613738/35359915-28256dbc-015c-11e8-92a8-257cc248bee5.png">

**Comment by garrynewman** [comment]
Is the Build 32bit or 64bit? Linux 32bit isn't really very well tested at this point, and is known to have some issues.

**Comment by Ornias1993** [comment]
Linux 64Bit, After some testing two things came up:
Firstoff it doesn't seem to "get" the steam DLL files at root and not get them in the "Plugins" directory either.

When I move all steam DLL's to Plugins/X86_64 it works when I excute this before starting the server:
export LD_LIBRARY_PATH="./Unitystation-Server_Data/Plugins/x86_64"

Also It might be worth documenting that steamclient.so is needed too....
