### ISSUE TITLE
How to implement Multiplayer in Unity?

### ISSUE THREAD

**Issue by Dubanator** [Facepunch/Facepunch.Steamworks#107]
Hello, 

I am a high school student looking to build a basic multiplayer game with some friends. Can anyone point me to a place where I can learn how to use use Facepunch.Steamworks in a multiplayer Unity Game, that includes a unity object's transform being synced over the network? I currently have code to setup a server, but I am stuck on the synchronization of an object's transform using only bytes...

Any help would be appreciated, 

Thanks!

**Comment by Skippeh** [comment]
Facepunch.Steamworks is only responsible for implementing steamworks into your c# based game, not all of the networking.

I recommend looking at these though:
https://docs.unity3d.com/Manual/UNetConcepts.html
https://docs.unity3d.com/Manual/UNetOverview.html
https://docs.unity3d.com/Manual/UNetUsingHLAPI.html
https://unity3d.com/learn/tutorials/topics/multiplayer-networking/introduction-simple-multiplayer-example

**Comment by Ornias1993** [comment]
@Dubanator 
We at [Unitystation](https://Github.com/unitystation/unitystation)  have quite some work done on that field already. But as @Skippeh explained, that does/didn't not require Steamworks at all.

@garrynewman You can close this one.

**Comment by Dubanator** [comment]
Thank you both for your information! You guys were a huge help!
