### ISSUE TITLE
Provide CloseP2PSessionWithUser in Networking

### ISSUE THREAD

**Issue by MrMMatricks** [Facepunch/Facepunch.Steamworks#109]
Hello!

I would need a public Access to the Method CloseP2PSessionWithUser.
Right now it seems like you already have it in the native converter but do not expose it in the Networking class. Would be cool to just add this method there:

		public void CloseP2PSessionWithUser(ulong steamId)
		{
			networking.CloseP2PSessionWithUser(steamId);
		}

Or did I just overlook this somewhere?
Alternatively give the Networking an Accessor to the NativeNetworking instance.

Thanks!

**Comment by garrynewman** [comment]
Added Networking.CloseSession :D
