### ISSUE TITLE
Mac Integration - How?

### ISSUE THREAD

**Issue by ThompsonCodes** [Facepunch/Facepunch.Steamworks#11]
Having trouble getting this to work for our OSX client; which files + folders should go where?  I've got the dylib and api dlls next to .app, to no success.

<3 FP

**Comment by garrynewman** [comment]
Are you running Unity - or something else?

**Comment by garrynewman** [comment]
And it doesn't work in the editor, or in standalone, or in both?

**Comment by ThompsonCodes** [comment]
It's working perfectly for the windows build, in and out of the editor. I haven't tried running the OSX version in editor.  Perhaps I should.

**Comment by garrynewman** [comment]
So in Rust on osx, we just copy these files next to the .app:

steam_appid.txt
libsteam_api.dylib

Does it give any errors? Do you have an output_log.txt?

**Comment by ThompsonCodes** [comment]
I do indeed have those files next to the .app.  I'll dig up some more information for us to work with.

**Comment by ThompsonCodes** [comment]
Getting a ton of variations for:
Fallback handler could not load library /Users/adamthompson/Library/Application Support/Steam/steamapps/common/Warpaint/Warpaint_MAC.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api64.so

Ending with:
DllNotFoundException: libsteam_api64.so

So, I assume I'll need to track down a "libsteam_api64.so" and chuck it somewhere it's looking.  Will try that now.

Thanks Garry

**Comment by ThompsonCodes** [comment]
Well, I found libsteam_api64.so, and I placed it in a few places the program says it's looking, but I'm still getting the same error.

Specifically, I put a copy next to the .app, as well as at one of the paths identified in the error:
/Users/adamthompson/Library/Application Support/Steam/steamapps/common/Warpaint/Warpaint_MAC.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api64.so

No dice.

**Comment by ThompsonCodes** [comment]
Trying an exhaustive search for the correct file structure: placing these files in different sub-directories.
I tried the same folder as the .app, the frameworks, and frameworks/mono.../osx
libsteam_api.dylib
 libsteam_api64.so
 steam_api.dll
 steam_api64.dll
 steam_appid.txt (edited for my app id)

No success, but placing them in the frameworks / osx folder yielded another clue:

Couldn't open /Users/adamthompson/Library/Application Support/Steam/steamapps/common/Warpaint/Warpaint_MAC.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api64.so, error: dlopen(/Users/adamthompson/Library/Application Support/Steam/steamapps/common/Warpaint/Warpaint_MAC.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api64.so, 2): no suitable image found.  Did find:
	/Users/adamthompson/Library/Application Support/Steam/steamapps/common/Warpaint/Warpaint_MAC.app/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api64.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

Not sure what to make of that one.

**Comment by garrynewman** [comment]
I think I know what this is. You just need to set the platform. Stick this in before you create the client.

```csharp
Facepunch.Steamworks.Config.ForUnity( Application.platform.ToString() );
```

This will tell it which platform it's being used on (it can't tell the difference between osx and linux under unity, so we have to help it).

**Comment by ThompsonCodes** [comment]
Perfection.  Many thank-yous.

Steam key for Warpaint:
E3H0A-C8QI9-YX3NI

If you have VR, I hear it's a good game to share with your son.  

<3
