### ISSUE TITLE
Client.Instance null after Server.Instance.Dispose()

### ISSUE THREAD

**Issue by RenNagasaki** [Facepunch/Facepunch.Steamworks#112]
Soo,
I am playing around with GameServer creation during Lobby activity.
So when I leave the Lobby and am the owner of it, then I'll Dispose of the Server.Instance to recreate it after  I create another Lobby.

But when I try to create another Lobby the Client.Instance is null.
Even though when I remove the Server.Instance.Dispose Call It works like it should.

With regards,
Risky aka RenNagasaki

**Comment by garrynewman** [comment]
This is normal. The way Steamworks works unfortunately - they're not really separate things under the hood.
