### ISSUE TITLE
SetLobbyGameServer not found

### ISSUE THREAD

**Issue by RenNagasaki** [Facepunch/Facepunch.Steamworks#113]
Soo,
another thing about the GameServer mechanics.

In the Steamworks SDK documentation I can find this call: [SetLobbyGameServer](https://partner.steamgames.com/doc/api/ISteamMatchmaking#SetLobbyGameServer)
for reference.

I think this is missing in your solution.

With regards,
Risky aka RenNagasaki

**Comment by garrynewman** [comment]
Added :D
