### ISSUE TITLE
Windows 10 + Unity3D Missing steam_api64.dll

### ISSUE THREAD

**Issue by CausticLasagne** [Facepunch/Facepunch.Steamworks#117]
Hi. I downloaded the Facepunch steamworks package from the asset store and it does not work within the editor or runtime. Here is a stacktrace:

`DllNotFoundException: steam_api64.dll`
`SteamNative.Platform+Win64.SteamApi_SteamAPI_Init () (at l:/workspace/Facepunch/Facepunch.Steamworks/master/Facepunch.Steamworks/SteamNative/SteamNative.Platform.Win64.cs:4014)`
`SteamNative.SteamApi.SteamAPI_Init () (at `l:/workspace/Facepunch/Facepunch.Steamworks/master/Facepunch.Steamworks/SteamNative/SteamNative.SteamApi.cs:59)`
`Facepunch.Steamworks.Interop.NativeInterface.InitClient (Facepunch.Steamworks.BaseSteamworks steamworks) (at `l:/workspace/Facepunch/Facepunch.Steamworks/master/Facepunch.Steamworks/Interop/Native.cs:41)`
Facepunch.Steamworks.Client..ctor (UInt32 appId) (at `l:/workspace/Facepunch/Facepunch.Steamworks/master/Facepunch.Steamworks/Client.cs:79)`
StealthGame.Steam.SteamInterface.Start () (at StealthLibrary/StealthLibrary/SteamInterface.cs:44)`

The installation succeeded and it looks like all the core libraries were copied, so not sure why it's being weird.

Thanks in advance.

**Comment by garrynewman** [comment]
Check out this section here

https://github.com/Facepunch/Facepunch.Steamworks#unity

**Comment by CausticLasagne** [comment]
Thanks Garry. Btw. GMod is awesome. Had to say it. :)
