### ISSUE TITLE
OnChatStringRecieved returning previous message data

### ISSUE THREAD

**Issue by Leuthil** [Facepunch/Facepunch.Steamworks#118]
It seems the OnChatStringReceived handler will return message data including previous message data depending on data length.

For example:
Message 1 sent: "Testing"
Message 1 received through OnChatStringReceived: "Testing"
Message 2 sent: "Hello"
Message 2 received through OnChatStringReceived: "Hellong"

**Comment by Silentor** [comment]
Its because of
`OnChatStringRecieved?.Invoke(steamid, Encoding.UTF8.GetString(chatMessageData));`
in Lobby.cs
For fix you need use a
`GetString(Byte[], Int32, Int32)`
overload. May be I will make a pull request

**Comment by garrynewman** [comment]
Just committed a fix for this
