### ISSUE TITLE
Server.Auth.StartSession always returns VACBanned with a different steam id

### ISSUE THREAD

**Issue by nidaynere** [Facepunch/Facepunch.Steamworks#123]
Server.Auth.StartSession is not working on the last build.
Returns VACBanned with another invalid steam id.

**Comment by garrynewman** [comment]
The latest build as in, the commit I did today?

**Comment by nidaynere** [comment]
I'm not sure, it's happened after static callback update. I'm downloading the current commit now and test.

**Comment by garrynewman** [comment]
Okay - I'm gonna throw it on Rust today and see if we see any issues.

Are you Windows 64, Unity?

**Comment by nidaynere** [comment]
Yes, Windows 7 64 and Unity.
I tried the current build, Auth returns VACBanned 3811158952595423375
but it's not my steamid, I guess it's not a proper steam id either

My code is working with the dll at Unity Asset Store version.
Okay I'm wondering, If it's working on Rust then my code is out of date.

**Comment by garrynewman** [comment]
Are you doing the Unity setup on startup? The Config.ForUnity stuff?

**Comment by nidaynere** [comment]
Yes ofcourse its Config.ForUnity("WindowsEditor")
Could you put the Facepunch dll here you compiled.
I start to suspect myself because I edited some code lines to get away from errors with netstandart2_0 before compiling the dll.

**Comment by garrynewman** [comment]
[archive (1).zip](https://github.com/Facepunch/Facepunch.Steamworks/files/1730634/archive.1.zip)

I'll do some tests later today - it's more likely to be my fault than yours

**Comment by nidaynere** [comment]
Returns VACBanned 4164128710829539471 with the dll you sent. Thanks, now my mind is ok to work on other things.

**Comment by garrynewman** [comment]
Can you give it a go with the latest commits?

**Comment by nidaynere** [comment]
It's working without a problem.
