### ISSUE TITLE
Networking AllowP2PPacketRelay / OnIncomingConnection problem

### ISSUE THREAD

**Issue by steel97** [Facepunch/Facepunch.Steamworks#126]
Hello, it would be nice if we have access to **AllowP2PPacketRelay** method, so network messages can be passed through steam relay servers. 

Also, I have a problem with **OnIncomingConnection** callback, it works fine in 0.7 release, but when I used master branch I found that this method working wrong(**steamid** parameter always a random number).

Thanks in advance!
P.S sorry for my bad english

**Comment by garrynewman** [comment]
Can you try it with the latest commits?

**Comment by steel97** [comment]
**OnIncomingConnection** seems to work fine now, thanks
