### ISSUE TITLE
Steamworks.Voice - How about this one?

### ISSUE THREAD

**Issue by ThompsonCodes** [Facepunch/Facepunch.Steamworks#13]
Not sure how to begin setting this one up, would be super cool to get some sample code here :)

**Comment by garrynewman** [comment]
Here you go

https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks.Test/Client/Voice.cs#L19

**Comment by ThompsonCodes** [comment]
<3
