### ISSUE TITLE
'RemoteFileWriteStream.Close()': no suitable method found to override

### ISSUE THREAD

**Issue by your1987** [Facepunch/Facepunch.Steamworks#130]
public class RemoteFileWriteStream : Stream

Impossible to build, even with a clean clone from the master branch.
Removing the override actually triggers a warning:
'RemoteFileWriteStream.Close()' hides inherited member 'Stream.Close()'.

**Comment by nidaynere** [comment]
Same, I changed the Close --> Close2 :) to build.
And remote file storage is working still fine.

**Comment by garrynewman** [comment]
What version of VS are you using?

**Comment by nidaynere** [comment]
my VS version:

![vsinfo](https://user-images.githubusercontent.com/36076974/36472395-6486736a-16fa-11e8-883d-953499eba4a6.jpg)

**Comment by your1987** [comment]
I'm using VS Community 2017
Version 15.2 (26430.6) Release

Microsoft .NET Framework
Version 4.7.02558
