### ISSUE TITLE
Documentation for Server / Client connection.

### ISSUE THREAD

**Issue by Arsonide** [Facepunch/Facepunch.Steamworks#134]
So setting up a server is simple with this, wonderful to use. Clients are similarly simple to use. Now in my game, I can connect via IP right now, but I have no idea on the Steamworks side how to connect a client to a server. I've checked the Wiki, the Readme, the test project, various forum posts, and Google. So right now in my game I have a client that can read off various stats about your Steam profile, but not actually connect to a server via Steamworks. Only directly connect.

There isn't any documentation for this. Note I'm not trying to use lobbies, and I can already connect in my game via direct IP. I just want to make a Steam connection between client and server.

If anybody could point out how to do this, I'll do the documenting myself.

**Comment by garrynewman** [comment]
Will aim to make a blog this week.

**Comment by Arsonide** [comment]
So I have successfully got the server and client to connect through Steam, but I appear to be experiencing #22 - my server is showing up on the web api, and in the LAN tab, but not on the internet. I am using NAT punchthrough and have verified that both the game port and the query port are open and forwarded. The server can be used to establish a connection so long as it is visible, but people over the net can't see it, even though it appears if I check my IP in the web API.

**Comment by austinmilt** [comment]
@Arsonide or @garrynewman Could you give me a hint or a snippet as to how to get a server and client connected through Steam? 

In case it helps, I am aiming at having Solo, Local Multiplayer, and Online Multiplayer, all with a single user having the server instance. I am aiming to program a single network management script that can handle communication between client(s) and server, just with different initialisations.

**Comment by DMeville** [comment]
I am interested in this as well.  Any sort of info would be incredibly useful!

**Comment by DMeville** [comment]
@Arsonide 

The solution seems to be there is no way to communicate the connection built-in.  
Instead, when a client initiates the connection to the server(using unet, photon, bolt, or steamworksP2P) you piggyback on that connection request to send an auth ticket and steamId.  The server then uses this to start the session.  

I was assuming there was a way for the client to initiate the session, but there is not, only the server can do that!

Eg:
- Server starts up, starts the server via var server = new Facepunch.Steamworks.Server(252490, options);
- Client starts an instance of the game client, starts up a client var client = new Facepunch.Steamworks.Client( 252490 );
- Client gets the server connection info (ip:port) via servery query or another means.
- Client generates an auth ticket (client.Auth.GetAuthSessionTicket())
- Client sends a connection request to the server ip, sending with it the ticket data and it's steam id
- Server receives the connection request, and checks the ticket. If the ticket is good accept the connection.server.Auth.StartSession(t.clientTicket, t.steamId); 
- Client is now connected to the server through your networking layer, and through steamworks. Verify by right clicking the player in steam. Join game is now clickable, and view game info shows the server you're connected to.

**Comment by grayjamn** [comment]
This is a bit different than how I remember steamworks.net doing this, I'm confused on how the lobby host communicates the game server information to the clients.

The scenario would be:
1. Host creates a lobby (Easy. Can do this)
2. Clients find the lobby via lobby list or matchmaking and join (Easy. Can do this)
3. Host starts the game, sets gameserver information to lobby (How is this done? Steamworks.net used a SteamMatchmaking.SetLobbyGameServer(), not finding anything similar for Facepunch )
4. Somehow clients are notified the game has started, beginning connecting...
5. Clients connect to game server by pulling GameServer information from lobby using SteamMatchmaking.GetLobbyGameServer() (How is this done?)

**Comment by DMeville** [comment]
@grayjamn 

3) After a client creates a lobby (and automatically joins the lobby), they can use             client.Lobby.SetGameServer(ip, port, serverSteamId);
4) Lobby owner sets lobby data "gameStarted = true", other players in the lobby listen for this and join the game server when they get the data update callback
5) client.Lobby.GameServerIp, client.Lobby, client.Lobby.GameServerPort, client.Lobby.GameServerSteamId

**Comment by JamieShelley** [comment]
@DMeville  Are you stating that a lobby is needed for the server to appear not just on LAN but also on the ServerList sorry?
In testing the publuc IP (Output below from the steamworks api tester) you can see I'm using the test 'spacewar' appid etc.
Alas the ;"gmsindex":-1,"reject":"bad_version; indicates it's rejected on the server list - (gms=gamemasterIndex?)

`{"response":{"success":true,"servers":[{"addr":"81.96.84.217:27016","gmsindex":-1,"reject":"bad_version","appid":480,"gamedir":"spacewar","region":-1,"secure":true,"lan":false,"gameport":27015,"specport":0}]}}`
