### ISSUE TITLE
Query leaderboard for specific username?

### ISSUE THREAD

**Issue by yyr57695** [Facepunch/Facepunch.Steamworks#136]
The Steamworks leaderboard documentation mentions the following method, which could be used to fetch scores for a specific user or set of users:

`SteamAPICall_t DownloadLeaderboardEntriesForUsers( SteamLeaderboard_t hSteamLeaderboard, CSteamID *prgUsers, int cUsers );`

This is as opposed to the usual DownloadLeaderboardEntries.  However, Facepunch.Steamworks currently only seems to offer FetchScores, which does not accept a list of usernames.

I'm trying to implement a function with which the player can check just their own score.  To be able to specify the user's own name and download just their own entry would be perfect.  I'm at a loss as to how I'd do this otherwise.  So...are there any plans to implement DownloadLeaderboardEntriesForUsers?  If not, can anyone suggest a method to do this using the current FetchScores?  Thanks much.

**Comment by yamlCase** [comment]
I do something like this:
```
leaderboard.FetchScores(Leaderboard.RequestType.GlobalAroundUser, 0, 0)
```

**Comment by yyr57695** [comment]
Thanks for the suggestion.  Unfortunately I can't test it right now because Leaderboards seem to be broken atm (https://github.com/Facepunch/Facepunch.Steamworks/issues/148) but I'll test it when/if they're working again!

**Comment by yyr57695** [comment]
This suggestion worked perfectly!  Thanks yamlCase!

**Comment by yyr57695** [comment]
I'm just going to add to the notes that I used this to add a "My Score" function.  I didn't use the term earlier, and I want this to come up in search results =)
