### ISSUE TITLE
Is the method : GetAvailableGameLanguages() available somehow?

### ISSUE THREAD

**Issue by ThompsonCodes** [Facepunch/Facepunch.Steamworks#14]
Localizing my game, is there any way I can get access to the user's chosen language?

I can see there's some implementation here, but it's internal.
https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/SteamNative/SteamNative.SteamApps.cs

**Comment by garrynewman** [comment]
I'll add this - shouldn't be an issue

**Comment by garrynewman** [comment]
Okay - all done

**Comment by ThompsonCodes** [comment]
thanks
