### ISSUE TITLE
OnLobbyJoinRequested returns incorrect lobby ID

### ISSUE THREAD

**Issue by axelucho** [Facepunch/Facepunch.Steamworks#142]
Before calling Lobby.InviteUserToLobby I check the current lobby ID and its X. When the OnLobbyJoinRequested callback gets called on the other persons client it says its Y. If i refresh the lobby list at that point and check all active lobbies the original X lobby id is indeed there but for some reason the callback's lobby ID is incorrect (and does not exist).

It is of note that the length of the correct ID and the incorrect one are different. For example:
Correct one: 
109775244761412440 

Incorrect:
106927512287744

Checked the OnLobbyJoinRequestedAPI and its indeed using callback.SteamIDLobby so I'm out of ideas as to whats going on..

Any ideas?

**Comment by axelucho** [comment]
As to further illustrate, if the invite happens while the other player has the game closed. The command line arguments have the correct room number. But if the invite happens while he is in game the call back gets the wrong info like stated above...

**Comment by Skippeh** [comment]
Somewhat related; i wonder if this is why you can't join people in Rust (the game) through steam if your game is already running.
