### ISSUE TITLE
32bit lobbies not working

### ISSUE THREAD

**Issue by Moukib** [Facepunch/Facepunch.Steamworks#143]
Hello, when I build for 64 bits architecture everything works fine, but when I try to build for 32 bits, I can not create a lobby, does not even return false on Client.Instance.Lobby.OnLobbyCreated = (success) =>
The library is working, because I can retrieve mi username from steam even on 32 bits.
Thanks guys!

**Comment by Danthekilla** [comment]
We are also having this issue. Did you happen to find a solution?

**Comment by SergioDelValle** [comment]
Maybe it's related to the leaderboards problem? In 64 bits leaderboards are ok (also in Unity Editor) but 32bit exe's doesn't connect to them. Other features such as Avatars or usernames work fine.

**Comment by Moukib** [comment]
May be, probably it got bugged on some update, hope it can be repaired soon.
