### ISSUE TITLE
Auth on Linux64 returns VACBanned

### ISSUE THREAD

**Issue by proepkes** [Facepunch/Facepunch.Steamworks#147]
My client sends his SteamID & ticket to my server, the server then validates the ticket with

`Server.Instance.Auth.StartSession(data.TicketData, data.SteamID)`

Then the callback is called, but the steamID is totally different from the one that started the session. The status is VACBanned. This only happens when I run the server on Ubuntu 64Bit. On Windows the callback-status is "Ok".

**Comment by proepkes** [comment]
I've fixed this by settings Config.UseThisCall = true

**Comment by V-ZINC** [comment]
hey @proepkes i made an auth script however the callback never fires. Cant get anyone's attention to help me. Mind if u can help? Here is the script (Dont mind the comments thats me talkin to myself): 
```
    //Now keep in mind this is now all running on the server not this machine any more! ok?
    [Command]
    public void CmdAuth(byte[] ticket, ulong SteamId)
    {
        Debug.Log("User Attempting to auth");

        Server.Instance.Auth.OnAuthChange = CmdAuthChanged;

        Server.Instance.Auth.StartSession(ticket, SteamId);
    }

    [Command]
    public void CmdAuthChanged(ulong SteamId, ulong OwnerId, ServerAuth.Status Status)
    {
        //You must get the connection here 

        //Check i the client is actully there 

        if (Status == ServerAuth.Status.OK)
        {
            Debug.LogWarning("Steam gave us a 'ok' ticket response for already connected id " + SteamId);
            return;
        }

        if (Status == Facepunch.Steamworks.ServerAuth.Status.VACCheckTimedOut)
            return;

        //If it made it here that means the guy should be kciked 
        //Bye
        Debug.Log("User Kicked");
    }
```

I only ever get that "User attempting to auth" in my server console. I tried it on a script attached to the server without all these commands this is just the latest version but it had the same problem

**Comment by proepkes** [comment]
@V-ZINC 
i dont see anything wrong in your codesnippet. Maybe you dont call Server.update?

**Comment by V-ZINC** [comment]
@proepkes ahhh no i dont! would i call that after i call startsession, do you use it?

**Comment by proepkes** [comment]
@V-ZINC I don't use the server inside unity, but I guess you can just put into Unitys Update() 

the same like the Client in this example calls Client.Update:
https://github.com/Facepunch/Facepunch.Steamworks.Unity/blob/master/Assets/Scripts/SteamTest.cs

**Comment by V-ZINC** [comment]
Yess im so excited i legit spent 3 weeks smashing my head for this one and you figured it out for me. I just updated the server in a update loop and badabing badaboom it was fixed. thanks heaps @proepkes

**Comment by V-ZINC** [comment]
@proepkes just to be clear this bassicly means you have joined the steam server right, and so it should be added to your server history?
