### ISSUE TITLE
After onDefinitionsUpdated Get NullReferenceException

### ISSUE THREAD

**Issue by liu0fanyi** [Facepunch/Facepunch.Steamworks#149]
Like this:

> onDefinitionsUpdated
NullReferenceException: Object reference not set to an instance of an object
  at (wrapper managed-to-native) SteamNative.Platform+Win64+Native:SteamAPI_RunCallbacks ()
  at SteamNative.Platform+Win64.SteamApi_SteamAPI_RunCallbacks () [0x00001] in C:\GitHub\Facepunch.Steamworks\Facepunch.Steamworks\SteamNative\SteamNative.Platform.Win64.cs:4168 
  at SteamNative.SteamApi.SteamAPI_RunCallbacks () [0x00001] in C:\GitHub\Facepunch.Steamworks\Facepunch.Steamworks\SteamNative\SteamNative.SteamApi.cs:83 
  at Facepunch.Steamworks.Client.RunCallbacks () [0x00001] in C:\GitHub\Facepunch.Steamworks\Facepunch.Steamworks\Client.cs:163 
  at Facepunch.Steamworks.Client.Update () [0x00010] in C:\GitHub\Facepunch.Steamworks\Facepunch.Steamworks\Client.cs:151 
  at SteamClient.Update () [0x0002c] in F:\Unity_Project\breast\Assets\Plugins\Facepunch.Steamworks\Utility\SteamClient.cs:57 
 (Filename: C:/GitHub/Facepunch.Steamworks/Facepunch.Steamworks/SteamNative/SteamNative.Platform.Win64.cs Line: 4168)

I use the init script like this in unity:

``` c#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//
// This class takes care of a lot of stuff for you.
//
//  1. It initializes steam on startup.
//  2. It calls Update so you don't have to.
//  3. It disposes and shuts down Steam on close.
//
// You don't need to reference this class anywhere or access the client via it.
// To access the client use Facepunch.Steamworks.Client.Instance, see SteamAvatar
// for an example of doing this in a nice way.
//
public class SteamClient : MonoBehaviour
{
    public uint AppId;

    private Facepunch.Steamworks.Client client;

	void Start ()
    {
        // keep us around until the game closes
        GameObject.DontDestroyOnLoad(gameObject);

        if (AppId == 0)
            throw new System.Exception("You need to set the AppId to your game");

        //
        // Configure us for this unity platform
        //
        Facepunch.Steamworks.Config.ForUnity( Application.platform.ToString() );

        // Create the client
        client = new Facepunch.Steamworks.Client( AppId );

        if ( !client.IsValid )
        {
            client = null;
            Debug.LogWarning("Couldn't initialize Steam");
            return;
        }

        Debug.Log( "Steam Initialized: " + client.Username + " / " + client.SteamId ); 
	}
	
	void Update()
    {
        if (client == null)
            return;

        try
        {
            UnityEngine.Profiling.Profiler.BeginSample("Steam Update");
            client.Update();
        }
        finally
        {
            UnityEngine.Profiling.Profiler.EndSample();
        }
    }

    private void OnDestroy()
    {
        if (client != null)
        {
            client.Dispose();
            client = null;
        }
    }
}
```

**Comment by Hertzole** [comment]
I'm experiencing something similar, but instead, my game outright crashes. The logs always end on "onDefinitionsUpdated". And once it actually gets passed that, it also gives me a NullReferenceException and then crashes. So you're not alone with this.

**Comment by liu0fanyi** [comment]
@Hertzole 
I get crashed either, after build and run in steam
I have deleted code in Update, I just use achievement method, and it just ok for now.
But still not sure what happened~

**Comment by MrMengis** [comment]
It's a little while since this post was updated but it's exactly the behaviour I've just been experiencing when running UnityRelease builds on Steam. The solution was to:

1. make sure the steam_api64.dll was *not in the Steam ContentBuilder/content root folder
2. make sure the steam_api64.dll  *is* in the Steam ContentBulder/content/project_name_Data/Plugins folder
3. don't add steam_appid.txt to the content folder

**Comment by liu0fanyi** [comment]
> It's a little while since this post was updated but it's exactly the behaviour I've just been experiencing when running UnityRelease builds on Steam. The solution was to:
> 
> 1. make sure the steam_api64.dll was __not__ in the Steam ContentBuilder/content root folder
> 2. make sure the steam_api64.dll  __is__ in the Steam ContentBulder/content/project_name_Data/Plugins folder
> 3. don't add steam_appid.txt to the content folder

Then I will get this error:
DllNotFoundException: steam_api64.dll
any help...
