### ISSUE TITLE
SteamClient.Inventory.Definitions does not contain playtime generator type items

### ISSUE THREAD

**Issue by hippovision** [Facepunch/Facepunch.Steamworks#15]
Is there an example for how to call TriggerItemDrop() successfully?

The item definitions that I'm trying to call this upon do not exist in Inventory.Definitions because Valve are hiding playtime generators in the ItemDefs list.

http://steamcommunity.com/groups/steamworks/discussions/21/135514151380831924/

An example would be super helpful, thanks!

**Comment by garrynewman** [comment]
Yeah sorry, 

```csharp
var myitem = Steam.Inventory.CreateDefinition( 10 );
myitem.TriggerItemDrop();
```

**Comment by hippovision** [comment]
Thanks! I thought I tried this, but it didn't work previously.

Works now though, typical.

And just to double check, the debug (test purposes only) call "GenerateItem()" isn't wrapped in this SDK yet?

**Comment by garrynewman** [comment]
No it isn't, is this something you think you might need?

**Comment by garrynewman** [comment]
I have added Inventory.GenerateItem
