### ISSUE TITLE
[Question] Offline Mode

### ISSUE THREAD

**Issue by Munkyfoot** [Facepunch/Facepunch.Steamworks#154]
I'm having issues when running the game in Offline Mode. I'm unable to create a Client.Instance (which makes sense I suppose). I have been looking for a way to tell whether Steam is in offline mode so I can create a solution by checking whether the game is in offline mode and using a different method than the Client.Instance, but I have been unable to find any such variable. Is there something I'm missing or is there currently no way to tell whether Steam is in offline mode?

**Comment by paulogodinhoaq** [comment]
Did you find anything about this @Munkyfoot ? I can't find the callbacks that tell if Steam is connected or not to its server(Online or Offline).

**Comment by Munkyfoot** [comment]
Unfortunately not. Currently, I’m just checking whether or not the Client.Instance successfully initiated and considering it offline if not.

**Comment by paulogodinhoaq** [comment]
Looks like I will have to mix and match Facepunch with Steamworks.net to have everything I want.

**Comment by Munkyfoot** [comment]
While it seems an "Offline Mode" variable does not exist you can fudge it by checking whether or not the Client.Instance is null.
