### ISSUE TITLE
Workshop: "Error creating new file: OK"

### ISSUE THREAD

**Issue by mklingen** [Facepunch/Facepunch.Steamworks#155]
When attempting to publish content to the workshop through Facepunch.net, the item never uploads, always says total bytes of 0 have been uploaded, and immediately exits the upload. The error message is "Error creating file: OK (\<string of numbers\>)". In the workshop, a new file with 0 bytes is created.

At first I thought this was due to the steam cloud settings being set to 0, or the file transfer settings being incorrect, but I have fixed and published these things and it had no effect.  Looking at the source, it's almost like Steam is now returning an acknowledgement "OK" in the error message field where before it would not fill the error message? Just a guess.

EDIT: if this is relevant I'm running 32 bit.

**Comment by Blecki** [comment]
Here I am, working on the same exact project (DwarfCorp), having the problem... and I find this issue.

**Comment by Blecki** [comment]
Here's a potential solution -

First: Pass the App id when creating the workshop item. 

          var item = Client.Workshop.CreateItem(AppID);

Second: The Error text contains a message and the number of errors. So you pretty much have to parse it and see if it says there are 0 errors.

**Comment by Blecki** [comment]
Alright that only works in the debugger, because this is a race condition. It works if I sleep at least one second between calls to Client.Update.
