### ISSUE TITLE
32bit Lobbies are broken

### ISSUE THREAD

**Issue by CrimsonCastel** [Facepunch/Facepunch.Steamworks#156]
Everything works perfectly in 64bit but many of our customers are trying to buy the game with a 32bit PC.

So I have built a 32bit version and everything except facepunch is working fine, when facepunch tries to access the lobby data after creating a lobby I get a null reference exception when trying to access Lobby.CurrentLobbyData

The rest of the API seems to be working.

I do get a **false** when I get the callback from steamClient.Lobby.OnLobbyCreated += delegate(bool in_Success)

Apparently this is known issue : https://github.com/Facepunch/Facepunch.Steamworks/issues/143
Are there any workarounds?

**Comment by SergioDelValle** [comment]
Something seems wonky with the 32 bit version. Leaderboards have the same problem but avatar, and usernames are working fine. 

I published a game back in january and have been working fine until recently so I believe a change in Steam have broken the implementation of some features in 32bits.

**Comment by Danthekilla** [comment]
Just wondering if anyone on the project has had a chance to look into this?

**Comment by SergioDelValle** [comment]
No idea... Did steam ever answer back?
