### ISSUE TITLE
EntryPointNotFoundException

### ISSUE THREAD

**Issue by desolator2k** [Facepunch/Facepunch.Steamworks#157]
Had no issues with the release version but upon compliling the current master branch I'm getting the follow errors:

```
EntryPointNotFoundException: SteamAPI_ISteamInventory_RequestPrices
SteamNative.Platform+Win64.ISteamInventory_RequestPrices ()
SteamNative.SteamInventory.RequestPrices (System.Action`2 CallbackFunction)
Facepunch.Steamworks.Inventory.UpdatePrices ()
Facepunch.Steamworks.Inventory..ctor (Facepunch.Steamworks.BaseSteamworks steamworks, SteamNative.SteamInventory c, Boolean server)
Facepunch.Steamworks.BaseSteamworks.SetupCommonInterfaces ()
Facepunch.Steamworks.Client..ctor (UInt32 appId)
```

**Comment by desolator2k** [comment]
I think I just needed to update the native steamapi.dlls etc. from the steam SDK. All working now.

**Comment by Roobubba** [comment]
I'm getting this error when I compile the latest version, but not when I use the unitypackaged version. Unfortunately, that version doesn't have functions in like Lobby.OpenFriendInviteOverlay(). I've tried about 3 difference versions of the steam_api dlls and nothing seems to work. Can anyone provide docs for a workaround for this?
Cheers in advance.
