### ISSUE TITLE
Just tried last version, Unity error -> EntryPointNotFoundException: SteamAPI_ISteamInventory_GetItemprice

### ISSUE THREAD

**Issue by RenNagasaki** [Facepunch/Facepunch.Steamworks#162]
Hello,
I just tried to compile the latest version cloned from here.

It compiles successfully but adding it to unity I get this error:

`EntryPointNotFoundException: SteamAPI_ISteamInventory_GetItemPrice
SteamNative.Platform+Win64.ISteamInventory_GetItemPrice (Int32 iDefinition, System.UInt64& pPrice)
SteamNative.SteamInventory.GetItemPrice (SteamItemDef_t iDefinition, System.UInt64& pPrice)
Facepunch.Steamworks.Inventory+Definition.UpdatePrice ()
Facepunch.Steamworks.Inventory+Definition..ctor (Facepunch.Steamworks.Inventory i, Int32 id)
Facepunch.Steamworks.Inventory.CreateDefinition (Int32 id)
Facepunch.Steamworks.Inventory.<LoadDefinitions>b__15_0 (SteamItemDef_t x)
System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[SteamNative.SteamItemDef_t,Facepunch.Steamworks.Inventory+Definition].MoveNext ()
System.Collections.Generic.List`1[Facepunch.Steamworks.Inventory+Definition].AddEnumerable (IEnumerable`1 enumerable) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:128)
System.Collections.Generic.List`1[Facepunch.Steamworks.Inventory+Definition]..ctor (IEnumerable`1 collection) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:65)
System.Linq.Enumerable.ToArray[Definition] (IEnumerable`1 source)
Facepunch.Steamworks.Inventory.LoadDefinitions ()
Facepunch.Steamworks.Inventory..ctor (Facepunch.Steamworks.BaseSteamworks steamworks, SteamNative.SteamInventory c, Boolean server)
Facepunch.Steamworks.BaseSteamworks.SetupCommonInterfaces ()
Facepunch.Steamworks.Client..ctor (UInt32 appId)
SteamClient.Connect () (at Assets/C#/Networking/SteamClient.cs:64)
SteamClient.Start () (at Assets/C#/Networking/SteamClient.cs:25)`

Greetings,
RenNagasaki

**Comment by mklingen** [comment]
#157 is a duplicate. I think you have to get the latest steam_api.dll from valve to fix this.

**Comment by RenNagasaki** [comment]
Ahh, thank you :)
