### ISSUE TITLE
Design-issue causing crashes during instancing Client

### ISSUE THREAD

**Issue by LennardF1989** [Facepunch/Facepunch.Steamworks#163]
Hello!

At first, great library. Works like a charm with indeed a proper C#-feel to it. 

I've run into an issue where I was trying to get the library to run with Mac and Linux (standalone FNA-based game).

Consider the following code:
```
try
{
    Client client = new Client(Constants.STEAM_APPID);

    if (!client.IsValid)
    {
        throw new Exception("Invalid Steam-client");
    }

    Debug.Success("Successfully loaded Steamworks, welcome {0}!", client.Username);
}
catch (Exception)
{
    Debug.Warning("Failed to load Steamworks, falling back to non-Steam version.");
}
```

I though I had it all covered with this: If Steam fails to load for whatever reason, we grab the exception and handle it accordingly. Perfect! 

However, a mistake is easily made and I at some point misplaced the `libsteam_api.dylib` (or corrupted, by whatever means). This obviously causes the `new Client` to throw an exception, but we got that covered right?

NOPE! Here's the problem. In order to check whether or not Steam is loaded I followed the internal design of doing 
`if(Client.Instance != null) { //do stuff }`, when I want to hand out an achievement in my AchievementManager. However, because of the point where the exception happened earlier, `Client.Instance` is not actually set back to `null`! So the if-check is no longer valid, and obviously, my game started crashing when I tried to hand out achievements because it thinks we got a valid client.

In this case, the solution would be to allow us to either reset `Instance` to `null` if we know something went wrong, eg.by means of a `Client.Reset()`. 

For now, I have to keep my own reference to Client around somewhere and not rely on `Client.Instance`, or hack the change above into the source.

**Comment by LoneDev6** [comment]
That's what I do:

```
public Client client { get { return Client.Instance; } }
 IEnumerator Start()
    {
        Config.ForUnity(Application.platform.ToString());
        new Client(gameId);
        // Wait for client to start up
        while (Client.Instance == null)
        {
            print("STEAM: client NOT initialized");
            yield return null;
        }
        print("STEAM: client INITIALIZED");
}
void Update()
    {
        if (Client.Instance != null)
        {
            // This needs to be called in Update for the library to properly function
            Client.Instance.Update();
        }
    }

```

**Comment by LennardF1989** [comment]
@LoneDev6 The point is that it doesn't work depending on when an exception occurs ;) 

> However, because of the point where the exception happened earlier, Client.Instance is not actually set back to null! So the if-check is no longer valid...

**Comment by igniuss** [comment]
That's weird, Client should turn null if the [initialization failed](https://github.com/Facepunch/Facepunch.Steamworks/blob/7b7cfa29c4b4bfa2128e17f6ea7a7984d4aebaa8/Facepunch.Steamworks/Client.cs#L79). You can call Dispose on the Client in your case, which'll [set the instance null](https://github.com/Facepunch/Facepunch.Steamworks/blob/7b7cfa29c4b4bfa2128e17f6ea7a7984d4aebaa8/Facepunch.Steamworks/Client.cs#L228)

**Comment by LennardF1989** [comment]
@igniuss I'm not quite sure how I missed the `Instance = null;` in the `Dispose` at the time. It's been there for a while according to the git blame :P
