### ISSUE TITLE
Client.IsValid is frequently (but not always) false

### ISSUE THREAD

**Issue by otrain13** [Facepunch/Facepunch.Steamworks#168]
Hello,

Thank you for creating Facepunch.Steamworks! It's been very helpful. However, we've had an ongoing issue that I thought might just be related to my machine, or just when running in the Unity editor, but we are now seeing on testers machines as well.

Quite often, during initialization:

```
client = new Facepunch.Steamworks.Client(appID);
if (!client.IsValid)
{
	Debug.LogWarning("Error initializing Steam!");
	return false;
}
```

client.IsValid will return false. Sometimes it returns true and the whole SDK works as expected (leaderboards and achievements all work as expected). But quite often, IsValid is false. It varies from day to day, from run to run. I always have my steam client running. Sometimes if I quit the client and relaunch it with the developer console active, then the next time I run the game the client IsValid will return true.

I thought this might have just been an issue with my machine, but we've started doing external testing and we're seeing about 75% of our users failing to initialize the framework and be able to submit scores. These testers are running a build we distribute through the Steam client.

This morning I downloaded your Unity test project and ran it, and it also fails to initialize for me today.

Has anyone else had this problem? Does anyone have any suggestions? :)

Thanks!
Owen

**Comment by dylanh724** [comment]
@SurDno + @otrain13 how did you fix this, in the end?

**Comment by SurDno** [comment]
@otrain13, any news?

**Comment by SurDno** [comment]
This guy got no GH activity since opening this issue. :(

**Comment by Deusald** [comment]
@SurDno I discovered that probably it happens if the wrong steam_api.dll is loaded. It's happening on 32bit system and in logs it says that game is using steam_api64.dll I'm not 100% sure. When the person with 32bit system will run the tests I will know for sure ;)

**Comment by SurDno** [comment]
Thanks! Any clue after 5 months with no solution. I’ll look into it.

**Comment by amigax** [comment]
Just finding this now, isValid suddenly becomes false in my unity game, any ideas?

**Comment by Nezio** [comment]
This should be re-opened.
Happens quite often for me.
