### ISSUE TITLE
Project doesn't build under Unity

### ISSUE THREAD

**Issue by zorbathut** [Facepunch/Facepunch.Steamworks#17]
I'm trying to integrate the library directly into Unity, not as a standalone .dll, to make debugging and modifications easier. Unfortunately it relies (in a very loose sense) on some syntactic sugar features that are part of .NET 6.0.

Would the project maintainers be okay with stripping these out and bringing the project to a state where it can be embedded directly in a Unity project?

Note that, if you're okay with the idea but don't want to spend the time yourself, I'm happy to do it for you and send a pull request. I just don't want to go forking the project if it's something unwanted.

**Comment by garrynewman** [comment]
I'd rather not to be honest. This isn't a project meant purely for Unity, and unity's c# version will catch up eventually.

**Comment by bddckr** [comment]
I agree with @garrynewman here: Unity 2017.1 will (and does already in beta) support .NET 4.6. and C# 6.

**Comment by zorbathut** [comment]
Alright, I'll revisit this project then!
