### ISSUE TITLE
Am i doing this right server doesn't get listed!

### ISSUE THREAD

**Issue by V-ZINC** [Facepunch/Facepunch.Steamworks#171]
Hey guys
Im new to this Facepunch.steamworks thing but have gathered some understanding by looking through the wiki and scripts and ended up with this server script:

`using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Facepunch.Steamworks;

public class Server : MonoBehaviour
{
    public void StartServer()
    {
        //Creates a bunch of options when starting server
        Facepunch.Steamworks.ServerInit options = new Facepunch.Steamworks.ServerInit("gamedir", "SuckMyNuts");
        options.SteamPort = 7778;
        options.QueryPort = 7779;
        options.GamePort = 7777;
        options.VersionString = "1.0";

        //Start server for app id and with options set beffore 
        var server = new Facepunch.Steamworks.Server(480, options);
        server.LogOnAnonymous();

        //Set even more settings
        server.ServerName = "Test Server";
        server.MaxPlayers = 100;
        server.Passworded = false;
        server.DedicatedServer = true;

        if (server.LoggedOn)
        {
            Debug.Log("Server Started");
        }
    }
}`

and this server list code:
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Linq;
using UnityEngine.UI;

public class ServerList : MonoBehaviour
{
    public List<ServerListClass> Servers = new List<ServerListClass>();
    [SerializeField] private GameObject ListObject;
    [SerializeField] private GameObject ListParent;

    public void InternetList()
    {
        using (var client = new Facepunch.Steamworks.Client(480))
        {
            var filter = new Facepunch.Steamworks.ServerList.Filter();
            filter.Add("appid", client.AppId.ToString());
            filter.Add("gamedir", "game");
            filter.Add("secure", "1");

            var query = client.ServerList.Internet(filter);

            for (int i = 0; i < 1000; i++)
            {
                client.Update();
                System.Threading.Thread.Sleep(100);

                if (query.Finished)
                    break;
            }

            foreach (var server in query.Responded.Take(20))
            {
                ServerListClass NewServer = new ServerListClass();
                NewServer.name = server.Name;
                NewServer.ip = Facepunch.Steamworks.Utility.IpToInt32(server.Address);
                NewServer.players = server.Players;
                NewServer.ping = server.Ping;
            }

            query.Dispose();

            for (int i = 0; i < 100; i++)
            {
                client.Update();
                System.Threading.Thread.Sleep(1);
            }
        }

        foreach (var S in Servers)
        {
            GameObject New = Instantiate(ListObject);
            New.transform.FindChild("txtServerName").GetComponent<Text>().text = S.name;
            New.transform.FindChild("txtPlayers").GetComponent<Text>().text = S.players.ToString();
            New.transform.FindChild("txtPing").GetComponent<Text>().text = S.ping.ToString();
        }
    }
}

[System.Serializable]
public class ServerListClass
{
    public string name;
    public uint ip;
    public int players;
    public int ping;

}`

my problem is nothing happens.
btw just in case u ask i have a client active

**Comment by V-ZINC** [comment]
All gods i fixed her up

**Comment by kkohno** [comment]
how do you fix it? I do same steps? but i have my server in Unresponsive list...

**Comment by V-ZINC** [comment]
You have to dmz you computer, if you dont know how to search it up. i found a quick tutorial and it worked. hope this helps

**Comment by JamieShelley** [comment]
> dmz you computer

This didn't work for me :(
