### ISSUE TITLE
[Feature Request] GetNumberOfCurrentPlayers()

### ISSUE THREAD

**Issue by thversfelt** [Facepunch/Facepunch.Steamworks#175]
First of all, awesome work on this Steamworks wrapper. 

I would really like a way to get the number of players currently playing my game (online + offline). It would be used in-game to inform players about how many other players are currently also playing.

Thanks! ;)

**Comment by SurDno** [comment]
That should already be in Facepunch.Steamworks since Rust Legacy (which used Facepunch.Steamworks) displayed that.

**Comment by dylanh724** [comment]
Hmm, I was looking for this same call. @trdwll , I believe that's for # of players currently inside a Server rather than # of players playing the game (`GetNumberOfCurrentPlayers()` from steamworks.net)

**Comment by igniuss** [comment]
Added [and sent pull request](https://github.com/Facepunch/Facepunch.Steamworks/pull/228) 👍 thought it was a decent idea, and was simple enough to add anyways. 

Not sure how accurate the call is from steam though, from my testing it seems like this number is the same as the steamdb graph number.
