### ISSUE TITLE
Connecting client to server

### ISSUE THREAD

**Issue by Edsparr** [Facepunch/Facepunch.Steamworks#179]
Hi! I've been looking through this dank rapper for a couple of Days and started making networking for my game in this. But something my Little brain didn't can't seem to figure out is how to actually send the AuthTicket to the server to start the session. And. Does the server have a "steamID" that the clients can send to. How can I accsses this steamID?

Thanks in advance!

**Comment by V-ZINC** [comment]
yo @Edsparr did you get the auth to work? I have access to the steam id but when i call start session the call back does not get fired
