### ISSUE TITLE
Steam Client Crashes with access violation in Unity Build

### ISSUE THREAD

**Issue by ArendPeter** [Facepunch/Facepunch.Steamworks#18]
I've implemented achievements in my game and it works fine in the editor however when I build the game and run it, the game crashes. Here's the logs that were generated

error.log
https://pastebin.com/reYGKhHv
output_log.txt
https://pastebin.com/hj9YS5cU

I think the core error from the log is here
`steamclient.dll caused an Access Violation (0xc0000005)
  in module steamclient.dll at 0023:386b34da.`

I tried multiple builds where I commented out pieces of code and I found that the following line caused the error
`SteamClient = new Client( ...... ); //went ahead and dotted out our app id`

Any idea what I could do differently?

**Comment by garrynewman** [comment]
These hard crashes usually happen when the steam_api dlls it's loading are mismatched, or the steam install is corrupt/not up to date.

Which version of FP.Steamworks are you using? Which version steamworks dlls do you have?

**Comment by BagheeraThePanther** [comment]
I'm using steamworks v1.40, and I'm using the plugin that you built in the getachievement/ setachievement issue thread. I'll go through and recopy the v1.40 files over, it's possible that I missed a file somewhere. The process of updating should just be to replace the following files right?

libsteam_api.dylib
steam_api.dll
steam_api64.dll
steam_appid.txt

**Comment by ArendPeter** [comment]
I'm using steamworks v1.40, and I'm using the plugin that you built in the getachievement/ setachievement issue thread. I'll go through and recopy the v1.40 files over, it's possible that I missed a file somewhere. The process of updating should just be to replace the following files right?

libsteam_api.dylib
steam_api.dll
steam_api64.dll
steam_appid.txt

**Comment by speedis** [comment]
@ArendPeter If you download the latest files from https://github.com/Facepunch/Facepunch.Steamworks.Unity then it should work. It contains the latest version of Facepunch.Steamworks as well as the latest steamworks sdk.

**Comment by ArendPeter** [comment]
Awesome thanks, I ended up managing to update the files manually, turns out I missed one of them last time I tried
