### ISSUE TITLE
Not a strong programmer, I need some idiot proof help for some very basic questions.

### ISSUE THREAD

**Issue by byolivierb** [Facepunch/Facepunch.Steamworks#184]
Hi, first off I'm french so sorry if my english is messy.

I'm very much a learning developer. I made a free game using Unity that is already available on itch.io and wanted to see if I could try to release it on Steam just to learn the process. The game will be free there too anyway. While I had no issues learning how to use butler for itch, the steam documentation and steamworks implementation is way beyond my level. It assumes a certain knowledge of programming that I don't have and every tutorials and information I've found by googling around is very much the same. 

So I've decided to use Facepunch.Steamworks, but even then I hit a wall very quickly. For the record, I've used this blog post to guide me: [http://gamasutra.com/blogs/KyleKukshtel/20170817/303919/A_Gentle_Introduction_To_Steamworks.php](url)

I might be a dummy, but even then I get stuck up really quickly. I started with my windows build (I have also a mac build working, but I'd like to understand the basic first before getting there). I have copied the Facepunch.Steamworks files as it is shown in the blog post and created a steam_appid.txt file (I'm still using 480 there, but I have an ID ready for later).

The blog post then says to have that code:

using System;
using UnityEngine;
using System.Collections;
using System.Linq;
using Facepunch.Steamworks;

```
public class SteamTest : MonoBehaviour 
{
    void Start ()
    {
        // Don't destroy this when loading new scenes
        DontDestroyOnLoad( gameObject );

        // Configure for Unity
        // This is VERY important - call this before doing anything
        Facepunch.Steamworks.Config.ForUnity( Application.platform.ToString() );

        // Create the steam client using the test AppID (or your own AppID eventually)
        new Facepunch.Steamworks.Client( 480 );

        // Make sure we started up okay
        if ( Client.Instance == null )
        {
                Debug.LogError( "Error starting Steam!" );
                return;
        }
        
        // Print out some basic information
        Debug.Log("My Steam ID: " + Client.Instance.SteamId);
        Debug.Log("My Steam Username: " + Client.Instance.Username );
        Debug.Log("My Friend Count: " + Client.Instance.Friends.AllFriends.Count() );
    }

    private void OnDestroy()
    {
        if ( Client.Instance != null )
        {
                // Properly get rid of the client if this object is destroyed
                Client.Instance.Dispose();
        }

    }


    void Update()
    {
        if ( Client.Instance != null )
        {
                // This needs to be called in Update for the library to properly function
                Client.Instance.Update();
        }

    }
}
```

I attached that script to a new empty object in the first scene of my game (the blog post is not clear where it should be, but it just make sense to put it on its own object at the beginning, right?).

When I launch my game I get an "Error Starting Steam" error. I've tried with my own ID or with the 480 ID with no success. Searching for that particular error it just seems people were using the wrong ID.

I'm logged into Steam on my computer, dunno if I should log somewhere else or if that change anything. My theory is that maybe I didn't understand where to put the steam_api.dll, steam_api64.dll and steam_appid.txt files? Right now they're at the highest folder available in my game, beside the assets, library, Project Settings, etc. folders.

What am I doing wrong. What do I don't understand. If you have a better tutorial than this blog post, I'd be happy to use it instead. Assume that I don't know very much about programming, I'm very much learning here.

Thank you for your help.

**Comment by byolivierb** [comment]
Just a quick update:

Using steamworks.net I managed to get steam to identify me as playing the game with no isssue (using the 480 appID). I'll continue working on a version using steamworks.net but I'd still like to have an answer on my issue here, as I don't understand why it's happening and the Facepunch package otherwise seems very easy to use.

**Comment by byolivierb** [comment]
@igniuss 
This works! Thanks you so much, it also helped me understand why the code I used above wasn't working (in the code you made, the AppId is public variable that you set up from the editor, this part wasn't in my code at all).

**Comment by igniuss** [comment]
The public part shouldn't actually matter 😅 it's where the dll's are all located

**Comment by byolivierb** [comment]
No ahah, it would work as a private too, but my first code didn't seem to inititate that part properly.
