### ISSUE TITLE
Lobby callbacks only invoked on first run

### ISSUE THREAD

**Issue by rewinded** [Facepunch/Facepunch.Steamworks#187]
Certain callbacks, namely OnLobbyMemberDataUpdated, are only invoked the first run of the program after starting Steam and Unity. After this initial run I have to restart both Steam and Unity again for the callbacks to work, I've been stuck on this issue for almost a month and only recently figured out this "fix". 

I'm not sure if this is a known issue or not but I couldn't find anyone reporting similar issues and it makes testing lobbies very tedious so I'd like to know if it's my fault or fp.steamworks.

**Comment by andgeno** [comment]
I have a similar problem. I'm using the OnAnyCallback to log everything that's happening with Steamworks and I noticed that it completely stops receiving events after the first run in the Unity Editor. I only have to restart Unity to make things work one more time again. After starting fresh and doing one Play Mode run receiving future events will stop working again.

**Comment by rewinded** [comment]
I was able to fix the issue by building the library from 4381272 (which was at the time the latest commit), I have not yet tried building from the current latest commit (7d66fc9).
