### ISSUE TITLE
Need help implementing achievements

### ISSUE THREAD

**Issue by byolivierb** [Facepunch/Facepunch.Steamworks#188]
Hi !

I'm still a bumbling programmer so again (this is the second time I'm asking for help here) I'm sorry if these are obvious questions.

I'm trying to implement some very simple achievements. My game is a point&click, so I don't need to track kills or stuff like that, I only need to trigger achievements upon entering certain scenes. What I thought would be to create an object in those rooms with an achievement script that would simply trigger on Awake().

While searching, I have found this code [here]https://github.com/Facepunch/Facepunch.Steamworks/issues/100(url)

```

public void TriggerAchievement(string achievementId)

    {

        if(SteamClient != null)

        {

            SteamClient.Achievements.Trigger(achievementId);

            SteamClient.Stats.StoreStats();

        }

    }

```

With this, I get the "SteamClient is type, which is not valid in the given context" error. While I understand what that error means, I'm not sure how I can fix it. What I need here is to basically check if the player is connected to Steam properly.

On the other hand, using the Achievement.cs code in Facepunch, I get a ton of "Feature 'null propagating operator' is not available in C# 4. Please use language version 6 or greater." errors. What I gather from that is that I should update Unity (I'm running 2017.3.1f1 personal), but this creates multiples issues with my game and I'd like to avoid that unless it's abolutely necessary (which it might be). The code in Facepunch also seems much more complicated than what I actually need if that makes sense, so I was hoping for a simpler solution.

My achievements are already set on steamworks and I have the IDs and all, so that I'm ok with. I'm just not great with the scripting.

If you can direct me to anything that could help me, it would be very much appreciated. Thank you.

**Comment by clansfear** [comment]
Have you resolved the problem by now?

**Comment by byolivierb** [comment]
> Have you resolved the problem by now?

Not with Facepunch no.

I manage to make it work using Steamworks.net, so that works for me, but I have no solution using Facepunch.

**Comment by Ayfel** [comment]
There is a class Called SteamClient.cs in the unity implementation that creates a client for you "client = new Facepunch.Steamworks.Client( AppId );" having this created the client (singleton) is accesible from anywhere in your code by simply writing Client.Instance (instead of writing SteamClient in your code above), remember to put at the top of your script "using Facepunch.Steamworks;"

**Comment by kaisametrine** [comment]
> > Have you resolved the problem by now?
> 
> Not with Facepunch no.
> 
> I manage to make it work using Steamworks.net, so that works for me, but I have no solution using Facepunch.

Hey! Could you please share your achievements code, I am new to programming and I can not make them work

**Comment by igniuss** [comment]
If you're running unity, this *should* do the trick (untested) 
```csharp
public class AchievementManager : Monobehaviour {
    const uint appId = 480;
    public void Start() {
        if(Facepunch.Steamworks.Client.Instance == null) {
            var client = new Facepunch.Steamworks.Client(appId); //Start up a client. This will set itself to Client.Instance
        }
    }
    public void Update() {
        if (Facepunch.Steamworks.Client.Instance != null) {
            Facepunch.Steamworks.Client.Instance.Update();
        }
    }
    public void TriggerAchievement(string id) {
        if(Facepunch.Steamworks.Client.Instance != null) {
            Facepunch.Steamworks.Client.Instance.Achievements.Trigger(id, true); //the true makes it so you don't need to call Achievements.StoreStats(); 
        }
    }
    public void OnDestroy() {
        Facepunch.Steamworks.Client.Instance.Dispose();
    }
}
```

**Comment by kaisametrine** [comment]
> If you're running unity, this _should_ do the trick (untested)
> 
> ```cs
> public class AchievementManager : Monobehaviour {
>     const uint appId = 480;
>     public void Start() {
>         if(Facepunch.Steamworks.Client.Instance == null) {
>             var client = new Facepunch.Steamworks.Client(appId); //Start up a client. This will set itself to Client.Instance
>         }
>     }
>     public void Update() {
>         if (Facepunch.Steamworks.Client.Instance != null) {
>             Facepunch.Steamworks.Client.Instance.Update();
>         }
>     }
>     public void TriggerAchievement(string id) {
>         if(Facepunch.Steamworks.Client.Instance != null) {
>             Facepunch.Steamworks.Client.Instance.Achievements.Trigger(id, true); //the true makes it so you don't need to call Achievements.StoreStats(); 
>         }
>     }
>     public void OnDestroy() {
>         if(Facepunch.Steamworks.Client.Instance != null) {
>             Facepunch.Steamworks.Client.Instance.Dispose();
>         }
>     }
> }
> ```

Shouldn't there be a condition which unlocks the achievement?

**Comment by igniuss** [comment]
You call `TriggerAchievement("my_achievement_id");` on another script to trigger it @kaisametrine
