### ISSUE TITLE
Steam Achievement updates only during exit instead of after Trigger

### ISSUE THREAD

**Issue by wraithseeker** [Facepunch/Facepunch.Steamworks#19]
I'm having an issue with Steam Achievements only updating after the game exits instead of updating when I call `SteamClient.Achievements.Trigger(some_string)`.

I am calling `SteamClient.Update ();` in Update as well.

I'm using the Facepunch.Steamworks dll in this [thread](https://github.com/Facepunch/Facepunch.Steamworks/issues/16) and my steam sdk version is 1.4.0

**Comment by garrynewman** [comment]
Hmm, does the steam overlay work in your game?

**Comment by wraithseeker** [comment]
Yes

**Comment by wraithseeker** [comment]
Yes. I checked again and I think I phrased the question wrongly. The steam achievements are earned after a few seconds, but the achievement popup does not appear in the game

**Comment by garrynewman** [comment]
👍
