### ISSUE TITLE
What does min max value do when fetching friends/user score?

### ISSUE THREAD

**Issue by TianheTHGame** [Facepunch/Facepunch.Steamworks#191]
I know when fetch global score, min max means a range of rank to get results, so i set it to 0, 0, no results, ok. 

but when i use Leaderboard.RequestType.GlobalAroundUser or .Friends
it give a results no matter how i set the min max value(leaderboard only have one user)....this just so weird, i'm not sure how to use it, and obviously i can't test it right now.

sorry for my bad english.

**Comment by LoneDev6** [comment]
Can you should your code and a screenshot of the bug?

**Comment by TianheTHGame** [comment]
![qq 20180904215206](https://user-images.githubusercontent.com/42908109/45035648-0e348380-b08d-11e8-9017-dd45057274ba.jpg)
![qq 20180904214935](https://user-images.githubusercontent.com/42908109/45035694-2f956f80-b08d-11e8-9844-d6b4f804f027.jpg)
![qq 20180904215006](https://user-images.githubusercontent.com/42908109/45035722-3c19c800-b08d-11e8-9efa-b1c705fe4e8c.jpg)
![qq 20180904215031](https://user-images.githubusercontent.com/42908109/45035732-420fa900-b08d-11e8-95ee-25f9040b7779.jpg)
![qq 20180904214852](https://user-images.githubusercontent.com/42908109/45035748-4936b700-b08d-11e8-860d-7c1760a4b3ab.jpg)

**Comment by TianheTHGame** [comment]
![qq 20180904220303](https://user-images.githubusercontent.com/42908109/45036266-9ff0c080-b08e-11e8-99e5-b448777e29e6.jpg)
even with this value, debug results still the same. wth???

**Comment by LoneDev6** [comment]
leaderboard.FetchScores(currentType, 0, int.MaxValue - 1);

By the way remember that you need to wait for leaderboard to be != null before accessing leaderboard.Results

You should take a look at Facepunch examples: https://github.com/Facepunch/Facepunch.Steamworks.Unity/blob/master/Assets/Scripts/SteamTest.cs

**Comment by TianheTHGame** [comment]
thanks...but still not answer my main question, the min max value clearly not getting same value when not fetch global score, this is what bother me, i need to know exactly why this happen.

i'm guessing..... is this some kind of auto correction?? like the api find out your given range not include player in it, or just ignore the value, and return a results with player in it if player exists in leaderboard? this could cause the return length always 1.(leaderboard only have one user)
