### ISSUE TITLE
Should I use the release version 0.7

### ISSUE THREAD

**Issue by Lestat** [Facepunch/Facepunch.Steamworks#193]
or download the repo :)

**Comment by reignofdave** [comment]
@Lestat I am using the repo directly and it seems pretty stable so far.
Just make sure you update steamworks to v1.42

**Comment by Lestat** [comment]
arent the steamworks already added in the repo? (I just copy the files to the root folder)

**Comment by reignofdave** [comment]
They are but i got an error that was resolved by updating the steamworks api

**Comment by jschlechte** [comment]
@reignofdave do you recall the prerequisites for compiling this? It sounds like you're using the source directly, so I figured you may know.

When opening the solution in vs5015, I get an error message:

```
The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.		
```

There seems to be no documentation on building from source, nor does it appear that the repository is regularly built/released.
