### ISSUE TITLE
Callbacks aren't being called. Anything I'm missing.

### ISSUE THREAD

**Issue by Lestat** [Facepunch/Facepunch.Steamworks#194]
I have these callbacks (added in start method Unity):

```
Client.Instance.Lobby.OnLobbyJoined += OnLobbyJoinedCallback;
Client.Instance.Lobby.OnLobbyCreated += OnLobbyCreatedCallback;
Client.Instance.Lobby.OnLobbyMemberDataUpdated += OnLobbyMemberDataUpdatedCallback;
Client.Instance.LobbyList.OnLobbiesUpdated += OnLobbiesUpdatedCallback;
```

None of them are being called, for example when I create a lobby.

```
if (Client.Instance!=null){
	Client.Instance.Lobby.Create(Facepunch.Steamworks.Lobby.Type.Public, 10);
}
```

```
void OnLobbyCreatedCallback(bool success){
    Debug.Log("Lobby Created Callback");
    if(success){
        Debug.Log("Lobby Created. Owner= "+Client.Instance.Lobby.Owner);
    }
}
```

I'm  also Updating every frame.

Anything I'm missing? I copied the files to the project root, changed the appid to 480 to test in both the file and when creating the client.

**Comment by Lestat** [comment]
I copied the files from the unity test repo, and restarted unity, now callbacks work :)

probably I only needed to restart, but oh well, now it works :D

**Comment by rewinded** [comment]
does OnLobbyMemberDataUpdated work consistently for you? 

I've been having issues with it in my project but the issue (https://github.com/Facepunch/Facepunch.Steamworks/issues/187) I submitted a while ago hasn't been answered. It works fine in a test project which makes me think it could be my fault, I'm just interested to see whether you've experienced any similar issues :)

**Comment by Lestat** [comment]
actually, just came here to comment , that and OnLobbyMemberDataUpdated dont work at all with me :/
they aren't called.

**Comment by rewinded** [comment]
I built from the latest master and am still having the same issue, let me know if you find a solution bc this has made testing really tedious and I dont have a work around yet

**Comment by Entevily** [comment]
> It seems they work until an exception is thrown, then they stop working until you restart unity

I agree. This seems to be the case for me. When I run everything in Unity, all the Callbacks work fine. Then I get an error, just once. Then it doesn't work until I completely reset Unity. Kind of a pain to restart unity just to let Callbacks come back in. Strange that it always Initializes with steam though.
