### ISSUE TITLE
Voice chat isn´t working

### ISSUE THREAD

**Issue by Anny2412** [Facepunch/Facepunch.Steamworks#195]
I could not figure out, how the voice chat works. The documentation is not really helping me out..
I´ve implemented the script from the test repo in Unity.
On my tests, the OnCompressed and OnUncompressed functions are responsing when i speak to the microphone, but how can i convert the buffer to an audio file and how can i send and receive those voice messages to/from lobbymembers? I really hope someone can help me out..

This script is giving me only some weird beep noises, when i speak to the microphone..

```
Client.Instance.Voice.OnCompressedData = (buffer, length) =>
{
    Client.Instance.Voice.WantsRecording = true;

     float[] floatArray = ToFloatArray(buffer);
     AudioClip audioClip = AudioClip.Create("VoiceSound", floatArray.Length, 1, 44100, false);
     audioClip.SetData(floatArray, 0);
     audioSource.clip = audioClip;
     audioSource.Play();
};

// Used to convert the byte array to float array for the audio clip
    public float[] ToFloatArray(byte[] byteArray)
    {
        int len = byteArray.Length / 4;
        float[] floatArray = new float[len];
        for (int i = 0; i < byteArray.Length; i += 4)
        {
            floatArray[i / 4] = BitConverter.ToSingle(byteArray, i);
        }
        return floatArray;
    }
```

**Comment by Anny2412** [comment]
Thank you very much nidaynere it works in the OnUncompressed function :)

My very last question: 
How can I send and receive those voice messages from the lobby members? Do I have to send them through P2P (like in NetworkingTest), or is there a special function for that?

**Comment by nidaynere** [comment]
https://github.com/nidaynere/snet-steam-p2p-multiplayer-shooter/blob/master/Assets/Scripts/SNet/SNet_Voice.cs

I didn't know any special function about it. I used P2P networking to send the byte array.
It's a networked voice script but it's connected with the other scripts so you may need to pick to pieces.
