### ISSUE TITLE
Unit Tests Failing

### ISSUE THREAD

**Issue by RebornRider** [Facepunch/Facepunch.Steamworks#2]
In a new clone of the project, **most unit tests are failing**. The two **successful** tests are:
- Server/Init
- Server/StatsGet

After some debugging I found the bug inside the **InitClient()** method of Facepunch.Steamworks.Interop.**NativeInterface**.

Inside of this method the calls to Valve.Interop.NativeEntrypoints.Extended.**SteamAPI_GetHSteamUser**() and Valve.Interop.NativeEntrypoints.Extended.**SteamAPI_GetHSteamPipe**() both **return zero**.

That triggers the `if ( pipe == 0 ) return false;` guard clause which prevents client initialization.

**Comment by garrynewman** [comment]
You need to have Steam open, and possibly need to own Rust for the sakes of the tests.

**Comment by RebornRider** [comment]
I installed rust, restarted steam, restarted my laptop made sure steam is connected to the internet and still all but two tests are failing. I

**Comment by garrynewman** [comment]
That''s odd. Do you have all the same settings here?

![](http://files.facepunch.com/garry/12c49/a7f14afb.png)

**Comment by RebornRider** [comment]
I have the same settings. I ran the tests with the Visual Studio Test Explorer, as well as the Resharper Test Runner and they fail with both runners.

**Comment by garrynewman** [comment]
I'm stumped.

**Comment by RebornRider** [comment]
As far as I can tell every test that relies on Valve.Steamworks.SteamAPIInterop.SteamAPI_Init() fails. The 2 Server test are successful, because they only rely on Valve.Interop.NativeEntrypoints.Extended.SteamInternal_GameServer_Init() which doesn't call SteamAPI_Init().
I can't debug this further because the Valve.Steamworks.SteamAPIInterop.SteamAPI_Init() fails somewhere inside the FacepunchSteamworksApi.dll extern call.

**Comment by garrynewman** [comment]
What version of visual studio are you using?

**Comment by RebornRider** [comment]
Visual Studio 2015 Community Edition Update 3

**Comment by garrynewman** [comment]
Anyone else having these issues?

**Comment by Selkcip** [comment]
I was having this issue today. Turns out I set Steam to always run as admin because it complains about needing it to install a service every time. When I run VS as admin most of the tests that were failing due to SteamAPI_Init pass. In this case Unity also needs to be run as admin.
