### ISSUE TITLE
Callback for microtransactions?

### ISSUE THREAD

**Issue by speedis** [Facepunch/Facepunch.Steamworks#20]
Thanks for the great work, it has simplified things a lot!

Is there an example on how to use the MicroTxnAuthorizationResponse_t callback?
I am looking to add microtransactions, and the client needs to register when their transaction has succeeded so it can send the information to the purchase server for verification.

**Comment by speedis** [comment]
Could you please help with this @garrynewman ?

I can see that MicroTxnAuthorizationResponse_t is referenced here at least:
Facepunch.Steamworks/SteamNative/SteamNative.Structs.cs
Generator/steam_sdk/isteamuser.h
Generator/steam_sdk/steam_api.json
Generator/steam_sdk/steam_api_interop.cs

So, basically the Client needs to receive the MicroTxnAuthorizationResponse_t event, so it can then tell the server that it has completed its purchase.

It's documented at https://partner.steamgames.com/documentation/MicroTxn#InGamePurchasing under step 5.

**Comment by garrynewman** [comment]
Heya - I've pushed this. I haven't got the ability to test it, so maybe you can confirm whether it works or not. Should be able to do.

```
            Facepunch.Steamworks.Client.Instance.MicroTransactions.OnAuthorizationResponse += ( authorized, appId, orderId ) =>
            {
                // Handle callback
            };
```

**Comment by speedis** [comment]
I've tested it and can confirm it works great, thanks a bunch!
