### ISSUE TITLE
IAP Callback

### ISSUE THREAD

**Issue by athai1** [Facepunch/Facepunch.Steamworks#206]
Hi, I attempted to use Client.Instance.Inventory.StartPurchase(...) to bring up the in-game overlay for users to complete their IAP. From the testing, they are able to complete the transaction and have the amount deducted from their wallet. However, the problem is it doesn't callback after the transaction is completed.

    private Inventory.StartPurchaseSuccess success;

    private void PurchaseSteamItem()
    {
        success += CheckSuccess;
        Client.Instance.Inventory.StartPurchase(Client.Instance.Inventory.Definitions, success);
    }

    private void CheckSuccess(ulong orderId, ulong transactionId) //this doesn't get called at all
    {
        NotificationManager.Instance.NotificationPopup("Purchased!", "Check your wardrobe and categories!", true, true, true, true);
        GameSparksManager.Instance.RecordVirtualGoodsPurchase(GameSparksManager.steamVirtualGoods);
        Debug.Log(orderId);
        Debug.Log(transactionId);
        success -= CheckSuccess;
    }

I figured this would be pretty simple, am I doing something wrong or missing something? Client.Instance.Update() is in Update(), Client is initialized in another script.

**Comment by dylanh724** [comment]
No idea, but I saw some samples have `success` as protected scope?

**Comment by athai1** [comment]
I'll take that into consideration but not sure if that would actually affect anything. I also inquired on steamworks discussion forum: https://steamcommunity.com/groups/steamworks/discussions/0/1734342793780424525/

It could very well be a wrong parameter but currently not able to test, can't get the overlay for the purchase window to open now.

I appreciate your looking into this though!

**Comment by dylanh724** [comment]
Are you compiling with il2cpp?

**Comment by athai1** [comment]
No, I'm using mono to compile.

**Comment by athai1** [comment]
Ah, the overlay not opening seems to be inherent with my main steam account. Using a secondary and it opens without issue, so not sure about that. I'll check with both suggestions and see if callback works. 
Thanks!
