### ISSUE TITLE
FetchScores RequestType.Friends gets results without limits

### ISSUE THREAD

**Issue by Lehha95** [Facepunch/Facepunch.Steamworks#211]
` leaderBoard.FetchScores(Leaderboard.RequestType.Friends, 0, 10);`

Gets the results of more than 10 people, which causes an error.

**Comment by Lehha95** [comment]
(Leaderboard.RequestType.Global, 0, 10) works correctly

**Comment by Princesseuh** [comment]
[Per the Steamworks documentation, the start and end parameter are ignored when using the Friends request type](https://partner.steamgames.com/doc/api/ISteamUserStats#ELeaderboardDataRequest)

> Used to retrieve all leaderboard entries for friends of the current user. The start and end parameters are ignored.

It's fairly confusing even in C++(IIRC, the spacewar exemple doesn't account for this either), not sure how it should be handled in the library. The most "noob friendly" way would probably be to include the pagination in the library but that would not respect the original API.
