### ISSUE TITLE
Exiting game seems to not be recognized by steam

### ISSUE THREAD

**Issue by enigmagame** [Facepunch/Facepunch.Steamworks#213]
Hi,
I'm trying the Unity sample with the AppId 480 (Spacewar).
If I launch the game I can see from another Steam instance (for example a friend of mine) that I'm playing on Spacewar.
If I exit the game, I can yet see from another Steam instance (for example a friend of mine) that I'm playing on Spacewar until I restart Steam.
Note that the Dispose method on the Client instance is correctly called.
Any suggestion?

**Comment by joshuahaag** [comment]
If you're attaching Steam to the Unity editor Steam won't consider the game to be closed until the editor itself is closed.

If you build the game to a standalone executable it should function as expected.

**Comment by enigmagame** [comment]
I'm working in Editor and forgot to mention it.
Thanks you very much for the explanation.
