### ISSUE TITLE
Server not listed on ServerList.Internet

### ISSUE THREAD

**Issue by mickaelblondeau** [Facepunch/Facepunch.Steamworks#22]
Hello,

I started to use your wrapper to implement steamworks on my game but I have an issue with creating a steam lobby, the lobby seems correctly registred to steam (server.LoggedOn returns true) but I can't find the server, even without filters
I'm using the source from the Facepunch.Steamworks.Unity project

Here is the code of the server creation :
```c#
// SteamManager.APP_ID = 480 (same as steam_appid.txt)
// version = "0.25.0"
// SteamManager.SteamClient is instance of Client

server = new Server (SteamManager.APP_ID, 0, port, port, port, true, version);
server.LogOnAnonymous ();
server.MaxPlayers = maxPlayers;
server.ServerName = serverName ;
// some other settings & setKeys

ticket = SteamManager.SteamClient.Auth.GetAuthSessionTicket ();
if (!server.Auth.StartSession (ticket.Data, SteamManager.SteamClient.SteamId)) {
    Debug.LogWarning ("Auth failed on server creation");
}
```

Is something missing from the server creation ?

For the listing I simply use
```c#
SteamManager.SteamClient.ServerList.Internet ();
```
With or without filters

Thanks for your support

**Comment by garrynewman** [comment]
Server lists are kind of a two stage thing. First your server needs to get itself listed with Steam. You can check if that's successful by starting your server and going to:

http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001/?format=json&addr=109.95.212.35

where the address is your own ip address.

Then the server needs to be reachable by the client. Your client will download a list of ips and ports from Steam, and then try to ping them and retrieve information like player count etc. If it can't ping them it'll assume they're not up.

Reasons for not being able to ping would usually be firewall related. But if you're hosting and checking on the same computer you can rule that out.

From your code it looks like you might be using the same port for the game connection port, the server query port and the steam connection. This would probably cause issues (and I should maybe put an assert there). 

I would try changing the steam port to port+1 to see if that fixes it. It's okay for the game and query port to be the same as long as your game is udp (query is tcp).

**Comment by mickaelblondeau** [comment]
Thanks for your quick response

Seems my server is not listed on the API

```json
{
	"response": {
		"success": true,
		"servers": [
		]
	}
}
```

I tested with 3 different ports (correctly routed on both TCP & UDP) for game, steam & query
7777, 7778 and 7779 in my case

On the steam client the informations seems OK : https://i.imgur.com/ngyz9Xm.png

**Comment by mickaelblondeau** [comment]
Maybe related to this issue ? https://github.com/Facepunch/Facepunch.Steamworks/issues/4

"server.PublicIp" correctly returns my current public address

**Comment by kkukshtel** [comment]
I think I'm having this issue as well. My code was just copy pasted from the Server.cs example function AuthCallback (minus the using block and the ticket cancellation - not sure if this is needed?), and I'm unable to see any servers at the API link, despite the assertions passing. It looks like @mickaelblondeau and I are both using appID 480 instead of our own, would that be an issue?

**Comment by kkukshtel** [comment]
@mickaelblondeau Did you resolve this on your end? Can you share what you did to fix it if so?

**Comment by mickaelblondeau** [comment]
Hey, as I was at the beginning of steam integration, I tried another wrapper (Steamworks.NET) after some code modifications I got a working result
I reopenned the issue

**Comment by garrynewman** [comment]
I think I found the issue. It needs Product, ModDir and GameDescription to be set before you call Logon.

Since these can't be changed afterwards, I have changed it so they can only be set as part of the server init process (part of the new ServerInit class). I also added ForceHeartbeat and called it in a couple of opportune places.

This fixed it locally for me - my server now lists with the GetServersAtAddress webapi call. Let me know if you have any luck.

**Comment by kkukshtel** [comment]
Can confirm that this API change allows me to see servers at the webapi call! Huzzah! I'm not seeing it listed yet with the basic pinging code though:

'''
ServerList.Request request = GameManager.NetworkManager.GetServerRequest();
Debug.Log( "Servers Responded: " + request.Responded.Count );
Debug.Log( "Servers Unresponsive: " + request.Unresponsive.Count );
foreach (ServerList.Server item in request.Responded)
{
   Debug.Log(item.Name);
}
'''

Would this be a separate issue or would it have to do with how the server is being inited?

**Comment by garrynewman** [comment]
My suspicion is that the server either isn't listed because of filters (version, mod folder etc), or that your firewall is blocking it.

**Comment by Metapyziks** [comment]
I haven't used this part of the API yet, but could it be that you have to wait for a bit for the request to get a response? You could try adding a listener to `request.OnUpdate`, and logging `request.Responded` each time that's invoked.

**Comment by kkukshtel** [comment]
@garrynewman I just did some testing and it looks like it wasn't being listed because it was being marked as unresponsive (verified by setting a valid filter only my game would resolve to be true and hence generating one unresponsive server). My firewall is off though and I can't think of other reasons it would be unresponsive. Any thoughts here?

Also I think I found here that you can't set arbitrary keys for filtering (I feel like I read this somewhere?). I.E. Setting a server filter for "Garry","Newman" won't filter the list of returned servers (failing the assertions). However, filtering by gamedir or appid does seem to work.

@Metapyziks I've got the server response setup as a coroutine that only executes once the SteamClient.ServerList.Internet(filter).Finished is true, so I don't think I'm calling it preemptively.

**Comment by garrynewman** [comment]
If it's unresponsive that means that your client tried to query the server (via the query port) but it didn't get a response. Usually happens because firewall, router blocking etc. Have you opened the port on your router, or DMZ'd it?

**Comment by kkukshtel** [comment]
@garrynewman @Metapyziks 

![serverworking](https://user-images.githubusercontent.com/7715279/27614025-d3a8d6b0-5b53-11e7-99b4-d175867a1707.PNG)

Finally - it was indeed a port issue and my router wasn't forwarding the ports I was using. Thanks for working through this! I'm sure I'll be back here soon enough with other questions. Hoping to also write up a step by step tutorial as well for this lib once I'm able to confidently say I can get it set up.

**Comment by jswigart** [comment]
Apologies for the necro, but it seemed preferable to keep related stuff in the same thread than starting a new one.

So I'm using Facepunch.Steamworks to register my dedicated server with steam. It seems to be working in so far as it is getting registered and then reflected in the http query mentioned above

![image](https://user-images.githubusercontent.com/4065267/121759278-82c46880-caea-11eb-93c6-fb1b392bec22.png)

I am using AppId 480 as a test which seems to be a Spacewar game that Valve recommends using to test with. My steam_appid.txt also has 480 into it.

Despite all this, the steam server window does not list my server at all, even in an unreachable state. I also have ports 14242 - 14245 forwarded to the machine the server is running on. Here is my initialization, and I am also doing RunCallbacks() in the update loop.

![image](https://user-images.githubusercontent.com/4065267/121759440-4ba28700-caeb-11eb-9afc-28b5dd510174.png)
(tried with and without a version string)

Finally, here is the minimal logging I was able to hook into and output

_[Callback SteamServersConnected server] : [no fields]
OnSteamServersConnected
OnDebugOutput Msg : Gameserver logged on to Steam, assigned identity steamid:90147825310175241
OnDebugOutput Msg : Set SteamNetworkingSockets P2P_STUN_ServerList to '155.133.253.50:3478' as per SteamNetworkingSocketsSerialized
[Callback GSPolicyResponse server] :     Secure: 0
[Callback 711 server] : [711 not in sdk]_

I'm kinda at the end of my troubleshooting steps and was hoping to get some fresh ideas on how I can proceed with figuring out what's going on. Thanks

**Comment by jswigart** [comment]
Ok a follow up. I was able to finally get it to show in the server browser. I noticed that my server was being returned by a client Steamworks.ServerList.Internet, despite not showing up on the master server list steam window, so on a whim I changed my moddir to match one that was showing up, in this case "spacewar" and eureka, the server started showing up. 

So apparently the mod directory can't just be anything. That leaves me with the question of, what determines valid values for the moddir to ensure the server will show up?

**Comment by JamieShelley** [comment]
@jswigart  I'm having similar issues.
Have you tested via the steam API? I notieced 'gmsindex' = -1- I assume this is 'gamemasterIndex' in otherwords; the steam master that has a part to play in providing these lists.
As to the ModDir correlation. I think perhaps modDir HAS to equal the appid inplied game name. But can't be sure!

**Comment by JamieShelley** [comment]
Is there any usual information in the following that helps me understand why I can't see the server on an internet query list?

`{"response":{"success":true,"servers":[{"addr":"81.96.84.217:27016","gmsindex":-1,"reject":"bad_version","appid":480,"gamedir":"spacewar","region":-1,"secure":true,"lan":false,"gameport":27015,"specport":0}]}}`

**Comment by Romavbg** [comment]
я тоже не вижу свой сервер уже 2й месяц... и не знаю как мне быть,хостинг мне не помогает. и говорит что у valve , в данном случае в КС ГО,  отображение 5000 серверов. максимум.
 но это странно что я ни разу его не видел там.

**Comment by rgarlik** [comment]
Hey all,
Regarding what @JamieShelley asked, whether there's any information that helps understand why one can't see the server.
`"reject":"bad_version"` means that the provided version is in the wrong format.
The version provided is a string that has to have a specific format. It has to be 4 numbers separated by a dot (`0.0.0.1`). If you provide a correctly formed version, the error goes away.

Also I'm assuming the version has to match the version provided in the Dedicated Server settings in your Stemworks settings I'm assuming? I'm still figuring this out myself..
![image](https://user-images.githubusercontent.com/7831167/167927821-a733b961-8abf-436a-9981-535a732bc477.png)

**Comment by StarKen69** [comment]
> Hey all, Regarding what @JamieShelley asked, whether there's any information that helps understand why one can't see the server. `"reject":"bad_version"` means that the provided version is in the wrong format. The version provided is a string that has to have a specific format. It has to be 4 numbers separated by a dot (`0.0.0.1`). If you provide a correctly formed version, the error goes away.
> 
> Also I'm assuming the version has to match the version provided in the Dedicated Server settings in your Stemworks settings I'm assuming? I'm still figuring this out myself.. ![image](https://user-images.githubusercontent.com/7831167/167927821-a733b961-8abf-436a-9981-535a732bc477.png)

I have put this format but the bad version error keeps appearing
