### ISSUE TITLE
Lobby.Joinable vs Lobby.CurrentLobbyData.GetData("joinable")

### ISSUE THREAD

**Issue by Dimma** [Facepunch/Facepunch.Steamworks#220]
When I call:
``` Debug.Log(client.Lobby.Joinable); ```
It returns ```false``` always. Even if I'll set ``` client.Lobby.Joinable = true; ```

When I call:
``` Debug.Log(client.Lobby.CurrentLobbyData.GetData("joinable")); ```
It returns actual state.

Is it me or what?

**Comment by igniuss** [comment]
It *should* return just fine.. Looking at the code 
```csharp
        /// <summary>
        /// Is the Lobby joinable by other people? Defaults to true;
        /// </summary>
        public bool Joinable
        {
            get
            {
                if ( !IsValid ) { return false; }
                string joinable = CurrentLobbyData.GetData( "joinable" );
                switch ( joinable )
                {
                    case "true":
                        return true;
                    case "false":
                        return false;
                    default:
                        return false;
                }
            }
            set
            {
                if ( !IsValid ) { return; }
                if ( client.native.matchmaking.SetLobbyJoinable( CurrentLobby, value ) )
                {
                    CurrentLobbyData.SetData( "joinable", value.ToString() );
                }
            }
        }
``` 

As you can see, it internally calls `GetData("joinable")`

I'll do some testing and edit my response with what I find.

**Comment by LoneSurvivor82** [comment]
I am sorry but the Lobby.cs doesn't has this property. Has this issue been closed without being implemented or am I in the wrong class? Lobby.cs has a SetJoinable but no Getter. Also for Invisible and FriendsOnly.

**Comment by igniuss** [comment]
This post is almost 3 years old, this lib has had a ton of rewriting in that time 😅 so I don't think you can still use the above snippet.
