### ISSUE TITLE
Unity crashes when trying to publish to workshop

### ISSUE THREAD

**Issue by oonis** [Facepunch/Facepunch.Steamworks#226]
item.OnChangesSubmitted doesn't appear to be called, and I'm guessing it's failing because

```csharp
while(item.Publishing) {
Thread.Sleep(10);
Debug.Log("Progress: " + item.Progress);
}
```

is infinite.

EDIT: So when I removed the loop I'm hit with
```
ArgumentException: The specified path is not of a legal form (empty).
System.IO.Path.InsecureGetFullPath (System.String path) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.IO.Path.GetFullPathInternal (System.String path) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.IO.FileInfo.Init (System.String fileName, System.Boolean checkHost) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.IO.FileInfo..ctor (System.String fileName) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
(wrapper remoting-invoke-with-check) System.IO.FileInfo..ctor(string)
Facepunch.Steamworks.Workshop+Editor.PublishChanges () (at <d803ac10e4884539971d017743ba32a8>:0)
Facepunch.Steamworks.Workshop+Editor.OnItemCreated (SteamNative.CreateItemResult_t obj, System.Boolean Failed) (at <d803ac10e4884539971d017743ba32a8>:0)
SteamNative.CallResult`1[T].RunCallback () (at <d803ac10e4884539971d017743ba32a8>:0)
SteamNative.CallResult.Try () (at <d803ac10e4884539971d017743ba32a8>:0)
Facepunch.Steamworks.BaseSteamworks.RunUpdateCallbacks () (at <d803ac10e4884539971d017743ba32a8>:0)
Facepunch.Steamworks.BaseSteamworks.Update () (at <d803ac10e4884539971d017743ba32a8>:0)
Facepunch.Steamworks.Client.Update () (at <d803ac10e4884539971d017743ba32a8>:0)
Core.Control.SteamManager.Update () (at Assets/Core/Control/SteamManager.cs:111)
Core.Control.NetworkController.Update () (at Assets/Core/Control/NetworkController.cs:219)
```
The specified path has been tested, and the value is a string that points to the correct folder.

**Comment by oonis** [comment]
> What does the path look like? Since System.IO seems to think it's an invalid/illegal path.

The path is valid and tested:
```
C:\Users\oonis\AppData\LocalLow\Better Games\Puttin Around\maps\test
```

**Comment by igniuss** [comment]
And you're setting `item.Folder` properly? Can you provide the full code where you create the item, and upload it?

**Comment by oonis** [comment]
Yes, that path was the value of item.Folder. My usage is based on looking at the test code
```csharp
var item = Client.Workshop.CreateItem();
item.Title = map.Name;
item.Description = map.WorkshopInfo.Description;
item.PreviewImage = map.WorkshopInfo.PreviewImagePath;
item.Visibility = map.WorkshopInfo.Visibility;
item.Folder = map.MapFolder;

item.OnChangesSubmitted += result => {
  Debug.Log( "OnChangesSubmitted called: " + result );
};

item.Publish();
```

interestingly enough it doesn't appear that the OnChangesSubmitted action is ever called.

**Comment by igniuss** [comment]
And printing `Item.Folder` returns `C:\Users\oonis\AppData\LocalLow\Better Games\Puttin Around\maps\test` right?

**Comment by oonis** [comment]
> And printing `Item.Folder` returns `C:\Users\oonis\AppData\LocalLow\Better Games\Puttin Around\maps\test` right?

correct

**Comment by igniuss** [comment]
Is `PreviewImage` a correct path? Just noticed the error comes from FileInfo, the only thing calling that is setting the preview image. 

The path appears to be an empty string (or just spaces), [you can look at the mono source for the error](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.IO/Path.cs#L373)

Try setting `PreviewImage` to null, or to an image that's smaller than 1MB.
If `PreviewImage` is null, it won't set the item preview in `PublishChanges()`

Sorry for the late reply btw, had to make dinner 😉

**Comment by oonis** [comment]
> Is `PreviewImage` a correct path? Just noticed the error comes from FileInfo, the only thing calling that is setting the preview image.
> 
> The path appears to be an empty string (or just spaces), [you can look at the mono source for the error](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.IO/Path.cs#L373)
> 
> Try setting `PreviewImage` to null, or to an image that's smaller than 1MB.
> If `PreviewImage` is null, it won't set the item preview in `PublishChanges()`
> 
> Sorry for the late reply btw, had to make dinner 😉

Hey! Thank you so much turns out it has to be set to null. This whole time I was thinking an empty string would be treated the same way.

**Comment by igniuss** [comment]
No problem! Took a bit to figure out where the error came from, now we both know ;)
