### ISSUE TITLE
(Leaderboard) Unable to determine why a score is not updated

### ISSUE THREAD

**Issue by trumpetx** [Facepunch/Facepunch.Steamworks#23]
Hey, all.  I'm in the process of converting a working Steamworks.NET leaderboard implementation to Facepunch.Steamworks so I'm familiar with the steamworks stuff.  I would like to move on to inventory management later, and I've read others talk about how awesome Facepunch.Steamworks is for that.  So, I've begun!

First: THANK YOU to whoever decides to help me.  Helping noobs sucks.  I know.

Issue:  User scores are not getting added to the leaderboard.  The success on callback is "false" and I have no clue why it's happening.  I wish I had some sort of additional logging, but I'm simply at a loss.  I've scoured the Tests Cases on this project and I'm now stuck.  I'm sure it's something I'm doing wrong, but I can't figure it out for the life of me and I've been stuck long enough now that I'm willing to ask for help.

1) My leaderboards can be queried using Facepunch.Steamworks just fine
2) Yes, my appidtxt is in the root of my project.
3) Yes, I'm calling client.Update() in Update() on a singleton game object (and I've confirmed it's still cookin' when I get this success=false -- though, I suspect if this wasn't happening I wouldn't even get the callback)
4) I am logged into steam, but I'm running this out of a Unity editor (I also tried making a game build too - same behavior)

My leaderboard init code (called at game startup).  This stuff works fine, no errors (leaderboard object is set to IsValid)
```
        private void Start()
        {
            worldUIHelper = GetComponent<WorldUIHelper>();
            foreach (string leaderboardName in new string[] { MOLE_MOUNTAIN, CLIFF_CASTLE })
            {
                Leaderboard leaderBoard;
                if (ALL_LEADERBOARDS.ContainsKey(leaderboardName))
                {
                    leaderBoard = ALL_LEADERBOARDS[leaderboardName];
                }
                else
                {
                    leaderBoard = client.GetLeaderboard(leaderboardName, Client.LeaderboardSortMethod.Ascending, Client.LeaderboardDisplayType.Numeric);
                    ALL_LEADERBOARDS.Add(leaderboardName, leaderBoard);
                }
                if (leaderBoard != null && !leaderBoard.IsError)
                {
                    StartCoroutine(DownloadLeaderboard(leaderBoard));
                }
            }
        }

        private IEnumerator DownloadLeaderboard(Leaderboard leaderBoard)
        {
            while (!leaderBoard.IsValid)
            {
                client.Update(); // This probably isn't necessary
                yield return new WaitForEndOfFrame();
            }
            Debug.Log("Downloading status of leaderboard: " + leaderBoard.Name);
            leaderBoard.FetchScores(Leaderboard.RequestType.GlobalAroundUser, 0, 100, (bool success, Leaderboard.Entry[] results) =>
            {
                if (!success)
                {
                    Debug.LogError("Leaderboard didn't download: " + leaderBoard.Name);
                }
                if (results != null && leaderBoard.Name == MOLE_MOUNTAIN) // TODO: multiple leaderboards on single GUI
                {
                    foreach (Leaderboard.Entry result in results)
                    {
                        AddLeader(result.Name, "" + result.Score);
                    }
                }
            });
        }
```

My update score method.  It wasn't always static, but I was trying different things and I'm just trying to "make it work" right now.
```
        public static void UpdateScore(string leaderboardName, int score)
        {
            bool tried = false;
            if (ALL_LEADERBOARDS.ContainsKey(leaderboardName))
            {
                Leaderboard leaderboard = ALL_LEADERBOARDS[leaderboardName];
                // Yes, the leaderboard IsValid=true, IsError=false, IsQuerying=false
                tried = leaderboard.AddScore(false, score, null, (bool success, Leaderboard.AddScoreResult result) => {
                    if (!success)
                    {
                        // This is the output that I see in my Unity logs
                        Debug.LogError("Score not updated: " + leaderboard.Name + " => " + score);
                    }
                });
            }
            if (!tried)
            {
                Debug.LogError("Leaderboard not valid for update: " + leaderboardName + " => " + score);
            }
        }
```

Is there any way to increase the visibility of what's going on?

**Comment by Metapyziks** [comment]
I could add an extra parameter to the callback that provides error information tomorrow, it would definitely be useful to have.

**Comment by garrynewman** [comment]
I kinda feel like the way steamworks does callbacks, with a single one for fail and success isn't very c#, so it might be better to add a separate callback for fail conditions.

**Comment by Metapyziks** [comment]
I've done as @garrynewman suggested, you can now give an optional `onFailure` callback that is invoked with a [Facepunch.Steamworks.Callbacks.Result](https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/Callbacks/Index.cs) value if an error occurred. The first callback you pass is now named `onSuccess`, and is only invoked if the action performed by the method completed without error.  I've done this for all callback accepting methods in the leaderboard and remote storage API.

For example, to add a score:

```csharp
if ( !leaderboard.IsValid ) throw new Exception( "Leaderboard is invalid!" );

leaderboard.AddScore( false, score, null, result => {
    Debug.LogFormat( "Score submitted successfully! New rank: {0}", result.GlobalRankNew );
}, error => {
    // "error" can be either Result.IOFailure or Result.Fail here
    Debug.LogFormat( "Could not submit score! Reason: {0}", error );
} );
```

Although I should note that unfortunately Steamworks itself doesn't provide much error information when a leaderboard score fails to submit, but at least now you will be able to distinguish between an IO error (if you get an `Result.IOFailure`) or some other error (if you get a `Result.Fail`).

Hope that helps, and if scores still aren't submitting please let me know which of those two `onFailure` results you get.

**Comment by trumpetx** [comment]
so, my apologies for this - but updated to the latest git version, ran a release build and then copied the .dll files to my unity project (over the old ones which originated from Facepunch.Unity) and now it's complaining about not finding Facepunch.Steamworks stuff.  

Any ideas what I'm missing?  (Attached the .zip of the built .dlls if that can help)

[Facepunch.Steamworks.zip](https://github.com/Facepunch/Facepunch.Steamworks/files/1068140/Facepunch.Steamworks.zip)

**Comment by Metapyziks** [comment]
It looks like that's the .NET Standard 1.6 build, I think you'll need the .NET 3.5 build (which should be in `Facepunch.Steamworks/bin/Release/net3.5`) if you're using Unity.

**Comment by trumpetx** [comment]
Hmm, so perhaps the .dll's in the Facepunch.Unity project are busted.  I just tried and the error is now gone (no changes other than changing the error callback to how you described above.)

So, I guess that's a big thanks!

**Comment by Metapyziks** [comment]
No problem, and I agree that the error callback is useful to have, so thank you for prompting me to add it!

I'll close this ticket for now, but please let us know if you encounter any other issues while porting to Facepunch.Steamworks.
