### ISSUE TITLE
steam_gameserver.h steam networking on dedicated server

### ISSUE THREAD

**Issue by steel97** [Facepunch/Facepunch.Steamworks#230]
Hello. I'am faced with problem, I can't use steam networking on gameserver. It seems that current implementation expose steam_api.h for both client and server, is it possible to initialize gameserver using this library with SteamGameServer_Init method from steam_gameserver.h?

**Comment by igniuss** [comment]
This library splits the Client & Server up. There's an [example on the readme page](https://github.com/Facepunch/Facepunch.Steamworks#server) on how to initialize a server

**Comment by steel97** [comment]
> 
> 
> This library splits the Client & Server up. There's an [example on the readme page](https://github.com/Facepunch/Facepunch.Steamworks#server) on how to initialize a server

yes, but it's still initialize server via steam_api.h and isteamgameserver.h, not steam_gameserver.h
From documentation [https://partner.steamgames.com/doc/sdk/api?language=english](https://partner.steamgames.com/doc/sdk/api?language=english) :
![default](https://user-images.githubusercontent.com/7414151/51051490-f5148400-15e4-11e9-8371-d51c56e8b611.png)

**Comment by igniuss** [comment]
Oh, sadly that'll require some rewriting I think. Can't help you much with that.

**Comment by steel97** [comment]
Yes, everything working fine, I have issue with GetSteamID() which I called before server logged on, sorry again

**Comment by igniuss** [comment]
Ah nice! Glad you got it sorted 👍
