### ISSUE TITLE
Implement ISteamNetworkingSockets

### ISSUE THREAD

**Issue by oonis** [Facepunch/Facepunch.Steamworks#235]
I know it's in beta, but this would definitely be a welcome addition to Steamworks, and figured I'd put the issue in now to see what people think.

SteamWorks API: https://partner.steamgames.com/doc/api/ISteamNetworkingSockets

**Comment by kscarlett** [comment]
Fixed clickable link: [https://partner.steamgames.com/doc/api/ISteamNetworkingSockets](https://partner.steamgames.com/doc/api/ISteamNetworkingSockets)

As for my opinion, I don't think implementing it while it is in beta is a very good idea. It might not be clear to people using the API that it is in beta, so they may use it in their code thinking it is production-ready.

I'm also not sure it's a good fit for this library. The networking sockets API is a very low level networking API, while Facepunch.Steamworks is supposed to be a higher level wrapper around the Steamworks API. Turning the networking sockets API into a high level API would require a lot more work and would basically be a whole networking library on its own. This is probably a much better fit for [Steamworks.NET](https://steamworks.github.io/) or even a whole separate library.
