### ISSUE TITLE
Lobby Owner always returns 0

### ISSUE THREAD

**Issue by Snotax** [Facepunch/Facepunch.Steamworks#238]
Facepunch.Steamworks.LobbyList.Lobby lobby = Client.Instance.LobbyList.Lobbies.Find(tmp => tmp.LobbyID == this.SteamLobbyID);

lobby.Owner always returns 0

What am I doing wrong?

**Comment by Roobubba** [comment]
You can get the owner's steam ID of a lobby you've already joined like this:

Facepunch.Steamworks.Client facepunchClient = Facepunch.Steamworks.Client.Instance;

facepunchClient.Lobby.Join(hostId);
facepunchClient.Lobby.OnLobbyJoined = (success) =>
  {
    ulong hostSteamID = facepunchClient.Lobby.Owner;
    Debug.Log("hostSteamID = " + hostSteamID);
  };

But as far as I can tell (and raised in issue 237 - https://github.com/Facepunch/Facepunch.Steamworks/issues/237), the steamworks function to get data from a lobby you haven't yet joined doesn't appear to be implemented (or working).

**Comment by Birgerev** [comment]
Should this really be closed? This has caused me hours of headache trying to hunt down why my connections are not working

**Comment by Birgerev** [comment]
nvm apparently just part of the steam API, maybe could be clarified however...
