### ISSUE TITLE
ISteamAppList.GetAppName()?

### ISSUE THREAD

**Issue by jacobcoughenour** [Facepunch/Facepunch.Steamworks#24]
It's a small thing but I want to get the name of the game a SteamFriend is playing with it's appid.
The Native method is ISteamAppList.GetAppName() and SteamAppList.GetAppName() with Steamworks.net.

I tried implementing it myself, but couldn't figure out how to return the System.Text.StringBuilder with the name.

**Comment by garrynewman** [comment]
I'm struggling to make this work too, looking into it though.

**Comment by jacobcoughenour** [comment]
I found that the [Steamworks.NET implementation](https://github.com/rlabrecque/Steamworks.NET/blob/master/Plugins/Steamworks.NET/autogen/isteamapplist.cs#L28) uses IntPtr to pass the char * parameter.  
How do you use the Generator?

**Comment by garrynewman** [comment]
Turns out some apps don't have permission to use this interface.
