### ISSUE TITLE
SteamAchievements with Steamworks.NET Unity C# 

### ISSUE THREAD

**Issue by kaisametrine** [Facepunch/Facepunch.Steamworks#245]
Hello! 
I have a trouble to implement achievements to my game. I am new to programming so I struggle a little bit. I downloaded and imported SteamManager but could not figure out how to write a script for SteamAchievements, please help!

**Comment by igniuss** [comment]
As long as SteamManager is in the scene, and running, you should be able to call 
`Facepunch.Steamworks.Client.Instance.Achievements.Trigger("achievement_id", true)` in *any* script and have it register the achievement.

**Comment by kaisametrine** [comment]
@igniuss I don't use Facepunch

**Comment by igniuss** [comment]
If you're not using Facepunch.Steamworks.. Then the SteamManager (provided in this repo) will not work. Since it relies on the SDK...

**Comment by kaisametrine** [comment]
@igniuss I installed facepunch but still smth is wrong Monobehaviour is highlighted
![Screenshot (47)](https://user-images.githubusercontent.com/49246376/55506452-5c265f80-564d-11e9-8476-b7f88d674f85.png)

**Comment by igniuss** [comment]
Oh, `MonoBehaviour`, my bad.

**Comment by kaisametrine** [comment]
@igniuss yeah thanks! I am sorry for taking your time but I have one more question I had this in my previous script that was not working but I think I need it here too. I have achievement for passing each level so it was looking like this: 

foreach (Achievement_t achievement in m_Achievements) {
			
			if (achievement.m_bAchieved)
				continue;
			
			switch (achievement.m_eAchievementID) {
			case Achievement.LEVEL_1:
				if (Save.Level1 == true)  {
					UnlockAchievement (achievement);
				}
				break;
			case Achievement.LEVEL_2: 
				if (Save.Level2 == true)  {
					UnlockAchievement (achievement);
				}
				break;
			case Achievement.LEVEL_3:
				if (Save.Level3 == true)  {
					UnlockAchievement (achievement);
				}
				break;

			  }

**Comment by igniuss** [comment]
```csharp
var client = Facepunch.Steamworks.Client.Instance;
if(client == null) { return; }
foreach (var achievement in client.Achievements.All) {
    if (achievement.State)
        continue;
            
    switch (achievement.Id) {
        //case level_1_id:
        //  achievement.Trigger(true); //unlocks the achievement.
        //break;
        //case level_2_id: 
       //....
    }
}
```

**Comment by kaisametrine** [comment]
@igniuss still doing smth wrong 
![Screenshot (62)](https://user-images.githubusercontent.com/49246376/55819862-ac8c3a00-5af1-11e9-8b7b-479e488f68b8.png)

**Comment by igniuss** [comment]
Well yeah.. You'd need to change the 'LEVEL_A_ID' things to what you're actually using.. Like `Achievement.LEVEL_1` in your example

**Comment by kaisametrine** [comment]
Now I have an error: cannot implicitly convert type 'AchievementManager.Achievement' to string
![Screenshot (68)](https://user-images.githubusercontent.com/49246376/55877576-4b687300-5b92-11e9-82b7-e09520b76816.png)

**Comment by kaisametrine** [comment]
@igniuss Having an error: cannot implicitly convert type 'AchievementManager.Achievement' to string. No idea how to fix it. 
![Screenshot (68)](https://user-images.githubusercontent.com/49246376/56315030-a3811580-614e-11e9-8fe3-bd62db535777.png)
