### ISSUE TITLE
Leaderboards: IndexOutOfRangeException and no Results

### ISSUE THREAD

**Issue by Blitzjoans** [Facepunch/Facepunch.Steamworks#248]
Hello.

First, thanks for the update! I managed to get almost everything to work on this new version!
However, like 0.7, i can't get Leaderboards to work.

With the new release:

`leaderboard.Value.GetScoresAroundUserAsync( -5, 5 );` returns: 
> IndexOutOfRangeException: Index was outside the bounds of the array.

and

`leaderboard.Value.GetScoresAsync( 20 );` doesn't return anything when i use `foreach (var e in relativeScores)`

The Leaderboard i'm using for testing has 1 entry. With 0.7 i was able to Get the Leaderboard name and TotalEntries 2 or 3 seconds after a function was called, but i wasn't able to get any Score. With this new version i'm doing `Debug.Log("" + leaderboard.HasValue);` and returns true, so i guess it gets the correct Leaderboard? I don't know how to get Name and TotalEntries with the new version.

The app it's not released but it shows on the Store. I can get Achievements to work perfectly.

**Comment by Blitzjoans** [comment]
`IndexOutOfRangeException: Index was outside the bounds of the array.
Steamworks.Data.Leaderboard+<LeaderboardResultToEntries>d__15.MoveNext () (at l:/workspace/cepunch.Steamworks_steamworks144/Facepunch.Steamworks/Structs/Leaderboard.cs:115)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Steamworks.Data.Leaderboard+<GetScoresAsync>d__12.MoveNext () (at l:/workspace/cepunch.Steamworks_steamworks144/Facepunch.Steamworks/Structs/Leaderboard.cs:72)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Steam_Leaderboards+<GetScoresAroundUserAsync>d__4.MoveNext () (at Assets/Scripts/Steam/Steam_Leaderboards.cs:30)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:112)
UnityEngine.UnitySynchronizationContext.Exec () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:73)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:94)`

**Comment by garrynewman** [comment]
So weird - looking at the code this shouldn't be possible. Will investigate further.

**Comment by garrynewman** [comment]
I've put some extra checks and tests but can't recreate the problem. Can you create a new ticket if this still happens?
