### ISSUE TITLE
How do you know when Steam wants to shut down?

### ISSUE THREAD

**Issue by klaritan** [Facepunch/Facepunch.Steamworks#249]
When Steam is shutting down, my game does not get a message so Steam will be stuck until the user has to manually shut my game down. This sometimes locks the user from unable to shut their system down properly.

Is there a way to get this as a callback?

**Comment by garrynewman** [comment]
Will add this

**Comment by garrynewman** [comment]
Turns out I already added it

```csharp
Steamworks.SteamUtils.OnSteamShutdown += YourFunction()
```
