### ISSUE TITLE
SteamFriend.IsOnline not working?

### ISSUE THREAD

**Issue by jacob15545** [Facepunch/Facepunch.Steamworks#25]
SteamFriend.IsOnline only returning false even when friend is actually online or IsPlaying is true.

Example ( in Unity )
`foreach (var friend in Client.Instance.Friends.AllFriends) {
           Debug.Log(friend.IsOnline);
}`

**Comment by garrynewman** [comment]
You're right - this wasn't hooked up. Have fixed it now.
