### ISSUE TITLE
Leaderboards: GetScoresAsync() Out of Range

### ISSUE THREAD

**Issue by Blitzjoans** [Facepunch/Facepunch.Steamworks#250]
Since this is still active and it was getting buried in the commits comments, i've opened an issue here for easier access and discussion.

The last update on this issue was this:

> Hello Garry!

> I've just tested the same script on Unity 2019. Nothing new, still the same error. Fresh dll's downloaded again from the release tab.

> Tested with a new Leaderboard created via Steamworks page, and again, same error:
> Steamworks.Data.Leaderboard+<LeaderboardResultToEntries>d__15.MoveNext () (at l:/workspace/cepunch.Steamworks_steamworks144/Facepunch.Steamworks/Structs/Leaderboard.cs:115)
> 
> ...
> 
> If i understand correctly, the dll's from the release tab doesn't include the changes made on this commit (the safeguards), so maybe that's the problem?
> I'm totally new to compiling things on Visual Studio, but maybe i can try to compile 'master' to get the latest version of the Facepunch.Steamworks dll's?
> 
> I've tried this before (Opening the project on VS and trying to get some dll's) but the result seems to be incomplete since later on Unity i get some errors with the dll's compiled on my computer.
> 
> ...
> 
> The other only option i can think of is the fact that my AppId it's not released? The commuity page for the Achievements and Leaderboards it's hidden (but this option seems strange since i can upload scores and unlock my achievements)
> 
> ...
> 
> Thanks for your time!
> Juan Ramón

> @garrynewman
Just to be sure, i changed the AppId to 480 and test the Leaderboard provided with Spacewar. Same error in Unity 2018.3.5 and 2019

Some other new things i tried:

- Create a new Leaderboard "Test". Numeric instead of miliseconds. And ups, different kind of error?!: 
`NullReferenceException: Object reference not set to an instance of an object
Steam_Leaderboards+<GetScoresGameAsync>d__3.MoveNext () (at Assets/Scripts/Test_Steam/Steam_Leaderboards.cs:46)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:112)
UnityEngine.UnitySynchronizationContext.Exec () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:73)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:94)`

Intead of "`IndexOutOfRangeException: Index was outside the bounds of the array.
Steamworks.Data.Leaderboard+<LeaderboardResultToEntries>d__15.MoveNext () (at l:/workspace/cepunch.Steamworks_steamworks144/Facepunch.Steamworks/Structs/Leaderboard.cs:115)`" i've got a NullReference. 

- And also, something interesting: The first Leaderboard i've tested ("Level 01") is set with Milisenconds and gives an error 'IndexOutOfRange' here:

` var relativeScores = await leaderboard.Value.GetScoresAsync(5);`

However, the "Test" Leaderboard it's set with Numeric display and gives a NullReference later on the function!:

```
var relativeScores = await leaderboard.Value.GetScoresAsync(5);
await Task.Delay(200);
foreach (var e in relativeScores) //This is were it fails
{
  Debug.Log("AYYY");
}
```
Which is really weird, because it awaits for GetScores and returns something. That Leaderboard has one entry made by me, same as Level 01.

So:

- If it's Numeric GetScores returns something but fails later.
- If it's Miliseconds fails.

Tested with my AppId and 480. On 480 the error it's the same as "Level 01".

At this point i don't know if it's because of the way i'm using Async operations or Steam or some small detail on the Leaderboard structs.
Each time i've tested this i've downloaded the dll's from the release tab and restart everything.

**Comment by garrynewman** [comment]
With the NullRefError you need to make sure relativeScores isn't null - with relativeScores.HasValue.

```csharp	
var leaderboard = await SteamUserStats.FindLeaderboard( "Testleaderboard" );
if ( !leaderboard.HasValue ) Leaderboard doesn't exist
}```

**Comment by Blitzjoans** [comment]
@garrynewman Hello! 

Sorry for the delay, i've tested that line and a couple more safeguards and nothing. 

Always throws and error on 
`var relativeScores = await leaderboard.Value.GetScoresAsync(5);`
(even with your last responde code)

The console keeps pointing at the Leaderboard struct. Yesterday i was able to talk about this with one of the teachers in my university and apparently my code should work (as you said some time ago)


Can i ask for a new release with the safeguards that you commited some days ago? I tried to compile the project to see if something is wrong on my side even with your newest commits, but i'm unable to get the correct .dlls after compiling in Visual Studio.


Thanks for your time!

**Comment by garrynewman** [comment]
Sure - give this a go

[archive.zip](https://github.com/Facepunch/Facepunch.Steamworks/files/3187588/archive.zip)

**Comment by scgsergiusz** [comment]
Hi there, any update on this? I'm using release 2.2.0 and this issue is still there.

I have a leaderboard with two entries and to got the scores I use:

`this.currentLeaderboard.GetScoresAsync(5);`

then I got:

`IndexOutOfRangeException: Index was outside the bounds of the array.
Steamworks.Data.Leaderboard+<LeaderboardResultToEntries>d__15.MoveNext () (at <851c292e1a9944c4920a6e84ebdaddb8>:0)
--- End of stack trace from previous location where exception was thrown ---`

**Comment by garrynewman** [comment]
There's going to be a big update next weekish, so lets try again then

**Comment by scgsergiusz** [comment]
@garrynewman thanks for the update. Any chance to get that piece next week for sure? Sorry for pushing but we're about to launch early access on steam next week and this one little thing prevents me from sleeping :)

**Comment by garrynewman** [comment]
That's what I'll be trying for, the new SDK came out last night so will try for first half next week
