### ISSUE TITLE
SteamUser RequestEncryptedAppTicket not implemebted

### ISSUE THREAD

**Issue by ykgamma** [Facepunch/Facepunch.Steamworks#251]
The method RequestEncryptedAppTicket is implemented in ISteamUser, but is not implemented in SteamUser.

This is a required method for authenticating a user on a backend server without access to Steam.

**Comment by garrynewman** [comment]
Will add this now

**Comment by garrynewman** [comment]
Done

```csharp
var data = await SteamUser.RequestEncryptedAppTicketAsync();
```
