### ISSUE TITLE
LobbyEntered missing

### ISSUE THREAD

**Issue by Fischer96** [Facepunch/Facepunch.Steamworks#252]
Noit sure if i just couldn't find a way to do it, but is LobbyEntered Callback missing? 
When creating a lobby or joining a lobby with an invite, the LobbyEntered Callback should be called, but it's nowhere to be found

**Comment by garrynewman** [comment]
I thought OnLobbyMemberJoined would work?

**Comment by garrynewman** [comment]
Oh I see what you're looking for. Lobby.Join is async.

```csharp
var roomEnter = await lobby.Join();
if ( roomEnter == roomEnter.Success ) Joined();
```

**Comment by Fischer96** [comment]
Ah yeah, but when i'm using SteamFriends.OnGameLobbyJoinRequested for joining a lobby via invite i only get the steam lobby id and not a lobby object for joining. Is that correct?

**Comment by garrynewman** [comment]
You're right - have just added it

**Comment by Fischer96** [comment]
Working fine, thank you!
