### ISSUE TITLE
No easy way to get User subscribed items

### ISSUE THREAD

**Issue by Stormy102** [Facepunch/Facepunch.Steamworks#253]
Hi Garry,

I may be missing something but I can't find an easy way to get the Ugc items that the user has subscribed to. Previously I could just do this:
`using (Facepunch.Steamworks.Workshop.Query query = SteamClient.CreateQuery())
{
    query.UserQueryType = Facepunch.Steamworks.Workshop.UserQueryType.Subscribed;
}`
But now it seems that there isn't any easy way to quickly get the items which the user is currently subscribed. Am I overlooking something?

**Comment by garrynewman** [comment]
You're right - this was a hell of an oversight. Have fixed it now.

```csharp
			var q = Ugc.Query.All
							.WhereUserPublished( <optionalsteamid> );
```

```csharp
			var q = Ugc.Query.All
							.WhereUserSubscribed( <optionalsteamid> );
```

If you don't pass an steamid it will query the current user

**Comment by Stormy102** [comment]
Excellent thanks!

**Comment by andefoo** [comment]
There also seems to be Internal.GetSubscribedItems which is not used anywhere. I noticed it is much faster than calling the async query to get the same result. I am not sure if the result can trusted to be as up-to-date as with the query but for my basic tests it seems to return the same values. 

So I added this to my SteamUGC class. Not tested enough yet to make a pull request...

https://github.com/andefoo/Facepunch.Steamworks/blob/7b068b4ed11bd3b0d39b3333eb2b2d69cf9242e2/Facepunch.Steamworks/SteamUgc.cs#L192

**Comment by 0kk470** [comment]
> There also seems to be Internal.GetSubscribedItems which is not used anywhere. I noticed it is much faster than calling the async query to get the same result. I am not sure if the result can trusted to be as up-to-date as with the query but for my basic tests it seems to return the same values.
> 
> So I added this to my SteamUGC class. Not tested enough yet to make a pull request...
> 
> https://github.com/andefoo/Facepunch.Steamworks/blob/7b068b4ed11bd3b0d39b3333eb2b2d69cf9242e2/Facepunch.Steamworks/SteamUgc.cs#L192

Agreed. For a custom mod manager in a game, quickly retrieving the currently installed Workshop files is very important. Ugc.Query is better suited as an in-game Workshop browser query interface, but not for fetching all files the player has subscribed to local.
