### ISSUE TITLE
Steam Networking API, question, discussion

### ISSUE THREAD

**Issue by Agoxandr** [Facepunch/Facepunch.Steamworks#254]
Right now I'm developing a multiplayer game. It works pretty well (using this https://github.com/nxrighthere/ENet-CSharp) but I would like to try the Steam Networking API. The same author made this wrapper https://github.com/nxrighthere/ValveSockets-CSharp for this https://github.com/ValveSoftware/GameNetworkingSockets
My understanding is that the Github library GameNetworkingSockets is the public open source version of Steam Netwoking API which is part of the Steam API.
So which one is better? Garry seems to have implemented the new Networking API, but a tutorial is missing and im not sure how well it is done or if it's complete. Valve also endorses the 
nxrighthere's C# implementation under the Third party language bindings section in the readme page.

I just don't want to waste my time. I'm also wondering which one will be easier to use. Also thanks for your work Garry.

**Comment by garrynewman** [comment]
A few differences as far as I'm aware:

- With steamworks no native libraries to build (works on osx, linux, win)
- FPS now is 64bit only - so no support for 32bit windows
- Can use Valve's relay network with FPS implementation
- FPS isn't tested, but we plan on trying it on on Rust, so it will be eventually

If I was you I'd probably use the other library for now. I've got tests that prove that the FPS implementation works technically, but I haven't actually implemented the networking of a game with it 
 yet.

**Comment by Agoxandr** [comment]
Thanks! Just make sure to blog about it or something when you feel confident with it!
