### ISSUE TITLE
SteamUser should implement GetAuthSessionTicketResponse_t

### ISSUE THREAD

**Issue by OndrishD** [Facepunch/Facepunch.Steamworks#256]
Currently ValidateAuthTicketResponse_t callback event is implemented in SteamUser. However this event is connected with different workflow.

Right now there is no proper way to react once `SteamUser.GetAuthSessionTicket();` is called. Intended workflow from steam documentation refers that after calling this method, we should wait until GetAuthSessionTicketResponse_t is triggered if we intend to proceed with ticket and send it to WEB API. Please read the steam doc: https://partner.steamgames.com/doc/api/ISteamUser#GetAuthSessionTicket

> When creating a ticket for use by the ISteamUserAuth/AuthenticateUserTicket Web API, the calling application should wait for the GetAuthSessionTicketResponse_t callback generated by the API call before attempting to use the ticket to ensure that the ticket has been communicated to the server. If this callback does not come in a timely fashion (10 - 20 seconds), then your client is not connected to Steam, and the AuthenticateUserTicket call will fail because it can not authenticate the user.

It would be very useful to have this GetAuthSessionTicketResponse_t callback event available via SteamUser. Could you please add this?

`GetAuthSessionTicketResponse_t.Install( x => OnGetAuthSessionTicketResponse?.Invoke(...) );`

**Comment by ip0p** [comment]
I would also like to see this!

**Comment by garrynewman** [comment]
Hopefully this does what you want: https://github.com/Facepunch/Facepunch.Steamworks/commit/761ff33663767c56295612359b4cace0c3e1a2db

**Comment by ip0p** [comment]
Ah before I forget... Thanks Garry! It's working fine!
