### ISSUE TITLE
Fallback handler could not load library

### ISSUE THREAD

**Issue by Agoxandr** [Facepunch/Facepunch.Steamworks#257]
Everything works as intended. But I get strange messages in the log file.

[output_log.txt](https://github.com/Facepunch/Facepunch.Steamworks/files/3203468/output_log.txt)

Any ideas why I get a spam of this only in **builds**:

> Fallback handler could not load library C:/Reconquer/Revision 5/Revision 5_Data/Mono/libsteam_api
> Fallback handler could not load library C:/Reconquer/Revision 5/Revision 5_Data/Mono/libsteam_api.dll

I assume this comes up every time I mace a Steamworks function call. Note the path. I don't even have a Mono folder in the game files.

Edit: I don't know what libsteam_api.dll is supposed to be. There is libsteam_api.so but that shouldn't have anything to do with Windows.

**Comment by garrynewman** [comment]
It's normal. I think it's just looking at the linux calls that are in the dll and trying to build them from the dll - but it's just saying the dll doesn't exist.

I could work around it by making separate builds for windows/linux. It would actually make things a bit neater all round - and would probably make 32bit support a ton easier too. I might do it, but for now - don't worry.
