### ISSUE TITLE
Can't find .unitypackage in the 2.0 alpha release

### ISSUE THREAD

**Issue by hugeATOM** [Facepunch/Facepunch.Steamworks#258]
Hello, 

I've downloaded both zip files in the  2.0 alpha  release but I can't seem to find the .unitypackage file? Is there supposed to be one?

Thanks in advance.

**Comment by Stormy102** [comment]
You just go into the Unity folder in the file and copy the contents of that folder into the Plugins/Facepunch.Steamworks folder.

**Comment by garrynewman** [comment]
Yeah UnityPackages are shitty for everyone - just copy the folder where it needs to go.

**Comment by hugeATOM** [comment]
I see. Thank you!
