### ISSUE TITLE
Just trying to get started

### ISSUE THREAD

**Issue by malkere** [Facepunch/Facepunch.Steamworks#260]
There's probably some step I'm just not aware of, but I would love a pointer if anyone can spot my mistake. I'm running on a windows EC2 for testing, with 27015 and 27016 open in the security groups, the test.exe allowed free movement in the windows firewall settings. I'm getting the client and the server to connect, but I can't seem to get a list of servers to show up, nor ping for a server in Steam -> View -> Servers -> Favorites -> Add a server -> Find servers at this address.

The test project code is as follows:

`using Steamworks;
using Steamworks.Data;
using Steamworks.ServerList;
using System.Threading.Tasks;
using UnityEngine;

public class SteamServerManager : MonoBehaviour {

    async void Start() {
        DontDestroyOnLoad(gameObject);

        try {
            SteamClient.Init(myAppId);
        }
        catch (System.Exception e) {
            Debug.Log(e);
            Debug.Log("SteamClient Init Failed");
            return;
        }
        Debug.Log("SteamClient connected");

        SteamServerInit serverInit = new SteamServerInit("", "MyGame") {
            GamePort = 27015,
            Secure = true,
            QueryPort = 27016
        };

        try {
            SteamServer.Init(myAppId, serverInit);
        }
        catch (System.Exception e) {
            Debug.Log(e);
            Debug.Log("SteamServer Init Failed");
            SteamClient.Shutdown();
            return;
        }
        Debug.Log("SteamServer connected");

        await GetServerList();
    }

    void Update() {
        
    }

    async Task GetServerList() {
        Debug.Log("Waiting 5s before updating");

        await Task.Delay(5000);

        Internet list = new Internet();

        await list.RunQueryAsync();

        foreach (ServerInfo server in list.Responsive) {
            Debug.Log("Server list response: " + server.Address + ", " + server.Name);
        }

        Debug.Log("Server Refresh Complete");
    }

    void OnDisable () {
        SteamClient.Shutdown();
        SteamServer.Shutdown();
    }

}`

**Comment by SVIk8** [comment]
Can you see your server with that?
http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001/?format=json&addr=***.***.***.***
(write host ip instead ***.***.***.***)

**Comment by garrynewman** [comment]
You need to call `SteamServer.LogOnAnonymous()` after the server is initialized

**Comment by malkere** [comment]
Thank you for the responses SVlk8 and Garry.

I added SteamServer.LogOnAnonymous() still no response from the foreach (ServerInfo... loop

I get
{"response":{"success":true,"servers":[]}}
from the api link

I've been trying to get Steamworks.NET for the past few days as well and got to this point with Steamworks.NET (just trying to get anything to work):
{"response":{"success":true,"servers":[{"addr":"<ip:port>","gmsindex":65534,"reject":"bad_version","appid":<appid>,"gamedir":"<myGame>","region":-1,"secure":false,"lan":false,"gameport":27015,"specport":0}]}}

I've been specifying the version as just "0"... I don't understand what it would be checking on the client side to verify that? There is no version specification built into the client logon that I'm aware of?

Facepunch.Steamworks has been recommended by a number of peers, I'd prefer to get it working, but am grasping at straws. I'll keep toying with it. These are just bare-bones projects to try and get the server list to respond before I add it to my actual game.

**Comment by Stormy102** [comment]
Try doing an [Nmap](https://nmap.org/download.html) scan on those specific ports
`nmap -p 27015-27016 [IP]`

**Comment by malkere** [comment]
Starting Nmap 7.70 ( https://nmap.org ) at 2019-05-27 21:03 Tokyo Standard Time
Nmap scan report for ec2-<ip>.ap-northeast-1.compute.amazonaws.com (<ip>)
Host is up (0.014s latency).
PORT      STATE    SERVICE
27015/tcp filtered unknown
27016/tcp filtered unknown
Nmap done: 1 IP address (1 host up) scanned in 3.03 seconds

**Comment by Stormy102** [comment]
If it is indicating that all ports are filtered, then the host is up, but the firewall on that host is dropping traffic to all the scanned ports. 
Having said that, it also uses UDP which doesn't necessarily play nice with Nmap. 
Double check your firewall and try running [Netcat](https://eternallybored.org/misc/netcat/) on one of these ports to try and connect and get the output. Most likely it is probably a firewall misconfig as I've had no problems doing it myself.

**Comment by malkere** [comment]
My game was originally built to listen on 5055, recently I added (first try) Steamworks.NET and just tried loading that up. That has an actively listening server, and is kind of showing up on the server list, some of the settings are wrong. Perhaps my test projects aren't working because there isn't something actively listening other than the Heartbeat?
I'll try adding a simple listener server into the Facepunch.Steamworks test project I opened with.

**Comment by malkere** [comment]
I added a Mirror server that is listening on 27015 and nmap is now showing 27015 as open, though 27016 tcp is still "closed" (maybe only using UDP?) though still nothing on Steam server list, both by game, or by adding manually.

Updated code:

`
public class SteamServerManager : MonoBehaviour {

    async void Start() {
        DontDestroyOnLoad(gameObject);

        try {
            SteamClient.Init(670260);
        }
        catch (System.Exception e) {
            Debug.Log(e);
            Debug.Log("SteamClient Init Failed");
            return;
        }
        Debug.Log("SteamClient connected");

        SteamServerInit serverInit = new SteamServerInit("", "Solace Crafting") {
            GamePort = 27015,
            Secure = true,
            QueryPort = 27016
        };

        try {
            SteamServer.Init(670260, serverInit);
        }
        catch (System.Exception e) {
            Debug.Log(e);
            Debug.Log("SteamServer Init Failed");
            SteamClient.Shutdown();
            return;
        }
        Debug.Log("SteamServer connected");

        SteamServer.LogOnAnonymous();
        await GetServerList();
    }

    async Task GetServerList() {
        Debug.Log("Waiting 5s before updating");
        await Task.Delay(5000);

        Internet list = new Internet();
        await list.RunQueryAsync();

        foreach (ServerInfo server in list.Responsive) {
            Debug.Log("Server list response: " + server.Address + ", " + server.Name);
        }
        Debug.Log("Server Refresh Complete");
    }

    void OnDisable () {
        SteamClient.Shutdown();
        SteamServer.Shutdown();
    }

}
`

and console output with Mirror debugs and "Fallback handler" stuff removed.

Setting breakpad minidump AppID = <appid>
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198966035391 [API loaded no]
SteamClient connected
SteamServer connected
Waiting 5s before updating
Server Refresh Complete

**Comment by malkere** [comment]
I met a guy in a Discord, shared his code with my from version 0.7:

```
    IEnumerator StartServer() {
        var serverInit = new ServerInit("FP07Test_Data", "My Game");
        serverInit.GamePort = 27015;
        serverInit.Secure = true;
        serverInit.QueryPort = 27016;
        serverInit.GameDescription = "My Game";
        serverInit.VersionString = Application.version;
        serverInit.ModDir = "FP07Test_Data";
        new Server(appId, serverInit);
        Server.Instance.ServerName = "Test Server";
        Server.Instance.DedicatedServer = true;
        Server.Instance.AutomaticHeartbeats = true;
        Server.Instance.MaxPlayers = 12;
        Server.Instance.LogOnAnonymous();
        Server.Instance.SetKey("Players", "00");
        Server.Instance.SetKey("Port", "27015");

        if (Server.Instance.IsValid) {
            yield return new WaitForSeconds(10f);
            Debug.Log("is valid");
            Debug.Log(Server.Instance.PublicIp);
            Debug.Log(Server.Instance.LoggedOn);
            Debug.Log(Server.Instance.ServerName);
        }
    }```
And this reports properly from the web api:
```{"response":{"success":true,"servers":[{"addr":"ip:27016","gmsindex":65534,"appid":appId,"gamedir":"FP07Test_Data","region":-1,"secure":true,"lan":false,"gameport":27015,"specport":0}]}}```
And shows up and responds on my favorite list, but still doesn't show up on the master list. Very much progress though! I should mention this server was connected to by a dozen people without problems. Still not on the internet server list though....

**Comment by malkere** [comment]
So I was looking at the Steamworks Dedicated Server settings and it says "Product name (also called mod dir or game dir)".... well in the Steamworks.NET examples it says to leave mod dir to "" unless you're your running a "mod" not the base game... Changing my ModDir = "MyGame" and now it's properly populating to the master server list =3

Thank you to everyone that offered suggestions.

**Comment by SVIk8** [comment]
Can you "see" server in Not responding servers? I got familiar problem. Solved it by turning firewall off. Try to turn it off until you'll find server.

**Comment by malkere** [comment]
no, client could connect to the server fine, and I could in fact ping the server in Steam by manually adding it to my favorites list. the modDir was set to an empty string though and because I have "Product name" in my Steamworks settings set to my game, not blank, it was being removed from the server list. Most people probably don't navigate to the "Dedicated Servers" section of Steamworks and end up leaving it blank I guess, but as soon as I had my modDir and Product Name matching the server now shows up on the Internet list right away.

**Comment by JamieShelley** [comment]
@malkere  Could you please tell me where to find the correct version string?
