### ISSUE TITLE
Can´t hear my voice

### ISSUE THREAD

**Issue by BurSari92** [Facepunch/Facepunch.Steamworks#261]
Hi,I´m sorry, I know this is not the right place to ask for help, but unfortunately no one answered me on unity forums..

I am trying to get my voice first, which I want to send to connected lobby members later on.
But the only thing I am able to hear are strange beep noises..

    void Update()
    {
        VoiceChat();
    }
 
    void VoiceChat()
    {
        var stream = new System.IO.MemoryStream();
        var output= new System.IO.MemoryStream();
 
        SteamUser.VoiceRecord = Input.GetKeyDown(KeyCode.K);
 
        if (SteamUser.HasVoiceData)
        {
            int length = SteamUser.ReadVoiceData(stream);
            SteamUser.DecompressVoice(stream, length, output);
 
            AudioClip audioClip = AudioClip.Create("VOICE", length, 1, 22050, false);
            float[] floatArray = new float[length / 2];
            print(floatArray.Length);
            for (int i = 0; i < floatArray.Length; i++)
            {
                try
                {
                    floatArray[i] = (short)(stream.GetBuffer()[i * 2] | stream.GetBuffer()[i * 2 + 1] << 8) / 32768.0f;
                }
                catch
                {
                    break;
                }
            }
            audioClip.SetData(floatArray, 0);
            GetComponent<AudioSource>().clip = audioClip;
            GetComponent<AudioSource>().Play();
        }
    }

I also tried "output" instead of "stream" everywhere unsuccessfully, but I think SteamUser.DecompressVoice is not doing anything at all (am I using it uncorrectly?).

**Comment by garrynewman** [comment]
Here's what I can see is different from our implementation in Rust:

1. You need to make AudioClip use `Steamworks.SteamUser.OptimalSampleRate` instead of 22050
2. I think you need to make floatArray quite big and keep adding to the end of it (and loop around back to the start). The voice data is going to be really short. You should only make one audioclip.

Here's some useful snippets from our code

```csharp
optimalRate = Steamworks.SteamUser.OptimalSampleRate;
bufferSize = optimalRate * 5;
buffer = new float[bufferSize];

mouthSpeaker.clip = AudioClip.Create( "VoiceData", (int)256, 1, (int)optimalRate, true, OnAudioRead, null );
mouthSpeaker.loop = true;

private void OnAudioRead( float[] data )
{
	for ( int i = 0; i < data.Length; ++i )
	{
		data[i] = 0;

		if ( playbackBuffer > 0 )
		{
			dataPosition++;
			playbackBuffer -= 1;

			data[i] = buffer[dataPosition % bufferSize];
		}
	}
}

void WriteToClip( byte[] uncompressed, int iSize )
{
	for ( int i=0; i < iSize; i += 2 )
	{
		WriteToClip( (short)( uncompressed[i] | uncompressed[i + 1] << 8 ) / 32767.0f );
	}
}

void WriteToClip( float f )
{
	buffer[dataReceived % bufferSize] = f;
	dataReceived++;
	playbackBuffer++;
}

```

**Comment by BurSari92** [comment]
Thank you very much Garry!
I will try this out, when I am back home :)

**Comment by TFlippy** [comment]
Doesn't seem to be working for me either. 

While **SteamUser.ReadVoiceData(Stream stream)** works fine (varying sample rates, from 11025 to the default 24000), but **SteamUser.DecompressVoice(Stream input, int length, Stream output)** returns 0 and doesn't write anything to the output stream.

Both streams' initial capacity is also set to 11025 (never seems to exceed 800 anyway).

**Comment by kristianpiacenti** [comment]
This is my implementation of Garry's code in case anyone finds useful #495 #530 

``` C#

using Mirror;
using Steamworks;
using System.IO;
using UnityEngine;

public class VoiceChat : NetworkBehaviour
{
    [SerializeField]
    private AudioSource source;

    private MemoryStream output;
    private MemoryStream stream;
    private MemoryStream input;

    private int optimalRate;
    private int clipBufferSize;
    private float[] clipBuffer;

    private int playbackBuffer;
    private int dataPosition;
    private int dataReceived;

    private void Start()
    {
        optimalRate = (int)SteamUser.OptimalSampleRate;

        clipBufferSize = optimalRate * 5;
        clipBuffer = new float[clipBufferSize];

        stream = new MemoryStream();
        output = new MemoryStream();
        input = new MemoryStream();

        source.clip = AudioClip.Create("VoiceData", (int)256, 1, (int)optimalRate, true, OnAudioRead, null);
        source.loop = true;
        source.Play();
    }

    [ClientCallback]
    private void Update()
    {
        SteamUser.VoiceRecord = Input.GetKey(KeyCode.V);

        if (SteamUser.HasVoiceData)
        {
            int compressedWritten = SteamUser.ReadVoiceData(stream);
            stream.Position = 0;

            CmdVoice(stream.GetBuffer(), compressedWritten);
        }

    }

    [Command()]
    public void CmdVoice(byte[] compressed, int bytesWritten)
    {
        RpcVoiceData(compressed, bytesWritten);
    }


    [ClientRpc(excludeOwner = true)]
    public void RpcVoiceData(byte[] compressed, int bytesWritten)
    {
        input.Write(compressed, 0, bytesWritten);
        input.Position = 0;

        int uncompressedWritten = SteamUser.DecompressVoice(input, bytesWritten, output);
        input.Position = 0;

        byte[] outputBuffer = output.GetBuffer();
        WriteToClip(outputBuffer, uncompressedWritten);
        output.Position = 0;
    }

    [Client]
    private void OnAudioRead(float[] data)
    {
        for (int i = 0; i < data.Length; ++i)
        {
            // start with silence
            data[i] = 0;

            // do I  have anything to play?
            if (playbackBuffer > 0)
            {
                // current data position playing
                dataPosition = (dataPosition + 1) % clipBufferSize;

                data[i] = clipBuffer[dataPosition];

                playbackBuffer --;
            }
        }

    }

    [Client]
    private void WriteToClip(byte[] uncompressed, int iSize)
    {
        for (int i = 0; i < iSize; i += 2)
        {
            // insert converted float to buffer
            float converted = (short)(uncompressed[i] | uncompressed[i + 1] << 8) / 32767.0f;
            clipBuffer[dataReceived] = converted;

            // buffer loop
            dataReceived = (dataReceived +1) % clipBufferSize;

            playbackBuffer++;
        }
    }

}
```

**Comment by BurSari92** [comment]
@kristianpiacenti 
WOW, what a surprise - it works like a charm!
Thank you very much Kristian, you just solved my problem, on which I gave up 2 years ago xD
Now I have the will to start my project again! :)

**Comment by sanj81640** [comment]
One problem Kristian. In the update you should get the subset of bytes that were written. Otherwise, you're sending the entire stream. I think you can just copy the first (compressed written) number of bytes to a new byte[], and that is all you need to send via command.

**Comment by kadiryumlu** [comment]
> This is my implementation of Garry's code in case anyone finds useful #495 #530
> 
> ```cs
> using Mirror;
> using Steamworks;
> using System.IO;
> using UnityEngine;
> 
> public class VoiceChat : NetworkBehaviour
> {
>     [SerializeField]
>     private AudioSource source;
> 
>     private MemoryStream output;
>     private MemoryStream stream;
>     private MemoryStream input;
> 
>     private int optimalRate;
>     private int clipBufferSize;
>     private float[] clipBuffer;
> 
>     private int playbackBuffer;
>     private int dataPosition;
>     private int dataReceived;
> 
>     private void Start()
>     {
>         optimalRate = (int)SteamUser.OptimalSampleRate;
> 
>         clipBufferSize = optimalRate * 5;
>         clipBuffer = new float[clipBufferSize];
> 
>         stream = new MemoryStream();
>         output = new MemoryStream();
>         input = new MemoryStream();
> 
>         source.clip = AudioClip.Create("VoiceData", (int)256, 1, (int)optimalRate, true, OnAudioRead, null);
>         source.loop = true;
>         source.Play();
>     }
> 
>     [ClientCallback]
>     private void Update()
>     {
>         SteamUser.VoiceRecord = Input.GetKey(KeyCode.V);
> 
>         if (SteamUser.HasVoiceData)
>         {
>             int compressedWritten = SteamUser.ReadVoiceData(stream);
>             stream.Position = 0;
> 
>             CmdVoice(stream.GetBuffer(), compressedWritten);
>         }
> 
>     }
> 
>     [Command()]
>     public void CmdVoice(byte[] compressed, int bytesWritten)
>     {
>         RpcVoiceData(compressed, bytesWritten);
>     }
> 
> 
>     [ClientRpc(excludeOwner = true)]
>     public void RpcVoiceData(byte[] compressed, int bytesWritten)
>     {
>         input.Write(compressed, 0, bytesWritten);
>         input.Position = 0;
> 
>         int uncompressedWritten = SteamUser.DecompressVoice(input, bytesWritten, output);
>         input.Position = 0;
> 
>         byte[] outputBuffer = output.GetBuffer();
>         WriteToClip(outputBuffer, uncompressedWritten);
>         output.Position = 0;
>     }
> 
>     [Client]
>     private void OnAudioRead(float[] data)
>     {
>         for (int i = 0; i < data.Length; ++i)
>         {
>             // start with silence
>             data[i] = 0;
> 
>             // do I  have anything to play?
>             if (playbackBuffer > 0)
>             {
>                 // current data position playing
>                 dataPosition = (dataPosition + 1) % clipBufferSize;
> 
>                 data[i] = clipBuffer[dataPosition];
> 
>                 playbackBuffer --;
>             }
>         }
> 
>     }
> 
>     [Client]
>     private void WriteToClip(byte[] uncompressed, int iSize)
>     {
>         for (int i = 0; i < iSize; i += 2)
>         {
>             // insert converted float to buffer
>             float converted = (short)(uncompressed[i] | uncompressed[i + 1] << 8) / 32767.0f;
>             clipBuffer[dataReceived] = converted;
> 
>             // buffer loop
>             dataReceived = (dataReceived +1) % clipBufferSize;
> 
>             playbackBuffer++;
>         }
>     }
> 
> }
> ```

Good but playback is not smooth. I have got some flickeriring souds. Do you have any advice to fix or any improved code sample?

**Comment by kristianpiacenti** [comment]
> > This is my implementation of Garry's code in case anyone finds useful #495 #530
> > ```cs
> > using Mirror;
> > using Steamworks;
> > using System.IO;
> > using UnityEngine;
> > 
> > public class VoiceChat : NetworkBehaviour
> > {
> >     [SerializeField]
> >     private AudioSource source;
> > 
> >     private MemoryStream output;
> >     private MemoryStream stream;
> >     private MemoryStream input;
> > 
> >     private int optimalRate;
> >     private int clipBufferSize;
> >     private float[] clipBuffer;
> > 
> >     private int playbackBuffer;
> >     private int dataPosition;
> >     private int dataReceived;
> > 
> >     private void Start()
> >     {
> >         optimalRate = (int)SteamUser.OptimalSampleRate;
> > 
> >         clipBufferSize = optimalRate * 5;
> >         clipBuffer = new float[clipBufferSize];
> > 
> >         stream = new MemoryStream();
> >         output = new MemoryStream();
> >         input = new MemoryStream();
> > 
> >         source.clip = AudioClip.Create("VoiceData", (int)256, 1, (int)optimalRate, true, OnAudioRead, null);
> >         source.loop = true;
> >         source.Play();
> >     }
> > 
> >     [ClientCallback]
> >     private void Update()
> >     {
> >         SteamUser.VoiceRecord = Input.GetKey(KeyCode.V);
> > 
> >         if (SteamUser.HasVoiceData)
> >         {
> >             int compressedWritten = SteamUser.ReadVoiceData(stream);
> >             stream.Position = 0;
> > 
> >             CmdVoice(stream.GetBuffer(), compressedWritten);
> >         }
> > 
> >     }
> > 
> >     [Command()]
> >     public void CmdVoice(byte[] compressed, int bytesWritten)
> >     {
> >         RpcVoiceData(compressed, bytesWritten);
> >     }
> > 
> > 
> >     [ClientRpc(excludeOwner = true)]
> >     public void RpcVoiceData(byte[] compressed, int bytesWritten)
> >     {
> >         input.Write(compressed, 0, bytesWritten);
> >         input.Position = 0;
> > 
> >         int uncompressedWritten = SteamUser.DecompressVoice(input, bytesWritten, output);
> >         input.Position = 0;
> > 
> >         byte[] outputBuffer = output.GetBuffer();
> >         WriteToClip(outputBuffer, uncompressedWritten);
> >         output.Position = 0;
> >     }
> > 
> >     [Client]
> >     private void OnAudioRead(float[] data)
> >     {
> >         for (int i = 0; i < data.Length; ++i)
> >         {
> >             // start with silence
> >             data[i] = 0;
> > 
> >             // do I  have anything to play?
> >             if (playbackBuffer > 0)
> >             {
> >                 // current data position playing
> >                 dataPosition = (dataPosition + 1) % clipBufferSize;
> > 
> >                 data[i] = clipBuffer[dataPosition];
> > 
> >                 playbackBuffer --;
> >             }
> >         }
> > 
> >     }
> > 
> >     [Client]
> >     private void WriteToClip(byte[] uncompressed, int iSize)
> >     {
> >         for (int i = 0; i < iSize; i += 2)
> >         {
> >             // insert converted float to buffer
> >             float converted = (short)(uncompressed[i] | uncompressed[i + 1] << 8) / 32767.0f;
> >             clipBuffer[dataReceived] = converted;
> > 
> >             // buffer loop
> >             dataReceived = (dataReceived +1) % clipBufferSize;
> > 
> >             playbackBuffer++;
> >         }
> >     }
> > 
> > }
> > ```
> 
> Good but playback is not smooth. I have got some flickeriring souds. Do you have any advice to fix or any improved code sample?

Probably like @sanj81640 said it can help to send an ArraySegment<byte> that has only the part of the buffer written.
Here some snippets of code from my other project in Godot if that can be useful.

<b>Send the packet</b>

`Client_SendVoice(new ArraySegment<byte>(_compressedVoiceStream.GetBuffer(), 0, numBytesWritten));
`


<b>Receive the packet</b>
```
private void Client_OnVoicePacketReceived(VoicePacket packet, Connection from)
{
      ArraySegment<byte> compressedVoiceData = packet.compressedVoiceData;

      DecompressAndListenVoiceData(compressedVoiceData);
}
```

```
private void DecompressAndListenVoiceData(ArraySegment<byte> voiceData)
{
    InitializeSpeaker();

    pcmSamples.Clear();

    _compressedVoiceStream.Position = 0;
    _compressedVoiceStream.Write(voiceData);

    _compressedVoiceStream.Position = 0;
    _decompressedVoiceStream.Position = 0;

    int numBytesWritten = SteamUser.DecompressVoice(_compressedVoiceStream, voiceData.Count, _decompressedVoiceStream);

    _decompressedVoiceStream.Position = 0;
    while (_decompressedVoiceStream.Position < numBytesWritten)
    {
        byte byte1 = (byte)_decompressedVoiceStream.ReadByte();
        byte byte2 = (byte)_decompressedVoiceStream.ReadByte();

        short pcmShort = (short)((byte2 << 8) | (byte1 << 0));
        float pcmFloat = Convert.ToSingle(pcmShort) / short.MaxValue;

        pcmSamples.Add(pcmShort);

        _streamingReadQueue.Enqueue(pcmFloat);
    }

    CurrentRMS = CalculateRMS(pcmSamples);
    // GD.Print(CurrentRMS);
    int framesAvailable = playback.GetFramesAvailable();
    // GD.Print($"Frames Available {framesAvailable}");
    for (int i = 0; i < _streamingReadQueue.Count; i++)
    {
        Vector2 data = new Vector2(0, 0);
        if (_streamingReadQueue.TryDequeue(out float sample))
        {
            data = new Vector2(sample, sample);
        }
        playback.PushFrame(data);
    }
}
```

**Comment by schouffy** [comment]
@kristianpiacenti's implementation, sending only the new bytes in each frame, using Netcode for GameObjects:

`public class VoiceChat : NetworkBehaviour
{
    public AudioSource AudioSource;

    private MemoryStream uncompressedStream;
    private MemoryStream voiceStream;
    private MemoryStream compressedStream;

    private float[] audioclipBuffer;
    private int audioclipBufferSize;

    private int playbackBuffer;
    private int dataPosition;
    private int dataReceived;

    void Start()
    {
        voiceStream = new MemoryStream();
        uncompressedStream = new MemoryStream();
        compressedStream = new MemoryStream();

        int optimalRate = (int)SteamUser.OptimalSampleRate;

        audioclipBufferSize = optimalRate * 5;
        audioclipBuffer = new float[audioclipBufferSize];

        AudioSource.clip = AudioClip.Create("VoiceData", (int)256, 1, (int)optimalRate, true, OnAudioRead, null);
        AudioSource.loop = true;
        AudioSource.Play();

        // TODO for this example it always records but you should push to talk or have a setting
        SteamUser.VoiceRecord = true;
    }

    void Update()
    {
        if (SteamUser.HasVoiceData)
        {
            int compressedRead = SteamUser.ReadVoiceData(voiceStream);
            voiceStream.Position = 0;
            var bytes = new System.ArraySegment<byte>(voiceStream.GetBuffer(), 0, compressedRead);
            SendVoiceServerRpc(bytes.Array, compressedRead, OwnerClientId);
        }
    }

    [ServerRpc(RequireOwnership = false)]
    public void SendVoiceServerRpc(byte[] compressed, int length, ulong clientId)
    {
        // TODO here you should only call clientrpc on clients other than clientId
        PlayVoiceClientRpc(compressed, length);
    }

    [ClientRpc]
    public void PlayVoiceClientRpc(byte[] compressed, int length)
    {
        compressedStream.Position = 0;
        compressedStream.Write(compressed, 0, length);
        compressedStream.Position = 0;

        uncompressedStream.Position = 0;
        int uncompressedWritten = SteamUser.DecompressVoice(compressedStream, length, uncompressedStream);

        byte[] outputBuffer = uncompressedStream.GetBuffer();
        WriteToClip(outputBuffer, uncompressedWritten);
    }

    private void OnAudioRead(float[] data)
    {
        for (int i = 0; i < data.Length; ++i)
        {
            // start with silence
            data[i] = 0;

            // do I  have anything to play?
            if (playbackBuffer > 0)
            {
                // current data position playing
                dataPosition = (dataPosition + 1) % audioclipBufferSize;

                data[i] = audioclipBuffer[dataPosition];

                playbackBuffer--;
            }
        }

    }

    private void WriteToClip(byte[] uncompressed, int iSize)
    {
        for (int i = 0; i < iSize; i += 2)
        {
            // insert converted float to buffer
            float converted = (short)(uncompressed[i] | uncompressed[i + 1] << 8) / 32767.0f;
            audioclipBuffer[dataReceived] = converted;

            // buffer loop
            dataReceived = (dataReceived + 1) % audioclipBufferSize;

            playbackBuffer++;
        }
    }

    public override void OnDestroy()
    {
        SteamUser.VoiceRecord = false;
        base.OnDestroy();
    }
}`

**Comment by schouffy** [comment]
I spent some more time on it because I still had some playback issues. Turns out this code is not really usable as-is:
- the buffer is filled through some clientRpc
- the buffer is read through Unity audio system in OnAudioRead

These are triggered at different times and different frequencies, so if you try to feed the audioclip directly in the RPC, you'll have issues. You have to bufferize somehow. I did an implementation using a Queue. So your clientRpc will enqueue buffers, and then regularly you dequeue from there to put in your AudioclipBuffer. You should have some sort of latency constant that can "absorb" the RPCs lag spikes.

I probably don't explain it very well but after I've done that I don't seem to have playback issues at all.
Something like this:

```
private void OnAudioRead(float[] data)
{
    for (int i = 0; i < data.Length; ++i)
    {
        // start with silence
        data[i] = 0;

        // do I  have anything to play?
        if (playbackBuffer > 0)
        {
            // current data position playing
            audioPlayerPosition = (audioPlayerPosition + 1) % audioclipBufferSize;
            data[i] = audioclipBuffer[audioPlayerPosition];
            playbackBuffer--;
        }
    }
}

internal void Update()
{
    while (true)
    {
        if (_pendingBuffers.Count == 0 || _pendingBuffers.ElementAt(0).ReadTime > Time.time)
            break;

        var pending = _pendingBuffers.Dequeue();
        WriteToClip(pending.Buffer, pending.Size);
    }
}

public void WriteToClip(byte[] uncompressed, int iSize)
{
    for (int i = 0; i < iSize; i += 2)
    {
        // insert converted float to buffer
        audioclipBuffer[dataReceived] = (short)(uncompressed[i] | uncompressed[i + 1] << 8) / 32767.0f;

        // buffer loop
        dataReceived = (dataReceived + 1) % audioclipBufferSize;

        playbackBuffer++;
    }
}

// This is what your clientRpc calls
internal void Append(float time, byte[] buffer, int size)
{
    _pendingBuffers.Enqueue(new PendingBuffer { ReadTime = time + LatencyBuffer, Buffer = buffer.ToArray() /* copy */, Size = size });
}
```

**Comment by GonzalitoL** [comment]
> I spent some more time on it because I still had some playback issues. Turns out this code is not really usable as-is:
> 
> * the buffer is filled through some clientRpc
> * the buffer is read through Unity audio system in OnAudioRead
> 
> These are triggered at different times and different frequencies, so if you try to feed the audioclip directly in the RPC, you'll have issues. You have to bufferize somehow. I did an implementation using a Queue. So your clientRpc will enqueue buffers, and then regularly you dequeue from there to put in your AudioclipBuffer. You should have some sort of latency constant that can "absorb" the RPCs lag spikes.
> 
> I probably don't explain it very well but after I've done that I don't seem to have playback issues at all. Something like this:
> 
> ```
> private void OnAudioRead(float[] data)
> {
>     for (int i = 0; i < data.Length; ++i)
>     {
>         // start with silence
>         data[i] = 0;
> 
>         // do I  have anything to play?
>         if (playbackBuffer > 0)
>         {
>             // current data position playing
>             audioPlayerPosition = (audioPlayerPosition + 1) % audioclipBufferSize;
>             data[i] = audioclipBuffer[audioPlayerPosition];
>             playbackBuffer--;
>         }
>     }
> }
> 
> internal void Update()
> {
>     while (true)
>     {
>         if (_pendingBuffers.Count == 0 || _pendingBuffers.ElementAt(0).ReadTime > Time.time)
>             break;
> 
>         var pending = _pendingBuffers.Dequeue();
>         WriteToClip(pending.Buffer, pending.Size);
>     }
> }
> 
> public void WriteToClip(byte[] uncompressed, int iSize)
> {
>     for (int i = 0; i < iSize; i += 2)
>     {
>         // insert converted float to buffer
>         audioclipBuffer[dataReceived] = (short)(uncompressed[i] | uncompressed[i + 1] << 8) / 32767.0f;
> 
>         // buffer loop
>         dataReceived = (dataReceived + 1) % audioclipBufferSize;
> 
>         playbackBuffer++;
>     }
> }
> 
> internal void Append(float time, byte[] buffer, int size)
> {
>     _pendingBuffers.Enqueue(new PendingBuffer { ReadTime = time + .5f /* latency buffer */, Buffer = buffer, Size = size });
> }
> 
> [ClientRpc]
> public void PlayVoiceClientRpc(byte[] compressed, int length)
> {
>     compressedStream.Position = 0;
>     compressedStream.Write(compressed, 0, length);
>     compressedStream.Position = 0;
> 
>     uncompressedStream.Position = 0;
>     
>     int uncompressedWritten = SteamUser.DecompressVoice(compressedStream, length, uncompressedStream);
> 
>     // ToArray to copy it, because otherwise all the appends will share the same underlying array. This can maybe be pooled to avoid too many allocations
>     byte[] outputBuffer = uncompressedStream.GetBuffer().ToArray();
>     Append(Time.time, outputBuffer, uncompressedWritten);
> }
> ```

Hi! I'm having the same problem you had in you previos reply, coud you share the full script you used for this? I can not get it to work correctly.
Regardless, your code was super super helpfull. Thanks a lot schouffy!

**Comment by JustLoren** [comment]
I've taken schouffy's snippets and adapted them to my solution, which is a Unity + Mirror solution. In game, it's not flawless, as the latency can very occasionally spike above the .5sec he's got setup as a buffer. His setup future-dates any received packet and only processes it when that Time comes to pass. This means that so long as your packets are received with less than .5s latency, they should be smoothly played together. It also means that every time people speak, there's a guaranteed .5s delay. I may work on solving some of this and update this post, or maybe it's in a "good enough" condition for my needs.

Here it is:

```using Mirror;
using Steamworks;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;

public class VoiceChat : NetworkBehaviour
{
    public AudioSource AudioSource;

    private MemoryStream uncompressedStream;
    private MemoryStream voiceStream;
    private MemoryStream compressedStream;

    private float[] audioclipBuffer;
    private int audioclipBufferSize;
    private int audioPlayerPosition;

    private int playbackBuffer;
    private int dataReceived;

    public override void OnStartLocalPlayer()
    {
        voiceStream = new MemoryStream();

        // TODO for this example it always records but you should push to talk or have a setting
        SteamUser.VoiceRecord = true;

        base.OnStartLocalPlayer();
    }

    public override void OnStartClient()
    {
        uncompressedStream = new MemoryStream();
        compressedStream = new MemoryStream();

        int optimalRate = (int)SteamUser.OptimalSampleRate;

        audioclipBufferSize = optimalRate * 5;
        audioclipBuffer = new float[audioclipBufferSize];

        // Here optimalRate * 2 seems to be what fixes the playback issues
        AudioSource.clip = AudioClip.Create("VoiceData", (int)optimalRate * 2, 1, (int)optimalRate, true, OnAudioRead, null);
        AudioSource.loop = true;
        AudioSource.Play();

        base.OnStartClient();
    }

    private void OnAudioRead(float[] data)
    {
        for (int i = 0; i < data.Length; ++i)
        {
            // start with silence
            data[i] = 0;

            // do I  have anything to play?
            if (playbackBuffer > 0)
            {
                // current data position playing
                audioPlayerPosition = (audioPlayerPosition + 1) % audioclipBufferSize;
                data[i] = audioclipBuffer[audioPlayerPosition];
                playbackBuffer--;
            }
        }
    }

    internal void Update()
    {
        //Recording from mic and sending to server
        if (isLocalPlayer)
        {
            if (SteamUser.HasVoiceData)
            {
                int compressedRead = SteamUser.ReadVoiceData(voiceStream);
                voiceStream.Position = 0;
                var bytes = new System.ArraySegment<byte>(voiceStream.GetBuffer(), 0, compressedRead);
                SendVoiceCmd(bytes.Array, compressedRead);
            }
        }

        //This bit is for playing what we received from the server
        while (_pendingBuffers.Count > 0 && _pendingBuffers.ElementAt(0).ReadTime <= Time.time)
        {
            var pending = _pendingBuffers.Dequeue();
            WriteToClip(pending.Buffer, pending.Size);
        }
    }

    public void WriteToClip(byte[] uncompressed, int iSize)
    {
        for (int i = 0; i < iSize; i += 2)
        {
            // insert converted float to buffer
            audioclipBuffer[dataReceived] = (short)(uncompressed[i] | uncompressed[i + 1] << 8) / 32767.0f;

            // buffer loop
            dataReceived = (dataReceived + 1) % audioclipBufferSize;

            playbackBuffer++;
        }
    }

    internal void Append(float time, byte[] buffer, int size)
    {
        _pendingBuffers.Enqueue(new PendingBuffer { ReadTime = time + .5f /* latency buffer */, Buffer = buffer, Size = size });
    }
    private Queue<PendingBuffer> _pendingBuffers = new();

    private class PendingBuffer
    {
        public float ReadTime { get; set; }
        public byte[] Buffer { get; set; }
        public int Size { get; set; }
    }

    [Command]
    public void SendVoiceCmd(byte[] compressed, int length)
    {
        // TODO here you should only call clientrpc on clients other than clientId
        PlayVoiceClientRpc(compressed, length);
    }

    [ClientRpc(includeOwner = true)]
    public void PlayVoiceClientRpc(byte[] compressed, int length)
    {
        compressedStream.Position = 0;
        compressedStream.Write(compressed, 0, length);
        compressedStream.Position = 0;

        uncompressedStream.Position = 0;

        int uncompressedWritten = SteamUser.DecompressVoice(compressedStream, length, uncompressedStream);

        // ToArray to copy it, because otherwise all the appends will share the same underlying array. This can maybe be pooled to avoid too many allocations
        byte[] outputBuffer = uncompressedStream.GetBuffer().ToArray();
        Append(Time.time, outputBuffer, uncompressedWritten);
    }

    public override void OnStopLocalPlayer()
    {
        SteamUser.VoiceRecord = false;

        base.OnStopLocalPlayer();
    }
}
