### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BigBadLoser** [Facepunch/Facepunch.Steamworks#262]
Where can I find the documentation for this?

**Comment by garrynewman** [comment]
I'll try to write something up over the next few days

**Comment by garrynewman** [comment]
How is this?

https://github.com/Facepunch/Facepunch.Steamworks/wiki/Client---Getting-Started

**Comment by BigBadLoser** [comment]
> How is this?
> 
> https://github.com/Facepunch/Facepunch.Steamworks/wiki/Client---Getting-Started

Yes, that's really helpful. Between this and the code snippets you reply with on issues, I can pretty fairly understand what's going on
