### ISSUE TITLE
RestartIfNecessary always returns true

### ISSUE THREAD

**Issue by Lotiuss** [Facepunch/Facepunch.Steamworks#263]
I'm using the 0.7.5 NuGet package with a wpf app and having an issue with the RestartIfNecessary method. For some reason it's always returning true, even when I launch via the Launch button in steam.

From the docs:
"If this returns true then it starts the Steam client if required and launches your game again through it, and you should quit your process as soon as possible."

```
private void Application_Startup(object sender, StartupEventArgs e)
{
   try
   {
      if (Facepunch.Steamworks.Client.RestartIfNecessary(_myAppID))
      {
         Application.Current.Shutdown();
      }
      else
      {
         // do startup stuff, like create a Facepunch.Steamworks.Client, set startup uri, etc
      }
   }
   catch (Exception)
   {
   }
}
```
A steam_appid.txt file in the executable directory also makes no difference.

Any ideas?

**Comment by garrynewman** [comment]
We've never really used RestartIfNecessary in any of our games, I've never seen the point of it. My advice would be to skip it unless you have some actual reason to use it.

**Comment by Lotiuss** [comment]
Yea, I'll just skip it. It was never really a priority - I just wasn't sure if I misread something and was using it wrong. It is the only option for .NET though because the wrapper won't work.

**Comment by Wikzo** [comment]
Sorry for opening this again. As far as I understand https://partner.steamgames.com/doc/sdk/api#SteamAPI_RestartAppIfNecessary, this is a good way to ensure Steam is running if a player opens the exe file manually outside of Steam. Is there a way to do this with Facepunch?

**Comment by garrynewman** [comment]
There's no real point. Once you load the library it's just like running it through steam.. everything works the same.. steam knows you're in the game - it shows your friends you're in the game, you can use all the same function calls.

**Comment by Wikzo** [comment]
> There's no real point. Once you load the library it's just like running it through steam.. everything works the same.. steam knows you're in the game - it shows your friends you're in the game, you can use all the same function calls.

Not sure I understand. If Steam is closed and the player opens the exe file manually, then how can the Steam library be loaded? As I wrote in https://github.com/Facepunch/Facepunch.Steamworks/issues/275, I'd like the game to quit itself if the player doesn't own the game on Steam (maybe this approach is bad in general and I should do something else entirely?). Wouldn't it be natural for the game to automatically opening Steam if it's not already running?

**Comment by garrynewman** [comment]
Oh sorry - I didn't realise it was actually meant to open Steam - let me look into it.

**Comment by garrynewman** [comment]
Okay - I've added this function to SteamClient.RestartAppIfNecessary.

What I would say is that you might want to isolate this call to release builds only. During development it's likely to always return true - because it wasn't called via Steam.

**Comment by Wikzo** [comment]
> Okay - I've added this function to SteamClient.RestartAppIfNecessary.
> 
> What I would say is that you might want to isolate this call to release builds only. During development it's likely to always return true - because it wasn't called via Steam.

Thanks! I probably won't have time to test it right now, but when I do, I'll let you know if it works as intended :)

**Comment by Agoxandr** [comment]
@Wikzo As far as I understand you can just put the AppId.txt into the game folder and RestartAppIfNecessary wont restart the game.

The point is that you can crash the executable yourself, if you cant log into Steam without using a flag that some genius at Valve made up.
