### ISSUE TITLE
Add FAQ Disclaimer about Steam not recognizing SteamClient.Shutdown() when the game is run from within the Unity Editor

### ISSUE THREAD

**Issue by Simerax** [Facepunch/Facepunch.Steamworks#264]
### Steam does not recognize that the Game is closed after using SteamClient.Shutdown()
When you play your game within the Unity Editor and call SteamClient.Shutdown() Steam will not recognize that your game is actually closed. This is because the Editor and the Unity Hub still run in the background.

Yes this is a "problem" (if you even want to call it a problem) within Unity and not the wrapper. However I think this behaviour could confuse users of the wrapper and make them look for the problem in the wrong spot.

Maybe add something like this to the FAQ:

## [UnityEngine] Steam does not recognize that my Game is closed after using SteamClient.Shutdown()

This is caused by the remaining Unity Processes still running (Unity Editor and Unity Hub). 
Make sure you also close the Editor and the Hub. After that Steam will recognize that you closed your Application.

**Comment by garrynewman** [comment]
Added something here: 

https://github.com/Facepunch/Facepunch.Steamworks/wiki/Client---Getting-Started
