### ISSUE TITLE
Server's fields

### ISSUE THREAD

**Issue by SVIk8** [Facepunch/Facepunch.Steamworks#265]
Hi.
I have some questions about server's fields.
The first one is keys. The only thing I found is Facepunch.Steamworks.Server.SetKey(). Are there any ways to delete key? And how to get them? ServerList.Server hasn't anything similar.
The second one is version. There is string Facepunch.Steamworks.ServerInit.VersionString and int ServerList.Server.Version. How do they match?

**Comment by malkere** [comment]
`        serverListQuery.Responded[selectedServer].FetchRules();

        while (!serverListQuery.Responded[selectedServer].HasRules) {
            yield return null;
        }

        foreach (KeyValuePair<string, string> pair in serverListQuery.Responded[selectedServer].Rules) {
            //whatev
        }`
Is how I do it. I'm running the old v0.7 though, not the latest alpha.

**Comment by SVIk8** [comment]
Thx a lot.

Player's count updates automaticly adding player auth ticket on server.

**Comment by malkere** [comment]
Ah I was starting to think that. I haven't gotten to auth yet, just letting players in for now.
