### ISSUE TITLE
SteamNetworking.OnP2PConnectionFailed should give an error message

### ISSUE THREAD

**Issue by benjaben** [Facepunch/Facepunch.Steamworks#267]
This keeps getting triggered every time I try to make a SendP2P call to a server
```
SteamNetworking.OnP2PConnectionFailed += (steamId) => Debug.Log("Failed to connect to " + steamId);
```
here is the SendP2P call to the server.
```
bool sent = SteamNetworking.SendP2PPacket(m_Servers[i].SteamId, m_Ticket.Data);
Debug.Log(sent);
```

I've been trying to figure out why it isn't working. The server shows up on the web api, but I'm not able to send any messages or anything to it at all. Would be nice to have an error behind why its broken.

The sent is always true also.

**Comment by Agoxandr** [comment]
I'm not sure how useful these error callbacks are if you can't connect.
https://partner.steamgames.com/doc/api/ISteamNetworking#P2PSessionConnectFail_t
https://partner.steamgames.com/doc/api/ISteamNetworking#EP2PSessionError
You could just go through the list and check if it setup correctly.
Maybe [this](https://partner.steamgames.com/doc/api/ISteamNetworking#GetP2PSessionState) will work.

**Comment by garrynewman** [comment]
Thanks - just added this - sorry for the delay
