### ISSUE TITLE
ISteamInput not generated

### ISSUE THREAD

**Issue by sqrMin1** [Facepunch/Facepunch.Steamworks#270]
I noticed that the interface **ISteamInput** is not getting generated, despite that the corresponding entries are set in the steam_api.json file.

Is there anything I can do to generate the ISteamInput interface or is the SteamInput feature coming in future versions of Facepunch.Steamworks?

**Comment by garrynewman** [comment]
I didn't realise it was something people used - I can definitely add that.

**Comment by garrynewman** [comment]
I've implemented this as far as I can - I can get it to show controllers but can't seem to capture input. Let me know if you have more luck.

**Comment by sqrMin1** [comment]
Thanks for adding the SteamInput interface; much appreciated.

I just tried your implementation for several hours till I figured it out how to receive input data from SteamInput (so I had success).

I encountered the same problems as you first and was unlucky to get any data. I noticed some things I want  to mention here as well as they might be helpful to pin down potencial issues.

1. The correct directory for the default ingame-actions-file (IGA) is `Steam Install Directory\controller_config` not the game directory itself.
2. This file should be named `game_actions_X.vdf` where X stands for the AppID.
**Example:** `D:\Programs\Steam\controller_config\game_actions_480.vdf`
3. It also seems to be necessarry to create a user config which is based on the IGA file.
**Example:** Start App. Open Overlay. Click Controller Configuration. Define Actions.
**Tip:** If the actions described in the default IGA appearing in the controller configuration overlay, then your file was taken / loaded correctly by steam (it's a good indicator for success).
4. The steam documentation recommends to create a user config from within BigPicture. However I successfully created and used the config without BigPicture, but it seems to be necessary to export the configuratoin through BigPicture when you are done with the whole setup. At least for the final release build / setting the official default configuration with the steam backend.
5. From the steam documentation: **"Make sure you set defaults for all your in-game action sets, not just the first one."**, but I currently don't know if this is technically necessary or just a reminder.
6. Launch your steam client with the following command line parameter: `-forcecontrollerappid your_game's_AppID `. This ensures that controllers are bound to the game window and nothing else, which could interfere with your debugging session.
**Example:** `D:\Programs\Steam\Steam.exe -forcecontrollerappid 480`
7. In your code make sure that you activate an ActionSet before trying to receive input data from this set.
8. Try it with your own AppID instead of 480. For me only my own AppID worked so far.

Aside from that I noticed something different and more critical. [This line](https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/Generated/Interfaces/ISteamInput.cs#L104) sometimes returns null, which fails the initialization, but still makes that the game launches and everything else besides SteamInput is working.

This happend because [this line](https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/SteamInput.cs#L15) sometimes said that _internal is not null, despite that it is or rather the game just starting up / intializes.

I don't know if this is something which happened only on my end during testing / debugging and maybe steam wasn't shut down correctly during that. However I commented out the if-statement to force the initialization and... then I suddenly started to receive SteamInput data for the first time. It even works now when I uncomment the line again. I don't know, it was a bit weird. I will further investigate and see if this happens again anytime soon.

With the info from this post it should be possible to receive input data from now on.

Hope this was helpful.

Oh, and thanks again for implementing this and your work on Facepunch.Steamworks!

**Comment by garrynewman** [comment]
Thanks for the write up. Jesus - they make it so easy eh ! I'll have a work through this and see if I can add the additional functionality.

**Comment by sqrMin1** [comment]
Just wanted to give a little update after another day testing SteamInput.

It also runs with different AppIDs (tested with AppID 480). Most important thing here is to don't forget to add a IGA file to the `Steam Install Directory\controller_config` folder and to run the steam client with `-forcecontrollerappid 480` (don't forget to update the AppID here when testing another app; otherwise you won't get connected controllers.).

Also the lines mentioned in my last post were never null during a day of testing. So it seems that it really was an issue on my end while testing it the first day.

I updated my last post accordingly.
