### ISSUE TITLE
Failed login on Steam still initiates Steamworks with appid, returns true on SteamClient.IsValid && SteamApps.IsSubscribed 

### ISSUE THREAD

**Issue by klaritan** [Facepunch/Facepunch.Steamworks#271]
1. Log on steam with the account that owns the appid.

2. Log off.

3. Do either: run steam (don't log in) / try to do a failed log in.

4. Run your executable that initiates the Steamworks

5. SteamClient.Init(appid) && SteamClient.IsValid && SteamApps.IsSubscribed  == true.

**Comment by thesupersoup** [comment]
Based on my understanding, I'm not sure this is an issue. IsValid simply returns true if Steam is running in any capacity. If you have methods which should be fetching specific user data, you might want to check IsLoggedOn, as that's what would enable Steam API functionality. Or don't check for it, as from what I understand it tests IsLoggedOn internally, and you don't need to necessarily worry yourself with it unless you have a specific purpose in mind and you know exactly how it will impact the user experience when that fails (i.e. Steam running in offline mode)

**Comment by klaritan** [comment]
The problem with IsLoggedOn is that, as you mentioned, it relies on Steam network, which goes down once or more every week. Our game supports offline mode so it's not a really good option.

The problem is not Steamworks reporting it during offline mode. The problem is when a user logs on to a different account that doesn't own the game, logs off, and then fails logging in with the original account, Steamworks still reports "IsSubscribed" to be true.
