### ISSUE TITLE
Examples/Guide on matchmaking

### ISSUE THREAD

**Issue by Lestat** [Facepunch/Facepunch.Steamworks#272]
the text (readme) is lacking examples and guidelines on matchmaking, creating/finding lobbies, starting the match etc :)

**Comment by Agoxandr** [comment]
Please take a look at the [tests](https://github.com/Facepunch/Facepunch.Steamworks/blob/362ba26729f9a4f600e77d85f1e7e2563b5af151/Facepunch.Steamworks.Test/SteamMatchmakingTest.cs).

**Comment by Lestat** [comment]
Thank you.

**Comment by Lestat** [comment]
about networking, im reading this test: https://github.com/Facepunch/Facepunch.Steamworks/blob/362ba26729f9a4f600e77d85f1e7e2563b5af151/Facepunch.Steamworks.Test/SteamNetworkingTest.cs

When I create the lobby and everyone has joined, I just send the messages and they will receive them? because im watching this OnP2PSessionRequest, I guess I have to accept it with AcceptP2PSessionWithUser  once the first message is received?

Also, once all have joined the lobby, I keep the lobby till the match finishes or do I cache the steamids of the other players and send messages leaving the lobby after the connection is accepted?

I just need someone who exp`lains to me how to do the matchmaking and networking session xd

I have this:

1. Search for lobbies, if one found, join it. if none, then create lobby with data ("map", currentmapselected)
2.-Once lobby is full (4 players). I start the match and start sending messages to the other members of the lobby.
3.???? will they just receive them? or do I have to accept the p2pconnection? do I leave the lobby or until the end of the match?

**Comment by Agoxandr** [comment]
I usually only distinguish between what message I sent where I know if its reliable or unreliable ahead of time. I also know of this page which roughly outlines how you would do Networking. https://partner.steamgames.com/doc/features/multiplayer/networking

I only use NetworkingSockets. They are easier to use in my opinion.
