### ISSUE TITLE
Encoding issue not fixed. Unable to upload to Workshop with title/description contains Asian characters

### ISSUE THREAD

**Issue by klaritan** [Facepunch/Facepunch.Steamworks#273]
https://github.com/Facepunch/Facepunch.Steamworks/pull/215

This is not fixed in v2 (latest commit).

When you try to upload a Workshop item with a title or description that contains Chinese/Korean/Japanese, it will fail and returns "InvalidParam".

In v1, this was fixed with a fork, but now that that work is outdated (v1), there is no wayw around it at the moment.

This is easily a unicode hadnling issue because

1. On their native computers, it will throw "InvalidParam".
2. On our computers (English), the entry will be uploaded with bunch of ??? ???? ?.

**Comment by garrynewman** [comment]
Can you show me the fork that fixed it before and I'll try to fix it in the main.

**Comment by garrynewman** [comment]
Okay - done - we should be in a much better position in now

**Comment by klaritan** [comment]
It looks good on our computers. Will report back once the players share the results.
