### ISSUE TITLE
Best way to check if player owns the game on Steam?

### ISSUE THREAD

**Issue by Wikzo** [Facepunch/Facepunch.Steamworks#275]
Hello. I am just getting started with Steamworks. I would like to ask what are the best ways to check that the player actually owns the game on Steam, so we can prevent people from just sharing the exe files manually?

My initial thought was to use SteamClient.IsValid, SteamAppsIsSubscribed and SteamApps.AppOwner, but after having read https://github.com/Facepunch/Facepunch.Steamworks/issues/271 I am not sure if this is the right way to do it.

**Comment by Wikzo** [comment]
Basically, I would like a way to check if the player owns the game on Steam, and if not, the game quits itself.

**Comment by garrynewman** [comment]
As far as I know the library won't initialize if they don't own the game

**Comment by Wikzo** [comment]
> As far as I know the library won't initialize if they don't own the game

I tried it on my friends computer (who doesn't own the game on Steam), but it seemed to work regardless. Was able to retrieve SteamClient.IsValid was TRUE.

**Comment by garrynewman** [comment]
Alright let me know

**Comment by Wikzo** [comment]
> Alright let me know

You were right. I did the mistake of using the wrong AppID. Just tried on two friends' computers (who don't own the game on Steam). As you said, the library won't initialize if they don't own it.

Issue can be closed :)

**Comment by garrynewman** [comment]
Perfect - thanks for investigating
