### ISSUE TITLE
AccessViolationException when using SteamUtils.OnSteamShutdown

### ISSUE THREAD

**Issue by klaritan** [Facepunch/Facepunch.Steamworks#279]
Use SteamUtils.OnSteamShutdown += Shutdown();
have "SteamClient.Shutdown()"; in the callback. 

Attempt to exit Steam. Steam will say "waiting for <game> to shut down...". Wait a few seconds and click "Exit Steam".
This will throw this:
https://i.imgur.com/G5bDDde.png

Is the Shutdown() call redundant?
The Shutdown() call feels necessary because the next time (after the Steam shutdown) any of the Steamworks calls is used, it will freeze the game.

**Comment by garrynewman** [comment]
I just took a look at this. I think you're right - we're trying to Shutdown but Steam is gone so all the pointers are invalid. I've handled this a bit better now - and you shouldn't need to call Shutdown because it should already be shut down.

**Comment by klaritan** [comment]
It looks like shutdown is now a lot better, but when we exit Steam without terminating the game, next time the Steam client launches (while the game was still being played with Steam features disabled), it is causing the same freezes when Steamworks is used (e.g. SteamClient.Init). The game does not crash, but simply freezes. It is completely okay while the Steam client is not running.

I had a Workshop query in a background thread so I didn't notice this, but that seemed to have been also frozen. Next time it was called in any of the game threads, it would just halt at any Steamworks method call.
