### ISSUE TITLE
Null reference exception on SteamNetworking.IsP2PPacketAvailable()

### ISSUE THREAD

**Issue by Roobubba** [Facepunch/Facepunch.Steamworks#280]
I'm working on integrating Facepunch.Steamworks into Forge Networking Remastered and have a working prototype here:
https://github.com/Roobubba/forge-facepunch-steamworksexample

Client joins steam lobby, client sends P2P packet to lobby owner who has the OnP2PSessionRequest callback set to accept all. On first attempt, the client has the following error:

```
Object reference not set to an instance of an object
  at Steamworks.ISteamNetworking.IsP2PPacketAvailable (System.UInt32& pcubMsgSize, System.Int32 nChannel) [0x00000] in <55a3ad92ff504373a23679fea4e17ddc>:0 
  at Steamworks.SteamNetworking.IsP2PPacketAvailable (System.Int32 channel) [0x00007] in <55a3ad92ff504373a23679fea4e17ddc>:0 
```

Subsequent connection attempts work fine.

To make my above example work, I have a horrible dirty hack: call SteamNetworking.CloseP2PSessionWithUser(0) early on in the menus to avoid a null ref exception that occurs on the client when attempting to connect to a server.

Without the dirty hack above, I *didn't* get the null ref exception when using the facepunch.steamworks.dll from Garry's UnityTest repo which I downloaded on 2019-06-18 at 10:26 GMT.
With exactly the same code - except requiring the extra P2PSessionError parameter in the OnP2PConnectionFailed callback - I then did and still do get the error on later versions of Facepunch.Steamworks. I've tested up to the git repo commit: 3b4d4bf

I don't know if it's me coding it wrong or a problem within facepunch.steamworks. I strongly suspect the former, but I'm not sure.

Thanks in advance!

**Comment by garrynewman** [comment]
I'll check it out

**Comment by garrynewman** [comment]
I can't find anything that could cause this

**Comment by Roobubba** [comment]
Thanks for looking.

I can't work out why it is happening in my example project. Do you have an example of implementing the P2P networking? I can only assume there's something weird in the ordering of functions in my project. Does the client need to listen for and accept P2P sessions as well as the server?

**Comment by Agoxandr** [comment]
It's [here](https://github.com/Facepunch/Facepunch.Steamworks/blob/51ab76893ab09c3f2d6175bd520a730913f62bb7/Facepunch.Steamworks.Test/SteamNetworkingTest.cs).

**Comment by Roobubba** [comment]
I did look through all the test code as well as trying to work it out from the source.

That test isn't an example of how to actually implement P2PNetworking across different machines over a network, though. For example, the receiving end has always sent a message first. I'm wondering what else may be different from the real world scenario that might help me track down the problem.

In my example, the dirty hack of closing a session with steam User (0) results in me not getting the NRE. If you comment that line out, it does give a null ref exception when the client first connects to the server.

A local test can't simulate this problem. I'd be most grateful if anyone has, or can point me to, a real world example *implementing* P2P Networking, or even just give an outline of the exact steps needed on client and server prior to sending/receiving messages?

Like I said, with that dirty one line hack, it works a charm - so thanks for all your efforts on Facepunch Steamworks, it's awesome!
