### ISSUE TITLE
Unity 64bit IL2CPP build keeps shutting down

### ISSUE THREAD

**Issue by hajimeku** [Facepunch/Facepunch.Steamworks#282]
I have a strange issue I have never seen before.. when I build 64 bit windows IL2CPP.. the game just shuts down when I call SteamUserStats.RequestCurrentStats();

It works perfectly fine with mono.. just not with il2cpp. its not even generating a crashreport. very weird.

**Comment by hajimeku** [comment]
I narrowed it down to this line:
SteamClient.Name
When I call this in Il2CPP builds, it just crashes

**Comment by garrynewman** [comment]
That's weird - I'll investigate

**Comment by garrynewman** [comment]
Just to confirm - I'm seeing the same thing and still investigating

**Comment by garrynewman** [comment]
Found the issue and fixed it on master

**Comment by hajimeku** [comment]
Thanks!!
Will this plugin have 32 bit support for windows?

**Comment by shah2002** [comment]
Hello I have this problem in unity 2017.4.20 or 2019.1.2 , How can I resolve it? you can see  this problem 
 in blow link : https://stackoverflow.com/questions/56687339/what-is-this-error-in-build-adroid-and-build-app-bundle-in-unity-2017-4-17            
please Help me Because I am in this problem for 2 month thanks

**Comment by garrynewman** [comment]
> Thanks!!
> Will this plugin have 32 bit support for windows?

Kind of - it compiles and works under 32 bit in a .net app - but for some reason it instantly crashes under unity/mono 32bit builds.

**Comment by hajimeku** [comment]
For me it doesn't crash on il2cpp with 32 bit..but just doesn't work

**Comment by garrynewman** [comment]
I'll try a 32bit il2cpp build to see if it's anything I can fix - but the official line really is that it doesn't work 32bit right now.

**Comment by Lestat** [comment]
we need a new release to get this fix I guess :p

**Comment by garrynewman** [comment]
I've fixed a bunch of errors in il2cpp with regards to how we were handling strings. This is on the main branch now. We're using il2cpp in Rust now so it's getting a lot more testing.
