### ISSUE TITLE
client.IsValid always false when Steam open in Offline mode

### ISSUE THREAD

**Issue by alex534488** [Facepunch/Facepunch.Steamworks#288]
When reaching this code : 

        client = new Facepunch.Steamworks.Client( AppId );

        if ( !client.IsValid )
        {
            client = null;
            Debug.LogWarning("Couldn't initialize Steam");
            return;
        }

        Debug.Log( "Steam Initialized: " + client.Username + " / " + client.SteamId ); 

If the Steam client is open in offline mode, client will never be valid. This is a huge problem when you want to support offline play in your game. How is that suppose to work in the original Steamworks.NET ?

I tried editing the Facepunch source code, but I can't seem to find where "new Facepunch.Steamworks.Client( AppId );" goes in the source code. 

I basically want to reproduce what you guys did 1 year ago here 

https://github.com/Facepunch/Facepunch.Steamworks/issues/174 

But the code has changed and I cannot find what to change and where. Any help on this ?

**Comment by garrynewman** [comment]
Offline mode working great for me at the moment
