### ISSUE TITLE
Netwoking SocketInterface OnDisconnected called multiple times on single disconnect

### ISSUE THREAD

**Issue by Agoxandr** [Facepunch/Facepunch.Steamworks#289]
https://github.com/Facepunch/Facepunch.Steamworks/blob/caea5ccb9b75e4f54f3080f86055f254752edca9/Facepunch.Steamworks/Classes/SocketInterface.cs

`				case ConnectionState.ClosedByPeer:
				case ConnectionState.ProblemDetectedLocally:
				case ConnectionState.None:
					OnDisconnected( connection, data );
					break;`
There is always the chance im doing something incorrectly but I'm pretty sure there has to be a better way. As far as I can tell OnDisconnected is called multiple times. At least once when it's supposed to but also when it's not supposed to. 
This is not an actual issue because you are overriding anyways.
I would make a pull request myself but right now im unsure what the cleanest fix would be. Maybe only call OnDisconnected when the connection is valid (check with if() statement).

**Comment by Agoxandr** [comment]
Right now my theory is that it's related to _ClosedByPeer_ and _None_ case both being called when the client disconnects willfully. I'm not sure what is by design and what isn't.

**Comment by Agoxandr** [comment]
Removing the None case fixes my game.

**Comment by garrynewman** [comment]
Is the ideal situation that it does nothing on None?

**Comment by Agoxandr** [comment]
I think so. At least on the server. It's also called twice on the client where it's less of an issue.
