### ISSUE TITLE
Compile. How?

### ISSUE THREAD

**Issue by johanneskraem3r** [Facepunch/Facepunch.Steamworks#29]
You write "Compile and add the library to your project."

Does this only work in Visual Studio? Or should I be able to compile this under Mono ( or using Rider) as well? Getting some errors when trying to compile in Rider.

**Comment by garrynewman** [comment]
Visual Studio 2017 - not sure if it compiles using mono, but you can certainly use the library under mono.

**Comment by johanneskraem3r** [comment]
Thx for the clarification. 

I'm currently trying to compile it with MSbuild/Rider. Will report back if successful.

**Comment by johanneskraem3r** [comment]
Yay, was able to build with Rider on Windows. You do need to install MSbuild ( https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15 ) and ( https://www.microsoft.com/net/download/core).
