### ISSUE TITLE
[Version 0.7] CopySteamLibraries.cs no more available

### ISSUE THREAD

**Issue by enigmagame** [Facepunch/Facepunch.Steamworks#292]
I'am on Unity 2017, so I can't use Facepunch.Steamworks version 2.1.0 because .NET 4.x is not supported, so I need to use version 0.7.
Since I only need achievement feature this is not a big issue.
Whit version 0.7 I know that I need to copy steam_api64.dll and steam_appid.txt files during the build phase but I can't find the old example script CopySteamLibraries.cs (the link is broken).
Can anyone provide me a copy of this script?
Thanks.

**Comment by Agoxandr** [comment]
[CopySteamLibraries.txt](https://github.com/Facepunch/Facepunch.Steamworks/files/3437792/CopySteamLibraries.txt)

**Comment by enigmagame** [comment]
Thanks!
