### ISSUE TITLE
"Exception: SteamApi_Init returned false." "AppId is ureleased"

### ISSUE THREAD

**Issue by Lestat** [Facepunch/Facepunch.Steamworks#293]
I get this with my appid. Init fails. is it because the game isn't published yet?

It also fails with appid 480. In editor mode.

EDIT.- I made a build, it didnt work, it got stuck on my loading screen, probably something to do with steam init, but now it works on the editor...

**Comment by ChristianWeber8** [comment]
Hi! Did you find a solution to this problem?

**Comment by Lestat** [comment]
Well, I don't remember this issue. I got my game published so I guess I did :p Anyways that was before facepunch.steamworks rewrite I think, probably unrelated and just fixes itself.

**Comment by Watcher3056** [comment]
Anyone figured it out?
