### ISSUE TITLE
I cant get seem to get achievements to work

### ISSUE THREAD

**Issue by FupsGamer** [Facepunch/Facepunch.Steamworks#295]
So from what I have found online to unlock achievments, I need to use  SteamClient.Achievements.Trigger(achievementId); but I get this error 
![image](https://user-images.githubusercontent.com/33037022/62381428-c1328900-b54b-11e9-9678-3658947d0838.png)
do I need something else in the script to make this work or is there a new system of triggering achievements??

**Comment by Lestat** [comment]
are you on the latest release?

**Comment by FupsGamer** [comment]
yes I installed it 2 days ago

**Comment by Lestat** [comment]
post what the error says

**Comment by FupsGamer** [comment]
![Facepunch Steamworks error](https://user-images.githubusercontent.com/33037022/62411878-61df8200-b5fa-11e9-8ad7-b111ec7eacec.png)

**Comment by FupsGamer** [comment]
It even happens in an empty scene when I install the plugin and even on the official steamworks unity test by garry

**Comment by Lestat** [comment]
maybe thats the old way of doing it? cause in the main readme, it says this:

Achievements
List them

    foreach ( var a in SteamUserStats.Achievements )
    {
        Console.WriteLine( $"{a.Name} ({a.State}})" );
    }	
Unlock them

    var ach = new Achievement( "GM_PLAYED_WITH_GARRY" );
    ach.Trigger();

**Comment by FupsGamer** [comment]
Thanks that worked :)
