### ISSUE TITLE
Do I have to use IL2CPP? cause my p2pmessages arent working

### ISSUE THREAD

**Issue by Lestat** [Facepunch/Facepunch.Steamworks#296]
I'm using Mono.. But If I change to IL2CPP, I can't even build the game.

EDIT.- they are working now, but the fkirst one takes too much time to arrive.

**Comment by LukasKastern** [comment]
Check this: https://partner.steamgames.com/doc/api/ISteamNetworking#SendP2PPacket
You should sent an initial message so the NAT-traversal code can run.

**Comment by Lestat** [comment]
Oh thank you, yeah I send 2 "dummy" messages when the match starts, one from each player. And everything works flawlessly.

**Comment by Lestat** [comment]
the question stays though, do I have to use IL2CPP? I'm using mono and everything seems to works well, well all except leaving a lobby....

**Comment by garrynewman** [comment]
No - it should work without IL2CPP

**Comment by Lestat** [comment]
thank you, I sorted the leaving a lobby not working too
