### ISSUE TITLE
lobby.Leave(); doesn't seem to work.

### ISSUE THREAD

**Issue by Lestat** [Facepunch/Facepunch.Steamworks#299]
For some reason it doesnt seem to work, I even have it repeated in several parts, to garantee.

I use it when the match ends, and even when trying to find a new lobby I "leave" the previous one (because for some reason it never leaves). But fo9r some reason it never leaves. If someone else tries to seek a lobby it finds the first user one (that should have left after 2+ lobby.Leave() calls) and enters a match even if the first user is not even in the "looking for players" screen.

To make it more clear:

1.-First user enters looking for players and creates a lobby.
2.- another player joins.
3.-match starts, and ends correctly.
4.I call lobby.Leave() in the ExitMatch method (that gets called when the user exits the match (in any way).
5.-first user then goes to any menu, even main menu.
6.-another user start looking for players and finds the lobby the first player was(IS) in, and another match starts. But the first user already called lobby.leave(), so It shouldnt happen.

I even put a new lobby.leave() in the looking for lobbies code (at the start). But that doesnt seem to work either.

I also have code that handles userleft and userdisconnected callbacks, they dont seem to be called at all when doing lobby,.Leave()... but when I close the game, they work as expected /programmed (the other user Wins the match).

Another detail, I cache the lobby ina  variable called thelobby, in all callbacks, *userjoined, userleft, userdisconnected, ondatachanged like this:

public void OnLobbyDataChanged(Lobby lobby){
        thelobby = lobby;

so when I call the lobby.Leave() is actually thelobby.Leave();

EDIT.- Well lobby is a astruct, so I'm probably making a copy when a call thelobby = lobby...

I just thouight of a workaround.

**Comment by Bdoom** [comment]
> I just thouight of a workaround.

What was your workaround?

**Comment by Lestat** [comment]
I don't remember xd sorry

**Comment by omer1615** [comment]
I don't know it's the workaround but just leaving it here so it might help someone in future. If you are storing the Lobby in a variable like `private Lobby? lobby;` on your manager class or something make sure to set to null once you call the `.Leave()` method.

```
lobby.Value.Leave();
lobby = null;
```
