### ISSUE TITLE
Any work being done on Lobby integration?

### ISSUE THREAD

**Issue by kkukshtel** [Facepunch/Facepunch.Steamworks#30]
I see that a lot of the interface classes for Lobby functionality are in place but have no ties in Steamworks.NetCore outside of their wrappers in SteamNative.SteamMatchmaking. I'd be interested in taking a whack at it, but I wasn't sure if you all were working on them already for a push or a release. I'd also be interested to hear more about the general philosophy/coding style of the library so I could better contribute to it if possible. Thanks!

**Comment by garrynewman** [comment]
Yeah - go for it.

I've resisted so far because I've never had to use lobbies, so I'd have to learn how they work first. If you wanna put it together and make a pull request, I'll gladly accept and do a cleanup run.

The philosophy of the library is pretty common sense. Avoid as much complication as you can, reduce the number of steps the end user has to perform to do stuff.

**Comment by kkukshtel** [comment]
Sounds great! I'll see what I can do.

**Comment by kkukshtel** [comment]
Okay so as an update, I've got a preliminary pass at this working over here:
https://github.com/kkukshtel/Facepunch.Steamworks/commit/e3f84eac32f7d6e068f649108ca881062f79ab60

I'm refactoring some stuff now that I see how it would actually look to someone using the library, as well as going in and making things a little nicer. It isn't complete coverage yet, but I know how to implement at least all the remaining functions besides assigning a game server to a lobby.

Also, for the test project, how are you actually running the tests?

**Comment by kkukshtel** [comment]
Update:

I've got almost full code coverage for Lobby functionality here: https://github.com/kkukshtel/Facepunch.Steamworks/commits/master

I also set up Unit tests as well for most of the core functionality, so the test project is tracking.

I'm going to pull in all the latest commits from master over here, make sure everything passes, then submit a PR. Hope it all goes well!

**Comment by GMR516** [comment]
Looks good so far. Excited to have it.

**Comment by kkukshtel** [comment]
Okay, submitted a pull request to the library. Only thing missing right now is the small server interop stuff. Would be happy if someone else took that on to make sure that servers work.

**Comment by NavidK0** [comment]
Hey there, I appreciate the work being done for lobbies! API seems great so far. However, I recently tried out the newly added lobby functionality, and I just can't seem to get it to work.

The code is relatively simple and follows the documentation. I'm using Unity 2017.1, by the way. Testing in the editor.
```
var lobby = SteamClient.Lobby;
lobby.OnLobbyCreated = success =>
 {
     if (success)
        {
            Debug.Log("Successfully made a lobby!");
        }
        else
        {
            Debug.Log("Couldn't create a lobby!");
        }
 };
SteamClient.Lobby.Create(Lobby.Type.Public, 8);
```
It seems that the callback never actually gets called. I used the debugger to trace the code and it seems like all is well. I have used the other lobby callbacks as well and it seems that none of them are getting called. I'm not sure what it could be. I'm using my own AppId for an unpublished game, maybe that has something to do with it. Kinda strange that there's no error though.

**Comment by kkukshtel** [comment]
Hello!

I think the issue is that you are declaring your callback handler as an
anonymous function, likely outside of a using block and part of some other
function call. This means your anonymous function is only locally scooped,
and hence ceases to exist once its parent function finishes execution.

You need to define a normal function to be the proper handler type and take
in the right params, and then subscribe by:
lobby.OnLobbyCreated += myNewFunction.

The test project is kind of misleading here, and is written to keep client
usage scoped to the test functions.

Hope this helps!

**Comment by NavidK0** [comment]
Hey there, 

I tried what you said and it unfortunately still didn't work. No Debug messages indicating whether the Lobby was created or not.

My updated code:
```
        public void OnHostClick()
        {
            Debug.Log("Host button clicked.");
            var lobby = SteamClient.Lobby;
            lobby.OnLobbyCreated += OnLobbyCreated;
            lobby.Create(Lobby.Type.Public, Utils.maxLobbyMembers);
        }

        private void OnLobbyCreated(bool success)
        {
            if (success)
            {
                Debug.Log("Successfully created Steam Lobby.");
                SteamClient.User.SetRichPresence("status", "Test user lobby status");
                SteamClient.User.SetRichPresence("connect", $"-joinGame {externIp}");
            }
            else
            {
                Debug.Log("Failed to create Steam Lobby!");
            }
        }
```
It still appears that the method call goes through to Steam but it never messages Unity about the Lobby creation (or it disappears somewhere). I know that *SOMETHING* is happening because the Join Game button on the Steam client is clickable when I call lobby.Create(...), but none of the callbacks are called causing the Lobby information to never update. Still no errors anywhere, sadly. 

Do you think it's something to do with Valve's end? Do they have to enable matchmaking for unpublished titles? I thought it was only for Free-to-play titles.

**Comment by garrynewman** [comment]
What platform are you on? Do any callbacks work?

**Comment by NavidK0** [comment]
I'm using Windows 10 64-bit, testing on Unity 2017.1.0f3 64-bit. Doesn't work in the editor or outside after building. I've tested Lobby, LobbyList, and Inventory callbacks, and none of them seem to work. That seems to indicate that it's a problem with my setup, perhaps.

I'm using Facepunch.Steamworks as is directly from this repo and the native dlls that come from the Unity Asset Store, if that helps any. The lib is successfully able to connect to steam and everything works as intended except for callbacks. I am able to pull information such as friends, avatars, and names successfully with no issues. I'm pretty lost as to why callbacks aren't working on my setup.

**Comment by kkukshtel** [comment]
Are you calling 
```
Facepunch.Steamworks.Config.ForUnity( Application.platform.ToString() );
```

before running anything? If you aren't getting _any_ callbacks it definitely seems likely something isn't setup right. Have you tried with AppID 480/verified all the references to AppID in your project are the right AppID, and your text file next to your project has the right AppID?

Also have you tried out the [Unity Test Project](https://github.com/Facepunch/Facepunch.Steamworks.Unity)?

**Comment by NavidK0** [comment]
I was calling that, so that wasn't the problem. I did end up solving it...

Turns out you have to call SteamClient.Update() inside a MonoBehaviour for long term Client objects. *sigh* You live, you learn. Sorry guys. I really do appreciate the help given. Keep up the great work on the lib, makes Steamworks development a hell of a lot easier.

**Comment by laurentopia** [comment]
Was Client.Update() replaced by SteamClient.RunCallbacks in the current version?
Config.ForUnity() is no longer required?
Finally, could someone point me to an example of Lobby creation, lifecycle and invitation? 

I'm converting an ollllllld Ludosity SteamworksManaged project and I am loving how terse this one is in contrast, here is a photo for a good laugh.
![steamworksdotnet vs facepunchsteamworks](https://user-images.githubusercontent.com/26075468/79852040-fd787480-837a-11ea-9645-e7e97a4de952.jpg)
