### ISSUE TITLE
SteamClient.Shutdown() not working on Unreal Editor

### ISSUE THREAD

**Issue by goldngood** [Facepunch/Facepunch.Steamworks#300]
When called SteamClient.ShutDown() on GameInstance nothing is happening , the steam status still display the game that was played

**Comment by LukasKastern** [comment]
That's because the Steam API is bound to the process, if you build the game and run it normally it should be working fine.

**Comment by goldngood** [comment]
Yeah i tested with a packaged build and is working as intended .
