### ISSUE TITLE
SteamServer.OnValidateAuthTicketResponse not called when SteamServer.BeginAuthSession( ticketData, clientSteamId ) called

### ISSUE THREAD

**Issue by pippinmole** [Facepunch/Facepunch.Steamworks#302]
I call
      SteamServer.BeginAuthSession(playerToken.SteamAuthTicket, playerToken.SteamID)

which never runs
      SteamServer.OnValidateAuthTicketResponse += this.OnTicketResponse;

https://pastebin.com/YMtZTx1A

**Comment by Agoxandr** [comment]
My man. You are wrong. Check this out.

`using Steamworks;
using System.Text;
using UnityEngine;

public class SteamServerManager : MonoBehaviour
{
    public uint AppId;

    private void Awake()
    {
        Instance = FindObjectOfType<SteamServerManager>();
    }

    public static SteamServerManager Instance { get; private set; }

    public void Initialize(ushort gamePort, ushort steamPort, ushort queryPort, string serverName, int maxPlayers)
    {
        // keep us around until the game closes
        DontDestroyOnLoad(gameObject);

        if (AppId == 0) throw new System.Exception("You need to set the AppId to your game");

        try
        {
            System.IO.File.WriteAllText("steam_appid.txt", AppId.ToString());
        }
        catch (System.Exception e)
        {
            Debug.LogWarning("Couldn't write steam_appid.txt: " + e.Message);
        }

        var init = new SteamServerInit("Mechanized Command", "Mechanized Command")
        {
            GamePort = gamePort,
            SteamPort = steamPort,
            QueryPort = queryPort,
            VersionString = "0.1.0.0",
            Secure = true
        };

        try
        {
            SteamServer.Init(AppId, init);
        }
        catch (System.Exception e)
        {
            Debug.LogWarning(e.Message);
        }
        SteamServer.ServerName = serverName;
        SteamServer.MaxPlayers = maxPlayers;
        SteamServer.Passworded = false;
        SteamServer.DedicatedServer = true;

        SteamServer.OnValidateAuthTicketResponse += OnValidateAuthTicketResponse;
        SteamServer.LogOnAnonymous();
    }

    private void OnDestroy()
    {
        SteamServer.Shutdown();
    }

    public void ValidatePlayer(ulong steamId, byte[] data)
    {
        SteamServer.BeginAuthSession(data, steamId);
    }

    public void OnValidateAuthTicketResponse(SteamId steamID, SteamId ownerId, AuthResponse status)
    {
        foreach (var client in NetworkManager.instance.Server.clients)
        {
            if (client.Value.steamId == steamID)
            {
                if (status == AuthResponse.OK)
                {
                    if (NetworkManager.instance.logLevel >= LogLevel.Event) print(status.ToString());
                    client.Value.vacOk = true;
                    if (!client.Value.playerInitialized)
                    {
                        // New player or not initialized
                        NetworkManager.instance.Server.ServerSendAllowSpawn(client.Value.connection);
                    }
                    else
                    {
                        client.Value.connected = true;
                        // Reconnect
                    }
                }
                else
                {
                    if (NetworkManager.instance.logLevel >= LogLevel.Event) print(status.ToString());
                    client.Value.connection.Close(false, (int)status, status.ToString());
                }
            }
        }
    }

    //private void DebugPrintSteamCallback(object obj)
    //{
    //    StringBuilder sb = new StringBuilder();

    //    sb.AppendLine(obj.GetType().Name);

    //    foreach (var f in obj.GetType().GetFields(System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance))
    //    {
    //        sb.Append(" ");
    //        sb.Append(f.GetValue(obj).ToString());
    //    }

    //    Debug.Log(sb.ToString());
    //}
}
`

**Comment by pippinmole** [comment]
> My man. You are wrong. Check this out.
> 
> `
> using Steamworks;
> using System.Text;
> using UnityEngine;
> 
> public class SteamServerManager : MonoBehaviour
> {
> public uint AppId;
> 
> ```
> private void Awake()
> {
>     Instance = FindObjectOfType<SteamServerManager>();
> }
> 
> public static SteamServerManager Instance { get; private set; }
> 
> public void Initialize(ushort gamePort, ushort steamPort, ushort queryPort, string serverName, int maxPlayers)
> {
>     // keep us around until the game closes
>     DontDestroyOnLoad(gameObject);
> 
>     if (AppId == 0) throw new System.Exception("You need to set the AppId to your game");
> 
>     try
>     {
>         System.IO.File.WriteAllText("steam_appid.txt", AppId.ToString());
>     }
>     catch (System.Exception e)
>     {
>         Debug.LogWarning("Couldn't write steam_appid.txt: " + e.Message);
>     }
> 
>     var init = new SteamServerInit("Mechanized Command", "Mechanized Command")
>     {
>         GamePort = gamePort,
>         SteamPort = steamPort,
>         QueryPort = queryPort,
>         VersionString = "0.1.0.0",
>         Secure = true
>     };
> 
>     try
>     {
>         SteamServer.Init(AppId, init);
>     }
>     catch (System.Exception e)
>     {
>         Debug.LogWarning(e.Message);
>     }
>     SteamServer.ServerName = serverName;
>     SteamServer.MaxPlayers = maxPlayers;
>     SteamServer.Passworded = false;
>     SteamServer.DedicatedServer = true;
> 
>     SteamServer.OnValidateAuthTicketResponse += OnValidateAuthTicketResponse;
>     SteamServer.LogOnAnonymous();
> }
> 
> private void OnDestroy()
> {
>     SteamServer.Shutdown();
> }
> 
> public void ValidatePlayer(ulong steamId, byte[] data)
> {
>     SteamServer.BeginAuthSession(data, steamId);
> }
> 
> public void OnValidateAuthTicketResponse(SteamId steamID, SteamId ownerId, AuthResponse status)
> {
>     foreach (var client in NetworkManager.instance.Server.clients)
>     {
>         if (client.Value.steamId == steamID)
>         {
>             if (status == AuthResponse.OK)
>             {
>                 if (NetworkManager.instance.logLevel >= LogLevel.Event) print(status.ToString());
>                 client.Value.vacOk = true;
>                 if (!client.Value.playerInitialized)
>                 {
>                     // New player or not initialized
>                     NetworkManager.instance.Server.ServerSendAllowSpawn(client.Value.connection);
>                 }
>                 else
>                 {
>                     client.Value.connected = true;
>                     // Reconnect
>                 }
>             }
>             else
>             {
>                 if (NetworkManager.instance.logLevel >= LogLevel.Event) print(status.ToString());
>                 client.Value.connection.Close(false, (int)status, status.ToString());
>             }
>         }
>     }
> }
> ```
> 
> }
> `
I'll give it a shot.
Last time I tried something very similar to this, it never called SteamServer.OnValidateAuthTicketResponse, but I know for sure it registered my method

**Comment by Agoxandr** [comment]
The issue is you is that it has to be in the right order. If it's not it won't work.

**Comment by Agoxandr** [comment]
@pippinmole I should probably tell you that `BeginAuthSession` calls OnValidateAuthTicketResponse. When a player connects you call `ValidatePlayer` on the server. The data array is the byte array of the ticket data that you sent. Don't forget to disconnect the player if he never send a ticket after lets say 5 seconds.

**Comment by pippinmole** [comment]
So it's in this order:

Client starts game (Generates steam auth ticket byte[])
Client connect request -> Server (sending auth ticket)
SERVER BeginAuthSession(authTicket)
TIMEOUT FOR STEAM SERVERS TO AUTHENTICATE TICKET
SteamServer.OnValidateAuthTicketResponse Invoked

**Comment by Agoxandr** [comment]
I generate the ticket when I'm connected already. https://partner.steamgames.com/doc/features/auth I had to check but it says you are only allowed to use a ticket once.

**Comment by pippinmole** [comment]
It works. Sorry for the late reply, but I really don't understand what I was doing wrong?
If you could point out the issue I had, it would be appreciated.

Thank you :)
