### ISSUE TITLE
GetFriends returns incomplete list

### ISSUE THREAD

**Issue by dralois** [Facepunch/Facepunch.Steamworks#303]
If I call the function GetFriends in the SteamFriends class I should get the immediate friends back. However the returned list contains both blocked accounts and is missing others. About half of my friend list is missing and about half of my blocked list is returned. Since there is no option to retrieve friends another way I cannot provide any details on the behaviour of other methods. I can however confirm that the accounts in questions are marked as IsFriend if retrieved by e.g. joining the same lobby.

**Comment by LukasKastern** [comment]
This is fixed on the master branch, see #286 for more information.

**Comment by dralois** [comment]
Ah okay so I suppose it's not in the latest release yet, I'll close the thread
