### ISSUE TITLE
Unhandled Exception: System.Exception: Couldn't find server interface SteamGameServer012

### ISSUE THREAD

**Issue by s76** [Facepunch/Facepunch.Steamworks#304]
I ran into this error when trying to run steam server on a virtual linux64 machine in windows hype-v. (it also happens on physical machine but I don't have access to the full logs)

```
$ uname -v
#26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019
```

There are actually 2 errors:
- the library couldn't find/ recognize `steamclient.so` which was located locally in the project root directory ( this is minor - I fixed it by copying  `steamclient.so` to `~/.steam/sdk64/steamclient.so` but would like to know what happened)
```
steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Loaded '/home/tc/.steam/sdk64/steamclient.so' OK.  (First tried 'steamclient.so')
```

- the missing interface 
```
Unhandled Exception: System.Exception: Couldn't find server interface SteamGameServer012
   at Steamworks.SteamInterface.InitServer() in C:\GitHub\Facepunch.Steamworks\Facepunch.Steamworks\Utility\SteamInterface.cs:line 83
   at Steamworks.SteamServer.get_Internal() in C:\GitHub\Facepunch.Steamworks\Facepunch.Steamworks\SteamServer.cs:line 28
   at Steamworks.SteamServer.get_LoggedOn() in C:\GitHub\Facepunch.Steamworks\Facepunch.Steamworks\SteamServer.cs:line 300
   at ConsoleApp1.Program.<>c__DisplayClass1_0.<StartSteamServer>g__InitializeSteamServer|0() in C:\Users\TuanChau\Documents\Visual Studio 2017\Projects\TestSteamServer\ConsoleApp1\Program.cs:line 63
```
All the .dll/ .so are 64bit versioned and code runs normally on windows.

Full error log: https://gist.github.com/s76/7cde572f97813489ca019e167b0da1e2

The project used to reproduce this issue can be found here:
https://github.com/s76/SteamServerTest/tree/master/ConsoleApp1

Steam server intialization code:
https://github.com/s76/SteamServerTest/blob/master/ConsoleApp1/Program.cs

Dotnet version:
- on windows : 2.2.108
- on linux : 2.2.401

Facepunch.Steamworks version :  2.1.0 

Does anyone have any idea why this is happening? Any help would be much appreciated.

**update (10/09/2019)**
Since the newer version 2.2.0 has been released not long ago, I will try it to see if it solves my problem and come back here later with results.

**update (10/10/2019)**
The same issue is still happening.

**Comment by Polemus** [comment]
I've noticed that if you set any Steam server property directly it fails with the above mentioned error.

simply doing the following will cause it: 
` Steamworks.SteamServer.ServerName = "SomeServerName";`

If you only make use of `SteamServerInit()` then it works.

Problem is, there are some more properties that can be set on SteamServer than what is available on `SteamServerInit`
