### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Sajadhaider** [Facepunch/Facepunch.Steamworks#306]
Hello, When i init steamclient with id of 480
im getting these errors
NullReferenceException: Object reference not set to an instance of an object
Steamworks.ISteamUser.BLoggedOn () (at Assets/Plugins/Facepunch.Steamworks/Generated/Interfaces/ISteamUser.cs:104)
Steamworks.SteamClient.get_IsLoggedOn () (at Assets/Plugins/Facepunch.Steamworks/SteamClient.cs:159)
NullReferenceException: Object reference not set to an instance of an object
Steamworks.ISteamFriends.GetFriendCount (System.Int32 iFriendFlags) (at Assets/Plugins/Facepunch.Steamworks/Generated/Interfaces/ISteamFriends.cs:213)
Steamworks.SteamFriends+<GetFriends>d__28.MoveNext () (at Assets/Plugins/Facepunch.Steamworks/SteamFriends.cs:117)

and the userid is returning as "1"

**Comment by trdwll** [comment]
Is Steam running?
