### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by TupiNUMBooR** [Facepunch/Facepunch.Steamworks#311]
Not sure it should be here, but i don't know where else to ask, and it should probably be a part of readme, so lets assume it is an issue.

It is said nothing about how to install this. I mean, for example, i work in unity, should i just copy **ALL** contents of Unity folder from zip file? Or only some files? Then what are other folders for?

**Comment by ScriptsEngineer** [comment]
I'm not an expert either, but try to put in a folder called "Plugins" inside "Assets", if it doesn't exist create one.

**Comment by TupiNUMBooR** [comment]
I think it will work anywhere in assets, but i'm insterested what to put there? There are 3 folders in archive: *Release*, *Debug*, *Unity*. What folders are needed for what? *Unity* is the most probable for unity, but it contains a lot of files. Should i skip some files if i don't use a platform or for some other reasons? Shoud we move contents of *redistributable_bin* somewhere?

**Comment by Lestat** [comment]
All files inside Unity folder goes to your project's Asset folder

**Comment by TheCubicNoobik** [comment]
https://github.com/Facepunch/Facepunch.Steamworks/wiki

**Comment by kamyker** [comment]
I've created fork with tight Unity integration, package manager and asmdefs support. https://github.com/kamyker/Facepunch.Steamworks

It allows to have source files and fast iteration times as plugin is compiled only once. Debugging, fixing stuff also very easy.
