### ISSUE TITLE
Can't get items list

### ISSUE THREAD

**Issue by clumba** [Facepunch/Facepunch.Steamworks#313]
Code taken from main page:
```c#
try
            {
                SteamClient.Init(440);
            }
            catch (System.Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");// Couldn't init for some reason (steam is closed etc)
            }
            var result = await SteamInventory.GetAllItemsAsync();

            // result is disposable, good manners to dispose after use
            using (result)
            {
                var items = result?.GetItems(true);
// always crash here, because result = null
                foreach (InventoryItem item in items)
                {
                    Console.WriteLine($"{item.Id} / {item.Quantity} / {item.Def.Name} ");
                }
            }
            SteamClient.Shutdown();
```

What's wrong? Why result is always null?

**Comment by LoneDev6** [comment]
You have to use await SteamInventory.WaitForDefinitions() in order to load definitions and then load inventory

https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks.Test/InventoryTest.cs

**Comment by kamyker** [comment]
Just check and works fine for me in Unity 2019.2. Null is returned only when user doesn't have any items. I guess it could be changed to empty array in.

Not sure if it changes anything but I'm not calling "get all items" instantly after init maybe try waiting few seconds.

**Comment by trdwll** [comment]
@clumba @LoneDev6 Just do `if (items != null)` before the foreach loop. I used the code above and with that check it was fine.
