### ISSUE TITLE
GetUserItemVote not fully implemented

### ISSUE THREAD

**Issue by alexcodejammer** [Facepunch/Facepunch.Steamworks#315]
While there's an internal GetUserItemVote in ISteamUGC.cs it has no usages and cannot be accessed via UgcItem the same way that SetUserItemVote can be

**Comment by trdwll** [comment]
It's already accessible from here. https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/Structs/UgcItem.cs#L375

**Comment by alexcodejammer** [comment]
Yeah, pretty sure you directed me to my own code I added after raising this issue. Should have closed it though, thanks.
