### ISSUE TITLE
SteamFriends doesn't allow getting pending friend request after #286

### ISSUE THREAD

**Issue by s76** [Facepunch/Facepunch.Steamworks#316]
As it was fixed in #286 `SteamFriends.GetFriends` now only returns "regular" friends (instead of "all" as before) and there is no way to get the pending friend requests.

**Comment by LukasKastern** [comment]
There was never a way to get "all" friends. 
Before #286 GetFriends returned friends of all flags but only by the amount of regular friends you have.

**Comment by s76** [comment]
That's true since the friend count is return by `Internal.GetFriendCount( (int) FriendFlags.Immediate )`. Can you add a method that let user get list of friends by given flag?

**Comment by LukasKastern** [comment]
I reworked my commit from earlier based upon your latest comment. 
This should be more fitting now.

**Comment by s76** [comment]
Thank you :)
