### ISSUE TITLE
RestartAppIfNecessary and BIsSubscribed

### ISSUE THREAD

**Issue by LoneDev6** [Facepunch/Facepunch.Steamworks#32]
Is there a way to call these functions with your API?
SteamAPI.RestartAppIfNecessary()  and SteamApps.BIsSubscribedApp(appID)
Thanks

**Comment by garrynewman** [comment]
Heya - you can use Client.App.IsSubscribed( appid ) for BIsSubscribedApp

Have just added RestartAppIfNecessary  - it's a static at Client.RestartIfNecessary( appid )

**Comment by johanneskraem3r** [comment]
Thanks for adding "RestartAppIfNecessary"!  — just came here to bug about it :-)
