### ISSUE TITLE
Can't get Leaderboard entries + request EntryCount

### ISSUE THREAD

**Issue by sniperemi** [Facepunch/Facepunch.Steamworks#325]
Hi,
After successfully getting a leaderboard with :
        **var leaderboard = await Steamworks.SteamUserStats.FindLeaderboardAsync("leaderboard");
        Debug.Log(leaderboard.HasValue);**
where HasValue is true and with entries in this leaderboard, I never managed to get any scores, wether by using 
        **Steamworks.Data.LeaderboardEntry[] entry = await leaderboard.Value.GetScoresAsync(1);**
or
        **Steamworks.Data.LeaderboardEntry[] entry = await leaderboard.Value.GetScoresAroundUserAsync(-1, 1);**

It is not that entries are null or there are no entries, **it doesn't even finish the internal calls** and I get this error in the console :
_IndexOutOfRangeException: Index was outside the bounds of the array.
Steamworks.Data.Leaderboard+<LeaderboardResultToEntries>d__15.MoveNext () (at <851c292e1a9944c4920a6e84ebdaddb8>:0)_

The user is connected, valid, the app too, I am able to get those entries with the Web API but can't get result with those lines.

As I would like to get the Global Rank of the user among x other players, could you also consider adding **GetLeaderboardEntryCount()** to the available functions ?

Thanks.

**Comment by sniperemi** [comment]
Here is a detailed log of the error happening :

The issue seems to come from the function LeaderboardResultToEntries and therefore must come from GetDownloadedLeaderboardEntry

@garrynewman Is the fact that my game is not published yet can interfere with this call ?

`Uploading Crash Report
IndexOutOfRangeException: Index was outside the bounds of the array.
  at Steamworks.Data.Leaderboard+<LeaderboardResultToEntries>d__15.MoveNext () [0x00091] in C:\Git\Facepunch.Steamworks\Facepunch.Steamworks\Structs\Leaderboard.cs:115 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <7d97106330684add86d080ecf65bfe69>:0 
  at Steamworks.Data.Leaderboard+<GetScoresAsync>d__12.MoveNext () [0x00116] in C:\Git\Facepunch.Steamworks\Facepunch.Steamworks\Structs\Leaderboard.cs:72 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <7d97106330684add86d080ecf65bfe69>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <7d97106330684add86d080ecf65bfe69>:0 
  at SteamWorksMainMenu+<GetWorldRanking>d__11.MoveNext () [0x0012c] in D:\Snipe\Documents\Arokma\SRX\Repo\SRX\Assets\SRX\SteamManager\Scripts\SteamWorksMainMenu.cs:95 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
<GetWorldRanking>d__11:MoveNext() (at D:\Snipe\Documents\Arokma\SRX\Repo\SRX\Assets\SRX\SteamManager\Scripts\SteamWorksMainMenu.cs:100)
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.AwaitTaskContinuation:InvokeAction(Object)
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run(Task, Boolean)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task:FinishStageThree()
System.Threading.Tasks.Task:FinishStageTwo()
System.Threading.Tasks.Task:Finish(Boolean)
System.Threading.Tasks.Task`1:TrySetException(Object)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
Steamworks.Data.<GetScoresAsync>d__12:MoveNext() (at C:\Git\Facepunch.Steamworks\Facepunch.Steamworks\Structs\Leaderboard.cs:72)
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.AwaitTaskContinuation:InvokeAction(Object)
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run(Task, Boolean)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task:FinishStageThree()
System.Threading.Tasks.Task`1:TrySetResult(Nullable`1)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(Nullable`1)
Steamworks.<DownloadLeaderboardEntries>d__90:MoveNext() (at C:\Git\Facepunch.Steamworks\Facepunch.Steamworks\Generated\Interfaces\ISteamUserStats.cs:486)
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.AwaitTaskContinuation:InvokeAction(Object)
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run(Task, Boolean)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task:FinishStageThree()
System.Threading.Tasks.Task`1:TrySetResult(Nullable`1)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(Nullable`1)
Steamworks.Data.<GetResultAsync>d__10:MoveNext() (at C:\Git\Facepunch.Steamworks\Facepunch.Steamworks\Generated\SteamStructs.cs:5137)
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.<>c:<.cctor>b__7_0(Object)
UnityEngine.WorkRequest:Invoke()
UnityEngine.UnitySynchronizationContext:Exec()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()`

**Comment by kamyker** [comment]
Issue in :
https://github.com/Facepunch/Facepunch.Steamworks/blob/32fbf63644dd30a93c2f90a2a8321ad42253991e/Facepunch.Steamworks/Structs/Leaderboard.cs#L111-L117

Somehow I gets changed to -1 after first call
