### ISSUE TITLE
Add ResetAllUserStats ?

### ISSUE THREAD

**Issue by johanneskraem3r** [Facepunch/Facepunch.Steamworks#33]
Just add one function to Stats.cs?  ( Sorry, bit too lazy to do a pull request for this right now).

        public bool ResetAllUserStats(bool shouldResetAchievementsToo)
        {
            return client.native.userstats.ResetAllStats(
                bAchievementsToo: shouldResetAchievementsToo);
        }

**Comment by garrynewman** [comment]
Done :)
