### ISSUE TITLE
LoadItemDefinitions doesn't return items above 1000000 id

### ISSUE THREAD

**Issue by kamyker** [Facepunch/Facepunch.Steamworks#330]
These should be workshop items. Steam docs say LoadItemDefinitions should also return them "Item definitions are a mapping of "definition IDs" (integers between 1 and  999999999) to a set of string properties." https://partner.steamgames.com/doc/api/ISteamInventory#LoadItemDefinitions

**Comment by garrynewman** [comment]
I can't see any reason why this should be the case, your pull request didn't reveal any reason to me either. Can you explain what you found?
