### ISSUE TITLE
Feature request: Dedicated relay server support

### ISSUE THREAD

**Issue by StagnationPoint** [Facepunch/Facepunch.Steamworks#337]
Many thanks for your Steam library! It's been very handy for this indie dev. :-)

Valve now offers the option to host servers in the major cloud providers (AWS, Azure and Google) and use their Steam Datagram Relay service to relay traffic to customers. I would like to support this feature and have joined their beta.

Documentation is here: https://partner.steamgames.com/doc/features/multiplayer/steamdatagramrelay

(Note that I'm not asking to support the features that are used when you host your server in one of Valve's datacenters. That's a slightly more esoteric ball of wax.)

At a first approximation it looks like the task consists of wrapping the additional ISteamNetworkingSockets stuff, as well as wrapping this: http://media.steampowered.com/apps/sdr/sdk/steamdatagram_gamecoordinator_sdk.zip

Edit: Also SteamDatagramRelayAuthTicket and SteamDatagramHostedAddress, which I see you have stubs for, as well as the utility functions in ISteamNetworkingUtils like InitRelayNetworkAccess(), GetRelayNetworkStatus(), etc...

**Comment by garrynewman** [comment]
I thought we already supported this?

**Comment by StagnationPoint** [comment]
Here's my understanding, apologies if I sound pedantic. I believe this library supports P2P SDR, but not dedicated server SDR. Two different flavors of relay. I think some of the dedicated server SDR bits are there, but it's not complete. P2P SDR assumes the server (such as it is) is running under a Steam account and is hosted wherever you like. Dedicated server SDR requires that a server is running in AWS, Azure or GCP, the server process does not need to be running under a Steam account, and for the moment you need to opt-in to the beta and send Valve a public key to sign certs for the auth workflow.

Maybe I'm missing something. A couple of examples that confuse me off the top of my head: The instructions I linked from Valve say to call CreateHostedDedicatedServerListenSocket(). I see that's marked internal, so I'm not sure how to call it from my app. I also need SteamDatagramHostedAddress, but that's got a comment in it "// Not implemented".

**Comment by garrynewman** [comment]
We have definitely successfully created a dedicated server with it in our internal projects. I think @willox  or @aylaylay did it - so they might have more info. I did plan to implement it in Rust at some point - so it'll get well tested soon.

**Comment by StagnationPoint** [comment]
Okay, looking forward to hearing some guidance from @willox or @aylaylay on how to approach this.

**Comment by garrynewman** [comment]
Hey, so after looking at this, this is my understanding..

**Networking Sockets** - normal sockets 

**Networking Relay** - Work like normal sockets but instead of IP addresses they use SteamIds and traffic is routed via Valve's backbone network

**Networking Dedicated Servers** - Servers hosted by Valve, currently in testing, need a linux build in a docker image and to talk to Valve to get it working.

You can use either of the top two to host dedicated servers. I've got it all working in Rust right now using the NetworkingSockets stuff. The last one is going to be hard for me to support.

**Comment by StagnationPoint** [comment]
Hi!

Steam has kinda overloaded the terms somewhat, which makes it confusing, so I'll give my understanding:

(1) Networking Sockets: Normal sockets, as you say.

(2) Networking Relay: There are actually two subsets of this:
   (a) P2P. Your library supports this now.
   (b) Dedicated servers. The packets are also transported by Valve's backbone, but the servers are not hosted in Valve's datacenters. They are hosted by the customer in AWS, GCP or Azure. I've been told by Valve that networking performance for (b) is much higher than (a) -- you can support many more clients with it. This is in beta, you do need to talk to Valve to get it working.

Networking Valve-hosted Dedicated Servers: This is your third item above, and it's what I referred to as an "esoteric ball of wax" in my initial message. I understand this would not be supportable.

What I'm looking for is support for (2)(b). Their documentation on that is a bit clearer now:

https://partner.steamgames.com/doc/api/ISteamNetworkingSockets#functions_hosted_servers

You can find a description of the connection flow here, which mentions a lot of the API pieces needed: https://partner.steamgames.com/doc/features/multiplayer/steamdatagramrelay

(Their section titled "Valve server hosting" is part of (3) which, again, I understand you won't support.

At a glance, here's what I think I need to make this work. I pulled latest and am looking at it:

ReceivedRelayAuthTicket(): Currently marked internal
SteamDatagramRelayAuthTicket: Has a placeholder that says "// Not implemented, not used"
FindRelayAuthTicketForServer(): Currently marked internal

I believe GetGameCoordinatorServerLogin would also need to be usable.

And then there's also the matter of the coordinator...

@fletcherdvalve It's not as clear as it could be, I think, what needs to be supported in a C# API to support dedicated server SDR (what I've called (2)(b) above). Would you be able to give us a succinct list of what's needed?

**Comment by mthsmb** [comment]
Is this implemented yet?
