### ISSUE TITLE
SetRichPresence() error

### ISSUE THREAD

**Issue by KrasGames** [Facepunch/Facepunch.Steamworks#340]
Hi!
I want to use rich presence, but I have this error: `NullReferenceException: Object reference not set to an instance of an object
Steamworks.SteamFriends.SetRichPresence (System.String key, System.String value)`. How can I fix it?
I use last release (2.2.0)
Thanks for help)

**Comment by TheCubicNoobik** [comment]
I already fix this in https://github.com/Facepunch/Facepunch.Steamworks/pull/308.
You must use the master branch because the last release is outdated.

**Comment by KrasGames** [comment]
> You must use the master branch because the last release is outdated.

Can you tell me which files I need to export to unity?
