### ISSUE TITLE
Where is GameCoordinator?

### ISSUE THREAD

**Issue by codefather-labs** [Facepunch/Facepunch.Steamworks#342]
https://partner.steamgames.com/doc/api/ISteamGameCoordinator

I can't find this handler in your library. Help please

**Comment by trdwll** [comment]
I assume that this won't be implemented as it's deprecated, however I could be wrong. _(This is largely deprecated, and only continues to exist for the couple games that still use this.)_

**Comment by iebb** [comment]
I think it could be a great addition to this library, when playing around with these existing games (incl. CS:GO and Dota 2) 😺
