### ISSUE TITLE
Creating a build for Unity

### ISSUE THREAD

**Issue by stonebirdarchitect** [Facepunch/Facepunch.Steamworks#345]
I used Facepunch.Steamworks 2.2.0 for development of my game, and while I was testing it in Unity itself everything was fine. All requests that could go through were going through. However when I try to create a build from my project, I get lots of "The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)"
Any suggestions ?

**Comment by LukasKastern** [comment]
Try moving your Steamworks dlls into your plugins folder.

**Comment by stonebirdarchitect** [comment]
If I just move them there VS doesn't see them existing, if I copy them there nothing changes

**Comment by LukasKastern** [comment]
That's weird, do you have "Any Platform" selected when you click on the dlls?

**Comment by stonebirdarchitect** [comment]
Just checked it, yes I do, on all of them.

**Comment by kamyker** [comment]
You can try https://github.com/kamyker/Facepunch.Steamworks.Package easy setup with Package Manager

**Comment by MBrown42** [comment]
I had this same issue using the json-based package in Unity 2019.  Make sure you don't skip step 2 in the json easy-add instructions on the url above "Set proper Scription Define Symbols in Unity Player settings".  Here is what my project root directory looks like, hopefully it helps.  I can get the sample project to build and run but was unable to get an OnIncomingConnection to fire on a server, curious how you proceed.
![FP_2 2_UnityProjectRoot](https://user-images.githubusercontent.com/54235752/73397387-6cc95580-42b1-11ea-8f20-c4c4cb7b9ad6.png)
