### ISSUE TITLE
Creating Normal Socket

### ISSUE THREAD

**Issue by m4chado1** [Facepunch/Facepunch.Steamworks#347]
Hello guys :)
Can someone give me some light? I've created a server using SteamNetworkingSockets.CreateNormalSocket but I got stuck I don't know how to send/receive messages on the server/client. They already connect by default using onconnect, connecting, disconnecting... but how to send data? 
just need some light, not the code, already read the Steamworks documentation but I'm still stuck Facepalm 
Thanks you

**Comment by LukasKastern** [comment]
The Socket Interface works with a Connection struct which is basically the handle to a connection id, you can call Connection.SendMessage to send data around.

**Comment by m4chado1** [comment]
Hey thanks for your Answer, and what about the server he just listen? Or can send packets too?

**Comment by LukasKastern** [comment]
It's the same for the Server, you can get the Connections which are connected to the Server by the Connected list of the SocketInterface.

**Comment by m4chado1** [comment]
Thank you very much Will check it later
