### ISSUE TITLE
SteamScreenshots.OnScreenshotRequested never called

### ISSUE THREAD

**Issue by UnknownSoldier1** [Facepunch/Facepunch.Steamworks#359]
Hello,

I'm currently facing the problem that the callback `SteamScreenshots.OnScreenshotRequested` is never called, even when setting `SteamScreenshots.Hooked` to true.

I'm using the latest released DLL version.

**Comment by garrynewman** [comment]
You need to do StreamScreenshots.Hooked = true for this to work

**Comment by UnknownSoldier1** [comment]
SteamScreenshots.Hooked is set to true. It doesn't work regardless. This is (the important bit) of my code:

`
public class SteamScreenshotManager : IDisposable
{
	private readonly SteamManager steamManager;

	public SteamScreenshotManager(SteamManager steamManager)
	{
		this.steamManager = steamManager;
		SteamScreenshots.OnScreenshotReady += OnScreenshotReady;
		SteamScreenshots.OnScreenshotRequested += OnScreenshotRequested;
		SteamScreenshots.Hooked = true;
	}
	
	public void Dispose()
	{
		SteamScreenshots.Hooked = false;
		SteamScreenshots.OnScreenshotReady -= OnScreenshotReady;
		SteamScreenshots.OnScreenshotRequested -= OnScreenshotRequested;
	}

	private void OnScreenshotRequested()
	{
		Debug.Log("Screenshot requested.");
	}
	
	private void OnScreenshotReady(Screenshot screenshot)
	{
		Debug.Log("Screenshot ready.");
	}
}
`

In my case, the method OnScreenshotReady is called, OnScreenshotRequested is not. From what I've seen in the Steam documentation, this should be the other way around.
