### ISSUE TITLE
What is the easiest way to make a non-Steam build?

### ISSUE THREAD

**Issue by Wikzo** [Facepunch/Facepunch.Steamworks#363]
I'd like to make a build where everything from the Steam API is stripped away. What would be the easiest way to exclude Steamworks-related code and DLL files?

I guess custom platform #defines would be a good idea, right? How about the DLL files; what should be removed and is there an automatic way to do it?

Thanks!

**Comment by Wikzo** [comment]
Do we have something similar to #DISABLESTEAMWORKS?

https://github.com/rlabrecque/Steamworks.NET/issues/125

**Comment by trdwll** [comment]
I'd say doing defines would be fine unless you would want to remove the library from the project.
https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-exclude-files-from-the-build?view=vs-2019

**Comment by garrynewman** [comment]
I could look at this if it's still something that you definitely want

**Comment by Wikzo** [comment]
I ended up making my own custom #defines, but I guess it would be nice to have something built-in in the future :)
