### ISSUE TITLE
SteamFriends.OnGameOverlayActivated does not fire when overlay is opened

### ISSUE THREAD

**Issue by mlaframboise** [Facepunch/Facepunch.Steamworks#367]
I am subscribed to the SteamFriends.OnGameOverlayActivated event and SteamClient.RunCallbacks() is being hit every frame, but the event is never received when the overlay opens.

**Comment by mkracik** [comment]
It fires for me but it's supposed to have bool parameter Active, without it the event is not very useful, unless I'm missing something.

**Comment by mlaframboise** [comment]
I'm definitely not seeing a bool parameter:
public static event Action OnGameOverlayActivated;

**Comment by mlaframboise** [comment]
The issue turns out to be that I had all of the Steamworks initialization behind UNITY_STANDALONE_WIN flags, which does not work with Steam apparently.
