### ISSUE TITLE
Not working without native DLL

### ISSUE THREAD

**Issue by mavericken** [Facepunch/Facepunch.Steamworks#369]
Using the 2.2.0 NuGet release, everything works if I include the native DLL from the SDK in the same directory as my program.  Without providing the native DLL, it fails.  I raise this as an issue because the README seems to indicate that this should not be the case, that it should just run without having to provide the native DLL separately.

**Comment by trdwll** [comment]
I can confirm this is an issue. I assume it's probably a legal thing, but I could be wrong. /shrug The 2.2.0 release can be downloaded [here](https://github.com/Facepunch/Facepunch.Steamworks/releases/download/2.2.0/Facepunch.Steamworksv2.2.0.zip) and it contains the steamapi dll.

**Comment by Lestat** [comment]
I wonder when the next release will be, it's like 5 months already?

**Comment by trdwll** [comment]
I assume it will be soon.

**Comment by the-mr-matt** [comment]
I can't wait for a new release. How can I get the necessary files for Unity using the master branch?

**Comment by Lestat** [comment]
It will probably fix my problem with p2p packets :/ I wish!

**Comment by garrynewman** [comment]
I'll take a look and see if there's a way I can make the nuget release include the native dll and put it in the right place.

**Comment by garrynewman** [comment]
I pushed 2.3.0 to nuget - can you let me know if that has changed anything?

**Comment by garrynewman** [comment]
Alright the nuget package now includes the steam_api64.dll - but you might have to set it to copy to output.
