### ISSUE TITLE
Unity 3D assets store new version

### ISSUE THREAD

**Issue by LoneDev6** [Facepunch/Facepunch.Steamworks#37]
May you update the version in the assets store?
I tried compiling with Visual Studio 2017 and when I use the library in Unity I get this:
`
steamclient64.dll caused an Access Violation (0xc0000005)
  in module steamclient64.dll at 0033:5dea84b9.
`
Thanks.

**Comment by garrynewman** [comment]
0.6 should be on the asset store now
