### ISSUE TITLE
Question: On Demo with exact same files, so using shared depot...

### ISSUE THREAD

**Issue by Lestat** [Facepunch/Facepunch.Steamworks#370]
On my demo that uses the exact same files as the full app, I will use SteamApps.issubscribedapp as the documentation says:

> Q: What if my demo consists of literally the same files as the full game?
A: Use a shared depot as described in the Shared Content Depots documentation. Do the following to make sure the demo and full app both work correctly.

> If you use Steam DRM, re-submit the exe for signing on the demo Steamworks app admin. Package the demo exe into a depot specific to the demo app. Alternatively, you can skip Steam DRM and just call SteamAPI_RestartAppIfNecessary.
> If there is behavior that is restricted to owners of the full app, gate it behind the ISteamApps::BIsSubscribedApp Steamworks API call with the App ID of the full app.

But I have a question regarding the Initialization. Because it currently initializes using the appid of the full game, can I do this:

```
try{
    SteamClient.Init( gamesteamid );
}catch ( System.Exception e ){
    Debug.Log(e.Message);
    try{
        SteamClient.Init( demosteamid );
    }catch ( System.Exception e2 ){
        // Couldn't init for some reason (steam is closed etc)
        Debug.Log(e2.Message);
        Application.Quit();
    }
}
```

So if it fails to initialize with the full game appid (because the person doesn't own it, they are playing the demo), then it tries to initialize with the demo appid, and if it also fails, the application quits. (but that one shouldn't fail, the demo is free and if they have the game files is because they downloaded the demo at least, or bought the full game.

So it would work fine like that, or am I missing something?

**Comment by trdwll** [comment]
You could ifdef (`#if DEMO_BUILD` etc then have the demo `SteamClient.Init(demoappid)`). Or you could just create 2 different builds to avoid shipping full game content with the demo etc.

**Comment by Lestat** [comment]
I will ship full content with the demo, and use the SteamApps.issubscribedapp to restrict access in the demo as the documentation suggests. So it will be the same build :p

**Comment by Lestat** [comment]
Should work, it throws exception if not own appid: https://github.com/Facepunch/Facepunch.Steamworks/blob/6fbc1e80f35f47eb0575c8e02e13197a6967cc2b/Facepunch.Steamworks/SteamClient.cs#L25
That's enough for me xd

**Comment by trdwll** [comment]
Yeah, it may work. I'm curious as to if it will.
