### ISSUE TITLE
Is there a way to prevent p2p messagespiling up?

### ISSUE THREAD

**Issue by Lestat** [Facepunch/Facepunch.Steamworks#371]
I think that's happening in my game. besides making the messages smaller or sending them at slower rate (currently 20 per second). Im talking about unreliable messages.

I use those unreliable messages to send current player position and other things. It doesn't matter if the other player doesnt receive all of them, only the last sent. So is there a way to "flush" the unreliable messages besides the last one i fthey are piling up?

I think they are piling up because with some friends, their character seem to be like 2 seconds late, and that time increases the more we play.

**Comment by LukasKastern** [comment]
You should be reading your P2P packets inside a loop like this to make sure that you are processing all available messages:
`        while (SteamNetworking.IsP2PPacketAvailable())
        {
            var packet = SteamNetworking.ReadP2PPacket();
        }
`

**Comment by Lestat** [comment]
Thank you, will try it out.
