### ISSUE TITLE
R2.2.0 - IndexOutOfRangeException in GetScoresAsync

### ISSUE THREAD

**Issue by scgsergiusz** [Facepunch/Facepunch.Steamworks#374]
Code:

`this.currentSteamOperation = this.currentLeaderboard.GetScoresAsync(5);`

_currentLeaderboard_ is properly retreived from Steam (has name, sorting properties, etc.)

**Comment by garrynewman** [comment]
What platform? Windows? Unity?

**Comment by scgsergiusz** [comment]
Windows, unity 2019.3
S.

niedz., 23 lut 2020, 10:16 użytkownik Garry Newman <notifications@github.com>
napisał:
