### ISSUE TITLE
SteamServer.Shutdown() causes crash 2.3.0

### ISSUE THREAD

**Issue by Agoxandr** [Facepunch/Facepunch.Steamworks#376]
public override void ServerStop()
    {
        if (Server != null)
        {
            for (int i = 0; i < Server.Connected.Count; i++)
            {
                Server.Connected[i].Flush();
                Server.Connected[i].Close();
            }
            Debug.Log("SERVER CLOSE");
            Server.Close();
            Debug.Log("SHUTDOWN");
            SteamServer.Shutdown();
            Debug.Log("NULL");
            Server = null;
        }
    }
This used to run. The interesting thing is that the Log _NULL_ is still executed. However a callback causes a crash.

[Player-prev.log](https://github.com/Facepunch/Facepunch.Steamworks/files/4246691/Player-prev.log)

**Comment by Agoxandr** [comment]
I fixed it. I added Dispatch.Wipe();

        public static void Shutdown()
        {
            Dispatch.Wipe();
            ShutdownInterfaces();
            SteamGameServer.Shutdown();
        }

**Comment by garrynewman** [comment]
Holy shit that's an awesome crash, f191ee5e42cecba02cad055c8d3cdf6d044cbc05 should fix it
