### ISSUE TITLE
Duplicate Callbacks v2.3.0

### ISSUE THREAD

**Issue by tommohawkaction** [Facepunch/Facepunch.Steamworks#378]
SteamMatchmaking.OnLobbyCreated
SteamMatchmaking.OnLobbyEntered

Both of the above events get called twice
OnLobbyCreated
OnLobbyCreated
OnLobbyEntered
OnLobbyEntered

**To Reproduce**
This doesn't seem to happen in the editor, only seems to happen on standalone builds

**Calling Code**
```
https://pastebin.com/XZLZLcb3

I'm not doing anything major, other then
CreateLobbyAsync
```

**Expected behavior**
Only have 1 OnLobbyCreated when you create a lobby 
Only have 1 OnLobbyEntered when you enter a lobby

**Desktop (please complete the following information):**
- Unity 2019.3.1f1
- Windows 10 64bit

**Comment by tommohawkaction** [comment]
So done some more testing on this, using an empty project and the problem goes away. At this point I'm not sure whats going on.

**Comment by garrynewman** [comment]
There's 2 things that could cause this

1. You're calling SteamClient.Init multiple times
2. Your OnEnable function is being called multiple times, without the matching OnDisable

**Comment by tommohawkaction** [comment]
Yes! Haha. That fixed it!

Turns out my duplicated singletons were calling SteamClient initialize before I had a chance to delete them.
Rookie mistake.

Once again thanks :)

**Comment by garrynewman** [comment]
No problem - 59eabc1302815fce59930cdb49a7ce28812e4ecd should prevent this happening in the future
