### ISSUE TITLE
SteamFriends.OnGameLobbyJoinRequested never called, works in v2.2.0 but not v2.3.0 

### ISSUE THREAD

**Issue by tommohawkaction** [Facepunch/Facepunch.Steamworks#379]
**Describe the bug**
SteamFriends.OnGameLobbyJoinRequested is never called when using v2.3.0 but does get called in v2.2.0

**To Reproduce**
1. Assign SteamFriends.OnGameLobbyJoinRequested on enable
2 Get your friend (If you have one) to invite you
3 Accept the invite

**Calling Code**
```
I'm calling SteamClient.Init and assigning SteamFriends.OnGameLobbyJoinRequested on OnEnable
```

**Expected behavior**
SteamFriends.OnGameLobbyJoinRequested should be called once you accept an invite

**Desktop (please complete the following information):**
 - OS: Windows 10
- Unity 2019.3.0f1

**Additional context**
.NET 4.0

**Comment by garrynewman** [comment]
Hmm - I'll add some debugging tools to see which callbacks are being called and look into it a bit further.

**Comment by garrynewman** [comment]
Actually no need for that - I found the problem!

**Comment by tommohawkaction** [comment]
Haha, what was it?

**Comment by garrynewman** [comment]
I wasn't calling InstallEvents() @ 5d9e4b5c0b977b1c358a7b0f1a180b96ee14825a

**Comment by tommohawkaction** [comment]
Haha quite a big one then :)

Once again, cheers!

**Comment by garrynewman** [comment]
Thanks for spotting it - will release an update soon
