### ISSUE TITLE
Missing NuGet packages

### ISSUE THREAD

**Issue by Phyxion** [Facepunch/Facepunch.Steamworks#381]
**Describe the bug**
At the moment the only thing on NuGet is the x64 build of Windows, so Posix and Win32 are missing. As a solution there are at least two possibilities:

1. Create a single nupkg file for all variants, such as [this one](https://github.com/appenginecorp/react-native-yoga-flexbox/blob/1d09227374b9d081bb763d9ee052e39c7d5b5bc0/csharp/nuget/Facebook.Yoga.nuspec). This is more work as you need to maintain / update this nuspec file and pack this nuspec file.
2. Publish each package separately to NuGet (so Facepunch.Steamworks.Win64, Facepunch.Steamworks.Win32 and Facepunch.Steamworks.Posix), this is probably the easiest as you can just use the built-in stuff.

**Comment by garrynewman** [comment]
Number 2 is easy enough except for posix. If we're including the native dlls we might end up including the so's for linux32 and linux64 and the .bundle for osx.

But I guess for those using linux/osx we can probably safely assume they can handle the native dll stuff themselves?

**Comment by Phyxion** [comment]
Yeah, makes sense for posix, a Win32 package would be welcome 👍

**Comment by garrynewman** [comment]
I'll put one up when I push 2.3.2

**Comment by garrynewman** [comment]
Done!

**Comment by Phyxion** [comment]
Thanks, one thing though, can you include steam_api.dll as well? It's missing at the moment.

**Comment by garrynewman** [comment]
There's another package for that, ending in .win32

**Comment by Phyxion** [comment]
That package doesn't contain the steam_api.dll (there's not even a content folder). Only the Win64 package contains steam_api64.dll in the content folder.

**Comment by garrynewman** [comment]
I see the problem - will be fixed next update

**Comment by PhyxionNL** [comment]
@garrynewman Can you update the NuGet package? It's almost a year old now 😊
