### ISSUE TITLE
Entry point not found on client initialization

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/Facepunch.Steamworks#382]
**Describe the bug**
Entry point not found on client initialization

EntryPointNotFoundException: SteamAPI_ManualDispatch_Init
Steamworks.Dispatch.Init () (at <19bd4cc6a4004258bf538b05ac1133d6>:0)
Steamworks.SteamClient.Init (System.UInt32 appid, System.Boolean asyncCallbacks) (at <19bd4cc6a4004258bf538b05ac1133d6>:0)

**To Reproduce**
Initialize SteamClient in Unity

**Calling Code**
```
SteamClient.Init(appid);
```

**Expected behavior**
No exceptions

**Desktop (please complete the following information):**
Windows 10, Unity 2019.3

**Comment by garrynewman** [comment]
Are you sure your native DLLs are up to date? (Steam_api.dll)

**Comment by cr4yz** [comment]
Yep that was it, thank you.  The steam_api packaged in the Unity folder is incompatible

**Comment by lzinga** [comment]
@cr4yz Where do you obtain the latest native steam_api package? I am running Facepunch.Steamworks in a console application for testing purposes and starting with `SteamClient.Init(4000);` however it throws an error stating - 
```
System.EntryPointNotFoundException: 'Unable to find an entry point named 'SteamAPI_ManualDispatch_Init' in DLL 'steam_api64'.'
```

**Comment by garrynewman** [comment]
The steam_api dlls are here: https://github.com/Facepunch/Facepunch.Steamworks/releases

**Comment by QTPah** [comment]
After updating all the DLLs theres still an error:
`System.EntryPointNotFoundException: 'Unable to find an entry point named 'SteamAPI_SteamInput_v001' in DLL 'steam_api64'.'`

**Comment by stoora** [comment]
> After updating all the DLLs theres still an error: `System.EntryPointNotFoundException: 'Unable to find an entry point named 'SteamAPI_SteamInput_v001' in DLL 'steam_api64'.'`

Hi, Did you find a solution for this one?

**Comment by QTPah** [comment]
I did find a solution but i don't really remember. Here are [some files](https://easyupload.io/t3kcb4) i found in my project i referenced which might've fixed the problem.

**Comment by hlpdev** [comment]
> After updating all the DLLs theres still an error: `System.EntryPointNotFoundException: 'Unable to find an entry point named 'SteamAPI_SteamInput_v001' in DLL 'steam_api64'.'`

Did you find a solution for this?
