### ISSUE TITLE
SteamFriends.SetRichPresence NullReferenceException

### ISSUE THREAD

**Issue by tommohawkaction** [Facepunch/Facepunch.Steamworks#383]
**Describe the bug**
Calling SteamFriends.SetRichPresence just after SteamClient.Init causes a NullReferenceException even when wrapped around SteamClient.IsValid, Is there a way to check whether SteamClient has been initialized or not or is it SteamClient.IsValid?

`NullReferenceException: Object reference not set to an instance of an object.
  at Steamworks.SteamFriends.SetRichPresence (System.String key, System.String value) [0x00000] in <00000000000000000000000000000000>:0 `

**To Reproduce**
1. Called SteamClient.Init
2. Just after call SteamFriends.SetRichPresence

**Calling Code**
```
SteamClient.Init(appid)
if(SteamClient.IsValid)
SteamFriends.SetRichPresence(bla,bla);

**Expected behavior**
Anything but a NullReferenceException

**Desktop (please complete the following information):**
- Unity 2019.3

**Comment by garrynewman** [comment]
Is SteamClient.Init throwing an error?

Did you also update the native dlls (steam_api64.dll)

**Comment by tommohawkaction** [comment]
No errors.
I am a few versions behind  v2.2.0

**Comment by tommohawkaction** [comment]
Ah, just updated to latest and I don't get the null reference exception. Apologies
