### ISSUE TITLE
Problem calling SteamFriends.OpenWebOverlay

### ISSUE THREAD

**Issue by PaulDryere** [Facepunch/Facepunch.Steamworks#384]
**Describe the bug**
Upon calling SteamFriends.OpenWebOverlay method game crashes and closes with the following error logged.

ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 000001E98D841838)
  ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 000001E98D841838)
0x000001E98D841838 ((<unknown>)) (function-name not available)
0x000001E9AC18A90B (Mono JIT Code) (wrapper managed-to-native) Steamworks.ISteamFriends:_ActivateGameOverlayToWebPage (intptr,string,Steamworks.ActivateGameOverlayToWebPageMode)
0x000001E9AC18A810 (Mono JIT Code) Steamworks.ISteamFriends:ActivateGameOverlayToWebPage (string,Steamworks.ActivateGameOverlayToWebPageMode)
0x000001E9AC18A7A7 (Mono JIT Code) Steamworks.SteamFriends:OpenWebOverlay (string,bool)

**To Reproduce**
Using release version 2.3.2 of Facepunch.Steamworks for Unity 2017.3
In Windows 64 build, call SteamFriends.OpenWebOverlay

**Calling Code**
if (SteamClient.IsValid && SteamUtils.IsOverlayEnabled)
    SteamFriends.OpenWebOverlay(url);

**Expected behavior**
Steam overlay is opened with web browser open to url

**Desktop (please complete the following information):**
 - OS: Windows 10
- Unity: 2017.3

**Additional context**

**Comment by garrynewman** [comment]
are your native dlls (steam_api64.dll) up to date?

**Comment by PaulDryere** [comment]
I first tried the one which Facepunch.Steamworks automatically puts into the build plugins folder. I then replaced that one with the 1.48 dll directly from steam, neither seemed to work.

**Comment by garrynewman** [comment]
I'm sorry but I can't get this to reproduce - do you think you could make a tiny project to show it happening?

**Comment by PaulDryere** [comment]
Thanks for looking into it. I'll try and see if I can get it working on my end.
