### ISSUE TITLE
SteamUGC.StartPlaytimeTracking not working in Linux DLL

### ISSUE THREAD

**Issue by UnknownSoldier1** [Facepunch/Facepunch.Steamworks#385]
**Describe the bug**
When using the methods `SteamUGC.StartPlaytimeTracking` and `SteamUGC.StopPlaytimeTrackingForAllItems` for a Linux build, Unity will abort compilation, claming these methods don't exist. This works with the Windows DLL.

**To Reproduce**
1. Create a method and call either of these methods
2. Set target platform to Linux 64 bit
3. Try creating a game build

**Desktop (please complete the following information):**
 - OS: Linux 64 bit (compiling from Windows 64 bit)
- Unity: 2019.3

**Additional context**
I didn't import the 32 bit DLLs, because the game is not supposed to support 32 bit anyway.

**Comment by garrynewman** [comment]
That's weird, could you cd to the linux steam_api and run

`nm -gD libsteam_api.so`

to list all the exported functions to see if it's there?

**Comment by UnknownSoldier1** [comment]
As said, I'm working from a Windows machine, so unfortunately I don't have access to that command. I assume though that the steam library should contain these features, as Unity specifically complains about calling `SteamUGC.StartPlaytimeTracking`. I think that something must have gone wrong when compiling for Linux or something.

**Comment by garrynewman** [comment]
Is it a dedicated server or a game client?

**Comment by UnknownSoldier1** [comment]
It's a game client.
