### ISSUE TITLE
ConnectionInfo.Identity points to address

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/Facepunch.Steamworks#386]
ConnectionInfo.Identity points to address rather than identity, can't access steamid anymore

https://github.com/Facepunch/Facepunch.Steamworks/blob/e48a0db798fd3d8e1f876abc8ba2741bab258b23/Facepunch.Steamworks/Networking/ConnectionInfo.cs#L38

**Comment by garrynewman** [comment]
`Identity.Steamid` should be what you're looking for?

**Comment by garrynewman** [comment]
Wait sorry you're right - I fucked it, fixed now
