### ISSUE TITLE
Ugc.Item.Description is being limited to 256 bytes

### ISSUE THREAD

**Issue by michelmcbride** [Facepunch/Facepunch.Steamworks#388]
When I get Ugc.Item.Description from a query it will truncate the actual description text to 256 bytes.

1. Call Ugc.Editor.WithDescription(string t) where t is greater than 256 bytes (a few lorem ipsum paragraphs)
2. View workshop item, and note the full string was updated.
3. Query the Ugc.Item and note Ugc.Item.Description is truncated to 256 bytes

My code (t > 256 bytes):
var editor = new Steamworks.Ugc.Editor(myModId);
editor = editor.WithDescription(t);
var editResult = await editor.SubmitAsync();

var query = Steamworks.Ugc.Query.Items.WhereUserPublished();
var page = await query.GetPageAsync(1);
foreach(Steamworks.Ugc.Item item in page.Value.Entries){
      Debug.Log(item.Description); //this is truncated to 256 bytes
}

**Expected behavior**
Ugc.Item.Description returns full description text

**Comment by michelmcbride** [comment]
Wait it turns out I don't actually know what 8000 bytes is. The bug is actually the Description I get from a query is being limited to 256 bytes.

**Comment by michelmcbride** [comment]
Also Ugc.Item.Title is returning 128 bytes instead of 129

**Comment by garrynewman** [comment]
In your query call `.WithLongDescription( true )` to get the full description.

Title is 128 bytes because one of the bytes is null to indicate the end of the string.

**Comment by michelmcbride** [comment]
I'm a fool!

Well, the Description and the Title are still returning 7999 bytes and 128 bytes respectively. I can update the workshop item with the full 8000 and 129. (ie. the last character is getting cut off in the query if you use the full amount of bytes)
