### ISSUE TITLE
RequestEncryptedAppTicketAsync() always returning null

### ISSUE THREAD

**Issue by DiscoJustice** [Facepunch/Facepunch.Steamworks#389]
I'm using Unity 2019.1.14 and I'm using the below code:

```
Debug.Log(SteamClient.Name);
Debug.Log(SteamClient.IsValid);
Debug.Log("Requesting encrypted app ticket from Steam");
byte[] encryptedTicket = null;
encryptedTicket = await SteamUser.RequestEncryptedAppTicketAsync();
Debug.Log(encryptedTicket);
```
I'm running Steamworks.SteamClient.Init(xxxx, true); earlier on, and it connects okay as can be seen by the result of IsValid in the output below:

```
<my steam name>
True
Requesting encrypted app ticket from Steam
Null
```

I've generated an Encrypted App Ticket Key in Steamworks. Is there something else I should be doing to get a result here?

**Comment by garrynewman** [comment]
Couple of dumb questions:

Did you publish your changes in Steamworks?
Are you using the right appid?

Also something to note is that RequestEncryptedAppTicket has a cooldown, so you need to wait at least 60 seconds between consecutive calls - maybe something is calling it before you get there?

**Comment by DiscoJustice** [comment]
Not dumb questions at all because I absolutely had not published the change, and now I have and it works perfectly. Sorry and thank you!
