### ISSUE TITLE
R2.3.0 - IndexOutOfRangeException while accessing leaderboard score

### ISSUE THREAD

**Issue by scgsergiusz** [Facepunch/Facepunch.Steamworks#392]
The same error in the new version.

There is leaderboard configured in steam and it has 3 entries.

While accessing top 5 scores by:

`this.currentSteamOperation = lb.Value.GetScoresAsync(5);
this.currentGlobalRank = await (this.currentSteamOperation as Task<Steamworks.Data.LeaderboardEntry[]>);`

IndexOutOfRangeException is thrown.

Exception is thrown even if I ask for exact number of entries, taken from:

`Steamworks.Data.Leaderboard?.Value.EntryCount`

`IndexOutOfRangeException: Index was outside the bounds of the array.
Steamworks.Data.Leaderboard+<LeaderboardResultToEntries>d__17.MoveNext () (at D:/a/Facepunch.Steamworks/Facepunch.Steamworks/Facepunch.Steamworks/Structs/Leaderboard.cs:116)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <437ba245d8404784b9fbab9b439ac908>:0)
Steamworks.Data.Leaderboard+<GetScoresAsync>d__14.MoveNext () (at D:/a/Facepunch.Steamworks/Facepunch.Steamworks/Facepunch.Steamworks/Structs/Leaderboard.cs:73)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <437ba245d8404784b9fbab9b439ac908>:0)
SteamIntegrationController+<LoadGlobalRankingV2>d__68.MoveNext () (at Assets/SteamIntegrationController.cs:474)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <437ba245d8404784b9fbab9b439ac908>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <94c5f4c38cdc42d2b006f8badef04394>:0)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()`

**Comment by garrynewman** [comment]
Can you use the template so I don't have to ask you all the questions that it asks

**Comment by scgsergiusz** [comment]
Do you really want me to create a new issue just to add a unity version? 
What else is missing there?

**Comment by garrynewman** [comment]
I don't know that you're using Unity, I don't know what unity version you're using, I don't know what .net version you're using, I don't know what OS you're using, I don't know if you're using IL2CPP, I don't know if it shows in the editor.

The template exists to answer these questions so I don't have to ask them. It might seem like an inconvenience and like it shouldn't matter - but it does - the more questions you can answer before I ask them the less questions I have to manually as you to try to fix your issues.

**Comment by scgsergiusz** [comment]
Instead of closing bug once again, esp. that it's quite clear where it happens I think it would be more efficient for everyone to use comments functionality.

Anyway, I created another request, using template and added additional answers to your questions here, not covered by template. Hope it helps.

Thanks,
S.
