### ISSUE TITLE
R2.3.0 - IndexOutOfRangeException while accessing leaderboard score

### ISSUE THREAD

**Issue by scgsergiusz** [Facepunch/Facepunch.Steamworks#393]
**Describe the bug**
Unable to retreive global score using SteamUserStats - IndexOutOfRangeException is thrown each time

**To Reproduce**
1. Obtain leaderboard using `SteamUserStats.FindLeaderboardAsync`
2. Ask for scores using `GetScoresAsync`

**Calling Code**
`Task steamTask = SteamUserStats.FindLeaderboardAsync("<leaderboard name>");
Steamworks.Data.Leaderboard? leaderBoard = await (steamTask as Task<Steamworks.Data.Leaderboard?>);
			if (steamTask.IsCompleted)
			{
				if (leaderBoard.HasValue)
				{
					steamTask = leaderBoard.Value.GetScoresAsync(2);
					Steamworks.Data.LeaderboardEntry[] scores = await (this.currentSteamOperation as Task<Steamworks.Data.LeaderboardEntry[]>);
				}
			}`

**Expected behavior**
Array of `Steamworks.Data.LeaderboardEntry` with leaderboard entries returned.

**Desktop (please complete the following information):**
 - OS: Windows 10
- Unity: 2019.3.2f1, IL2CPP, .NET 4.x

**Additional context**
Except for console stack trace, no additional information is displayed in the editor / player
Does not matter if requested number of entries is more/less existing ones - exception is thrown each time

_Stack Trace_
`IndexOutOfRangeException: Index was outside the bounds of the array. Steamworks.Data.Leaderboard+<LeaderboardResultToEntries>d__17.MoveNext () (at D:/a/Facepunch.Steamworks/Facepunch.Steamworks/Facepunch.Steamworks/Structs/Leaderboard.cs:116) --- End of stack trace from previous location where exception was thrown --- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <437ba245d8404784b9fbab9b439ac908>:0) System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0) System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0) System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0) System.Runtime.CompilerServices.TaskAwaiter1[TResult].GetResult () (at <437ba245d8404784b9fbab9b439ac908>:0)
Steamworks.Data.Leaderboard+d__14.MoveNext () (at D:/a/Facepunch.Steamworks/Facepunch.Steamworks/Facepunch.Steamworks/Structs/Leaderboard.cs:73)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.TaskAwaiter1[TResult].GetResult () (at <437ba245d8404784b9fbab9b439ac908>:0) SteamIntegrationController+<LoadGlobalRankingV2>d__68.MoveNext () (at Assets/SteamIntegrationController.cs:474) --- End of stack trace from previous location where exception was thrown --- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <437ba245d8404784b9fbab9b439ac908>:0) System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <437ba245d8404784b9fbab9b439ac908>:0) UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <94c5f4c38cdc42d2b006f8badef04394>:0) UnityEngine.UnitySynchronizationContext:ExecuteTasks()`

**Comment by garrynewman** [comment]
Check this out: https://github.com/Facepunch/Facepunch.Steamworks.UnityTest

Does this cause the same errors for you?

https://github.com/Facepunch/Facepunch.Steamworks.UnityTest/blob/master/Assets/SteamworksTest.Leaderboards.cs

Can you add a test to it that does cause the issue you're seeing?

**Comment by scgsergiusz** [comment]
Test case you mentioned uses different method:

`var friendScores = await leaderboard.Value.GetScoresFromFriendsAsync();`

Anyway, I used it and result is the same: exception and location of the problem is at:

`Leaderboard.cs:116`

Code I used for testing:

`Task steamTask = SteamUserStats.FindLeaderboardAsync("Spike_WA1b_Main");
			Steamworks.Data.Leaderboard? leaderBoard = await (steamTask as Task<Steamworks.Data.Leaderboard?>);
			if (steamTask.IsCompleted)
			{
				if (leaderBoard.HasValue)
				{
					steamTask = leaderBoard.Value.GetScoresFromFriendsAsync();// GetScoresAsync(2);
					Steamworks.Data.LeaderboardEntry[] scores = await (steamTask as Task<Steamworks.Data.LeaderboardEntry[]>);
				}
			}`

**Comment by garrynewman** [comment]
If you download that project and run it - do you get the error?

**Comment by scgsergiusz** [comment]
I downloaded project and and it worked.
I noticed though that it's 2.3.2 version used in the test project, which seems to have this bug resolved. 
I was using version 2.3.0 so I think we can close this with reason: end-user negligence :)
