### ISSUE TITLE
Can't start steam game server without steam_appid.txt on linux

### ISSUE THREAD

**Issue by EvMac0** [Facepunch/Facepunch.Steamworks#394]
**Describe the bug**
InitGameServer/SteamInternal_GameServer_Init returned false without file "steam_appid.txt"
After adding file "steam_appid.txt" in program folder, server start

**To Reproduce**
1. Write and build with dotnet for netcore 2.1, move and add execute privlidges to file
2. Run and see error
4. Put steam_appid.txt with 480 to current folder, run again, server will be start succesfully

**Calling Code**
```
SteamServerInit init = new SteamServerInit("ratibor", "Ratibor");
init.IpAddress = IPAddress.Parse("0.0.0.0");
init.GamePort = 28015;
init.Secure = false;
init.VersionString = 101.ToString();
init = init.WithQueryShareGamePort();

try {
	SteamServer.Init(480, init, true);
} catch (Exception ex) {
	Console.WriteLine("Couldn't initialize Steam Server (" + ex.Message + ")"); // throw if steam_appid.txt not found
	return;
}
```

**Desktop:**
 - OS: Ubuntu 18.04.4 LTS x64
- Unity: without

**Comment by EvMac0** [comment]
Solved! 
To discard steam_appid.txt, add code:
```
Environment.SetEnvironmentVariable("SteamAppId", appid.ToString());
Environment.SetEnvironmentVariable("SteamGameId", appid.ToString());
```

**Comment by EvMac0** [comment]
```
Environment.SetEnvironmentVariable("SteamAppId", appid.ToString());
Environment.SetEnvironmentVariable("SteamGameId", appid.ToString());
```
the code exists by default in "SteamServer.Init" method and this doesn't work.
On my system, if you set LD_LIBRARY_PATH to path that contains steam_appid.txt, you can start succesfully game server, otherwise it will be wrong.

**Comment by EvMac0** [comment]
I downloaded rust server on linux and he works fine without any steam_appid.txt. 
But when i try to start my own server, he won't works without steam_appid.txt

**Comment by garrynewman** [comment]
Last I saw Valve hadn't updated the linux dedicated server libraries to the latest sdk.

I fixed this in Rust by using the .so's from the linux client - and has been working fine.

Here they are:

[linux64.zip](https://github.com/Facepunch/Facepunch.Steamworks/files/4367906/linux64.zip)
