### ISSUE TITLE
list lobbies in csgo

### ISSUE THREAD

**Issue by Neroli-realy** [Facepunch/Facepunch.Steamworks#395]
hi, i wanted to list community servers in csgo then get players names in each one

here is my approch: 

![image](https://user-images.githubusercontent.com/25514920/77260820-ea4a8a00-6c92-11ea-8828-b9814344fabf.png)

can you help me?

**Comment by Neroli-realy** [comment]
after a while i used this code 

![image](https://user-images.githubusercontent.com/25514920/77375664-d7a98100-6d76-11ea-96ae-0381b0f3b5e8.png)

but always got , no lobbies found

**Comment by garrynewman** [comment]
I'm not sure - it might just be that they use a different way to create lobbies?

**Comment by Neroli-realy** [comment]
mm , i want to connect to servers and list steamids of players ... do you  is that possible ?

**Comment by garrynewman** [comment]
No, you need a source engine query
