### ISSUE TITLE
Unable to access API? Please help

### ISSUE THREAD

**Issue by Equinox100** [Facepunch/Facepunch.Steamworks#396]
I am new to programming and trying to use this API to make a bot to query and collect which servers players visit on a steam game. However at the first hurdle of just running an example I'm having problems, I know this might be trivial but I can't find the solution and would appreciate if you could give advice. I believe that I have incorrectly setup the project and am getting an error when trying to run an example. "The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)	test	C:\Users\josh\Desktop\2020\steambot\Program.cs"

Using this:

```using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Steamworks;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            // ...

            try
            {
                SteamClient.Init(4000);
            }
            catch (System.Exception)
            {
                // Couldn't init for some reason (steam is closed etc)
            }
        }
    }
}
```

If you would be able to help I'd greatly appreciate it, thankyou

**Comment by garrynewman** [comment]
You need to add a reference to the steamworks dll

**Comment by Equinox100** [comment]
Hey thanks for the reply, is that the steam_api64.dll? Whenever I try add the reference it says "Please make sure that the file is accessible, and that it is a valid assembly or COM component"

**Comment by garrynewman** [comment]
No - it's the Facepunch.Steamworks.*.dll

**Comment by Equinox100** [comment]
Forgive me for my ignorance, I could only find Facepunch.Steamworks.Win64.dll.meta in the unityplugin folder, is that the one, or is it something else? Thanks for your time

**Comment by garrynewman** [comment]
Check out the Releases page

https://github.com/Facepunch/Facepunch.Steamworks/releases

**Comment by Equinox100** [comment]
Oh wow thanks I downloaded the source code instead of the compiled one, thanks a lot for your help
