### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by Equinox100** [Facepunch/Facepunch.Steamworks#397]
Hey, I made a post earlier about an error caused by me not having the Facepunch.Steamworks.*.dll in my project folder as I mistakenly used the uncompiled version, but now that I have this and the steamapidll with a reference to the steamworksdll I'm getting an exception
 ```Exception thrown: 'System.DllNotFoundException' in Facepunch.Steamworks.Win64.dll``` 
My root directory is here:
![](https://i.gyazo.com/84139a7d0d4734ab384e326f5cf13146.png)

and this is the basic example that im using, could you please tell me what I'm doing wrong? Thanks for your time

``` using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Steamworks;
namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            // ...

            try
            {
                Console.WriteLine("Initializing Steam Client!");
                SteamClient.Init(4000);
            }
            catch (System.Exception)
            {
                // Couldn't init for some reason (steam is closed etc)
                Console.WriteLine("Failed to initialise steam client!");
            }
            Console.WriteLine("Initialised Steam Client!");
        }
    }
}
```

**Comment by garrynewman** [comment]
You need to make sure steam_api64.dll is copied to the output. If you add it to your solution you can right click, properties and change "copy to output directory" to "always copy".

**Comment by Equinox100** [comment]
Hey, sorry I'm not sure what you mean by that, I try add a reference to the steam_api64.dll but it gives me an error

**Comment by garrynewman** [comment]
Add it to your project - not as a reference.
