### ISSUE TITLE
Server starts on first ip that he can use

### ISSUE THREAD

**Issue by Bombardir** [Facepunch/Facepunch.Steamworks#4]
A lot of the servers missing from the list. 
(like this one https://lab.facepunch.com/rust/eyw8/server_not_showing_up_server_list_/page/1#unseen)
I think problem is with new Steamworks, because steam (not game) server starts on first ip on the machine (0.0.0.0, any) after last update.

**Comment by rustov** [comment]
Same problem. This started after the last update. Steam masterserver does not have more than 500 rust servers for now (maybe 500-1000)

**Comment by garrynewman** [comment]
This was fixed, update released, should work now.
