### ISSUE TITLE
SteamNetworkSockets [Help 🙏] 

### ISSUE THREAD

**Issue by unicornxiii** [Facepunch/Facepunch.Steamworks#400]
**Describe the bug**
When connecting via ConnectP2P
I get a connection error

(ERROR)
ProblemDetectedLocally
Couldn't connect
End-to-end connection: closed due to problem detected locally, reason code 4003 (Bad cert: CA key is not know to us)

Failed crypto init in ConnectOK packet Bad cert

**Calling Code**
```
public async Task RelayEndtoEnd()
		{
			SteamNetworkingUtils.InitRelayNetworkAccess();
			SteamNetworkingUtils.DebugLevel = NetDebugOutput.Warning;
			SteamNetworkingUtils.OnDebugOutput += DebugOutput;

			// For some reason giving steam a couple of seconds here 
			// seems to prevent it returning null connections from ConnectNormal
			await Task.Delay( 2000 );

			Console.WriteLine( $"----- Creating Socket Relay Socket.." );
			var socket = SteamNetworkingSockets.CreateRelaySocket<TestSocketInterface>( 6 );
			var server = socket.RunAsync();

			await Task.Delay( 1000 );

			Console.WriteLine( $"----- Connecting To Socket via SteamId ({SteamClient.SteamId})" );
			var connection = SteamNetworkingSockets.ConnectRelay<TestConnectionInterface>( SteamClient.SteamId, 6 );
			var client = connection.RunAsync();

			await Task.WhenAll( server, client );
		}
```
**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
- Unity: [e.g Unity 2019.2]

**Additional context**

**Comment by unicornxiii** [comment]
`var connection = SteamNetworkingSockets.ConnectRelay<TestConnectionInterface>( SteamClient.SteamId, 6 );`

**Comment by unicornxiii** [comment]
🤕

**Comment by garrynewman** [comment]
Not sure what to tell you - the test works here in visual studio test explorer. 

I could make a test in Unity if that's where you're having the problem, but I feel like given that error message it's more likely to do with Steam needing an update or a backend problem?

**Comment by unicornxiii** [comment]
I tested several computers (Not on the same Internet connection network) and basically connected successfully (Sometimes I received this error, but when reconnecting - excellent).  But from one computer.  I get this error.  Always. (Reconnecting doesn't help) Can I help?  Something to send?

**Comment by unicornxiii** [comment]
Yes, the error on Unity

**Comment by unicornxiii** [comment]
![3396986F-184A-49A4-A654-439BEE31A634](https://user-images.githubusercontent.com/62686238/77643959-14959380-6f82-11ea-9f25-aea27a204abf.jpeg)

**Comment by unicornxiii** [comment]
```
public async Task RelayEndtoEnd(ulong steam_id)
		{


			SteamNetworkingUtils.InitRelayNetworkAccess();
			
			SteamNetworkingUtils.DebugLevel = NetDebugOutput.Warning;
			SteamNetworkingUtils.OnDebugOutput += DebugOutput;
			print(SteamNetworkingUtils.Status);
			
			await Task.Delay(2000);

			if (STEAM_ID == SteamClient.SteamId)
			{

				Console.print($"----- Creating Socket Relay Socket..");
				var socket = SteamNetworkingSockets.CreateRelaySocket<TestSocketInterface>(0);
				var server = socket.RunAsync();

				await Task.Delay(3000);
			}

			Console.print($"----- Connecting To Socket via SteamId ({steam_id})");
			var connection = SteamNetworkingSockets.ConnectRelay<TestConnectionInterface>(steam_id, 0);
			var client = connection.RunAsync();

			
		}
```

**Comment by unicornxiii** [comment]
![93248261-0A34-41F2-963D-832D3330A2D8](https://user-images.githubusercontent.com/62686238/77716457-0ede9300-7000-11ea-9bf6-b0c645c06c0b.png)

**Comment by unicornxiii** [comment]
Hello Garry, hopelessly?

**Comment by unicornxiii** [comment]
Help me, please  🙏
