### ISSUE TITLE
Helpers is not thread-safe

### ISSUE THREAD

**Issue by DoubleOhmSeven** [Facepunch/Facepunch.Steamworks#401]
**Describe the bug**
Steamworks is generally thread-safe, but `Helpers`' methods aren't, this sometimes causes the same buffer to be re-used.

**To Reproduce**
Call `TakeBuffer` or `TakeMemory` from multiple threads and change values to it, the expected result will not always be the same.

**Idea**
An alternative is to use ArrayPool from NuGet, which is thread-safe:
https://www.nuget.org/packages/System.Buffers/

**Comment by garrynewman** [comment]
Thanks, I've made them ThreadStatic

**Comment by DoubleOhmSeven** [comment]
Thanks, but ThreadStatic isn't thread-safe either if you use async/await, which is pretty common nowadays. A better solution would be to surround these methods with a lock. ThreadStatic also causes more allocations than necessary, on high core CPUs this can allocate quite a lot.

**Comment by garrynewman** [comment]
Their usage in the API should be such that async never causes a problem - if you can find instances where that isn't true please highlight them and I'll come up with alternatives.

**Comment by DoubleOhmSeven** [comment]
I've went through the code and I've not seen it used in an async method so it should be fine right now. It's something to stay aware of for future usage. A greatly increased allocated memory on high core CPUs is still a problem though. Why not just use ArrayPool? It's taking care of all of this and is available for .NETStandard 1.1 and up.

**Comment by garrynewman** [comment]
Converted this to use locks like you suggested
