### ISSUE TITLE
There is no RequestLobbyData method.

### ISSUE THREAD

**Issue by eralpzr** [Facepunch/Facepunch.Steamworks#404]
I can't find any RequestLobbyData method. I want to get lobby metadata like the name of the lobby owner, but I can't get data without joining the lobby. Is there a similar method to this method or is it forgotten?

Steamworks Link:
https://partner.steamgames.com/doc/api/ISteamMatchmaking#RequestLobbyData

**Comment by laurentopia** [comment]
`CreateLobbyAsync ` returns a lobby
you then do `lobby.Value.GetData()`

**Comment by garrynewman** [comment]
You should have able to do:

```
var lobby = new Lobby( steamid );
lobby.GetData();
```

Does that work?
