### ISSUE TITLE
Which version of the editor is it compatible with?

### ISSUE THREAD

**Issue by laurentopia** [Facepunch/Facepunch.Steamworks#409]
![image](https://user-images.githubusercontent.com/26075468/79673190-d0ff0580-818c-11ea-813d-9694babc9a2a.png)
Unity 2017 LTS doesn't seem to like it

**Comment by Lestat** [comment]
Why not use the latest? I always use the latest version in all my projects.

**Comment by laurentopia** [comment]
@Lestat off topic

**Comment by garrynewman** [comment]
4.x and netstandard
