### ISSUE TITLE
runcallback

### ISSUE THREAD

**Issue by laurentopia** [Facepunch/Facepunch.Steamworks#410]
In the wiki it is recommended to call `RunCallbacks` from within `Update()`, I guess favoring that over setting the async flag of Init() to true.
```
	void Update()
	{
		Steamworks.SteamClient.RunCallbacks();
	}
```
Is it recommended to add some sort of test that the client is still running?

**Comment by garrynewman** [comment]
I'd favour the async version.

Yeah you should test SteamClient.IsValid.

**Comment by laurentopia** [comment]
Ok so ignore the documentation that recommends that we use Update() RunCallbacks.
