### ISSUE TITLE
SteamApps.OnNewLaunchParameters [no fields]

### ISSUE THREAD

**Issue by AsdfXyzt** [Facepunch/Facepunch.Steamworks#411]
Q: Have you ever faced such problem, got some workaround ?

I'm trying to pass some parameters from www page/HTTP redirect to **running** Unity application.
I was trying 
```
win+r
steam://run/{{app_id}}//-commandline/?param=test

steamoverlay + fake page with redirect 
steam://gamewebcallback?param=test
steam://run/{{app_id}}//-commandline/?param=test
```
methods implemented:
```
SteamUser.OnGameWebCallback
SteamApps.OnNewLaunchParameters
```

I know that application is notified about trigger but I can see only:
`-steamapi_debug ... NewUrlLaunchParameters: [no fields]`

Release: 2.32, Unity + IL2CPP + win64

**Comment by AsdfXyzt** [comment]
Found workaround with steam overlay, but not with browser.
```
appId is required which is not so obvious according to documentation 

HTTP 301 location:steam://gamewebcallback/{{appId}}/?param=test
SteamUser.OnGameWebCallback 
```

**Comment by garrynewman** [comment]
Thanks, have updated the docs to show that you need the appid. 

My feeling is that this doesn't actually work with the browser, the documentation on Steam's site only mentions the overlay.
