### ISSUE TITLE
Is this the proper way to call SetInt?

### ISSUE THREAD

**Issue by laurentopia** [Facepunch/Facepunch.Steamworks#412]
After initialization:
`SteamServerStats.SetInt(SteamClient.SteamId, stat, value);`
it nullrefs and since the debugger shows steamclient.steamid is set I wonder what could be wrong.
the compilo doesn't have an issue with that form

**Comment by garrynewman** [comment]
Is the server initialized?

**Comment by laurentopia** [comment]
I used autocomplete too aggressively, it was SteamUserStats.SetStat I needed...
