### ISSUE TITLE
Lobby.Leave() does not work

### ISSUE THREAD

**Issue by Bdoom** [Facepunch/Facepunch.Steamworks#414]
The lobby.leave() method does not work under any circumstances from what I can tell. 
I made a method like this:

public async void LeaveLobby()
    {
        lobbyList = await SteamMatchmaking.LobbyList.RequestAsync();
        foreach (var lobby in lobbyList)
        {
            if (lobby.Id == ourLobbyId)
            {
                lobby.Leave();
            }
        }
    }

OurLobbyID is set upon connecting to a lobby. 

private void SteamMatchmaking_OnLobbyEntered(Lobby lobby)
    {
        Debug.Log("Joined lobby.");
        lobbyCountText.text = "Lobby Count: " + lobby.MemberCount + "/" + lobby.MaxMembers;

        ourLobbyId = lobby.Id;
        isInLobby = true;

        if (lobby.IsOwnedBy(SteamClient.SteamId))
        {
            Debug.Log("we own the lobby");
            ownsLobby = true;
            lobby.SetPublic();
            StartCoroutine(LobbyCheckCoRoutine(lobby));
        }
    }

        ourLobbyId = lobby.Id;

lobby.Leave() is called when we kick everyone out of the lobby, or the application quits

**Comment by Bdoom** [comment]
lobby.SetGameServer(hostAddress, port);
                        lobby.SetJoinable(false); // lock the lobby once we have started a match. 

SetJoinable() is also broken. People are able to join my lobbies even after they have been locked!

**Comment by jpalacios2** [comment]
lobby.leave() doesn't seem to be working, joining the same lobby after leaving and joinable set to false.

**Comment by garrynewman** [comment]
I'm not sure what could be going wrong. Internally we're just calling [Leave Lobby](https://partner.steamgames.com/doc/api/ISteamMatchmaking#LeaveLobby) with the Id of the Lobby.

**Comment by Bdoom** [comment]
> I'm not sure what could be going wrong. Internally we're just calling [Leave Lobby](https://partner.steamgames.com/doc/api/ISteamMatchmaking#LeaveLobby) with the Id of the Lobby.

Hey Garry,

Sorry for not contacting you. I looked at this as well and it looks fine. I think the issue we were having was our own internal fault. Sorry for not closing out this ticket beforehand.

I hope you stay safe and have a nice day.

:)
