### ISSUE TITLE
Achievement.cs Object reference not set to an instance of an object when steam isn't valid

### ISSUE THREAD

**Issue by pippinmole** [Facepunch/Facepunch.Steamworks#415]
**Describe the bug**
Calling achievement.Trigger() causes object reference error when SteamClient.IsValid == false

**To Reproduce**
1. Close steam (or make SteamClient.IsValid false)
2. Try and unlock an achievement

**Calling Code**
```
var achievement = new Achievement(achievementId);
achievement.Trigger();
```

![image](https://user-images.githubusercontent.com/40035529/80663984-73709000-8a8d-11ea-8a31-26edbf49788c.png)

**Expected behavior**
Probably a warning/not an error

**Desktop (please complete the following information):**
 - OS: Windows 10
- Unity: Unity 2019.3.11f1

**Comment by garrynewman** [comment]
What would you like to happen?

**Comment by pippinmole** [comment]
> 
> 
> What would you like to happen?

Maybe a log warning, or some handled error?
