### ISSUE TITLE
NewCommunityFile - SubmitAsync always failing

### ISSUE THREAD

**Issue by ItemME** [Facepunch/Facepunch.Steamworks#417]
**Describe the bug**
When executing a NewCommunityFile (SubmitAsync) - If you're doing it with "WithContent" or "WithPreviewFile" it will always result in a failure, and more, it won't apply correctly to the item created, title, visibility, description etc.. (because, it is created anyway)

**To Reproduce**
1. Create a new C# Console project, add the x86 library (latest release & latest steamworks API)
2. Run a basic code to connect to a steam app id, and create a new item to the workshop
3. If you create an item, without content or preview image, it should work
4. If you create an item with either one of them, it will fail to proceed (but still create an empty item)

**Calling Code**
```
SteamClient.Init(app_id, true);

//This always fails
var result = await Steamworks.Ugc.Editor.NewCommunityFile
                          .WithTitle("Title")
                          .WithDescription("Description")
                          .WithContent("C:/absolute/path/to/the/folder")
                          .WithPreviewFile("C:/absolute/path/to/the/image.jpg")
                          .WithTag("ATag")
                          .WithPublicVisibility()
                          .SubmitAsync();

//This works fine
var result = await Steamworks.Ugc.Editor.NewCommunityFile
                          .WithTitle("Title")
                          .WithDescription("Description")
                          .WithTag("ATag")
                          .WithPublicVisibility()
                          .SubmitAsync();
```

**Expected behavior**
Item should be created, but isn't in the case where we're mentioning a content or a preview image

**Desktop (please complete the following information):**
 - OS: Windows 10
- Unity: Not using unity
- Visual Studio - C# Console Project .NET Framework 4.6 x86 targeted platform

**Comment by garrynewman** [comment]
Is `C:/absolute/path/to/the/folder` empty?

**Comment by ItemME** [comment]
Well it's not, there's a file (a .json one) at the root and then subfolders.

**Comment by garrynewman** [comment]
I can't reproduce this, in my unit test it's succeeding fine as long as the folder isn't empty.

**Comment by onewheelstudio** [comment]
I had a similar issue. The problem seemed to be by the steam cloud settings. The storage settings need to be increased to handle the image file. Not 100% sure why this didn't occur without the preview image, but the files I was uploading were quite small. Hope this helps someone.
