### ISSUE TITLE
Game's achievement activity view is blank

### ISSUE THREAD

**Issue by TiliSleepStealer** [Facepunch/Facepunch.Steamworks#420]
**Describe the bug**
I trigger an achievement, and I can see the little pop-up, like normal.
The achievement is viewable in the post-game summary and in the achievement list/sidebar. 
But it's missing from the activity feed.

![2020-05-07 14_21_01-steam](https://user-images.githubusercontent.com/6567869/81301903-92fd4f00-9071-11ea-8505-609d3d26d911.png)

You can see it says: Tili achieved [blank]
There should be content there.

**Calling Code**
```
// got a reference to the achievement before here
someAchievement.Trigger(true);
Steamworks.SteamUserStats.StoreStats();
SteamUserStats.RequestCurrentStats();
```

**Expected behavior**
I would like to see the activity feed contain text + imagery of achievements..

**Desktop (please complete the following information):**
 - OSX and Windows 10
- Unity 2018.4 LTS

**Additional context**
Using latest version of Facepunch.Steamworks.

**Comment by garrynewman** [comment]
This is more of a Steam thing than a FP.SW thing. I'd have a look in the backend and make sure you've published your changes etc.. maybe it doesn't work if your app isn't live?
