### ISSUE TITLE
No way to update KeyValueTags, can only add extra tags with the same key

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/Facepunch.Steamworks#422]
When updating workshop items AddKeyValueTags are submitted and multiple tags are added with the same key.  

Could expose RemoveItemKeyValueTags or RemoveAllItemKeyValueTags to UGC editor maybe to make it possible to update existing tags.

**Comment by kamyker** [comment]
RemoveItemKeyValueTags added in #423
