### ISSUE TITLE
Linking to steam only works when launched from unity.

### ISSUE THREAD

**Issue by mickev36** [Facepunch/Facepunch.Steamworks#426]
Hi !

I've implemented the basic code to get Facepunch.steamworks with unity running. Everything works great when i'm in the editor, and when I run the game with "Build and run..." from within Unity (game shows up in steam, I can open the invite overlay, etc...). But when launching directly from the .exe, Steam overlay doesn't activate even though the game shows up in steam with the correct name.

Set up a simple game, call SteamClient.Init with my steam app id. 
Build the game, then run it directly from the .exe
Try to call the steam overlay for example, the overlay doesn't show up

Platform : Win 10 64-bit, Unity 2019.3.7f1, latest Facepunch.steamworks (current)

**Comment by mickev36** [comment]
I'm not sure if you need any more details regarding this issue, is you need any more information, please hit me up, i'll be glad to provide it to you.

Thanks for your awesome work.

**Comment by mickev36** [comment]
UPDATE : The game actually show up in steam now, but the overlay still doesn't show up when I launch the .exe directly, only when using "Build and run...".

**Comment by kamyker** [comment]
Try again with higher Unity version, they had some issues with dlls

**Comment by mickev36** [comment]
Thanks for the advice ! I'm downloading the latest version and will try it asap. I will update you when it's done

**Comment by mickev36** [comment]
Just upgraded to 2019.3.13f1 (latest), same behaviour. Additional change : the "build and run" launch now does not trigger the steam overlay. But game is still showing as played in steam

**Comment by mickev36** [comment]
Investigated, and probably not linked directly to Facepunch.steamworks, but rather to the underlying Steamworks.NET

**Comment by mattluard** [comment]
Hi @mickev36, can you expand on what you found out here? I'm experiencing the exact same issue but I'm less clear on what's going on: Steam connects to my game when running in the editor, but it doesn't appear to when building it - I can't bring up the overlay, at least. The game shows as being "running" in the list in the Steam client, so there's some awareness there, and SteamClient.Init doesn't throw any errors.

I'm also using 2019.3.13f1. Appreciate any help!

**Comment by LukasKastern** [comment]
I'm pretty sure that the game actually has to be started through steam for the overlay to pop up.

**Comment by mattluard** [comment]
> I'm pretty sure that the game actually has to be started through steam for the overlay to pop up.

Thanks @LukasKastern, I think you're probably right, I uploaded my build through Steampipe and I get the overlay through Shift+Tab...

However! The problem I still have is that `Steamworks.SteamFriends.OpenWebOverlay(url);` still does nothing? Even when the game is launched from Steam. Are there any known reasons why OpenWebOverlay can silently fail? Maybe this is a slightly different issue to the original post.

What complicates this for me is that I _was_ able to get the overlay up in the Unity Editor, and OpenWebOverlay worked then. (I couldn't get rid of the overlay though, had to restart Steam.) I haven't been able to get it working in Unity today however. I'm confused!
