### ISSUE TITLE
steam_api64.dll can not be loaded in builds, only in the editor

### ISSUE THREAD

**Issue by LiterallyFabian** [Facepunch/Facepunch.Steamworks#451]
**Describe the bug**
Using methods from facepunch.steamworks works in the editor as long as some files are removed, but never works in the build

**To Reproduce**
List of my installation process:
1. I put the files from the Unity folder in my project/Assets/Plugins/Facepunch.Steamworks folder as shown in [this guide](https://wiki.facepunch.com/steamworks/Installing_For_Unity)
2. When opening Unity, I get this error from all lines I call any method from the package from
`Assets\Scripts\ButtonCtrl.cs(52,13): error CS0433: The type 'SteamClient' exists in both 'Facepunch.Steamworks.Posix, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Facepunch.Steamworks.Win32, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
`
3. I now can't run my game unless I remove the win32 & posix files (dll, pdb, xml) and only keep windows, but in the installation guide the files are not removed 
4. If I remove the win32 & posix files the game works in the editor, but running the build will cause an error:
`
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/steam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/steam_api64.dll
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/steam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/libsteam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/libsteam_api64.dll
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/libsteam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/steam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/steam_api64.dll
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/steam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/libsteam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/libsteam_api64.dll
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/libsteam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/steam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/steam_api64.dll
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/steam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/libsteam_api64
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/libsteam_api64.dll
Fallback handler could not load library E:/SajberSim Build/SajberSim_Data/Mono/libsteam_api64
Steam: Could not connect to steam.
System.DllNotFoundException: steam_api64
  at (wrapper managed-to-native) Steamworks.SteamAPI+Native.SteamAPI_Init()
  at Steamworks.SteamAPI.Init () [0x00001] in <19bd4cc6a4004258bf538b05ac1133d6>:0 
  at Steamworks.SteamClient.Init (System.UInt32 appid, System.Boolean asyncCallbacks) [0x00039] in <19bd4cc6a4004258bf538b05ac1133d6>:0 
  at ButtonCtrl.Start () [0x00000] in <5cc883b6741a4bb696f53a28ba3577b4>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
`

**Calling Code**
```
public void Start()
    {
        try
        {
            SteamClient.Init(Helper.AppID);
            Helper.loggedin = true;
            UnityEngine.Debug.Log($"Steam: Connected to {SteamClient.Name} (ID: {SteamClient.SteamId})");
        }
        catch (System.Exception e)
        {
            UnityEngine.Debug.LogError($"Steam: Could not connect to steam.\n{e}");
            Helper.loggedin = false;
        }
}
```

**Expected behavior**
I'd expect it to work like it does in the editor, but steam_api64 can't be found

**Desktop (please complete the following information):**
 - Windows 10
- Unity: 2019.3.15f1

**Comment by LiterallyFabian** [comment]
Going into build settings and changing architecture to x86_64 seems to solve the issue, as long as I still delete the two files in step 3. Everything works fine now

**Comment by fegabe** [comment]
thank you! this helped me fixing the error compiling on Github Actions CI :)
