### ISSUE TITLE
SteamInternal_GameServer_Init returns false without no detail whatsoever

### ISSUE THREAD

**Issue by xiaoxiao921** [Facepunch/Facepunch.Steamworks#453]
I tried joining the steamworks steam discussion before making this issue, but apparently the number of pending request to join is too huge and you can't seem to able to join it currently.

I'm trying to run an unity game through my linux VPS and wine, so far the game seems to boot just fine with -nographics and -batchmode, the game doesnt ship linux build atm for its dedicated server build availabe directly from STEAMCMD, sadly.
When comes the moment to call the steam api for creating the Server,
SteamInternal_GameServer_Init seems to be returning false without any indication on why it could fail. Any solution for this ?

**Comment by cr4yz** [comment]
https://partner.steamgames.com/doc/api/ISteamGameServer#InitGameServer

https://github.com/Facepunch/Facepunch.Steamworks/blob/a7954f9e2172eb9e25a2081186256d9fddb42329/Facepunch.Steamworks/Classes/SteamInternal.cs#L16

Documentation differs from api, this could be the issue.

**Comment by LukasKastern** [comment]
Having the same issue with AWS instances.
On my local machine it's working fine but the servers are not being listed, even tho the machine is fully exposed.

I doubt that this is related to this wrapper.

**Comment by garrynewman** [comment]
When you try it on your local machine, do you have Steam running? Does it work locally without Steam running?

**Comment by xiaoxiao921** [comment]
I suspect wine just fails to bind properly with the steam_api.dll for some reason
I know that people host servers games fines when using Steam on linux, probably because how Valve did proton, forked their own wine and probably fixed a bunch of things related to the steam native dlls.
I don't think its related to this wrapper too, but it's a bit sad we have no other places for this kind of thing as the steamworks server forum is full for some reason.
Being able to run proton while being headless would probably solve this but last time I checked i couldn't find anything for doing that

**Comment by cr4yz** [comment]
I've had a few reports from Linux players on Proton, SteamClient fails to init.  If I remember right some old version of Proton works fine.  Possibly related?

**Comment by xiaoxiao921** [comment]
This issue seems to get fixed if you get the `steamclient.dll`
https://github.com/avivace/ror2-server/issues/1#issuecomment-672383266
