### ISSUE TITLE
InstallScript analog

### ISSUE THREAD

**Issue by Replica7or** [Facepunch/Facepunch.Steamworks#456]
Hello. I am developing a game on Unity. I need to install third-party software for its work. Steamworks uses InstallScript for this. What is the counterpart in Facepunch?

**Comment by garrynewman** [comment]
It's not a client thing, you do it in the backend of Steamworks

**Comment by Replica7or** [comment]
Thanks. Maybe it was a stupid question. I just started learning steamworks today
