### ISSUE TITLE
GetLargeAvatarAsync does not work correctly?

### ISSUE THREAD

**Issue by barsovya** [Facepunch/Facepunch.Steamworks#457]
Hi Garry.
When using the function **SteamFriends.GetLargeAvatarAsync**(steamId) in response comes question mark on white background. I'm using the library version 2.3.2 
It is suspected that SteamID in function does not work.

Example of my code:
```
var image = await SteamFriends.GetLargeAvatarAsync(steamId);
Texture2D Avatar;
Avatar.LoadImage(image.Value.Data);
AvatarChanged.Invoke(Avatar.ConvertToSprite());

private protected void OnAvatarChanged(Sprite sprite)
{
     Image.sprite = sprite;
}
```

The result of the function is always the same - question mark on white background in response from steam.
[https://imgur.com/5uozljL](https://imgur.com/5uozljL)
When I use a similar function from Steamworks.NET everything works fine.

**Comment by barsovya** [comment]
Resolved when used GetPixel. 
The question is closed

**Comment by onewheelstudio** [comment]
This took me a good long while to figure out what the second comment was referring to with "GetPixel." In case I'm not the only one my solution is shown below. The function takes in a Steamworks Friend, grabs the avatar from Steamworks, converts the data to an array of colors, sets the pixels in the texture, creates a sprite and finally sets the sprite in an image component (avatar); 

Almost for sure not the cleanest, but it works, maybe it'll save other folks some time.

`private async Task LoadPlayerAvatar(Steamworks.Friend friend)
    {
        var results = await SteamFriends.GetSmallAvatarAsync(friend.Id);

        if (results.HasValue)
        {
            //avatars are square so no need for height and width
            uint size = results.Value.Width;
            Texture2D texture = new Texture2D((int)size, (int)size); //create blank texture
            Color[] tempColors = new Color[size * size]; // intialize array of colors
                        
            for (int i = 0; i < size; i++)
            {
                for (int j = 0; j < size; j++)
                {
                    //using GetPixel was a sol'n from github
                    //The avatar pixels seem to be saved in a different order from Unity - image was flipped
                    //that's why the parameters in the GetPixel are adjusted
                    Steamworks.Data.Color steamColor = results.Value.GetPixel(j, (int)size - i - 1); 

                    //convert byte data to floats and create new color
                    tempColors[i * size + j] = new Color(steamColor.r / 255f, steamColor.g / 255f, steamColor.b / 255f, steamColor.a/ 255f);
                }
            }

            texture.SetPixels(tempColors);
            texture.Apply(); //crucial!

            //with the texture created it must now be converted to a sprite
            Sprite sprite = Sprite.Create(texture, new Rect(0, 0, texture.width, texture.height), new Vector2(0.5f, 0.5f));
            avatar.sprite = sprite; //avatar is an image component set in the inspector.
        }
        else
        {
            Debug.Log("Couldn't get avatar");
        }
    }`

**Comment by exiledgamesstudio** [comment]
> This took me a good long while to figure out what the second comment was referring to with "GetPixel." In case I'm not the only one my solution is shown below. The function takes in a Steamworks Friend, grabs the avatar from Steamworks, converts the data to an array of colors, sets the pixels in the texture, creates a sprite and finally sets the sprite in an image component (avatar);
> 
> Almost for sure not the cleanest, but it works, maybe it'll save other folks some time.
> 
> ```
> private async Task LoadPlayerAvatar(Steamworks.Friend friend)
>     {
>         var results = await SteamFriends.GetSmallAvatarAsync(friend.Id);
> 
>         if (results.HasValue)
>         {
>             //avatars are square so no need for height and width
>             uint size = results.Value.Width;
>             Texture2D texture = new Texture2D((int)size, (int)size); //create blank texture
>             Color[] tempColors = new Color[size * size]; // intialize array of colors
>                         
>             for (int i = 0; i < size; i++)
>             {
>                 for (int j = 0; j < size; j++)
>                 {
>                     //using GetPixel was a sol'n from github
>                     //The avatar pixels seem to be saved in a different order from Unity - image was flipped
>                     //that's why the parameters in the GetPixel are adjusted
>                     Steamworks.Data.Color steamColor = results.Value.GetPixel(j, (int)size - i - 1); 
> 
>                     //convert byte data to floats and create new color
>                     tempColors[i * size + j] = new Color(steamColor.r / 255f, steamColor.g / 255f, steamColor.b / 255f, steamColor.a/ 255f);
>                 }
>             }
> 
>             texture.SetPixels(tempColors);
>             texture.Apply(); //crucial!
> 
>             //with the texture created it must now be converted to a sprite
>             Sprite sprite = Sprite.Create(texture, new Rect(0, 0, texture.width, texture.height), new Vector2(0.5f, 0.5f));
>             avatar.sprite = sprite; //avatar is an image component set in the inspector.
>         }
>         else
>         {
>             Debug.Log("Couldn't get avatar");
>         }
>     }
> ```

Thanks a ton buddy, i had another prototyped method that didn't work no more and your tidy bit of code helped me.
