### ISSUE TITLE
SteamNetworkingSocket not receiving messages

### ISSUE THREAD

**Issue by ikomhoog** [Facepunch/Facepunch.Steamworks#458]
**Describe the bug**
I'm not receiving messages, what am I doing wrong?

I'm also calling socketManager.Receive(); every frame.(it doesn't matter if I do this or not)
but I only get the OnConnecting, OnConnected, and OnDisconnected messages.

**To Reproduce**
1. try this code(it is in unity)
2. see that "OK" gets logged for every connection*buttonpress
3. see that there are no messages incoming

**Calling Code**
this is my interface:
```
public class SteamSocketManagerInterface : ISocketManager
{
    public void OnConnected(Connection connection, ConnectionInfo info)
    {
        Debug.Log("OnConnected!!");
    }

    public void OnConnecting(Connection connection, ConnectionInfo info)
    {
        connection.Accept();
        Debug.Log("OnConnecting!!");
    }

    public void OnDisconnected(Connection connection, ConnectionInfo info)
    {
        Debug.Log("OnDisconnected!!");
    }

    public void OnMessage(Connection connection, NetIdentity identity, IntPtr data, int size, long messageNum, long recvTime, int channel)
    {
        Debug.Log("Got A Message!!");
    }
}
```
this is how I try to use it:
```
socketManager = SteamNetworkingSockets.CreateRelaySocket<SocketManager>();
socketManager.Interface = new SteamSocketManagerInterface();
SteamNetworkingSockets.ConnectRelay<ConnectionManager>(SteamClient.SteamId);
```
and later on  in the code, on a button press:
```
for (int i = 0; i < socketManager.Connected.Count; i++)
        {
            Result result = socketManager.Connected[i].SendMessage(bytes, sendType);
            Debug.Log(result);
        }
```

**Expected behavior**
I expected to get a message.

**Desktop (please complete the following information):**
 - OS: Windows10
- Unity: Unity 2019.4.0f1

**Additional context**
I first made a class derive from SocketManager but this didn't work and I read that it needs to be an interface to receive messages, so I tried it with this simple interface.
there is also additional code so other people can join my lobby and connect with me, but I also don't receive messages from them.

**Comment by ikomhoog** [comment]
i also just replaced the initial lines of socket/connection creation to the normal sockets via:
```
socketManager = SteamNetworkingSockets.CreateNormalSocket(NetAddress.AnyIp(12345), new teamSocketManagerInterface());
SteamNetworkingSockets.ConnectNormal<ConnectionManager>(NetAddress.LocalHost(12345));
```

And I get the same result,  I get "OnConnecting!!" and "OnConnected!!" at the start, and "OK" every time I click a button. 
But no incoming messages.

**Comment by Scarso327** [comment]
Are you running a task to call the to "Recieve" the messages?

**Example:**
```
        public async Task Listener()
        {
            while (true)
            {
                base.recieve();
                await Task.Delay(100);
            }
        }
```

**Comment by ikomhoog** [comment]
Yes i do, i also stated that in my issue.

**Comment by Scarso327** [comment]
Ah, I missed that. I mentioned it as I'd forgotten it and found myself confused as to why it wasn't working.

If I am not mistaken you have to call `SteamNetworkingUtils.InitRelayNetworkAccess();` before creating and using relays.

**Comment by ikomhoog** [comment]
According to the documentation that should not be necessary:
```
static void InitRelayNetworkAccess()
If you know that you are going to be using the relay network (for example, because you anticipate making P2P connections), call this to initialize the relay network. If you do not call this, the initialization will be delayed until the first time you use a feature that requires access to the relay network, which will delay that first access. You can also call this to force a retry if the previous attempt has failed. Performing any action that requires access to the relay network will also trigger a retry..
```
But ill try it when i get back to my pc again tomorrow.

**Comment by ikomhoog** [comment]
it still doesn't work, I tried making a new Unity project and trying simple code without clutter there, but it still doesn't want to work.
Am I sending the messages correctly?
I only get "logged in as: Ikomhoog", "OnConnecting!!", "OnConnected!!", lots of "OK", and "Shutdown".
this is my whole test code(both relay socket and normal socket give the same result):
```
using System;
using Steamworks;
using Steamworks.Data;
using UnityEngine;

public class ConnectionTest : MonoBehaviour
{
    public SocketManager socketManager;

    void Start()
    {
        SteamClient.Init(480);
        SteamNetworkingUtils.InitRelayNetworkAccess();
        Debug.Log("logged in as: " + SteamClient.Name);
        socketManager = SteamNetworkingSockets.CreateRelaySocket<SocketManager>();
        socketManager.Interface = new SteamSocketManagerInterface();
        SteamNetworkingSockets.ConnectRelay<ConnectionManager>(SteamClient.SteamId);
        /*socketManager = SteamNetworkingSockets.CreateNormalSocket(NetAddress.AnyIp(12345), new SteamSocketManagerInterface());
        SteamNetworkingSockets.ConnectNormal<ConnectionManager>(NetAddress.LocalHost(12345));*/
    }

    // Update is called once per frame
    void Update()
    {
        for (int i = 0; i < socketManager.Connected.Count; i++)
        {
            Debug.Log(socketManager.Connected[i].SendMessage("Hello"));
        }
    }

    void OnApplicationQuit()
    {
        SteamClient.Shutdown();
        Debug.Log("Shutdown");
    }
}

public class SteamSocketManagerInterface : ISocketManager
{
    public void OnConnected(Connection connection, ConnectionInfo info)
    {
        Debug.Log("OnConnected!!");
    }

    public void OnConnecting(Connection connection, ConnectionInfo info)
    {
        connection.Accept();
        Debug.Log("OnConnecting!!");
    }

    public void OnDisconnected(Connection connection, ConnectionInfo info)
    {
        Debug.Log("OnDisconnected!!");
    }

    public void OnMessage(Connection connection, NetIdentity identity, IntPtr data, int size, long messageNum, long recvTime, int channel)
    {
        Debug.Log("Got A Message!!");
    }
}
```

**Comment by Scarso327** [comment]
`SteamNetworkingSockets.ConnectRelay<ConnectionManager>(SteamClient.SteamId);`

This connection manager doesn't appear to have anything for receiving running... Using that test script just add a variable for saving the connection manager returned from the ConnectRelay and then in update call to receive from that.

**Comment by ikomhoog** [comment]
Ohh, i see that i forgot the socketManager.Receive() in the update.
Do i need to do the receive in both connection and socket?
Im going to try this, i didnt even notice before that there was also a receive in the connectionManager.

**Comment by ikomhoog** [comment]
I just tested it and i was under the impression that socketManager.Receive(); received the data on all connections.
Apparently it doesnt, and connectionManager.Receive(); does get it.
But now another question pops up, what does socketManager.Receive(); do if it doesnt receive data for connecting or for connections?

Ill be going to make my own socketmanager and put my own ReceiveAll() in there which will just proc the receive on every connection and then forward all the things to the socketManager.OnMessage().
This is the way i think it was supposed to work.

please tell me if ill be breaking other functionality if i do this, or if my issues are just a bug.

**Comment by Scarso327** [comment]
The SocketManager would be used by your server as it can handle multiple connections and then ConnectionManager is used by the client to manage their personal connection with the server.

Receive is used to basically "read" all messages sent from clients that are already connected. You need to call Recieve on all instances of SocketManager and ConnectionManager. SocketManager's Recieve will handle messages from **ALL** connections so you don't have to loop through all connections or something like that.

**Comment by ikomhoog** [comment]
"SocketManager's Recieve will handle messages from ALL connections so you don't have to loop through all connections or something like that."
thats what i also thought, but it doesnt work like you described in my code.
i need to call connectionManager.Receive() to get anything, socketManager.Receive doesnt do anything(for me).
Please try this code:
```
using System;
using Steamworks;
using Steamworks.Data;
using UnityEngine;

public class SteamNetworkingTest : MonoBehaviour
{
    public SteamSocketManager socketManager;
    public SteamConnectionManager connectionManager;

    void Start()
    {
        SteamClient.Init(480);
        SteamNetworkingUtils.InitRelayNetworkAccess();
        Debug.Log("logged in as: " + SteamClient.Name);
        socketManager = SteamNetworkingSockets.CreateRelaySocket<SteamSocketManager>();
        connectionManager = SteamNetworkingSockets.ConnectRelay<SteamConnectionManager>(SteamClient.SteamId);
    }

    // Update is called once per frame
    void Update()
    {
        socketManager.Receive();
        //connectionManager.Receive();
        for (int i = 0; i < socketManager.Connected.Count; i++)
        {
            Debug.Log(socketManager.Connected[i].SendMessage("Hello"));
        }
    }

    void OnApplicationQuit()
    {
        SteamClient.Shutdown();
        Debug.Log("Shutdown");
    }
}

public class SteamSocketManager : SocketManager
{
    public override void OnConnected(Connection connection, ConnectionInfo info)
    {
        Debug.Log("SocketOnConnected");
    }

    public override void OnConnecting(Connection connection, ConnectionInfo info)
    {
        connection.Accept();
        Debug.Log("SocketOnConnecting");
    }

    public override void OnDisconnected(Connection connection, ConnectionInfo info)
    {
        Debug.Log("SocketOnDisconnected");
    }

    public override void OnMessage(Connection connection, NetIdentity identity, IntPtr data, int size, long messageNum, long recvTime, int channel)
    {
        Debug.Log("Socket Got A Message");
    }
}

public class SteamConnectionManager : ConnectionManager
{
    public override void OnConnected(ConnectionInfo info)
    {
        Debug.Log("ConnectionOnConnected");
    }

    public override void OnConnecting(ConnectionInfo info)
    {
        Debug.Log("ConnectionOnConnecting");
    }

    public override void OnDisconnected(ConnectionInfo info)
    {
        Debug.Log("ConnectionOnDisconnected");
    }

    public override void OnMessage(IntPtr data, int size, long messageNum, long recvTime, int channel)
    {
        Debug.Log("Connection Got A Message");
    }
}
```

**Comment by Scarso327** [comment]
socketManger.Recieve() isn't doing anything as you're not sending any messages to the "server". Instead you're only sending from the "server" to all connections on it. This code works perfectly fine if you uncomment the `connectionManager.Receive();` line.

My Console (After uncommenting the line mentioned):
https://i.gyazo.com/c5782f8e3437d21193784ffe22076305.png

**Comment by ikomhoog** [comment]
I know connectionmanager.Receives makes it receive on the connection, but i want to receive on the socket.
How do i send messages to the server if not through the connection?

Socket.Receive also doesnt do anything when i connect from pc A to pc B.

**Comment by Scarso327** [comment]
`ConnectionManager` has a variable called `Connection`. Literally just send messages to that and as long as you're looping the receive on both socket and connection it'll work.

**Comment by ikomhoog** [comment]
I thought that the connection in socketManager was the same as the connection in the connectionManager.
thanks for clarifying, now it works.

**Comment by bthomas2622** [comment]
> `ConnectionManager` has a variable called `Connection`. Literally just send messages to that and as long as you're looping the receive on both socket and connection it'll work.

I've tried this and I'm still not getting any messages on my SocketManager OnMessage. Wouldn't the "connection" variable on the ConnectionManager be the same as the connection variable on the socketmanager.connected[0]? So how would connection know directionally which way send the message?

I'm having a lot of difficulty sending message to my socket manager from a client who only has a connection manager

**Comment by Scarso327** [comment]
@bthomas2622 Are you connecting normally or through relays? I am going to try and help but I haven't done this since August last year so might be a little rusty.

**Comment by Scarso327** [comment]
Actually, scratch that. It doesn't really change anything. Could you show me your code and how everything is set up? I don't have much to go on.

The socket manager is used as the server. It manages all the connections made to the server while the connection manager is how a client would connect to the socket manager. You want the socket manager to be listening for messages from clients to be able to send messages between them and you want the connection manager on the client to do the same for the server. Remember this project doesn't contain anything for how to handle data sent. You'll need to set that up yourself.

**Comment by bthomas2622** [comment]
@Scarso327 connecting through relays. Thanks so much for helping. I posted a new issue trying to explain where I'm at: https://github.com/Facepunch/Facepunch.Steamworks/issues/529

The way I have it set up in my 1v1 game is 1 host sets up the socket manager as a server and then their own connection manager to connect to it. And their opponent just has a connection manager. But I've been unable to send messages from connection manager to socket manager from either host or joining person.
