### ISSUE TITLE
Can't compile game with ambiguous reference message

### ISSUE THREAD

**Issue by nCore** [Facepunch/Facepunch.Steamworks#462]
**Describe the bug**
`Assets\Scripts\Game\Steam.cs(12,17): error CS0433: The type 'SteamClient' exists in both 'Facepunch.Steamworks.Posix, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Facepunch.Steamworks.Win32, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`

Can't compile game with simple initialization script with Facepunch.Steamworks because of this. Tried to remove Posix and Win32 assemblies with no luck (these are coming back automagically). Tried assigning them aliases - same problem.

**To Reproduce**

1. You need to have empty Unity project ;) 
2. Download v2.3.2 release zip from github and do exactly what is on the https://wiki.facepunch.com/steamworks/Installing_For_Unity
3. Unpack zip and Unity folder contents to Assets/Plugins/Facepunch.Steamworks
4. Create simple Steam.cs script with:
```
using UnityEngine;

namespace Game
{
    public class Steam : MonoBehaviour
    {
        // Start is called before the first frame update
        void Start()
        {
            try
            {
                Steamworks.SteamClient.Init(480); // FIXME: this is test steam app id
            }
            catch (System.Exception e)
            {
                // Something went wrong - it's one of these:
                //
                //     Steam is closed?
                //     Can't find steam_api dll?
                //     Don't have permission to play app?
                //
                Debug.Log(e.Message);
            }
        }
    }
}
```
4. Attach to any empty component on the scene in Unity
5. Try to compile

**Calling Code**
```
Code is pasted above.
```

Got this in the code:
![image](https://user-images.githubusercontent.com/2129826/88467498-062b9a00-ced8-11ea-997c-f4e38f8ccf3c.png)

**Expected behavior**
Should properly compile and allow to run the game in editor/built game no matter the platform.

**Desktop (please complete the following information):**
 - OS: Windows 10 latest build
- Unity: 2020.1.0f1
- IDE: Rider: 2020.1.3 or VS 16.5.5 (does it matter at all ?)

**Comment by nCore** [comment]
Unfortunatelly making `Facepunch.SteamWorks.Win64` with alias `w64` then using this like:

```
extern alias w64;
using w64lib=w64::Steamworks;

...

w64lib.SteamClient.Init(480);

...
```

doesn't work.

After cleaning/rebuilding it lost my alias.

**Comment by nCore** [comment]
If any of you stumbles upon this problem, simply remove other versions of dll's/pdb's and xmls - I did that for the sake of development - I left only Win64 version and works like a charm. 

We're waiting for @garrynewman to see his point of view on this. Maybe there's something I am missing.

**Comment by garrynewman** [comment]
You're not meant to drag all the source code into Unity, you're meant to use the dlls in the release.

**Comment by nCore** [comment]
That's fine, but the docs clearly states to unpack everything into plugins folder. This is how I understood that.

![image](https://user-images.githubusercontent.com/2129826/89095906-4c01ca00-d3d2-11ea-928c-2e644777d34b.png)

As a beginner in Unity I thought it will automagically handle all the stuff in there.

**Comment by garrynewman** [comment]
Is your project using .meta files?

If not you'll need to go to each dll in Unity and make sure it's only loading on the platform you're targetting.

**Comment by HumanGamer** [comment]
I just ran into this issue also and I found out why. For some reason when extracting the archive, a bunch of the .meta files are hidden in windows for some reason! You need to turn on hidden files to view them. If it matters, this happens on both the latest WinRAR (paid version), and the latest 7-zip.

**Comment by ElwoodHogan** [comment]
Ive just encountered this error as well.  After reading this thread im still unsure how to fix the problem.  Im using unity, and my plugin folder looks like the one shown in the image provided by @nCore.

**Comment by qmarsala** [comment]
Ran into this today and wanted to share how I fixed the issue.

The release zip does seem to be missing the .meta files as others have pointed out.
To get around this, I downloaded and extracted the unity folder into my assets as the docs say to do.
At this point, my unity project has all the Facepunch code, and autogenerated .meta files that are incorrect. To fix the autogenerated .meta files, I followed these steps from the "building from main" section of the docs.
Everything is now working as expected.
 
https://wiki.facepunch.com/steamworks/#howtobuildfrommasterbranch 
```
Facepunch.Steamworks.Posix.dll:

Any Platform: Unchecked
Include Platforms: Editor, Standalone
Platform Settings:
CPU: Any
OS: OSX
Switch tabs:
Windows: all unchecked
Linux and OSX: all checked


Facepunch.Steamworks.Win32.dll:

Any Platform: Checked
Include Platforms: Both Unchecked
Platform Settings:
CPU: x86
OS: Windows
Switch tabs:
Windows: check x86
everything else: Unchecked


Facepunch.Steamworks.Win64.dll:

Any Platform: Checked
Include Platforms: Both Unchecked
Platform Settings:
CPU: x86_64
OS: Windows
Switch tabs:
Windows: check x86_64
Linux and OSX: Unchecked
```

**Comment by Lothsahn** [comment]
HumanGamer's comment on 11/24/2020 is correct.  Same problem with windows zip, but when I used 7-zip to extract the files it included a bunch of .meta files that windows skipped.  This fixed the issue.

**Comment by jan** [comment]
I couldn't fix it by applying the settings as stated above (or any other settings I've tried). 

```
The type 'SteamClient' exists in both 'Facepunch.Steamworks.Posix, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Facepunch.Steamworks.Win64, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```

I'm building on a Mac, for a Mac, so Win64 shouldn't have loaded.

Removing the files that are not to be used with the current build works for me. And then move them mack in and the other ones out when I build for a different platform.

It's a hassle, but at least I can build and don't have to migrate the integration.

**Comment by restush** [comment]
Mine is Result and Screenshot. Unity 2022 and Unity 6.

The type 'Result' exists in both 'Facepunch.Steamworks.Win32, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Facepunch.Steamworks.Win64, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

The type 'Screenshot' exists in both 'Facepunch.Steamworks.Win32, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Facepunch.Steamworks.Win64, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by UnityMark** [comment]
Me too boy

**Comment by Milk-Drinker01** [comment]
same issue on unity 6. deleting the 32 bit dll +xml fixed it for me

**Comment by UnityMark** [comment]
I use unity 6 and i cant build, i go to change my version unity to 2023.

**Comment by UnityMark** [comment]
> same issue on unity 6. deleting the 32 bit dll +xml fixed it for me

Where this file "win32"? Can you please write path.

**Comment by Milk-Drinker01** [comment]
> > same issue on unity 6. deleting the 32 bit dll +xml fixed it for me
> 
> Where this file "win32"? Can you please write path.

Plugins/Facepunch.Steamworks/Facepunch.Steamworks.Win32.dll

**Comment by restush** [comment]
Unity bug. They will fix it soon. 

https://forum.unity.com/threads/dll-cannot-set-cpu-x86-missing-x86-option.1572409/#post-9758769

**Comment by UnityMark** [comment]
I got everything working, when i delete Facepunch.Steamworks.Win32.dll

**Comment by MaxCalderonReyes** [comment]
> HumanGamer's comment on 11/24/2020 is correct. Same problem with windows zip, but when I used 7-zip to extract the files it included a bunch of .meta files that windows skipped. This fixed the issue.

In the extract file , you should check the hidden elements , after this you just copy all and  in my case Stearwork.Steamclien.init dont show any error
