### ISSUE TITLE
SteamMatchmaking.OnLobbyInvite - Lobby.MaxMembers is always zero

### ISSUE THREAD

**Issue by barsovya** [Facepunch/Facepunch.Steamworks#465]
Hi everyone.
When the event occurs **SteamMatchmaking.OnLobbyInvite**, the parameter **Lobby.MaxMembers** is always zero.
Code example:
```
private protected void OnLobbyInvite(Friend friend, Lobby lobby)
    {  
            Debug.Log(lobby.MaxMembers); //output is always 0     
    }
```
 **SteamMatchmaking.JoinLobbyAsync(lobbyID);** - always occurs, even if there is only one player slot in the lobby which is already occupied. And **OnLobbyEntered** runs even if there are no more slots.
How is it supposed to solve the issue of connecting to a lobby that has no free slots at use **OnLobbyInvite**?

**Comment by kamyker** [comment]
Haven't tried but from Steam docs I guess it should be:
```
private protected void OnLobbyInvite(Friend friend, Lobby lobby)
{
    lobby.OnLobbyDataChanged += LobbyChanged;
    lobby.Refresh();

    void LobbyChanged(Lobby lobbyRefreshed)
    {
        if(lobby.Id == lobbyRefreshed.Id)
        {
            Debug.Log(lobbyRefreshed.MaxMembers);
            lobby.OnLobbyDataChanged -= LobbyChanged;
        }
    }
}
```

**Comment by barsovya** [comment]
> Haven't tried but from Steam docs I guess it should be:
> 
> ```
> private protected void OnLobbyInvite(Friend friend, Lobby lobby)
> {
>     lobby.OnLobbyDataChanged += LobbyChanged;
>     lobby.Refresh();
> 
>     void LobbyChanged(Lobby lobbyRefreshed)
>     {
>         if(lobby.Id == lobbyRefreshed.Id)
>         {
>             Debug.Log(lobbyRefreshed.MaxMembers);
>             lobby.OnLobbyDataChanged -= LobbyChanged;
>         }
>     }
> }
> ```

Thanks, this seems to be the only solution.

**Comment by kamyker** [comment]
Np, close the issue :)
