### ISSUE TITLE
Socket Manager does not receive messages

### ISSUE THREAD

**Issue by barsovya** [Facepunch/Facepunch.Steamworks#467]
Hi everyone.
When I inherit from the interface **ISocketManager** in this case in **OnMessage** a message is coming.

```
private protected SocketManager SocketServerManager;

private protected void Update()
    {
		SocketServerManager.Receive();
		ConnectionManager.Receive();
    }

public async void CreateRelaySocket()
    {
		SteamNetworkingUtils.DebugLevel = NetDebugOutput.Everything;
		SteamNetworkingUtils.OnDebugOutput += DebugOutput;

		SocketServerManager = SteamNetworkingSockets.CreateRelaySocket<SocketManager>();
		SocketServerManager.Interface = new SteamSocketManager();

		Debug.Log($"Created Socket: {SocketServerManager}");

		ConnectionManager = SteamNetworkingSockets.ConnectRelay<SteamConnectionManager>(SteamClient.SteamId);

		await Task.Delay(3000);

		var result = ConnectionManager.Connection.SendMessage(Encoding.ASCII.GetBytes("Say hi"));
		Debug.Log($"{result} {ConnectionManager.Connection}");
	}

public class SteamSocketManager : ISocketManager
{
	public  void OnConnecting(Connection connection, ConnectionInfo data)
	{
		connection.Accept();
		UnityEngine.Debug.Log($"{data.Identity} is connecting");
	}

	public  void OnConnected(Connection connection, ConnectionInfo data)
	{
		UnityEngine.Debug.Log($"{data.Identity} has joined the game");
	}

	public  void OnDisconnected(Connection connection, ConnectionInfo data)
	{
		UnityEngine.Debug.Log($"{data.Identity} is out of here");
	}

	public  void OnMessage(Connection connection, NetIdentity identity, IntPtr data, int size, long messageNum, long recvTime, int channel)
	{
		Debug.Log($"We got a message from !");
	}
}
```

if you change ISocketManager implementation on a SocketManager, there is no response in **OnMessage**

```
    private protected SteamSocketManager SocketServerManager = new SteamSocketManager();
    public SteamConnectionManager ConnectionManager = new SteamConnectionManager();


    private protected void Update()
    {
		SocketServerManager.Receive();
		ConnectionManager.Receive();
    }

    public async void CreateRelaySocket()
    {
		SteamNetworkingUtils.DebugLevel = NetDebugOutput.Everything;
		SteamNetworkingUtils.OnDebugOutput += DebugOutput;

		SocketServerManager = SteamNetworkingSockets.CreateRelaySocket<SteamSocketManager>();

        Debug.Log($"Created Socket: {SocketServerManager}");

		ConnectionManager = SteamNetworkingSockets.ConnectRelay<SteamConnectionManager>(SteamClient.SteamId);

		await Task.Delay(3000);

		var result = ConnectionManager.Connection.SendMessage(Encoding.ASCII.GetBytes("Say hi"));
		Debug.Log($"{result}");
	}

public class SteamSocketManager : SocketManager
{
	public override void OnConnecting(Connection connection, ConnectionInfo data)
	{
		connection.Accept();
		UnityEngine.Debug.Log($"{data.Identity} is connecting");
	}

	public override void OnConnected(Connection connection, ConnectionInfo data)
	{
		UnityEngine.Debug.Log($"{data.Identity} has joined the game");
	}

	public override void OnDisconnected(Connection connection, ConnectionInfo data)
	{
		UnityEngine.Debug.Log($"{data.Identity} is out of here");
	}

	public override void OnMessage(Connection connection, NetIdentity identity, IntPtr data, int size, long messageNum, long recvTime, int channel)
	{
		Debug.Log($"<color=red>We got</color> a message from !");
	}
}
```

**Comment by FakeByte** [comment]
You need to call the base classes, change your SocketManager to something like this:
`public class SteamSocketManager : SocketManager
{
	public override void OnConnecting(Connection connection, ConnectionInfo data)
	{
		base.OnConnecting(connection, data);//The base class will accept the connection
		UnityEngine.Debug.Log($"{data.Identity} is connecting");
	}

	public override void OnConnected(Connection connection, ConnectionInfo data)
	{
                base.OnConnected(connection, data);
		UnityEngine.Debug.Log($"{data.Identity} has joined the game");
	}

	public override void OnDisconnected(Connection connection, ConnectionInfo data)
	{
                 base.OnDisconnected(connection, data);
		UnityEngine.Debug.Log($"{data.Identity} is out of here");
	}

	public override void OnMessage(Connection connection, NetIdentity identity, IntPtr data, int size, long messageNum, long recvTime, int channel)
	{
		Debug.Log($"<color=red>We got</color> a message from !");
	}
}`

**Comment by barsovya** [comment]
> You need to call the base classes, change your SocketManager to something like this:
> 
> ```
> public class SteamSocketManager : SocketManager
> {
> 	public override void OnConnecting(Connection connection, ConnectionInfo data)
> 	{
> 		base.OnConnecting(connection, data);//The base class will accept the connection
> 		UnityEngine.Debug.Log($"{data.Identity} is connecting");
> 	}
> 
> 	public override void OnConnected(Connection connection, ConnectionInfo data)
> 	{
>                 base.OnConnected(connection, data);
> 		UnityEngine.Debug.Log($"{data.Identity} has joined the game");
> 	}
> 
> 	public override void OnDisconnected(Connection connection, ConnectionInfo data)
> 	{
>                  base.OnDisconnected(connection, data);
> 		UnityEngine.Debug.Log($"{data.Identity} is out of here");
> 	}
> 
> 	public override void OnMessage(Connection connection, NetIdentity identity, IntPtr data, int size, long messageNum, long recvTime, int channel)
> 	{
> 		Debug.Log($"<color=red>We got</color> a message from !");
> 	}
> }
> ```

Yes, thanks
