### ISSUE TITLE
Request: add binding for ISteamUGC.AddDependency

### ISSUE THREAD

**Issue by ShinyMark** [Facepunch/Facepunch.Steamworks#468]
I'm making a CLI Workshop mod uploader tool with Facepunch.Steamworks currently. I would like to add the ability for mod authors to define mod ID dependencies and then have them set by the uploader at upload time. It looks like this is the API call I need to make but it's not exposed:

https://partner.steamgames.com/doc/api/ISteamUGC#AddDependency

Thanks for the library - it's working great for this mod uploader context so far outside of this need. I may try to add it myself and submit a PR but if this is trivially easy for someone who is familiar with the project to add I'd appreciate the help.

**Comment by kamyker** [comment]
added in #447

**Comment by kamyker** [comment]
got merged, close :) @ShinyMark

**Comment by ShinyMark** [comment]
Thank you!
