### ISSUE TITLE
Could not load assembly Steamworks

### ISSUE THREAD

**Issue by Noxalus** [Facepunch/Facepunch.Steamworks#469]
**Describe the bug**

I have a CI server that build my game using [this](https://hub.docker.com/layers/homolus/unity/2020.1.0f1-windows/images/sha256-9b476392671bbe388eca1ed4b9640af96c90964427fa90595d375503e8f04904?context=repo) Docker image (running on Linux environment).

Here is the error I get:

```
Start importing Assets/Plugins/Facepunch.Steamworks/redistributable_bin/linux64/libsteam_api.so using Guid(a3b75fd2a03fb3149b60c2040555c3fe) Importer(-1,00000000000000000000000000000000)  -> (target hash: '3a1ede127da4047ae756f122896527e5') in 0.558551 seconds
Start importing Assets/Plugins/Facepunch.Steamworks/Facepunch.Steamworks.Win64.dll using Guid(b3ad7ccc15f481747842885a21b7b4ab) Importer(-1,00000000000000000000000000000000)  -> (target hash: '6020022bb5ae380b501cbc721695cfc8') in 0.180582 seconds
Start importing Assets/Plugins/Facepunch.Steamworks/redistributable_bin/steam_api.dll using Guid(f47308500f9b7734392a75ff281c7457) Importer(-1,00000000000000000000000000000000)  -> (target hash: '719a622d266dbbec9cbfcaad3bad4d71') in 0.004972 seconds
Start importing Assets/Plugins/Facepunch.Steamworks/Facepunch.Steamworks.Win32.dll using Guid(fb41692bc4208c0449c96c0576331408) Importer(-1,00000000000000000000000000000000)  -> (target hash: 'fe5b7939d222023beac8cd8060e94dbb') in 0.050592 seconds
Start importing Assets/Plugins/Facepunch.Steamworks/Facepunch.Steamworks.Posix.dll using Guid(fc89a528dd38bd04a90af929e9c0f80e) Importer(-1,00000000000000000000000000000000)  -> (target hash: '2a7bfaf641c3b093beb1fbf65a32e7b3') in 0.040369 seconds
Start importing Assets/Plugins/Facepunch.Steamworks/redistributable_bin/osx/libsteam_api.bundle using Guid(7d6647fb9d80f5b4f9b2ff1378756bee) Importer(-1,00000000000000000000000000000000)  -> (target hash: 'c1bba71b19b5f87752cfef8071e94739') in 0.004326 seconds
Start importing Assets/Plugins/Facepunch.Steamworks/redistributable_bin/linux32/libsteam_api.so using Guid(fd99b19e202e95a44ace17e10bac2feb) Importer(-1,00000000000000000000000000000000)  -> (target hash: '8593427794e4856ded643d9bc44805d1') in 0.004315 seconds
Start importing Assets/Plugins/Facepunch.Steamworks/redistributable_bin/win64/steam_api64.dll using Guid(cf5718c4ee1c31e458f8a58a77f4eef0) Importer(-1,00000000000000000000000000000000)  -> (target hash: '2489f72496502944a3b6a508fcacae29') in 0.004956 seconds
Begin MonoManager ReloadAssembly
Symbol file LoadedFromMemory doesn't match image /builds/Team/Project/Library/PackageCache/com.unity.ext.nunit@1.0.0/net35/unity-custom/nunit.framework.dll
Native extension for LinuxStandalone target not found
Native extension for WindowsStandalone target not found
Refreshing native plugins compatible for Editor in 160.22 ms, found 1 plugins.
Preloading 0 native plugins for Editor in 0.00 ms.
Could not load assembly Steamworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
```

However I have no problem to make local build on Windows.

For the installation, I only did the steps described [here](https://wiki.facepunch.com/steamworks/Installing_For_Unity).

I'm using Unity **2020.1.0f1**

**Comment by Noxalus** [comment]
Ok, I've did a test trying to import the Facepunch.Steamworks DLLs on a fresh installation of Ubuntu 20.04 in a new project using Unity 2020.1.0f1.

And I just can't use `Steamworks` namespace without error!

Did I miss something for this platform? :thinking:

**Comment by fanmanpro** [comment]
Not sure what the solution is but maybe I can help you.

Two things I think is worth investigating:
- When you install Facepunch.Steamworks, it comes with meta files. These dlls likely target specific platforms that might not be targeted when you enter Unity's `-batchmode` command line mode via docker. Try always enabling the linux dll (posix?) and build it using the container (despite the compile errors coming up in the editor)
- Try just doing the build manually. In the editor (for win/lin) **and** through the terminal. I run this to build my game in batch mode using Ubuntu 16:
```
${UNITY_EXECUTABLE:-xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity} \
  -projectPath $(pwd) \
  -quit \
  -batchmode \
  -buildTarget $BUILD_TARGET \
  -executeMethod BuildCommand.PerformBuild \
  -logFile /dev/stdout
```
That `BuildCommand.PerformBuild` function has to exist and it could be that, within that scope, your dll's aren't loaded properly.

Good luck!

**Comment by Noxalus** [comment]
Thank you for your answer @fanmanpro !

When I import the Facepunch Steamworks DLLs (with the associated meta files), here is what I get in the Inspector window for `Facepunch.Steamworks.Posix.dll` file:

![image](https://user-images.githubusercontent.com/1321964/89947377-a7c72100-dc24-11ea-9642-882ec78ae332.png)

Which still lead me to the error:

```
Assets/Scripts/SimpleCameraController.cs(7,7): error CS0246: The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)
```

Here is my target platform:
![image](https://user-images.githubusercontent.com/1321964/89947587-fbd20580-dc24-11ea-8ac3-308a7a100dac.png)

But it appears that if I click on the "Editor Settings" tab in the "Platform settings" section of the DLL from the Inspector window, I get this:

![image](https://user-images.githubusercontent.com/1321964/89947714-3471df00-dc25-11ea-86a5-5960bb22e746.png)

And switching from OSX to Linux make the error disappear 😮 

However, going back to the "PC, Mac & Linux Standalone settings" tab, nothing changed compared to the first screenshot... 🤔 

I still have some tests to do (like build the game for Linux and Windows through the Editor then using the command line), but I think this is good to know.

**Comment by Noxalus** [comment]
OK, I confirm the solution given in my previous message works.

Before to made the change, I can't compile neither for Linux nor Windows. But if I make the change, it's ok for both target platform.

Doing the same change on my project, the issue is fixed too when the CI build the project in the Docker container too. 

Here are the changes detected by Git:

![image](https://user-images.githubusercontent.com/1321964/89953903-4f961c00-dc30-11ea-8918-96f34e167cb8.png)

I suppose that the issue will be the same if the host environment to build is a Mac OS, but for now the solution is good enough for me. 👍

**Comment by linjmeyer** [comment]
Thankyou @Noxalus! I had the same issue.  Everything worked locally, but in CI I was getting `namespace not found 'steamworks'`.  After changing the editor .dll platform to Linux from OSX all three of my CI builds (OSX, Windows, Linux) began working.

**Comment by mastef** [comment]
I was stuck for a day on this - would be great to have this in the installation manual or on the front of the readme. Building worked locally, since I'm on a mac. But auto builders ( e.g. game-ci ) would fail with "The type or namespace name 'Steamworks' could not be found".

Switching the `Facepunch.Steamworks.Posix.dll` from `Mac` in Editor settings to `Any OS` - fixed it for me. Not sure if that will create issues for Windows people, we'll see.

**Comment by mastef** [comment]
I think I know now what the issue is - a dll cannot be marked to be only available for the mac and linux editor. The setting only allows for `mac || windows || linux || all`. So setting it to "Any OS" causes issues in Windows editors.

Possible solution: Copy paste the `Facepunch.Steamworks.Posix.dll` and set it to be only available for Linux editors.

**Comment by fegabe** [comment]
thank you! this helped me fixing the error compiling on Github Actions CI :)
