### ISSUE TITLE
Having trouble removing/updating additional preview images from Workshop file

### ISSUE THREAD

**Issue by richdog** [Facepunch/Facepunch.Steamworks#47]
I have modified the source of Workshop.Editor.cs to accept an array of additional preview images (utilizing workshop.ugc.AddItemPreviewFile for each image). This is working (yay).

For my game, the desired behavior would be to clear all of the preview images from a workshop item, then add all of the new ones. However, when I update an existing workshop item, all of the old preview images still remain, and the new ones are added to that list.

To achieve the behavior I want, I would need to get the number of preview files using GetQueryUGCNumAdditionalPreviews and call workshop.ugc.RemoveItemPreview on each of them before adding the new preview images.

My question is, should I attempt to make this behavior generic to be merged into Facepunch.Steamworks, or should I just keep this as a local "hack" for my game? I would imagine other people would want similar functionality (the ability to add more than one preview image to a workshop item, and to clear the preview images from a workshop item on update).

Alternatively, if you already had different plans on how you wanted to implement this functionality, maybe you could enlighten me on a better solution.

Thanks!

**Comment by richdog** [comment]
I'm actually currently looking into a solution that involves adding some initialization to the Workshop.Editor object. If the object has a workshop id, the editor object will raise a flag saying it's initializing and will query the workshop to find the file.

Once the results come back, it will populate all the workshop editor fields with known information about the file. This includes data about all of the existing preview files for the workshop item. When this is done, the flag will be set to say initialization is complete, and you will be able to modify or publish the editor file.

Please let me know if this approach goes against the current architecture, I am trying my best to make this a versatile solution that will hopefully be able to be merged into the main branch.

**Comment by PsykomantaBrain** [comment]
Hi, 

Did this get implemented in the main branch at some point (in some way or another?). I'm trying to get additional images uploaded to workshop items here too, and I can't seem to find anything in the exposed API for doing that.

Thanks in advance for any help!

Cheers

**Comment by richdog** [comment]
Hey PsykomantaBrain, I ended up implementing my own solution to this. There may be an official implementation by now but I haven't kept up to date with Facepunch.Steamworks in a while. Feel free to look at my old commit as a reference to implement a version that suits your needs.
https://github.com/richdog/Facepunch.Steamworks/commit/b51a1402c7a1c1aaf133366d27da9b1ed4fe39bb
