### ISSUE TITLE
Add quantity parameter to BeginPurchaseAsync

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/Facepunch.Steamworks#471]
Need to be able to set quantity here:
https://github.com/Facepunch/Facepunch.Steamworks/blob/631969360c8cb1cb2582ef78b483b5987d9d5c1b/Facepunch.Steamworks/SteamInventory.cs#L351

**Comment by garrynewman** [comment]
Okay, I did this, you should now be able to pass in multiple of the same item to purchase multiple of them.

**Comment by cr4yz** [comment]
That'll work, thanks
