### ISSUE TITLE
[Newbie] Steam P2P with 10 Players.

### ISSUE THREAD

**Issue by trungdeveloper199** [Facepunch/Facepunch.Steamworks#480]
Hi everyone, I'm working with a multiplayer game with 10 players for maximum. I'm trying to use server/client with Facepunch Steamworks. But I can't find any documentation for this. So if you know it, Can you share some information about how to create a server/client (the request to create a server will do in the owner lobby of the client app? after the lobby is created?), How to communicate between the client/server in Unity, Example: how to request moving an object from a client to the server and sync it with other clients.

**Comment by kamyker** [comment]
I'm using mirror but haven't tried this many players yet, transport: https://github.com/Chykary/FizzyFacepunch
