### ISSUE TITLE
NullReferenceException when calling authTicket.Cancel()

### ISSUE THREAD

**Issue by dan335** [Facepunch/Facepunch.Steamworks#484]
When I call this

authTicket.Cancel();

I get this error

NullReferenceException: Object reference not set to an instance of an object
Steamworks.AuthTicket.Cancel () (at D:/a/Facepunch.Steamworks/Facepunch.Steamworks/Facepunch.Steamworks/Classes/AuthTicket.cs:18)

Happens here.  https://github.com/Facepunch/Facepunch.Steamworks/blob/26b79db7e4b5812dad71f832d47fff8dbaa2c4da/Facepunch.Steamworks/Classes/AuthTicket.cs#L18

Am I doing something wrong or is this a bug?

**Comment by dan335** [comment]
I think I got it working.  Might have been calling Cancel multiple times.

**Comment by Vixxd** [comment]
Did you find out a way to troubleshoot that sort of null reference?

I'm getting a similar error when trying to set an achievement, but I don't have a `D:\a\etc...` filepath - so I imagine it's within the library itself. I can't see anyway to drill down deeper into SetAchievement to find out what's causing it.

`System.NullReferenceException: Object reference not set to an instance of an object
  at Steamworks.SteamServerStats.SetAchievement (Steamworks.SteamId steamid, System.String name) [0x00001] in D:\a\Facepunch.Steamworks\Facepunch.Steamworks\Facepunch.Steamworks\SteamServerStats.cs:86 `

**Comment by dan335** [comment]
You should be able to look at SteamServerStats.cs here on github Vixxd.  Sounds like either steamid or name is null.

https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/SteamServerStats.cs#L86
