### ISSUE TITLE
LobbyChatMessage message is giving strange result

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/Facepunch.Steamworks#498]
```c#
SteamMatchmaking.OnChatMessage += SteamMatchmaking_OnChatMessage;

private void SteamMatchmaking_OnChatMessage(Lobby lobby, Friend friend, string message)
{
	Debug.Log(friend.Name + ":" + message);
}
```

![chat bug](https://user-images.githubusercontent.com/9637557/98431414-ad44d380-207a-11eb-9940-a6eec57e708c.png)

Seems to be a problem reading buffer

**Comment by garrynewman** [comment]
There was a commit a while back to fix this I believe

**Comment by cr4yz** [comment]
> There was a commit a while back to fix this I believe

You're right, thank you
