### ISSUE TITLE
NativeInterface.InitClient() returning false on Ubuntu (32bit)

### ISSUE THREAD

**Issue by andythepandy93** [Facepunch/Facepunch.Steamworks#50]
Hi there! 
Thanks for this great C# implementation of Steamworks, it's doing a great job for us atm, however running our Unity game on a Ubuntu machine is causing some problems...

We are getting "Client not setup okay" printed into log (see code below). However Client.Dispose() is getting called before it is called in quit() (see other code below), as in the log I can see "BShutdownIfAllPipesClosed returned false" printed before "Client not setup okay", and this is printed in NativeInterface.Dispose(). So I think NativeInterface.InitClient() is returning false. 

```
 hPipe = api.SteamAPI_GetHSteamPipe();
            if ( hPipe == 0 )
                return false;
```
I think this is where it is returning false, as at the very top of the log I also see the line: 
`"Assertion Failed: IsValidHSteamPipe(hSteamPipe)"`
(This is the same error being caused by the other issue posted, however the assertion fail isn't happening in Dispose)

Unity Awake() code 
```
void Awake() {
	//.....other init code
	mClient = new Client(APPID);
	if(!mClient.IsValid) {
		Debug.Log("Client not setup okay");
		quit();
		return;
	}
	//.....other init code
}
```

```
void quit() {
		dispose();
#if UNITY_EDITOR
		UnityEditor.EditorApplication.isPlaying = false;
#else
		Application.Quit();
#endif
	}
```

Cheers!

**Comment by garrynewman** [comment]
Just to check, do you call 

```csharp
Facepunch.Steamworks.Config.ForUnity( Application.platform.ToString() );
```

before you initialize?

**Comment by andythepandy93** [comment]
Yes, definitely

Cheers

On 26 Jul 2017 17:12, "Garry Newman" <notifications@github.com> wrote:

Just to check, do you call

Facepunch.Steamworks.Config.ForUnity( Application.platform.ToString() );

before you initialize?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Facepunch/Facepunch.Steamworks/issues/50#issuecomment-318103376>,
or mute the thread

**Comment by garrynewman** [comment]
Is the linux build 32bit or 64bit?

**Comment by andythepandy93** [comment]
32bit

**Comment by garrynewman** [comment]
Alright - that's the one platform that hasn't had much testing (we only ship 64bit linux with Rust). Are the .so files next to the shipped application?

**Comment by andythepandy93** [comment]
Okay cool, I'll try a 64bit build when I've next got my linux machine around, and will post back here with updates.
The .so files were next to the application, however I had to move them after getting library not found errors. This is a Unity built app, and I've moved the .so files to xxx_Data\Plugins\x86 as that is where some other .so files were sitting.

**Comment by moldfield1995** [comment]
If this helps i have just releced a game and having the same problem, this is what Unitys Preformance tracker is sending back. 
`DllNotFoundException: libsteam_api.so`

```
SteamNative.Platform+Linux32.SteamApi_SteamAPI_Init () 

SteamNative.SteamApi.SteamAPI_Init ()

Facepunch.Steamworks.Interop.NativeInterface.InitClient (Facepunch.Steamworks.BaseSteamworks steamworks)

Facepunch.Steamworks.Client..ctor (UInt32 appId)

SteamManager.Awake ()
```

**Comment by njbrown09** [comment]
@moldfield1995 did you put libsteam_api.so next to the executable?

**Comment by soulthreads** [comment]
This is because the libsteam_api.so bundled is an x64 library and simply doesn't work with x86.

**Comment by andythepandy93** [comment]
Finally got around to trying the 64bit libraries, worked a treat! Doesn't help the 32bit issues but reporting back as promised
