### ISSUE TITLE
Tutorial for P2P-Multiplayer Code

### ISSUE THREAD

**Issue by LoneSurivor** [Facepunch/Facepunch.Steamworks#500]
Hi,

I can't believe that it should be that simple to implement the whole P2P-communication in a multiplayer-game with for e.g. 4 players by just using the three methods you described in https://wiki.facepunch.com/steamworks/Sending_P2P_Messages.

On my investigations for a tutorial, a blog-post, an example or anything else that shows a best practice way how to implement multiplayer games with Facepunch.Steamworks I found this page with a downloadable example: https://unitylist.com/p/jrv/Steam-Networking

But the version they use is 0.7, many years before the current version and the code has been restructured a lot in the meantime. They use server/client-scenes for the creator of a lobby and the client scene for the other players which makes sense in my mind. 

But are the three methods you provide in 2.3.2 such powerful that all the other methods aren't necessary anymore? That would be great. :-)

Maybe you can provide a small working example starting after a lobby is filled with players and everyone is ready to play?

**Comment by LukasKastern** [comment]
The wiki entry you refer to only shows how to use the P2P transport layer which steam providers.  You still have to implement all the more or less high-level stuff. Rpcs, object-synchronization, or whatever else you might need,

If you do not have a lot of experience with networked games and the challenges that come with it I highly recommend to start with one of the already existing solutions (Photon, Mirror)

**Comment by LoneSurivor** [comment]
Oh my god, the last sentence was the push in the right direction. You can't imagine how much time I already spent for looking around something easy to start with. I didn't want to try Photon. It's free in the beginning but it seems to take no long until you have to pay for. But the "Mirror"-hint is worth gold! 
I never heard of this before but just entered "unity mirror" in Google and the first result was https://mirror-networking.com. And then there is also a documentation that says, Facepunch.Steamworks can be used, so no need to add another plugin (I already use Facepunch.Steamworks for handling userlogin and achievements): https://mirror-networking.com/docs/Articles/Transports/FizzyFacepunch.html

This is great! Thank you so much for that hint again!

**Comment by Lestat** [comment]
I use only those 3 methods and it works wonders.

Yeah, you have to use those messages to sync the game objects, but that is easy.

For example you send a message that has the action 2 for example, and that means your character shot their weapon, and when other players receive the message, they see your character shooting. You have to code all that, but it's pretty simple, I have made several prototypes for several kind of games, including a published game using it.

I havent used mirror nor unet. Is Mirror that simple to use? Probably not worth my time as I already have it all working at low level and that means I can switch easily to another networking solution like epic games one (is that ready yet anyways?).
