### ISSUE TITLE
Steam Only properly working when"build + run"

### ISSUE THREAD

**Issue by hashcoin-project** [Facepunch/Facepunch.Steamworks#51]
This library works perfectly when I do build and run in the build menu, but as soon as I try to run the exe outside of unity it doesn't work. I've tested it on multiple pc's with the same issue

**Comment by njbrown09** [comment]
I have this issue too

**Comment by NavidK0** [comment]
When you test the executable outside of unity, do you include the steam_appid.txt and steam libraries (OS specific, steam_api.dll, steam_api.so, etc) with the application?

Steamworks requires the files to be with the application when opened outside of Steam in order for Steamworks to work. Make sure you put them next to the executable when testing.

**Comment by hashcoin-project** [comment]
I do, that's the weird part.

**Comment by garrynewman** [comment]
Do you call 

```csharp
Facepunch.Steamworks.Config.ForUnity( Application.platform.ToString() );
```

before you initialize?

**Comment by njbrown09** [comment]
Aha! I was doing that after. Thanks!
