### ISSUE TITLE
Squad like EAC feature for proton

### ISSUE THREAD

**Issue by jatin-cbs** [Facepunch/Facepunch.Steamworks#519]
Squad has made EAC wine build through which the developers won't have to do alot of work to support Linux, and all of the easy anti cheat calls will be called. using this using a very minimal effort and will not require any maintenance as it will be done by Easy Anti Cheat.

https://github.com/imaami/eac-tools

This is the repository which shows game IDs having easy anti cheat wine build can be downloaded for supported games like SQUAD, Currently as you can see Squad offers wine EAC support. And Epic does have an inhouse EAC build. Please include them to get the game run through proton.

Rust already runs great using proton (just won't let you in official Easy Anti Cheat) servers. Or any server not having EAC disabled. Using what Squad did with easy anti cheat wine build, EAC will work using proton. Let me be clear, this is not a hack or any kind of Cheat. And as @garrynewman  said that it is not worth the effort for a small player base, This solution will almost be a no effort solution as game already runs gold using Valve's proton. And Linux is a very rapidly growing player base and Companies like Feral Interactive, Valve and others are creating tools to optimize and making it easy for developers like Facepunch to port the games to Linux. We don't want a native port but this solution will just be perfect.

Thanks and Regards

Other useful links-

https://github.com/ValveSoftware/Proton/issues/3104

**Comment by ShaunTheQuietGamer** [comment]
Can we at least get a reason why this isn't possible, instead of just closing the ticket and ignoring it, without explaining?

**Comment by Synkstar** [comment]
Is it possible to at least whitelist someone to be able to join an EAC enabled server that you own?  I mainly just want to be able to join my own server from linux while having EAC enabled so it will appear in the server list and not be riddled with lots of cheaters. It would be great if I didn't have to boot into a foreign os( windows ) to play this. Would be great if they could enable the wine64 version of EAC so everyone can join though....

**Comment by jatin-cbs** [comment]
@Synkstar  Ya EAC has a wine64 version but garry don't want to enable it.. I bet this thread is not even getting noticed.

**Comment by garrynewman** [comment]
This is a GitHub for steamworks, why are you asking about EAC here

**Comment by Synkstar** [comment]
What would be the best place to ask about stuff related to EAC on rust as there is no rust issues repo like gmod has ? I get why @garrynewman closed this. Its because this repo is unrelated to rust. The OP probably got confused as to where to ask.

**Comment by jatin-cbs** [comment]
@garrynewman  Ya sorry for opening the issue here, however just request wine64  EAC like Squad did not much work and you will get the Linux users covered. Also provide us a forum or suggestion page where we can reach out.

**Comment by Synkstar** [comment]
@jatin-cbs Honestly dude from what ive seen some people say to them regarding linux on this game. I wouldn't blame them for not supporting it because if I didn't use Linux daily/ love it and I was a game dev that had a bunch of people harassing me idk if I would want to do anything for them. This is a very common issue in this world 2bh ever one harassing each other over their differences that's the down fall of the human race its programmed into all of us(hate).

**Comment by smirgol** [comment]
First please keep in mind that English isn't every ones native tongue, it isn't for me. So some things probably get lost in translation and sound more rude than they are meant to be. That happens very often, unfortunately.

I think what he wanted to say is, that first, there does not seem to be a place where this can be properly discussed, hence he figured the only way to draw attention to this matter is to create this issue ticket.
Second, it isn't expected that the devs do port the game to Linux, as it will run using Valve's Proton just fine. 

The only problem is the EAC module that got added mid-development, which prevents Linux players, old and new, from participating in the online mode. Which essentially renders this game useless on Linux, as it is online only.
Now, it is possible to create an EAC version that works with Wine/Proton and would enable Linux players to participate in this game, without risking anything. There are a number of games that do provide such a version, amongst them is Squad, Fortnite and others.

I cannot say how much effort the devs would need to put into this, but I guess it's not that much and once it works, not much support is needed. This would allow existing Linux players to play the game and also draw new players to it, which pretty much is a win-win in my book.

Therefore, please consider looking into providing such an EAC module. And if this isn't the right place to discuss this, as it probably isn't, maybe you can provide us with a place where it is. 

Thank you.

**Comment by russiantux** [comment]
https://forum.facepunch.com/

The forums were brought back so you can discuss EAC for Rust there.

**Comment by jatin-cbs** [comment]
@Synkstar  I am not asking for native support I know. But enabling wine64 EAC is not hard.. SQUAD did that as well, I am a game developer and I know for big companies it's not just about making a binary version, it's about polishing it and have people who have knowledge of third party softwares and APIs like Vulkan or directX. That's why I am not asking for native support but just enabling wine EAC. I am not blaming at this point.

**Comment by Synkstar** [comment]
> https://forum.facepunch.com/
> 
> The forums were brought back so you can discuss EAC for Rust there.

Good idea someone make a forum post and we can all like it and up vote it.

@jatin-cbs  I know but like what I wanted to say is they probably don't like the Linux community very much due to the things some people said. Which I 100% agree with. People shouldn't be shaming someone for running a different OS on their PC. It would be amazing if all companies can make their software available for Linux but for lots its not viable. Linux on the desktop is still kind of an enthusiast thing. It would be cool if Microsoft comes in and makes an official wine or contributes to it etc. Idk if that would ever happen but they are starting to support Linux more before they would shun it.

**Comment by Synkstar** [comment]
I made a forums post but 2bh the forums are pretty quiet( I guess some people don't know its back up because I had no clue before @russiantux told me lmao). https://forum.facepunch.com/t/method-of-allowing-linux-players-to-join-eac-secured-servers-with-the-wine64-build/240528/2

**Comment by ShaunTheQuietGamer** [comment]
> I made a forums post but 2bh the forums are pretty quiet( I guess some people don't know its back up because I had no clue before @russiantux told me lmao). https://forum.facepunch.com/t/method-of-allowing-linux-players-to-join-eac-secured-servers-with-the-wine64-build/240528/2

Copy-pasted to suggestion board for more visibility – https://rust.nolt.io/22684
