### ISSUE TITLE
Make Lobby.SendChatBytes public

### ISSUE THREAD

**Issue by james7132** [Facepunch/Facepunch.Steamworks#523]
**Is your feature request related to a problem? Please describe.**
Sending raw bytes to all members in a channel is currently impossible without encoding as a string.

**Describe the solution you'd like**
Change Lobby.SendChatBytes to public, and add an unsafe variant that takes a byte* and a length.

**Describe alternatives you've considered**
Using hex-encoded bytes in a string, or some other encoding could work, but for some inputs, there's no guarantee what's produced is validly encoded UTF8. This wastes CPU/memory due to a library limitation.

**Additional context**
This is useful if you are using binary encoded message formats like MessagePack, Protobuf, Flatbuffers, Cap'n'Proto, etc. or when using a custom message serializer.

**Comment by Rohansi** [comment]
One of the comments you removed explained why it was not exposed. If you send binary messages, how would you read them? There would need to be changes made to allow these messages to be read - preferably without incurring the cost of string decoding if it is unused.

**Comment by james7132** [comment]
[OnLobbyChatMessageRecievedAPI](https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/SteamMatchmaking.cs#L71) could be updated with a `OnRawLobbyChatMessage` event.

More generally, I think it'd be healthier for the entire library to migrate to using `(ReadOnly)Span<byte>` instead and let the consumer of the library determine what they're going to do with the raw message, but that's a major breaking change and would change what runtimes would be supported.

**Comment by Rohansi** [comment]
I'd love `Span<T>` everywhere too but it's an annoying issue since you might need to pull in System.Memory.dll for Unity.
