### ISSUE TITLE
Unable to "SendMessage" from ConnectionManager to SocketManager server

### ISSUE THREAD

**Issue by bthomas2622** [Facepunch/Facepunch.Steamworks#529]
**Describe the bug**
I am trying to implement P2P multiplayer with Steam NetworkingSockets. And from the player with server I am able to send messages to all the connections and have their ConnectionManager "OnMessage" proc. But whenever I try and use "SendMessage" on the ConnectionManager connection the SocketManager "OnMessage" never procs. 

**Setting up socket server and connecting with connectionManager**
```
steamSocketManager = SteamNetworkingSockets.CreateRelaySocket<SteamSocketManager>();
steamConnectionManager = SteamNetworkingSockets.ConnectRelay<SteamConnectionManager>(PlayerSteamId);
```

Works
```
Result success = steamSocketManager.Connected[0].SendMessage(data, sizeOfMessage);
```

Does not work
```
Result success = steamConnectionManager.Connection.SendMessage(data, sizeOfMessage);
```

**Desktop (please complete the following information):**
 OS: Windows
Unity 2020.1

**Additional context**
```
public class SteamConnectionManager : ConnectionManager
{
    public override void OnConnected(ConnectionInfo info)
    {
        Debug.Log("ConnectionOnConnected");
    }

    public override void OnConnecting(ConnectionInfo info)
    {
        Debug.Log("ConnectionOnConnecting");
    }

    public override void OnDisconnected(ConnectionInfo info)
    {
        Debug.Log("ConnectionOnDisconnected");
    }

    public override void OnMessage(IntPtr data, int size, long messageNum, long recvTime, int channel)
    {
        Debug.Log("Connection Got A Message");
    }
}

public class SteamSocketManager : SocketManager
{
    public override void OnConnected(Connection connection, ConnectionInfo info)
    {
        Debug.Log("SocketOnConnected");
    }

    public override void OnConnecting(Connection connection, ConnectionInfo info)
    {
        connection.Accept();
        Debug.Log("SocketOnConnecting");
    }

    public override void OnDisconnected(Connection connection, ConnectionInfo info)
    {
        Debug.Log("SocketOnDisconnected");
    }

    public override void OnMessage(Connection connection, NetIdentity identity, IntPtr data, int size, long messageNum, long recvTime, int channel)
    {
        Debug.Log("Socket Got A Message");
    }
}
```

And I am calling
```
steamSocketManager.Receive();
steamConnectionManager.Receive();
``` 

There are 3 other threads with people having similar issues but I'm not see conclusion. 
https://github.com/Facepunch/Facepunch.Steamworks/issues/513
https://github.com/Facepunch/Facepunch.Steamworks/issues/511
https://github.com/Facepunch/Facepunch.Steamworks/issues/458

Thanks so much for help! Loving Facepunch.steamworks

**Comment by bthomas2622** [comment]
Basically I've never been able to proc "Socket Got A Message" in my debug log.

**Comment by Scarso327** [comment]
How are you calling the steamConnectionManager.Receive();

**Comment by bthomas2622** [comment]
````    
void Update()
    {
        SteamClient.RunCallbacks();
        steamSocketManager.Receive();
        steamConnectionManager.Receive();
    }
```

I wouldn't think the SteamClient.RunCallbacks is interfering with it? Since connection manager is receiving messages ok

**Comment by Scarso327** [comment]
Yeah, no that shouldn't be a problem. I am going to tinker for a bit to see if I can get something working. I am assuming the server says that someone connected yeah?

**Comment by bthomas2622** [comment]
correct, I still get the "SocketOnConnecting" followed by "ConnectionOnConnecting" followed by "SocketOnConnected" followed by "ConnectionOnConnected" in debug

**Comment by Thornation** [comment]
Your SocketManager overrides should call the base functions.

See https://github.com/Facepunch/Facepunch.Steamworks/issues/467#issuecomment-699650846

**Comment by bthomas2622** [comment]
@Thornation oh man I can't believe I missed this thread, thanks so much this fixed!

**Comment by bthomas2622** [comment]
See #467 (comment)
