### ISSUE TITLE
SteamInventory.GetItems() does not exist

### ISSUE THREAD

**Issue by SniperED007** [Facepunch/Facepunch.Steamworks#536]
On the ReadMe.md is mentions the below, but SteamInventory.GetItems() doesn't exist, think it should be GetAllItemsAsync();
Tried Release 2.3.2 and also doing a build with the latest check-in (Jan 14, 2021)

`    var result = await SteamInventory.GetItems();

    // result is disposable, good manners to dispose after use
    using ( result )
    {
        var items = result?.GetItems( bWithProperties );

        foreach ( InventoryItem item in items )
        {
            Console.WriteLine( $"{item.Id} / {item.Quantity} / {item.Def.Name} " );
        }
    }`

**Comment by DarklightStudios** [comment]
Used the code from the Test project (slight modifications). Adjust as needed.

https://pastebin.com/erCw2Vt3
