### ISSUE TITLE
Workshop Upload Progress always 0

### ISSUE THREAD

**Issue by JackDn** [Facepunch/Facepunch.Steamworks#54]
Workshop.Editor.Progress, Workshop.Editor.BytesUploaded and Workshop.Editor.BytesTotal always return 0.
This could be the case because CreateItem is never set to null, it's only disposed [here](https://github.com/Facepunch/Facepunch.Steamworks/blob/72c5427be652e46cab35d8fa536eb59d73d373d8/Facepunch.Steamworks/Interfaces/Workshop.Editor.cs#L118).

**Comment by garrynewman** [comment]
Looked into this. Steam isn't doing us any favours here but I've made it behave more like we'd expect it to.
