### ISSUE TITLE
(P2P multiplayer)Is there a way to local test my game without using second steam account?

### ISSUE THREAD

**Issue by TianheTHGame** [Facepunch/Facepunch.Steamworks#542]
i googled this, and there are complain about this problem, so is there a way?

**Comment by FuzzySmurf** [comment]
I'm running into this problem too. It looks like, when I join with the same SteamID multiple times, it only registers once, and stops.

**Comment by DarklightStudios** [comment]
Install SandBoxie and run a second instance of Steam with it. I'd recommend registering a second account though.

**Comment by TianheTHGame** [comment]
thanks for the answers, but i really want a proper solution, so i decided to write a whole new framework to switch between PUN2 & SteamP2P at any time.

**Comment by Lestat** [comment]
> Install SandBoxie and run a second instance of Steam with it. I'd recommend registering a second account though.

Does this really work? will try it out.

**Comment by DarklightStudios** [comment]
> > Install SandBoxie and run a second instance of Steam with it. I'd recommend registering a second account though.
> 
> Does this really work? will try it out.

Yup, works perfectly. As for a proper solution I think SandBoxie might be the most effective, besides getting 2 computers. It allows you to run Steam and your game in their own sandbox with just a right click and "Run in SandBoxie". As for the PUN2 and Steam, I've been looking into that was well, but my idea is to use PUN2 for matchmaking while at the same time connecting to Steam P2P, then disconnecting PUN so I don't have to pay for massive servers and running the game networking off Steam. Then again Steamworks has matchmaking... Just got sick of PUN disconnecting when the client wasn't responding lol

**Comment by Lestat** [comment]
> > > Install SandBoxie and run a second instance of Steam with it. I'd recommend registering a second account though.
> > 
> > 
> > Does this really work? will try it out.
> 
> Yup, works perfectly. As for a proper solution I think SandBoxie might be the most effective, besides getting 2 computers. It allows you to run Steam and your game in their own sandbox with just a right click and "Run in SandBoxie". As for the PUN2 and Steam, I've been looking into that was well, but my idea is to use PUN2 for matchmaking while at the same time connecting to Steam P2P, then disconnecting PUN so I don't have to pay for massive servers and running the game networking off Steam. Then again Steamworks has matchmaking... Just got sick of PUN disconnecting when the client wasn't responding lol

I use steam matchmaking with no problems :p

**Comment by therenaydin** [comment]
You can use VMware aswell

**Comment by Lestat** [comment]
I don't even remember commenting on this. Lol never tried it, gonna do it now.
