### ISSUE TITLE
Getting a lobby's data without joining it

### ISSUE THREAD

**Issue by adamsoutar** [Facepunch/Facepunch.Steamworks#547]
**Describe the bug**

Hi, I'd like to grab a string from a lobby's associated data before joining it. The Steamworks documentation seems to suggest this is possible (and the right thing to do in some situations):

```
"Do not join lobbies just to find out their metadata.  Lobby metadata can be downloaded separately [...]"
```

If I have not yet joined, let's say, Lobby A, then `lobbyA.GetData("foobar")` returns an empty string (I **know** there _is_ data there). If I actually join said lobby then `lobbyA.GetData("foobar")` works just fine, and returns the data I expect.

Here's what makes me think this is a bug: after _leaving_ Lobby A, I can read its metadata from outside (I guess maybe it's cached?)

I'd like to be able to `GetData()` before calling `JoinLobbyAsync()`. Is this intended to be a feature of Facepunch.Steamworks? Maybe it used to work and has broken?

**To Reproduce**
1. Attempt to get data from a lobby you're not in - returns blank string
2. Join lobby
3. Get data - works just fine
4. Leave lobby
5. Get data - works just fine

**Calling Code**
```
lobby.GetData("foobar");
```

**Desktop:**
 - OS: macOS 11.2.3 (Intel, not M1)
- Unity: 2020.3.2f1

**Comment by adamsoutar** [comment]
May be worth noting that I did find [this](https://github.com/Facepunch/Facepunch.Steamworks/issues/404#issuecomment-625173696) issue, though the method signature Garry mentions (without passing a key `string`) doesn't seem to exist

**Comment by dampete** [comment]
I think what you're looking for is the Refresh() method. Unfortunately it's not an async method, instead it triggers a OnLobbyDataChanged event which you must listen for. I did create this method so I can send an await lobby.RefreshAsync(); without having to set up clunky event handlers in my class.

`public static async Task RefreshAsync( this Lobby lobby )
    {
        TaskCompletionSource<bool> resultWaiter = new TaskCompletionSource<bool>();
        Action<Lobby> eventHandler = ( Lobby queriedLobby ) =>
        {
            if( lobby.Id != queriedLobby.Id ) return;
            resultWaiter.SetResult( true );
        };

        SteamMatchmaking.OnLobbyDataChanged += eventHandler;
        UnityEngine.Debug.Log( lobby.Refresh() );
        var result = await resultWaiter.Task;
        SteamMatchmaking.OnLobbyDataChanged -= eventHandler;
    }`

**Comment by adamsoutar** [comment]
@dampete  This works a treat, thank you so much!

I'd seen the Refresh() method in IntelliSense but didn't understand it since the data was still empty after calling it (I hadn't waited for the data changed event)
