### ISSUE TITLE
How to get a name or avatar with Steam ID

### ISSUE THREAD

**Issue by EvilBozkurt** [Facepunch/Facepunch.Steamworks#552]
I switched from Facepunch v0.8 to the latest version. It was a big change for me and when I was updating the codes I was stuck at the beginning. For example, in the old version I could get a user's name with this code SteamClient.Instance.Friends.GetName (_SteamId). How do we do this in the latest version?

**Comment by kristianpiacenti** [comment]
Not sure if it's the best way I do like this -> new Friend(_steamId).Name

**Comment by SupinePandora43** [comment]
avatar
> `var image = await SteamFriends.GetLargeAvatarAsync( steamid );`

**Comment by EvilBozkurt** [comment]
> avatar
> 
> > `var image = await SteamFriends.GetLargeAvatarAsync( steamid );`

Yes I did it that way. But I stopped changing everything and went back to version 0.8 :D
