### ISSUE TITLE
How to install facepunch????

### ISSUE THREAD

**Issue by jackfmaxwell** [Facepunch/Facepunch.Steamworks#567]
What files and where do they go.

The scereenshot in the wiki shows a folder called Facepunch.Steamworks under the plugins folder in unity but the contents of Facepunch.Steamworks are not the same as the zip you download. The contents you see in the screenshot are from the folder called unity Plugin. 

What I tried is putting the files from the folder called unity plugin into my unity project under the folder Assets/Plugins. But doing this gives the warning:
A meta data file (.meta) exists but its asset 'Assets/Plugins/UnityPlugin/Facepunch.Steamworks.Posix.pdb' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.

And there are a bunch of these errors for various files. How do I install ??? Help please :(

**Comment by trushing** [comment]
In Windows Explorer, go to view and check the hidden files box. Meta files are hidden.
