### ISSUE TITLE
SteamAPI not shutting down correctly?

### ISSUE THREAD

**Issue by andythepandy93** [Facepunch/Facepunch.Steamworks#57]
After stopping the game whist developing in Unity, it still registers as "Running" in my Steam library. I have to close Unity completely in order for it to register as not playing anymore. This has the side affect of when in Visual Studio, pressing Shift+Tab to unindent also causes the Steam overlay appears in Visual Studio (very buggily too!)

I call client.Dispose() in OnApplicationQuit(), which has been confirmed as running with a print

Windows 64bit

Cheers

**Comment by garrynewman** [comment]
Yup. No way around it as far as I know, sorry :(

**Comment by andythepandy93** [comment]
Ah bumma, no worries, cheers
