### ISSUE TITLE
Steam Overlay Not Showing

### ISSUE THREAD

**Issue by ObayNeeam** [Facepunch/Facepunch.Steamworks#587]
i just started working on deploying a game on steam after publishing it on mobile platforms,
i followed instructions facepunch wiki page and when i bulid the project steam detect am playing spacewar (i used spacewar app id)
but steam overlay never appear

**Comment by LukeSeers** [comment]
The steam overlay is not handled by SteamWorks. It's handled by the steam client. Add your game to your steam library as a **"non-steam game"** then launch it through steam.

**Comment by ObayNeeam** [comment]
> The steam overlay is not handled by SteamWorks. It's handled by the steam client. Add your game to your steam library as a **"non-steam game"** then launch it through steam.

you're right, thank you

**Comment by seasonseong** [comment]
> The steam overlay is not handled by SteamWorks. It's handled by the steam client. Add your game to your steam library as a **"non-steam game"** then launch it through steam. 

How did you figured it out?
