### ISSUE TITLE
Advertise Game?

### ISSUE THREAD

**Issue by njbrown09** [Facepunch/Facepunch.Steamworks#59]
Is this implemented?

**Comment by garrynewman** [comment]
What's the api call?

**Comment by njbrown09** [comment]
AdvertiseGame( CSteamID steamIDGameServer, uint32 unIPServer, uint16 usPortServer );  Im trying to get the server info to show up in "View game info", unless im doing it the wrong way, i cant seem to find it

**Comment by bddckr** [comment]
[Link](https://partner.steamgames.com/doc/api/ISteamUser#AdvertiseGame) to Steamworks documentation.

**Comment by garrynewman** [comment]
Will add it, I don’t think we’ve ever needed it because we we use the with system.

**Comment by njbrown09** [comment]
I'm assuming rust is using this library. What are you using to show the info on view game info in rust?

**Comment by garrynewman** [comment]
As per docs, it auto populates that information on server auth.

**Comment by njbrown09** [comment]
Ah ok, thanks
