### ISSUE TITLE
Null reference exception within FindOrCreateLeaderboardAsync() after clearing data from the web portal...  

### ISSUE THREAD

**Issue by Tresiris** [Facepunch/Facepunch.Steamworks#590]
**Describe the bug**
Null reference exception when calling FindOrCreateLeaderboardAsync() with an empty Leaderboard.  If I have values in the leaderboard this does not trigger.  For example, if I comment out my Leaderboards and play my levels to generate the data on the Steam server, and then go back and enable my leaderboard code, it works just fine.  I could potentially just front load my Leaderboards to prevent it from happening, but that definitely wouldn't be a safe long term fix.

Seems to be failing here: `foreach (var e in entries)` which makes sense I guess if there aren't any values, but I assumed that the "OrCreate" meant it should work even if no values already on the server?  To be clear, the leaderboards have all been setup on the web portal, and the code works just fine _if_ entries already exist.

**To Reproduce**
I'm simply running my game after I have reset all Leaderboard values on the web portal.  I call `ShowLeaderboard_GlobalScore()` upon entry to my main menu.  SteamManager is already active from my login/start screen.

**Calling Code**
```
public async void ShowLeaderboard_GlobalScore()
    {
        var leaderboard = await SteamUserStats.FindOrCreateLeaderboardAsync("Global Score", LeaderboardSort.Ascending, LeaderboardDisplay.Numeric);
        //var leaderboard = await SteamUserStats.FindLeaderboardAsync("Global Score");
        if (leaderboard.HasValue)
        {
            steamLeaderboard = leaderboard.Value;
            LeaderboardEntry[] entries = await steamLeaderboard.GetScoresAroundUserAsync(-5, 5);
            foreach (var e in entries)
            {
                GameObject temp = Instantiate(LeaderboardListItem, LeaderboardGlobal);
                temp.transform.Find("PlayerName").GetComponent<Text>().text = e.User.ToString();
                temp.transform.Find("PlayerRank").GetComponent<Text>().text = e.GlobalRank.ToString();
                temp.transform.Find("PlayerScore").GetComponent<Text>().text = e.Score.ToString();
                AssignFriendImage(temp, e.User.Id);
                
            }
        }
        else { Debug.Log("Leaderboard has no values!"); }
    }

```

**Expected behavior**
I would expect it to actually jump to the else segment, but it is still running as if the leaderboard does have values.

**Desktop (please complete the following information):**
 - OS: Window 10
- Unity: 2020.2.1f1

**Additional context**
Thanks for any help here!  I apologize if this is something stupid simple that I have missed.

**Full Error Console Output**
`NullReferenceException: Object reference not set to an instance of an object
SteamLeaderboards+<ShowLeaderboard_GlobalScore>d__24.MoveNext () (at Assets/Scripts/Steam/SteamLeaderboards.cs:109)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <9577ac7a62ef43179789031239ba8798>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e414e10bfe5f45729ff122f3359de21b>:0)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()`

**Comment by Tresiris** [comment]
Hey guys, realizing now this is probably not a _bug_...  Having my Leaderboards with at least one value is fixing this, but I know if I ever have to clear those values this will fail for everyone.  Is there a correct message board for Facepunch/Steamworks that would be more appropriate for my issue?  The wiki is very helpful, but couldn't seem to figure out what I am doing wrong here just with that info.  Thanks!

**Comment by hankditton** [comment]
I was running into this same issue but I found a way around it. 

At least for me (my code was almost identical to yours), the actual problem is that the "GetScores" (and related "GetScoresAroundUserAsync") function actually returns null if there are no scores in the leaderboard (as opposed to an empty array). The code I had that was then consuming that value was throwing the NullPointerException. 

For you case, try to handle the case where entries can be null (if the leaderboard is empty):

`public async void ShowLeaderboard_GlobalScore()
    {
        var leaderboard = await SteamUserStats.FindOrCreateLeaderboardAsync("Global Score", LeaderboardSort.Ascending, LeaderboardDisplay.Numeric);
        //var leaderboard = await SteamUserStats.FindLeaderboardAsync("Global Score");
        if (leaderboard.HasValue)
        {
            steamLeaderboard = leaderboard.Value;
            LeaderboardEntry[] entries = await steamLeaderboard.GetScoresAroundUserAsync(-5, 5);
            if (entries == null)
            {
                // or maybe just "return;"
                entries = new LeaderboardEntry[]{};
            }
            foreach (var e in entries)
            {
                GameObject temp = Instantiate(LeaderboardListItem, LeaderboardGlobal);
                temp.transform.Find("PlayerName").GetComponent<Text>().text = e.User.ToString();
                temp.transform.Find("PlayerRank").GetComponent<Text>().text = e.GlobalRank.ToString();
                temp.transform.Find("PlayerScore").GetComponent<Text>().text = e.Score.ToString();
                AssignFriendImage(temp, e.User.Id);
                
            }
        }
        else { Debug.Log("Leaderboard has no values!"); }
    }`

**Comment by Tresiris** [comment]
Awesome, thanks hankditton!  This looks like it will work great.
