### ISSUE TITLE
WorkShopItem query NumPerPage support?

### ISSUE THREAD

**Issue by 0kk470** [Facepunch/Facepunch.Steamworks#593]
**Is your feature request related to a problem? Please describe.**
Hi, the default numPerPage for workshop items is 50 , which is too large for me now. 

**Describe the solution you'd like**
Is there any way to add a method like this?
``` C#
Ugc.Query.All.GetPageAsync(int page, int num_perpage)

```

**Describe alternatives you've considered**
Or I can set a global value for the query. 
``` C#
Ugc.Query.defaultNumPerPage = 10
```
**Additional context**
None.

**Comment by Scylin232** [comment]
Is anyone find out how to implement that?

**Comment by 0kk470** [comment]
> Is anyone find out how to implement that?

Hi, the numperpage is a constant value according to the [steamworks documentation](https://partner.steamgames.com/doc/api/ISteamUGC#kNumUGCResultsPerPage).

A tricky way is to query a large amount of items , store them in a cache List and make a paging yourself.
