### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by SeiferCleric** [Facepunch/Facepunch.Steamworks#6]
Good Day

I require leaderboards for my game but unless I'm mistaken the api does not include leaderboards yet. I started to code my own with the intent to request a pull and add it to the project if I get it working in a nice easy way. Everything went very well from within Unity and my leaderboards worked perfectly but when I build my game the game crashes with an "steam_api.dll caused an Access Violation (0xc0000005)
in module steam_api.dll at 0023:5cbc7b80." error. I really noob with this and I'm hoping someone who knows a bit more about the steamworks sdk could point out my mistake.

I've attached my code. I created a completely new class Leaderboard.cs because I didn't want to mess to much with the original api. My code is still experimental but it works fine from Unity with the following code:

        LeaderboardSeason = steamClient.Leaderboards.GetLeaderoard("Sample Leaderboard");
        LeaderboardSeason.LoadLeaderboard();

        if (LeaderboardSeason.LeaderboardLoaded)
            LeaderboardSeason.DownloadEntries();

[Leaderboard Class.docx](https://github.com/Facepunch/Facepunch.Steamworks/files/758958/Leaderboard.Class.docx)

Thanks
Rousseau

**Comment by garrynewman** [comment]
I'll put something together today for you

**Comment by SeiferCleric** [comment]
Thanks much appreciated. From as far as I can tell the error occurs when the callback is triggered.

**Comment by garrynewman** [comment]
I've committed the leaderboards

```csharp

var board = client.GetLeaderboard( "TestLeaderboard", Steamworks.Client.LeaderboardSortMethod.Ascending, Steamworks.Client.LeaderboardDisplayType.Numeric );

board.FetchScores( Steamworks.Leaderboard.RequestType.Global, 0, 20 );

foreach ( var entry in board.Results )
{
     ...
}
```

There's a test that kind of shows how it works

**Comment by SeiferCleric** [comment]
Hi. Thanks for the update, I tested it last night but still couldn't get it to work. It still gives the same exception in the final build of my game. I eventually found a work around using steamworks.net and facepunch but I attached the ouput of the exception if you want to take a look at it.

[output_log.txt](https://github.com/Facepunch/Facepunch.Steamworks/files/762763/output_log.txt)

**Comment by garrynewman** [comment]
Looks like a different issue, something to do with getting a server list on a 32bit windows build - I'll try to fix that today.

**Comment by garrynewman** [comment]
After further exploration - I can't recreate the crash. I've added tests to https://github.com/Facepunch/Facepunch.Steamworks.Unity/ and tried it in 32bit, and it works for me.

Are you doing anything else that might cause a crash in a callback?

**Comment by SeiferCleric** [comment]
I also downloaded avatars of the users on the leaderboard. In my second test after you updated the library I'm sure I left that part out although some code might have remained that I overlooked. Except for that there is really nothing else I can think of that I changed. Everything seems to be working for me now with my work-around so don't waste your time if you can't reproduce it. But thanks allot for the effort its much appropriated and your library rocks !
