### ISSUE TITLE
Symmetric connect for sockets?

### ISSUE THREAD

**Issue by Skippeh** [Facepunch/Facepunch.Steamworks#631]
Is it possible to use symmetric connect when using sockets?

https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/include/steam/steamnetworkingtypes.h#L1221

**Comment by Skippeh** [comment]
Solved it, modified my fork to set the option. Not the best implementation but it works for my purposes

The commit if anyone stumbling upon this is curious:
https://github.com/Jump-King-Multiplayer/Facepunch.Steamworks/commit/281380ff2edea049fe0458406a6c988650488d62

**Comment by MattTree** [comment]
Thanks for this.

I'm trying to understand if I need this.

Can you tell me about your use case?

It seems like the race conditions could be avoided by initiating the connection deterministically; for example, from the peer with the smaller Steam ID.

(I'm new to Steamworks)
