### ISSUE TITLE
How to use SteamInput functionality?

### ISSUE THREAD

**Issue by semihsmg** [Facepunch/Facepunch.Steamworks#636]
I couldn't figure it out... Can't find any kind of example or proper doc related to SteamInput.
Any help appreciated!

**Comment by stoora** [comment]
Great you had it working. 
How were you able to test the app locally and prototype with steamInput?
Did you use '1456390 ' for app id? Launched app from steam as a non steam game?
Any configurations worth mentionning? I've been digging the internet for days and SteamInput process is not documented unfortunately. Thank you in advance!
