### ISSUE TITLE
Workshop item search

### ISSUE THREAD

**Issue by Justusvh** [Facepunch/Facepunch.Steamworks#639]
I would like a way to search the workshop for items based on a string (similar to the steam workshop browser).

Currently I get a page of results, which I query by a tag ("Map".
Then look through each result.items title, description & metadata to compare see if it contains the search string.

I feel like this is not a particularly good solution as I'm assuming it will created issues as the amount of content available on the workshop increases. It would be great to  get a page of results based on an input string (or CSV or similar).

**Comment by Jake-NSW** [comment]
`query.WhereSearchText( "Search Text" );`

**Comment by Justusvh** [comment]
Thanks, I found that a while later but forgot to close this topic
