### ISSUE TITLE
Callbacks?

### ISSUE THREAD

**Issue by njbrown09** [Facepunch/Facepunch.Steamworks#64]
I'm trying to register the Game rich presence join callback. Where would I register it?

**Comment by njbrown09** [comment]
?

**Comment by mpc1999** [comment]
Did you find the solution? I have a similar one though I'm unable to get the server to detect when a player is attempting to join.

**Comment by garrynewman** [comment]
Not sure what you're looking for, you can set rich presence using user.SetRichPresence - are you looking for something different?

**Comment by BrinerLovo** [comment]
Hi.

I have same problem, basically I want to subscribe a callback for GameRichPresenceJoinRequested_t, 
I want handle the response when this event is fired, but I'm not sure how, help will be appreciate!

**Comment by garrynewman** [comment]
Added Friends.OnInvitedToGame callback
