### ISSUE TITLE
Mac - works in Editor, Builds fine. Does not work standalone.

### ISSUE THREAD

**Issue by Justusvh** [Facepunch/Facepunch.Steamworks#652]
The game runs 100% on Windows both in the Unity Editor and as a stand alone build.
On Mac, the game will run fine in editor and I can cross play from PC to mac. However, When I build the Game on Mac and launch is as standalone, the game no longer has access to steam -> the SteamClient.IsValid always returns false.

Any one got any ideas?

**Comment by incendy** [comment]
Same issue, I cannot get it to work on MacOS but everything working correctly on Windows. When I catch the error for Steamworks.SteamClient.Init(appId); I get what is shown below

libsteam_api assembly:<unknown assembly> type:<unknown type> member:(null)
UnityEngine.Debug:Log (object)
steamworksUtility:Start () (at Assets/_myScripts/steamworksUtility.cs:34)

**Comment by yaxamie** [comment]
I've upgraded from 2019's LTS to the 2021 LTS and I am not not able to load the api 

Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.dylib
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.dylib
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.so
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.bundle
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.dylib
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.dylib
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.so
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api.bundle
Fallback handler could not load library <path/to/app/here>/Contents/Frameworks/MonoEmbedRuntime/osx/libsteam_api

I'll be looking into it a bit more today.

**Comment by yaxamie** [comment]
Tried the latest release, adding recommended scripting defines, etc.  Getting the above issue as well, at least in our project.  Looks like I'll be rolling back to 2019 LTS for the time being.

**Comment by vincent-savysoda** [comment]
any news on a fix for MacOS builds? I'm getting the following errors when client tries to run SteamUser.GetAuthSessionTicketAsync:
<img width="526" alt="Screen Shot 2022-08-03 at 2 14 52 pm" src="https://user-images.githubusercontent.com/21209077/182523864-a6fc267e-96f4-4f36-8bcf-15d558838412.png">

**Comment by Justusvh** [comment]
I did end up getting it to work, Here's the exact setup:

Latest facepunch dlls -> we re-built them from the git project,
Set the MAC dlls to 64 bit only.
Make sure you have created a new Depot in steam that is set as a MAC depot.
