### ISSUE TITLE
Lobby.Refresh does not return false if a lobby no longer exists

### ISSUE THREAD

**Issue by MrGentle** [Facepunch/Facepunch.Steamworks#660]
From the description of the method it says "If the specified lobby doesn't exist, LobbyDataUpdate_t::m_bSuccess will be set to false"
Shouldn't this be reflected in the Lobby.Refresh call?

If not, how would I go about checking if a lobby still exists without joining it?

**Comment by seasonseong** [comment]
How do you check whether the lobby doesn't exist? SteamMatchmaking.OnLobbyDataChanged isn't called when the lobby does not exist.
