### ISSUE TITLE
Namespace "Steamworks" wasn't found

### ISSUE THREAD

**Issue by ozhanghe** [Facepunch/Facepunch.Steamworks#665]
**Describe the bug**
I import the library from the releases page, it says that the namespace "Steamworks" wasn't found. I'm on linux if that helps. Unity Version: 2020.3.24f1. My Unity Player uses Mono with Net Standard 2.0.

**To Reproduce**
1. Use Unity Editor 2020.3.24f1.
2. Select Mono with Net Standard 2.0.
3. Attempt to import the library.
4. See error.

**Calling Code**
```
    public uint id;
    // Start is called before the first frame update
    void Start()
    {
        DontDestroyOnLoad(gameObject);
        try
        {
            Steamworks.SteamClient.Init( id );
        }
        catch ( System.Exception e )
        {
            // Something went wrong - it's one of these:
            //
            //     Steam is closed?
            //     Can't find steam_api dll?
            //     Don't have permission to play app?
            //
            Debug.LogError(e.Message);
        }
    }

    // Update is called once per frame
    void Update()
    {
        Steamworks.SteamClient.RunCallbacks();
    }

    void OnDisable()
    {
        Steamworks.SteamClient.Shutdown();
    }
```

**Expected behavior**
I expected to be able to use the namespace Steamworks.

**Desktop (please complete the following information):**
 - OS: Linux
- Unity: 2020.3.24f1

**Additional context**
Mono Net Standard 2.0 (No IL2CPP). Tried to compile library from source but still didn't work.

**Comment by TLmaK0** [comment]
@ozhanghe as a workaround install latest version and change `Facepunch.Steamworks.Posix` dll Editor settings to OS linux:

![image](https://user-images.githubusercontent.com/399935/183356505-a51d0f6a-832e-4e51-902f-89e7964c20ec.png)
![image](https://user-images.githubusercontent.com/399935/183356612-4b0abae5-f3af-465d-a0f6-1f83384bbc64.png)

**Comment by yunhailuo** [comment]
Just to share info FWIW, it seems working fine if setting OS to `AnyOS` **and** adding a `UNITY_EDITOR_OSX || UNITY_EDITOR_LINUX` constraint. It should support Mac and Linux with the same code then.

**Comment by ozhanghe** [comment]
It's working now. Thanks!
