### ISSUE TITLE
Workshop items created blank

### ISSUE THREAD

**Issue by Talsidor** [Facepunch/Facepunch.Steamworks#67]
When I call Publish on a workshop item it does show up in Steam, but none of the content travels with it.
Here's the code I'm using to submit the item:
```
Workshop.Editor workshopItem = Steam.client.Workshop.CreateItem(Workshop.ItemType.Community); 
workshopItem.Title = MapManager.selectedMap.name; 
workshopItem.Folder = tempDirPath; 
workshopItem.PreviewImage = "preview.jpg"; 
workshopItem.Visibility = Workshop.Editor.VisibilityType.Public; 
workshopItem.Publish();
```

Here's a screenshot of an uploaded item, blank name, no image, 0 bytes of data. (You'll also notice it's Hidden when I set visibility above to Public.)
![image](https://user-images.githubusercontent.com/2403289/29912742-130c014c-8e76-11e7-97d6-d9826acfd41c.png)

No errors or warnings are thrown, this is using the latest release (0.6). I can also confirm there's a 9.84 KB preview.jpg and 86.3 KB of other data in the folder at the time Publish is called.

**Comment by MollerVictor** [comment]
Does "workshopItem.Error" say anything after the publishing is finished?
I remember getting the same problem, when trying to upload before I allowed users to have space/files on steam cloud and enabling "ISteamUGC for file transfer".

**Comment by Talsidor** [comment]
workshopItem.Error is just an empty string, even a minute after Publish was called.
I created a coroutine to report upload progress but workshopItem.Progress and workshopItem.BytesUploaded stay at 0 indefinitely. workshopItem.Publishing also stays true indefinitely.

I double-checked the Steam portal for the title but ISteamUGC file transfer and Steam Cloud user data are both set correctly and published.

**Comment by Talsidor** [comment]
Would anyone else be able to paste the code of their working implementation of uploading a workshop item? I still can't get this to upload a non-blank item.

**Comment by Talsidor** [comment]
I pulled down the source code and stepped through the code. The issue appears to be that the OnItemCreated callback (registered on Line 113 of Workshop.Editor) simply never gets executed. I'm at a loss as to why this would be.

**Comment by MollerVictor** [comment]
https://gist.github.com/MollerVictor/c1b8a9c16fce4078aa1f006dbee4dd41

I have had no troubles running this code.

**Comment by Talsidor** [comment]
@MollerVictor Thanks. I've made my code practically identical to yours but still no callback. 
Can I ask if you've used it from inside the Unity editor or only builds?
And are you using Facepunch.Steamworks 0.6 or a different version?

**Comment by MollerVictor** [comment]
I don't use the callback, I checking it every frame. 

https://gist.github.com/MollerVictor/d5d7a0440ce946e1b742a049d273be59

**Comment by Talsidor** [comment]
Sorry, I mean internally to the API, Steam is not executing the OnItemCreated callback, which I mentioned above seems to be the reason it's not working for me. I'm also checking it every frame.

**Comment by Talsidor** [comment]
I spent the last few hours coding up the same functionality using Steamworks.NET, and it works. Facepunch.Steamworks still isn't receiving the OnItemCreated callback from Steam. :frowning_face:

**Comment by garrynewman** [comment]
Are you running 64bit or 32bit?
