### ISSUE TITLE
How in the world do I get this working on Linux?

### ISSUE THREAD

**Issue by Wolf-086** [Facepunch/Facepunch.Steamworks#682]
Linux user but I'm no Linux giga chad. I use visual studio code cuz regular old visual studio doesn't run on Linux. When it comes to building the Facepunch.Steamworks.sln I am completely lost. The instructions are for Windows, which for a Linux user like me, aren't very helpful.

Would appreciate some guidance.

**Comment by Wolf-086** [comment]
So I installed Monodevelop as I realized visual studio code doesn't really have that functionality (never tried building an app, just games). When I load the script in Monodevelop I get:

 error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found.
Unable to create package spec for project.

I believe the issue stems from the fact that I cannot install dotnot 4.6 on Linux. I have dotnot 6.0, but cannot find 4.6 anywhere.

When I try to build I get the error:

NuGet packages need to be restored before building. NuGet MSBuild targets are missing.and are needed for building.

This is once again bringing it back to the issue. Is there any work around for linux? Or am I royally screwed here? Is there any chance I can get a built version of this? I even tried cheesing it by installing Mono via Wine but I couldn't get it working.

**Comment by Wolf-086** [comment]
This is 100% a dotnet issue, it doesn't like dotnet 6.0, I get errors with it installed, but when I install a lower version, I simply get the following build errors when building:

/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. (MSB3971) (Generator)

/home/scott/.cache/MonoDevelop/7.0/MSBuild/148391_1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(5,5): Error NETSDK1073: The FrameworkReference 'NETStandard.Library' was not recognized (NETSDK1073) (Facepunch.Steamworks.Win64)

When dotnet 6 sdk is installed I get a could not restore packages error: 

Getting restore information for project /home/scott/Downloads/Facepunch.Steamworks-master/Facepunch.Steamworks.Test/Facepunch.Steamworks.TestWin64.csproj
/usr/share/dotnet/sdk/6.0.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props(14,38) : error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found.
Unable to create package spec for project. '/home/scott/Downloads/Facepunch.Steamworks-master/Facepunch.Steamworks.Test/Facepunch.Steamworks.TestWin64.csproj'


I have 0 clue how to fix this.

**Comment by Wolf-086** [comment]
I installed and ran a trial for jetbrains rider, it seems to have built properly, will confirm once I've tested this out in Unity.

**Comment by Wolf-086** [comment]
Yep, it's working, I'm an idiot. Problem solved.

**Comment by axvemi** [comment]
How did you manage to build with .net 4.6 on linux? Can you explain it please?
