### ISSUE TITLE
SteamFriends.GetFromSource(steamId) does not return data.

### ISSUE THREAD

**Issue by azcoffeehabit** [Facepunch/Facepunch.Steamworks#697]
**Describe the bug**
SteamFriends.GetFromSource(steamId) does not return data.  Interestingly this function returns an Ienumerable when requesting a single friend.

**To Reproduce**
Calling the function  "SteamFriends.GetFromSource(friendId)" returns 0 results when passed a valid SteamId.

**Calling Code**
```
	public string GetFriendName(SteamId friendId)
    {
		string friendname = null;
		var friend = SteamFriends.GetFromSource(friendId);
		foreach (var fiend in friend)
        {
			Console.WriteLine($"fiend.Name");
			friendname = $"fiend.Name";
		}
		return friendname;
    }
```

**Expected behavior**
Return a Friend Object from the SteamId Provided

**Desktop (please complete the following information):**
 - Windows 11
 - Unity 2022.3.9f1

**Additional context**
Debuger image attached

![image](https://user-images.githubusercontent.com/3053659/209990002-61fd7f84-16e9-4d24-b07a-fb1b715d3e0b.png)

**Comment by Derek-R-S** [comment]
Pretty sure you are using the wrong function here.

GetFromSource is for a Steam group, chat room, lobby, or game server.

I'm guessing you're intending to do something like such:
`
public string GetFriendName(SteamId friendId)
{
    return new Friend(friendId).Name;
}`

or in the case you are accessing players where you need to request the information:

`
public async Task<string> GetFriendName(SteamId friendId)
{
    var friend = new Friend(friendId);
    await friend.RequestInfoAsync();

    return friend.Name;
}`

**Comment by azcoffeehabit** [comment]
Thanks for the reply, I will look into this. Best Regards!
