### ISSUE TITLE
Trying to use on OSX — need "libsteam_api64.so"

### ISSUE THREAD

**Issue by kkukshtel** [Facepunch/Facepunch.Steamworks#7]
Trying to get the library working in the OSX editor play mode and it needs a libsteam_api64.so file. Any chance this can be generated from the project?

**Comment by garrynewman** [comment]
You should only need libsteam_api.dylib in your root folder.

If you're using Unity take a look at https://github.com/Facepunch/Facepunch.Steamworks.Unity/blob/master/Assets/Scripts/SteamTest.cs#L16

Calling `Facepunch.Steamworks.Config.ForUnity( Application.platform.ToString() );` before trying to init steam should set the platform properly for you.
