### ISSUE TITLE
Leaderboard.AddScore onlyIfBeatsOldScore is back to front

### ISSUE THREAD

**Issue by SoftwareGeezers** [Facepunch/Facepunch.Steamworks#72]
According to documentation, when set to true the score won't be updated unless it's greater than the current score.

I was having problems with my score not updating using this. Setting it to _false_, the scores are updated but only when greater than the existing scores.

**Comment by igniuss** [comment]
I have the same issue, except setting it to _false_ updates it every time. 
I've tried on 2 leaderboards, one set to Ascending, other to Descending, both have the same issue.

**Comment by garrynewman** [comment]
This seems to be fixed now - thanks

**Comment by Dimma** [comment]
It's not fixed. Same problem as described @igniuss
