### ISSUE TITLE
Unity Game: Crash on Steam Platform Startup 

### ISSUE THREAD

**Issue by benthroop** [Facepunch/Facepunch.Steamworks#73]
Hi Garry - thanks so much for releasing this package. It was a pleasure to work with. I hate to bug you but we're at a dead end. We are seeing crashes with a small minority of users at this moment in the Unity output_log.text:

Facepunch.Steamworks Unity: WindowsPlayer
Facepunch.Steamworks Os: Windows
Facepunch.Steamworks Arch: x64
Crash!!!

Normally it should look like this:

Facepunch.Steamworks Unity: WindowsPlayer
Facepunch.Steamworks Os: Windows
Facepunch.Steamworks Arch: x64
Steam platform successfully initialized.

Error.log is attached with crash in steamclient64.dll.
[error (1).log.txt](https://github.com/Facepunch/Facepunch.Steamworks/files/1290108/error.1.log.txt)

We've verified that the steam_api.dll and steam_api64.dll in the root of the Unity project are the same versions as ship with 0.7 of Facepunch.Steamworks which we've integrated. Works great normally but there's just a handful of users that are crashing. We haven't found any common configurations between them other than being Win10/Nvidia and pretty beefy machines. 

Any other ideas for what could be causing this or how to better debug it? We cannot repro locally - we're just relying on a small handful of helpful users who have been submitting reports. We are building with Unity 5.4.4p3 and this game is released on Steam (Headmaster). 

Thanks for any insight

**Comment by garrynewman** [comment]
Are you shipping 32bit versions? Do they have any hardware config in common?

**Comment by benthroop** [comment]
When you say shipping 32bit versions, do you mean of your .dll's? Or of the game itself? The game is 64bit. The Facepunch DLL is set to "any cpu", 32 or 64 bit.

The hardware config that they have in common is WIn10 64bit, 1070+ series Nvidia GPU, 16+GB ram, fast processors. The game is VR so that is probably driving that. However none of us on the dev team have had these problems, and we're all 970, 980, and 1060. 

It's crashing when I call this line:
SteamClient = new Client(Convert.ToUInt32(appId));

**Comment by garrynewman** [comment]
Sorry for the delay. These crashes usually mean that it's loading the wrong steam_api dll.

**Comment by krunal9SGS** [comment]
hey @benthroop what you find any solution , i have same problem when Init().

**Comment by krunal9SGS** [comment]
@garrynewman it's not work for me
