### ISSUE TITLE
RemoteStorage on Mac doesn't work

### ISSUE THREAD

**Issue by hungweng** [Facepunch/Facepunch.Steamworks#77]
Hi, the RemoteStorage on Mac doesn't seem to work for me...

Everything works perfectly fine on Windows, but when I try it on Mac to Read the file using RemoteStorage.ReadString, the string returned is garbage.
I checked the file in "steam/userdata/(id)/(appid)/remote", the file content is correct.

Is it just me doing something wrong?

(I also tried RemoteStorage.WriteString a test file, then RemoteStorage.ReadString the same file, the file couldn't be found even though WriteString returned True. I checked QuotaRemaining, it still has alot of free spaces)

**Comment by Metapyziks** [comment]
This could be related to something I'd fixed on another branch last month, but forgot to merge into `master`. I've merged it now, could you see if 2e65cfe9bb4192fc64c17d81df01b77bda80ae1d helps?

**Comment by hungweng** [comment]
Thank you! It's working now.
