### ISSUE TITLE
Achievement.Percentage documented incorrectly

### ISSUE THREAD

**Issue by metzsg** [Facepunch/Facepunch.Steamworks#78]
Achievement.Percentage: summary states "If this achievement is linked to a stat this will return the progress," however, the source shows it calls native function GetAchievementAchievedPercent from ISteamUserStats, which steam docs indicate returns a percentage of players that have unlocked this achievement, not our personal progress toward achieving the stat. (https://partner.steamgames.com/doc/api/ISteamUserStats#GetAchievementAchievedPercent)

**Comment by garrynewman** [comment]
Thanks, fixed
