### ISSUE TITLE
EntryPointNotFoundException on SteamAPI_Init (using latest Steamworks SDK)

### ISSUE THREAD

**Issue by PedroMarangon** [Facepunch/Facepunch.Steamworks#783]
Hi guys, I'm getting this error when I try to test my Unity game with Steam open (just implemented achievements and I want to test them). Does anyone know what I can do to fix this?
```
System.EntryPointNotFoundException: SteamAPI_Init assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Steamworks.SteamAPI+Native.SteamAPI_Init()
  at Steamworks.SteamAPI.Init () [0x00001] in D:\STEAMWORKS_FACEPUNCH\Facepunch.Steamworks\Classes\SteamApi.cs:31 
  at Steamworks.SteamClient.Init (System.UInt32 appid, System.Boolean asyncCallbacks) [0x00039] in D:\STEAMWORKS_FACEPUNCH\Facepunch.Steamworks\SteamClient.cs:26 
```
I'm using the latest version of Facepunch (compiled from source), and the Steamworks SDK version 1.60.

The error happens when I call `SteamClient.Init(appId)` at the very start of the game (code snapshot below - in this case, neither `forceDemoAppID` or `forceMainAppID` are active, but it still happens when either is active)
![image](https://github.com/user-attachments/assets/59460a47-01c9-469f-a484-813d8dfae939)

**Comment by Boy132** [comment]
You need the changes from https://github.com/Facepunch/Facepunch.Steamworks/pull/773 to use 1.6.0

**Comment by PedroMarangon** [comment]
Thenk you @Boy132 !!
