### ISSUE TITLE
Update the version in the AssetStore.

### ISSUE THREAD

**Issue by michidk** [Facepunch/Facepunch.Steamworks#8]
Hey, 
I just saw there are tons of new commits here... Great job!

The version in the Unity AssetStore was never updated since release (Nov 14, 2016).
Could you please upload the new version?

Thanks!

**Comment by TheRedShadow** [comment]
Yes, you should really create a unitypackage of the latest version :+1:

**Comment by garrynewman** [comment]
Yep. It's on my todo list.

**Comment by garrynewman** [comment]
Done this a few days ago.
