### ISSUE TITLE
InitServer: GameServer_Init returned false

### ISSUE THREAD

**Issue by Lohoris** [Facepunch/Facepunch.Steamworks#80]
I'm trying to setup a game server with Unity, and I keep getting this cryptic error: `InitServer: GameServer_Init returned false`.

I'm pretty sure I must be doing something wrong, like passing a wrong option or something, but I really can't understand what could it be, as it could be anything.

Is there a way to debug it further, or is there a detailed list of what I would be supposed to do?

I've browsed through all the Test and -Unity examples here, but somehow they didn't help…

Here's my init call:

```
                steamServerInit = new ServerInit( "The Gridiron", "Gridiron" );
                
                steamServerInit.IpAddress = System.BitConverter.ToUInt32( IPAddress.Parse( Network.player.ipAddress ).GetAddressBytes(), 0 );
                steamServerInit.RandomSteamPort();
                steamServerInit.GamePort = 22001;
                steamServerInit.QueryPort = 22002;
                steamServerInit.Secure = false;
                steamServerInit.VersionString = "0.0.1";
                
                steamServer = new Server( _steamGameId, steamServerInit );
```

Thank you in advance.

**Comment by garrynewman** [comment]
GameServer_Init returning false usually means it can't find the appid txt file, or can't find the right dlls.

**Comment by Lohoris** [comment]
Ok but… the appid is there, and the DLLs are there… how do I debug it?
