### ISSUE TITLE
How do you get a session ticket properly?

### ISSUE THREAD

**Issue by CrookGrimes** [Facepunch/Facepunch.Steamworks#81]
I've tried the script below, then I tried to use ticketData as the session ticket, and I don't think it's working. Am I missing something?

`var client = new Facepunch.Steamworks.Client(220);
var ticket = client.Auth.GetAuthSessionTicket();
var ticketData = ticket.Data;`

**Comment by CrookGrimes** [comment]
It would be nice if you leave a comment about it when closing.

**Comment by CrookGrimes** [comment]
So, how come the session ticket isn't being approved? Is anyone going to reply at all?

**Comment by CrookGrimes** [comment]
I'm assuming support is dead for this plugin.

**Comment by Ornias1993** [comment]
I'm assuming you made a shit-quality issue.
Maybe, just a guess, because it includes close to no info about what is not working in your opinion.
