### ISSUE TITLE
OnP2PData returning incorrect DataLength

### ISSUE THREAD

**Issue by MuletTheGreat** [Facepunch/Facepunch.Steamworks#82]
During development, we've found that **OnP2PData** delegate is rarely (once in every ~500 packets) returning an incorrect **DataLength**. 

The **DataLength** coming in, is sometimes significantly shorter than the packet that was actually sent by the other machine.

We tried to modify **ReadP2PPacket** to read all available data, without using **IsP2PPacketAvailible** to find the amount of data available. Instead we read all available data by passing in 65kb byte buffer into the internal **ReadP2PPacket**. 

This gives us the correct data in the byte array! However, the **pcubMsgSize** returned, is still shorter than the actual data that is there.

Do you have any idea what's going on here? And what can we do to help fix/diagnose this?

Below is our modified read that shows the discrepancy.

```
        private unsafe bool ReadP2PPacket( int channel )
        {

            if ( ReceiveBuffer.Length < ushort.MaxValue )
                ReceiveBuffer = new byte[ ushort.MaxValue ];

            fixed ( byte* p = ReceiveBuffer )
            {
                uint dataFound;
                SteamNative.CSteamID steamid = 1;
                if ( !networking.ReadP2PPacket( (IntPtr)p, ushort.MaxValue, out dataFound, out steamid, channel ) )
                    return false;

                OnP2PData?.Invoke( steamid, ReceiveBuffer, (int) dataFound, channel );
                return true;
            }
        }
```

**Comment by MuletTheGreat** [comment]
Additional Info:

The amount the **DataLength** is wrong by, is consistent. It is the length of the Sender's next packet.

So the client is getting **DataLength** of the next packet, for the current packet.

**Comment by garrynewman** [comment]
No idea what's happening. I'll look over the bindings to see if there could be anything wrong there.

**Comment by MuletTheGreat** [comment]
Ok, I figured out what's happening.

I was calling Facepunch.steamworks.Client.Update() from multiple threads, without locks. 

So the OnP2P delegate was being called multiple times at the same time. It behind this, is a cached array that is passed in. So it was being written and read to at the same time, creating a garbled mess.

My bad!
