### ISSUE TITLE
OSX Standalone build can't find libsteam.dylib when build with OSX Unity 5.6.3p4

### ISSUE THREAD

**Issue by Tinytouchtales** [Facepunch/Facepunch.Steamworks#86]
Hi,

i am encountering a weird issue on OSX. I can run and test my game in the editor, everything works as expected. 
Once i build the game from the "Build & Run" menu it gives me an error that it can't find libsteam.dylib. I manually fixed this issue by going into the .app package to Contents/Frameworks/MonoEmbedRuntime/osx/ and copying the missing dylib manually there. After that the error is gone but steam won't init. (no detailed error here)
When i upload the build with steam pipe and starting the game via steam itself everything works as expected again. 

I'm not sure if this is the expected behavior but at least the manual coping of dylib should be an issue.

**Comment by Metapyziks** [comment]
I'm not sure if there's a nicer way to do this at the moment, but here's an example of an editor script you can use to automate copying those libraries on build:

https://github.com/Facepunch/Facepunch.Steamworks.Unity/blob/master/Assets/Scripts/Editor/CopySteamLibraries.cs

You'll just need to put that file inside an `Editor` folder somewhere in your `Assets`.

I haven't got an OSX machine set up at the moment, so I can't guarantee the paths in that script are correct.

**Comment by Metapyziks** [comment]
That's a fair point, so I've updated the readme to mention the editor script.

**Comment by cpioli** [comment]
I am having an issue with CopyStreamLibraries.cs in my game's Mac Build w/ Unity 5.6.3f1. The script is only moving steam_appid.txt to the correct position, not libsteam_api.dylib. Any attempt to copy/paste the .dylib into the .app file's directory or into Contents/Frameworks/MonoEmbedRuntime/osx/ results in the same problems @Tinytouchtales mentioned.

Until I can be sure our Mac build can connect to Steamworks and update Achievements I do not feel safe uploading the new build.

**Comment by cpioli** [comment]
I'm having a problem with CopySteamLibraries.cs on my Mac OS X build: the script is only moving steam_appid.txt, not libsteam_api.dylib. Any attempt to copy/paste the .dylib into the .app file's directory or into Contents/Frameworks/MonoEmbedRuntime/osx/ results in the same problems described by @Tinytouchtales.

I mentioned this in Facepunch.Steamwork's Steam Development discussion, too, but haven't gotten a response. I apologize if I'm simply being impatient due to the holidays.

**Comment by Tinytouchtales** [comment]
@cpioli After you've moved the file by hand you need to publish the game to Steam itself. For me Steam only works either in the Unity3D editor or when running the game from the official steam client. Starting the App from your desktop with the files correctly copied will not start steam correctly.

**Comment by cpioli** [comment]
If that's the case, I suppose my team and I have no choice. For clarification, though, does the dylib has to be put into the .app file's directory, or Contents/Frameworks/MonoEmbedRuntime/osx/?

**Comment by Tinytouchtales** [comment]
@cpioli like it described above: _manually fixed this issue by going into the .app package (right click, show package content) to Contents/Frameworks/MonoEmbedRuntime/osx/ and copying the missing dylib manually there._

**Comment by cpioli** [comment]
Hi @Tinytouchtales, it didn't work. I manually copied the dylib to Contents/Framework/MonoEmbedRuntime/osx as well. The achievement didn't register. I looked at the local files on my mac, and there is no Steam app id text file next to the .app file. Do you have any suggestions?

**Comment by Tinytouchtales** [comment]
@cpioli here's how my Unity root looks like: https://imgur.com/PvJ1OPs
here's how my .app content looks like: https://imgur.com/ttm3Xap

here's my achievement code:

`IEnumerator CoReportAchievementComplete(AchievementType achievementType)
	{
		if(SteamManager.Instance.steamClient.IsValid)
		{
			#if !UNITY_EDITOR

			// get achievements

			while(SteamManager.Instance.steamClient.Achievements.All.Length == 0)
			{
			SteamManager.Instance.steamClient.Achievements.Refresh();

			yield return new WaitForEndOfFrame();
			}

			Facepunch.Steamworks.Achievement achievement = SteamManager.Instance.steamClient.Achievements.Find(achievementType.ToString());

			// if achievement not unlocked

			if(!achievement.State)
			{
			print("Unlock achievement: "+achievement.Name);

			achievement.Trigger(true);
			}

			#endif

			yield return null;
		}

	}`

**Comment by cpioli** [comment]
Hi @Tinytouchtales, I actually got it working. The final issue was that I forgot the steam_appid.txt file. Once that was in it worked perfectly! Thanks for all your help, we're going to launch sometime this week.

**Comment by danoli3** [comment]
Modifying the Application package as described after the Post Build, unity flags the application as modified and not genuine. I'm working on an alternate solution I'll PR when finished.

**Comment by kkukshtel** [comment]
Any follow up here? @danoli3 did you submit at PR that fixes this?
