### ISSUE TITLE
Lobby API not working?

### ISSUE THREAD

**Issue by Cosmas47** [Facepunch/Facepunch.Steamworks#89]
Hey all, just getting started here with FP.S and Steamworks as a whole actually.
On the readme page the line:

> To create a Lobby do this.
> 
> client.Lobby.Create(Steamworks.Lobby.Type.Public, 10);

Doesn't seem to work, there's no Lobby namespace. 
Is this correct? Using the Asset Store version. 
Also, is this even possible with the Spacewar AppID?
Also, do you gents have a discord? Would love to ask more questions.
Also, thanks to GNuman so much for making this.

**Comment by nick-morhun** [comment]
We need this too. I wrote a wrapper but having trouble to get it working.

**Comment by nick-morhun** [comment]
It seems like they added this after the latest release (v. 0.6 in Summer). We have to clone this repo and build ourselves.

**Comment by nick-morhun** [comment]
Maybe Steam requires the latest client version for this?

**Comment by Cosmas47** [comment]
@nick-morhun - Let me know if you figure out how to compile it. I can't get the main library to load.

**Comment by nick-morhun** [comment]
@Cosmas47 What do you mean by saying

> get the main library to load

?
You need files from directory \Facepunch.Steamworks\bin\Release\net35 .
I'm quite new to VS 2017 so I did some hacks.
From what I see in Git:

In file 'Facepunch.Steamworks.csproj' with notepad I changed

```
    <TargetFrameworks>netstandard2.0;net45;net35;net40</TargetFrameworks>
```
to

```
     <TargetFrameworks>net35</TargetFrameworks>
```

and built only the Facepunch.Steamworks project, not the entire solution.
Then I replaced the files I had in my project with those from  \Facepunch.Steamworks\bin\Release\net35.

steam_api dlls are the same as in 0.6.

Unity sees the classes and connects with default steam ID. As for how it works, I'm still to test.

**Comment by nick-morhun** [comment]
For now, no luck for me with Lobby.Create neither with default appID, nor with our custom one.

**Comment by nick-morhun** [comment]
And now it works but I have no idea why...

**Comment by Cosmas47** [comment]
I see. I was using VS 2015 - The main Facepunch.Steamprojects.csproj doesn't load there but after upgrading to VS 2017 it loads. Still didn't compile until I found in a roundabout way I needed to install the .Net Core SDK 2.0. Now it compiles fine. No changes to project file needed.

**Comment by Mehmet-Burak-Aslan** [comment]
can you find how change spacewar id?
