### ISSUE TITLE
Unity 3D crashing

### ISSUE THREAD

**Issue by TheRedShadow** [Facepunch/Facepunch.Steamworks#9]
Hello!
Unity version: 5.5.2f1 (latest)
Facepunch.Steamworks version: the lastes on AssetsStore

My Unity 3D crashes when I try to call client variable without surrounding the part of code with a
 "using (client) { }"

I don't want to use it because it seems to be the cause of the lag in my game when I get usernames and avatars of 6 players (in my scoreboard).

this is the crash.dmp : http://pastebin.com/Tyb6Bv9e

And this is error.log : http://pastebin.com/7F8kpCfY

**Comment by garrynewman** [comment]
You'll have to show some of your code. You shouldn't be using using. You should be creating a single instance of the client and then accessing that one from everywhere. Then only disposing it when you're shutting down.

**Comment by TheRedShadow** [comment]
Thanks it's working now, I don't really know what I changed but now it's working...

Thanks again :)
