### ISSUE TITLE
No callbacks for GetLeaderboard?

### ISSUE THREAD

**Issue by yyr57695** [Facepunch/Facepunch.Steamworks#90]
I am trying to call GetLeaderboard asynchronously, so that the player's score can be added to the leaderboards seamlessly while my Game Over animation is playing.  But I don't see any parameters or methods that would allow me to do this.

The Steamworks API seems to allow for obtaining leaderboards asynchronously, so can this capability be added to Facepunch.Steamworks?  Or if I'm completely missing an existing way to do this, could someone point a finger in that direction?  Thanks! =)

**Comment by nick-morhun** [comment]
Hi. From what I see, they tend to oversimplify APIs by making async calls look sync. By doing this, they (inevitably) create their own ways for us to wait for async. operations.

In this case I can see in source code (not 0.6 but the latest master branch) that you should store that leaderboard but wait in some async. loop until its' IsValid property is true.

**Comment by garrynewman** [comment]
Yeah it's all very contrived. Ideally we'd be able to use async and do this stuff properly. For now, if it helps, I've added Leaderboard.OnBoardInformation
