### ISSUE TITLE
Deferred Avatar Loading Todo

### ISSUE THREAD

**Issue by nick-morhun** [Facepunch/Facepunch.Steamworks#91]
Before I switched to Facepunch.Steamworks, I was trying to implement deferred avatars loading because Steam docs say it's possible to not have avatars cached.
But now I look at Friends.GetAvatar() code and see that it's not implemented here either. So, I have 2 questions:
1. I can see that this TODO is unreachable - is this a bug?
2. Has anyone ever experienced need for loading Steam avatars in async. manner?

**Comment by nick-morhun** [comment]
After I fixed reach-ability of the code, the exception is thrown sometimes where it returns a gray texture in current master branch.

**Comment by garrynewman** [comment]
Yeah - this was a bit of a mess, and it's a common problem. Have changed GetAvatar to take a callback, GetCachedAvatar is the old behaviour

**Comment by nick-morhun** [comment]
I see the new API, but it doesn't work.
