### ISSUE TITLE
A strange place in Lobby code

### ISSUE THREAD

**Issue by nick-morhun** [Facepunch/Facepunch.Steamworks#93]
As I was scrolling through the Lobby class in an attempt to understand meaning of what I receive in the OnChatMessageRecieved event, I came across the OnLobbyChatMessageRecievedAPI method.
In it, I saw a strange place : "ReceiveBuffer.Length < readData". So, did this really happen?
Steam docs say that readData is "The number of bytes copied into" ReceiveBuffer. I doubt that it's legal to copy more bytes in that buffer than ReceiveBuffer.Length.

**Comment by garrynewman** [comment]
Thanks, have cleaned this up
