### ISSUE TITLE
ConsumeItem is not realized?

### ISSUE THREAD

**Issue by Wroud** [Facepunch/Facepunch.Steamworks#95]
Looked into source code and not found ConsumeItem.
Also have some problems with inventory update, sometimes inventory onUpdate not fire when im trying to load inventory (have items, steam online, can get info about user) but cant do anything with inventory. Cant hanle this issue, with some peoples its works fine, but some not. First time when i create library with Facepunch.Steamworks its not work, but when i create new project it become working.

**Comment by TarasDev** [comment]
same here

**Comment by Wroud** [comment]
Add pull request that probably solve issue #96

**Comment by garrynewman** [comment]
Added Item.Consume
