### ISSUE TITLE
How to get GameConnectedFriendChatMsg_t to work?

### ISSUE THREAD

**Issue by LeoGigliotti** [Facepunch/Facepunch.Steamworks#99]
Hey, I am trying to show received messages from Steam friends inside my game!
I've tried doing some stuff like:
`Client.Instance.native.friends.SetListenForFriendsMessages(true);
GameConnectedFriendChatMsg_t.RegisterCallback(Client.Instance.native.friends.steamworks, OnChatMessageReceived);`

And:
`Client.Instance.native.friends.SetListenForFriendsMessages(true);
GameConnectedFriendChatMsg_t.RegisterCallback(Client.Instance, OnChatMessageReceived);`

But none of this seems to work... The callback is never called.
Am I missing the correct way to set it up?

Thanks in advance!

**Comment by garrynewman** [comment]
Hey dude - believe I just added everything you need - let me know if it works/doesn't work.
